firebase-database/src/main/java/com/google/firebase/database/core/DatabaseConfig.java
=> Update TODO in DatabaseConfig

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/publish/PublishingPlugin.groovy
* Change the license of the published artifacts to "Apache 2.0"
* Add git repository information to the generated poms
=> Update maven artifact configuration.

test-apps/functions-test-app/functions/package-lock.json, test-apps/functions-test-app/functions/package.json
I tested by deploying the new functions and using curl to verify `addNumbers` still works.
=> Update functions test app to a newer version of firebase functions.

firebase-firestore/src/test/resources/json/listen_spec_test.json, firebase-firestore/src/test/resources/json/offline_spec_test.json, firebase-firestore/src/test/resources/json/remote_store_spec_test.json, firebase-firestore/src/test/resources/json/write_spec_test.json
This PR pulls in the spec tests from https://github.com/firebase/firebase-js-sdk/pull/1247
=> Update spec tests from JS #1247

firebase-common/firebase-common.gradle, firebase-database/src/main/java/com/google/firebase/database/android/package-info.java, firebase-database/src/main/java/com/google/firebase/database/annotations/package-info.java, firebase-database/src/main/java/com/google/firebase/database/connection/package-info.java, firebase-database/src/main/java/com/google/firebase/database/connection/util/package-info.java, firebase-database/src/main/java/com/google/firebase/database/core/package-info.java, firebase-database/src/main/java/com/google/firebase/database/logging/package-info.java, firebase-database/src/main/java/com/google/firebase/database/snapshot/package-info.java, firebase-database/src/main/java/com/google/firebase/database/tubesock/package-info.java, firebase-database/src/main/java/com/google/firebase/database/util/package-info.java, firebase-firestore/firebase-firestore.gradle, firebase-functions/firebase-functions.gradle, firebase-storage/src/main/java/com/google/firebase/storage/internal/package-info.java, firebase-storage/src/main/java/com/google/firebase/storage/network/package-info.java, root-project.gradle
Fixes coming out the recent release
=> Release fixes

firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
=> bug fix on a race

firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
address comment missed on #107
=> a tiny refactoring on ensureClientConfigured()

firebase-common-ktx/firebase-common-ktx.gradle, firebase-common-ktx/gradle.properties, firebase-common-ktx/src/main/AndroidManifest.xml, firebase-common-ktx/src/main/java/com/google/firebase/Firebase.kt, firebase-common-ktx/src/test/java/FirebaseTest.kt, firebase-common/src/main/java/com/google/firebase/FirebaseApp.java, firebase-common/src/main/java/com/google/firebase/FirebaseOptions.java, firebase-common/src/main/java/com/google/firebase/annotations/NonNullGeneric.java, firebase-common/src/main/java/com/google/firebase/annotations/NullableGeneric.java, firebase-common/src/main/java/com/google/firebase/internal/FirebaseAppHelper.java, firebase-common/src/main/java/com/google/firebase/internal/InternalTokenProvider.java, root-project.gradle, subprojects.cfg
=> Adds initial Kotlin support via firebase-common-ktx

firebase-firestore/CHANGELOG.md
Backport of http://cl/223040594
=> CHANGELOG.md updates for firestore 17.1.4

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/AffectedProjectFinder.groovy, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationExtension.groovy, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationPlugin.groovy, root-project.gradle
The tasks determine what tests to run based on the contents of the PR as
opposed to testing the whole repo.
=> Adds CI gradle tasks.

firebase-firestore/gradle.properties
last released version is inaccurate
=> update firebase-firestore gradle.properties

firebase-common/proguard.txt, firebase-common/src/main/java/com/google/firebase/components/Component.java, firebase-common/src/main/java/com/google/firebase/components/Dependency.java, firebase-common/src/test/java/com/google/firebase/components/ComponentTest.java, firebase-common/src/test/java/com/google/firebase/components/DependencyTest.java
Set-components are components of type T that contribute values into a
larger Set<T> rather than registering one unique T value whose
uniqueness is enforced at runtime.
=> Add the concept of Set-components and dependencies.

firebase-common/src/main/AndroidManifest.xml, firebase-database-collection/src/main/AndroidManifest.xml, firebase-database/src/androidTest/AndroidManifest.xml, firebase-database/src/main/AndroidManifest.xml, firebase-firestore/src/androidTest/AndroidManifest.xml, firebase-firestore/src/main/AndroidManifest.xml, firebase-firestore/src/test/AndroidManifest.xml, firebase-functions/src/androidTest/AndroidManifest.xml, firebase-functions/src/main/AndroidManifest.xml, firebase-inappmessaging-display/src/main/AndroidManifest.xml, firebase-storage/src/androidTest/AndroidManifest.xml, firebase-storage/src/main/AndroidManifest.xml, firebase-storage/src/test/AndroidManifest.xml
Commenting versions in manifest files
=> Commenting out version info

firebase-firestore/src/main/java/com/google/firebase/firestore/remote/Datastore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java, firebase-firestore/src/test/resources/json/listen_spec_test.json, firebase-firestore/src/test/resources/json/write_spec_test.json
This corresponds to a server-side change that will be released for the v1 protocol only (see b/119437764).
This is a port of firebase/firebase-js-sdk#1456.
=>  Treat ABORTED writes as retryable

firebase-firestore/CHANGELOG.md, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/POJOTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ServerTimestampTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/CollectionReference.java, firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentReference.java, firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentSnapshot.java, firebase-firestore/src/main/java/com/google/firebase/firestore/Transaction.java, firebase-firestore/src/main/java/com/google/firebase/firestore/UserDataConverter.java, firebase-firestore/src/main/java/com/google/firebase/firestore/WriteBatch.java, firebase-firestore/src/main/java/com/google/firebase/firestore/util/CustomClassMapper.java, firebase-firestore/src/test/java/com/google/firebase/firestore/model/FieldValueTest.java
This reverts commit 6c2e9a5ecd98118c8fa0012a5721f12c68c56d56.
This reverts https://github.com/firebase/firebase-android-sdk/pull/140.
This re-applies https://github.com/firebase/firebase-android-sdk/pull/76.
=> Revert "Revert "Better POJO Support for Document Fields" (#140)"

firebase-common/src/main/java/com/google/firebase/components/ComponentRuntime.java, firebase-common/src/test/java/com/google/firebase/components/ComponentRuntimeTest.java
The issue manidests with registered value components being missing at runtime.
=> Fix set component registration issue.

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ServerTimestampTest.java
Port of https://github.com/firebase/firebase-js-sdk/pull/1511
=> Port flaky test fix from web.

tools/errorprone/src/main/java/com/google/firebase/errorprone/ComponentsAppGetCheck.java, tools/errorprone/src/main/java/com/google/firebase/errorprone/NoStaticOrDefaultMethodsInInterfaces.java
This is needed due to cl/233688101
=> Remove the deprecated category attribute from errorprone bug checkers.

firebase-firestore/src/test/java/com/google/firebase/firestore/util/MapperTest.java
Adds tests to specify exactly how we handle properties with all caps names.
=> Test how to handle all caps properties

firebase-firestore/src/main/java/com/google/firebase/firestore/util/CustomClassMapper.java, firebase-firestore/src/test/java/com/google/firebase/firestore/util/MapperTest.java
Pull request for this issue : https://github.com/firebase/firebase-android-sdk/issues/239
=> Use PropertyName value for enum serialization/deserialization

firebase-storage/CHANGELOG.md
See https://github.com/firebase/firebase-android-sdk/pull/266
=> Add Changelog Entry for Firebase Storage's RestrictTo change

firebase-database-collection/firebase-database-collection.gradle, firebase-database/CHANGELOG.md, firebase-database/src/main/java/com/google/firebase/database/DatabaseError.java, firebase-database/src/main/java/com/google/firebase/database/DatabaseException.java, firebase-database/src/main/java/com/google/firebase/database/DatabaseRegistrar.java, firebase-database/src/main/java/com/google/firebase/database/InternalHelpers.java, firebase-database/src/main/java/com/google/firebase/database/Query.java, firebase-database/src/main/java/com/google/firebase/database/Transaction.java, firebase-database/src/main/java/com/google/firebase/database/android/package-info.java, firebase-database/src/main/java/com/google/firebase/database/annotations/package-info.java, firebase-database/src/main/java/com/google/firebase/database/connection/package-info.java, firebase-database/src/main/java/com/google/firebase/database/connection/util/package-info.java, firebase-database/src/main/java/com/google/firebase/database/core/operation/package-info.java, firebase-database/src/main/java/com/google/firebase/database/core/package-info.java, firebase-database/src/main/java/com/google/firebase/database/core/persistence/package-info.java, firebase-database/src/main/java/com/google/firebase/database/core/utilities/encoding/package-info.java, firebase-database/src/main/java/com/google/firebase/database/core/utilities/package-info.java, firebase-database/src/main/java/com/google/firebase/database/core/utilities/tuple/package-info.java, firebase-database/src/main/java/com/google/firebase/database/core/view/filter/package-info.java, firebase-database/src/main/java/com/google/firebase/database/core/view/package-info.java, firebase-database/src/main/java/com/google/firebase/database/logging/package-info.java, firebase-database/src/main/java/com/google/firebase/database/snapshot/package-info.java, firebase-database/src/main/java/com/google/firebase/database/tubesock/package-info.java, firebase-database/src/main/java/com/google/firebase/database/util/package-info.java
Same as https://github.com/firebase/firebase-android-sdk/pull/266 but for the RTDB and firebase-database-collection.
Addresses #264
=> Add RestrictTo annotations to Firebase Database

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/device/FirebaseTestServer.groovy
This makes sure results land in PRs artifacts directory to make them
accessible through CI UI.
=> Upload FTL results to a specified directory.

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
In particular this will detect leaked Cursors in Firestore's integration tests.
This is in response to #382, which suggests leaked cursors as a possible culprit, but this shows that's not the case.
=> Enable strict mode to detect leaks of SQLite objects

firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
=> Fix typo for transactions/batch

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/FirebaseLibraryExtension.java, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/publish/PublishingPlugin.groovy, buildSrc/src/test/groovy/com/google/firebase/gradle/plugins/publish/PublishingPluginSpec.groovy, firebase-common/firebase-common.gradle, firebase-database-collection/firebase-database-collection.gradle, firebase-database/firebase-database.gradle, firebase-datatransport/firebase-datatransport.gradle, firebase-firestore/firebase-firestore.gradle, firebase-functions/firebase-functions.gradle, firebase-inappmessaging-display/firebase-inappmessaging-display.gradle, transport/transport-runtime/transport-runtime.gradle
* Adds sources.jar artifact for opted in libraries
* Allows libraries to customize their pom.xml contents
=> Artifact publishing capability improvements.

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
Without this change, these tests cause a:
"junit.framework.AssertionFailedError: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f030000 "
error.
=> Alter a few tests to fix them within google3

root-project.gradle
See [Retrolambda Changelog](https://github.com/evant/gradle-retrolambda/blob/master/CHANGELOG.md#371)
=> Update Retrolambda to support Gradle 5

firebase-database/src/androidTest/java/com/google/firebase/database/IntegrationTestHelpers.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java, firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
* update comments for API doc as well
=> Remove synchronous exception throwing from clearPersistence() 

firebase-firestore/src/test/resources/json/persistence_spec_test.json
This pulls in the the latest version of the Spec tests from firebase-js-sdk
=> Updating spec tests

smoke-tests/src/database/java/com/google/firebase/testing/database/DatabaseTest.java, smoke-tests/src/firestore/java/com/google/firebase/testing/firestore/FirestoreTest.java, smoke-tests/src/main/java/com/google/firebase/testing/common/Tasks2.java, smoke-tests/src/storage/java/com/google/firebase/testing/storage/StorageTest.java
=> Moar Smoke Tests

smoke-tests/build.gradle, smoke-tests/src/combined/java/com/google/firebase/testing/combined/AllTests.java, smoke-tests/src/functions/java/com/google/firebase/testing/functions/FunctionsTest.java
This commit adds two simple smoke tests for Functions.
=> Added smoke tests for Functions.

firebase-database/src/androidTest/java/com/google/firebase/database/InfoTest.java, firebase-storage/src/test/java/com/google/firebase/storage/AdaptiveStreamBufferTest.java, firebase-storage/src/test/java/com/google/firebase/storage/DeleteTest.java, firebase-storage/src/test/java/com/google/firebase/storage/DependencyTest.java, firebase-storage/src/test/java/com/google/firebase/storage/DownloadTest.java, firebase-storage/src/test/java/com/google/firebase/storage/ListTest.java, firebase-storage/src/test/java/com/google/firebase/storage/MetadataTest.java, firebase-storage/src/test/java/com/google/firebase/storage/PathingTest.java, firebase-storage/src/test/java/com/google/firebase/storage/StorageReferenceTest.java, firebase-storage/src/test/java/com/google/firebase/storage/StreamProgressWrapperTest.java, firebase-storage/src/test/java/com/google/firebase/storage/UploadTest.java
Manual port since we don't have Copybara set up yet.
https://critique.corp.google.com/#review/250550507
=> Storage: Port test changes from cr/250550507

firebase-storage/src/main/java/com/google/firebase/storage/StorageTaskScheduler.java
This triggers an ErrorProne check Google3.
=> Storage Copybara: SuppressWarnings("ThreadPriorityCheck")

firebase-storage/src/testUtil/java/com/google/firebase/storage/TestCommandHelper.java
go/errorprone/bugpattern/ThreeLetterTimeZoneID
=> Storage Copybara: ThreeLetterTimeZoneID

firebase-storage/src/testUtil/java/com/google/firebase/storage/TestDownloadHelper.java
Sorry - another one. 51% chance this is the last.
=> Storage: Fix Preconditions checks in tests

fiamui-app/fiamui-app.gradle, firebase-common/firebase-common.gradle, firebase-common/gradle.properties, firebase-database-collection/firebase-database-collection.gradle, firebase-database-collection/gradle.properties, firebase-database/firebase-database.gradle, firebase-database/gradle.properties, firebase-datatransport/gradle.properties, firebase-firestore/firebase-firestore.gradle, firebase-firestore/gradle.properties, firebase-firestore/ktx/ktx.gradle, firebase-functions/firebase-functions.gradle, firebase-functions/gradle.properties, firebase-functions/ktx/ktx.gradle, firebase-inappmessaging-display/firebase-inappmessaging-display.gradle, firebase-inappmessaging-display/gradle.properties, firebase-storage/firebase-storage.gradle, firebase-storage/gradle.properties, firebase-storage/test-app/test-app.gradle, protolite-well-known-types/gradle.properties, tools/measurement/apksize/src/firestore/firestore.gradle, transport/transport-api/gradle.properties, transport/transport-backend-cct/gradle.properties, transport/transport-runtime/gradle.properties
Additionally configure sources.jar for SDKs.
=> Update deps to post-androidx gms versions.

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/publish/Publisher.groovy, firebase-firestore/gradle.properties
Additionally fix pom filter to exclude multidex from deps.
=> Bump firestore version for release

firebase-abt/gradle.properties, firebase-remote-config/gradle.properties
Versions are out of date with latest release.
=> Update Remote Config and AB Testing versions

firebase-abt/firebase-abt.gradle
AB Testing does not have device tests.
=> Disable FTL for AB Testing

firebase-functions/firebase-functions.gradle, firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.java, firebase-functions/src/main/java/com/google/firebase/functions/HttpsCallableReference.java, firebase-functions/src/main/java/com/google/firebase/functions/HttpsCallableResult.java
They will be re-applied upon the coordinated breaking change release.
=> Undo functions nullability annotations.

firebase-database/CHANGELOG.md, firebase-database/src/main/java/com/google/firebase/database/FirebaseDatabase.java
Fixes https://github.com/firebase/firebase-android-sdk/issues/372
=> Report the correct version for the RTDB

transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/Destination.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportRuntime.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/backends/BackendRequest.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/AlarmManagerScheduler.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/AlarmManagerSchedulerBroadcastReceiver.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoScheduler.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoSchedulerService.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/Uploader.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/AlarmManagerSchedulerTest.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoSchedulerTest.java
- We introduce the `Destination` API.
- Extras are wired all the way through to the backends.
- Updated relevant tests
=> Apis to wire in extras

firebase-storage/src/main/java/com/google/firebase/storage/ListResult.java, firebase-storage/src/main/java/com/google/firebase/storage/StorageReference.java
=> Backport Javadoc Changes from cr/257434818

.idea/runConfigurations/Firestore_Integration_Tests__Firestore_Emulator_.xml, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/FieldFilter.java
From https://github.com/firebase/firebase-ios-sdk/pull/2670
=>  Port null/NaN validation text from iOS

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigStorageClient.java
Don't use try-with-resources instead explicity close it
=> Replace try-with-resources with try and finally so that we don't have desugaring issues

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigStorageClient.java
=> fix resource leak

firebase-firestore/CHANGELOG.md
This change actually missed the release train for 20.2.0, so it will be in the next release.
=> Move the fix for #155 to unreleased

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/UserData.java
=> Disallow empty document fields

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/TransactionTest.java
Context: [b/138139044](https://buganizer.corp.google.com/issues/138139044)
=> Fix flaky Transaction test

firebase-firestore/src/test/resources/json/limit_spec_test.json
Ports https://github.com/firebase/firebase-js-sdk/pull/2050
=> Add spec test for limit query initialization

firebase-firestore/src/test/resources/json/limit_spec_test.json
https://github.com/firebase/firebase-js-sdk/pull/2051
=> Import spec tests

firebase-functions/firebase-functions.gradle
Seems like we did not merge this back from the M47 release branch.
=> Bumping auth interop 

firebase-firestore/api.txt
Used ./gradlew :firebase-firestore:generateApiTxtFile.
These methods are scheduled to become public in the next release.
=> Update firebase-firestore/api.txt based on recent changes

firebase-firestore/src/test/java/com/google/firebase/firestore/util/ThrottledForwardingExecutorTest.java
Fixes https://sponge.corp.google.com/target?id=45f95096-0542-4506-87d1-4a7725d601a8&target=//third_party/firebase/android/firebase_firestore/tests/robolectric_tests:firestore.util.ThrottledForwardingExecutorTest
=> Add RunWith to ThrottledForwardingExecutorTest

firebase-common/src/main/java/com/google/firebase/heartbeatinfo/DefaultHeartBeatInfo.java, firebase-common/src/main/java/com/google/firebase/heartbeatinfo/HeartBeatInfo.java
use android x annotations instead of jetbrain annotations
=> use android x annotations

firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexFreeQueryEngine.java
This PR adds logging for which query mode we used for query execution.
=> Add logging for query mode

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
Fixes an internal integration test failure, internal reference: b/140307854
=> Setup FirebaseApp with fake APP_ID to fix test failure.

smoke-tests/build.gradle, smoke-tests/src/combined/java/com/google/firebase/testing/combined/AllTests.java, smoke-tests/src/combined/java/com/google/firebase/testing/dynamiclinks/DynamicLinksTest.java
This commit adds two dynamic links tests.
=> [Smoke-tests] Add Dynamic Links to smoke tests.

firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java, firebase-firestore/src/test/resources/json/collection_spec_test.json, firebase-firestore/src/test/resources/json/existence_filter_spec_test.json, firebase-firestore/src/test/resources/json/limbo_spec_test.json, firebase-firestore/src/test/resources/json/limit_spec_test.json, firebase-firestore/src/test/resources/json/listen_spec_test.json, firebase-firestore/src/test/resources/json/offline_spec_test.json, firebase-firestore/src/test/resources/json/orderby_spec_test.json, firebase-firestore/src/test/resources/json/persistence_spec_test.json, firebase-firestore/src/test/resources/json/query_spec_test.json, firebase-firestore/src/test/resources/json/remote_store_spec_test.json, firebase-firestore/src/test/resources/json/resume_token_spec_test.json, firebase-firestore/src/test/resources/json/write_spec_test.json
Porting from [web](https://github.com/firebase/firebase-js-sdk/pull/2178).
=> Rename spec test functions

firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
Ports: https://github.com/firebase/firebase-js-sdk/pull/2179/files
=> Add Query to Target ID Map

firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
Backporting validation spec test functions from [iOS](https://github.com/firebase/firebase-ios-sdk/pull/3895).
=> Backport spec test function renaming

transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctBackendFactory.java
=> Change lflg URL.

firebase-firestore/src/test/resources/json/limbo_spec_test.json
Port of https://github.com/firebase/firebase-js-sdk/pull/2205
=> Add test for NoDocument assert

root-project.gradle
Exclude test class files which were incorrectly included in the calculation.
=> Fix coverage calculation.

firebase-functions/src/main/java/com/google/firebase/functions/Serializer.java
`k` is a String variable, so `(k instanceof String)` can only be false if `k` is `null`. Updated the condition to reflect this.
=> Update Serializer condition to the check for null.

firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/ProtoStorageClient.java
this addresses part of the confusion from #881
=> Change fiam warning log to info log

firebase-inappmessaging-display/firebase-inappmessaging-display.gradle, firebase-inappmessaging/firebase-inappmessaging.gradle, transport/transport-runtime/transport-runtime.gradle
Update FIAM version of Dagger to address #712
=> Update FIAM version of Dagger to address #712

.opensource/project.json, README.md, docs/README.md, docs/ktx/database.md
**Should only be merged after the first release of firebase-database-ktx**
=> docs: add docs for firebase-database-ktx

firebase-config/src/proto/com/google/android/gms/config/proto/client_metrics.proto
Added EVENT_TYPE_UNSPECIFIED to EventType enum and set as default value for event_type field.
=> Added unspecified value to EventType enum and set as default.

docs/ktx/firestore.md, firebase-firestore/api.txt, firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/Firestore.kt, firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/FirestoreTests.kt, firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestoreSettings.java
Add a Kotlin Extension for building `FirebaseFirestoreSettings` objects.
=> feat: add FirebaseFirestoreSettings builder ktx

firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/internal/FiamWindowManager.java
Attempt to fix #379 by changing window visibility check
=> Change FIAM window manager visibility check

transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CCTDestination.java, transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java, transport/transport-backend-cct/src/main/proto/google/cct/google_cct.proto, transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctDestinationTest.java, transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctTransportBackendTest.java, transport/transport-backend-cct/transport-backend-cct.gradle
=> Add JSON payload support to CCT destination.

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java, firebase-firestore/src/main/java/com/google/firebase/firestore/UserDataConverter.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/UserData.java
Porting from [web](https://github.com/firebase/firebase-js-sdk/pull/2346).
=> Allow querying for arrays in IN queries

transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/SchedulerConfig.java
It uses reflection and hence not proguard friendly(b/143637813).
=> Remove use of EnumSet.

firebase-installations/src/androidTest/java/com/google/firebase/installations/FisAndroidTestConstants.java
=> touch file

firebase-database/src/androidTest/java/com/google/firebase/database/DataTest.java, firebase-database/src/main/java/com/google/firebase/database/ServerValue.java, firebase-database/src/main/java/com/google/firebase/database/core/Repo.java, firebase-database/src/main/java/com/google/firebase/database/core/ServerValues.java, firebase-database/src/main/java/com/google/firebase/database/core/SyncTree.java
* New (currently) package protected method for serverside increments
* Updated ServerValues.resolveFoo to take an existing snapshot
* Added integration tests for new behavior
NOTE: I think I need help undertsanding why I see an integration failure. If my new
tests run then other tests (In EventTest an KeepSyncedTest) fail. It's not clear if
this is because I temporarily go offline or if it's because I've filled the server
queue with an operation the database doesn't yet support and the client cannot handle
the error.
=> Add ServerValue.increment() methods.

encoders/firebase-encoders-processor/firebase-encoders-processor.gradle, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/EncodableProcessor.java, encoders/firebase-encoders-processor/src/test/java/com/google/firebase/encoders/processor/EncodableProcessorTest.java
This is achieved by registering the generated auto value class in
addition to the abstract class.
=> Add AutoValue support.

encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/EncodableProcessor.java, encoders/firebase-encoders-processor/src/test/java/com/google/firebase/encoders/processor/EncodableProcessorTest.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedTypeWithListEncoder.java
* Encoders for members of Collection<T> and Map<T,U> were not generated.
* Enum encoders were generated but they should not be.
=> Fix bugs in encoder codegen

firebase-crashlytics-ndk/CHANGELOG.md, firebase-crashlytics/CHANGELOG.md
=> Update Crashlytics and Crashlytics NDK changelogs

firebase-abt/src/main/java/com/google/firebase/abt/AbtExperimentInfo.java, firebase-abt/src/main/java/com/google/firebase/abt/FirebaseABTesting.java, firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/AbtIntegrationHelper.java
This is to help keep RC proto dep free
=> Remove proto dep from ABT. Make the POJO public and use that instead

firebase-crashlytics/firebase-crashlytics.gradle, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransformTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransform.java
Uses firebase-encoders-json DataEncoder for serialization and
uses JsonReader manually for deserialization, as there is not yet
a firebase-decoders-json.
=> Add CrashlyticsReport JSON de/serialization

.opensource/project.json, docs/README.md, docs/ktx/dynamic-links.md
**PS:** Only merge after firebase-dynamic-links-ktx is released
=> docs: add docs for dynamic-links-ktx

firebase-installations/src/test/java/com/google/firebase/installations/FirebaseInstallationsTest.java
=> XXS: Fixed test comment (No logic change intended)

transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java, transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/ClientInfo.java, transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/internal/LogRequestTest.java, transport/transport-backend-cct/src/test/proto/google/cct/google_cct.proto
Also removes the previous client type of ANDROID (value: 4)
=> Change datatransport CLIENT_TYPE to ANDROID_FIREBASE

firebase-installations/FCM_TOKENS_CHANGE.md
Extended document "FCM Tokens may change." by addressing the possible issue of end-users receiving duplicated FCM push notifications due to duplicated FCM registrations.
=> Added section "Duplicate FCM push notifications"

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsLifecycleEvents.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
Pass timestamp directly for events that need it
=> Remove time provider from reporting coordinator

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/SettingsJsonParserTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/SettingsV3JsonTransformTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsV3JsonTransform.java
New DNS to facilitate backend migration
=> Crashlytics update Update endpoint from api. => update.

firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
=> Removed erroneous line (missing semicolon).

firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
Fixes formatting for changes in #1301
=> Fix formatting for FIS NPE changes

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/core/CrashlyticsControllerTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/FileStore.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/FileStoreImpl.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/send/DataTransportCrashlyticsReportSender.java
- Also remove obsolete FileStoreImpl constructor
=> Remove file create in coordinator constructor

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/core/CrashlyticsControllerTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/core/CrashlyticsCoreTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/core/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/core/CrashlyticsCore.java
Collapse finalizing previous native report into existing session
finalize operation.
=> Simplify finalizing native reports

firebase-installations-interop/gradle.properties, firebase-installations/gradle.properties
To installations and installations-interop
=> Add missing latestReleasedVersion property.

firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/ApiClient.java, firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/InAppMessageStreamManager.java
Additionally, cleanup the way Installation IDs are handled
=> Remove ABT Experiment Cleanup from FIAM fetch path

firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
Revising some minor areas for style and format per b/150147918.
Thanks!
=> Making minor changes to Javadoc text.

firebase-firestore/src/main/java/com/google/firebase/firestore/remote/GrpcCallProvider.java
=> Call onConnectivityStateChange from async queue.

firebase-installations/REQUIRED_FIREBASE_OPTIONS_ANDROID.md
Created public documentation that can be linked to from error messages thrown if client-side lenient format checks of Firebase options fail.
* b/153238875
* https://docs.google.com/document/d/1iuA_LsX650KVlrwS6bN-eVUUQIv_cgKmqMxI7lMGFao/
=> Created REQUIRED_FIREBASE_OPTIONS_ANDROID.md

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/NumericTransformsTest.java
Ports tests from https://github.com/firebase/firebase-js-sdk/pull/3048/files
=> Port Test for increment with merge

firebase-firestore/src/main/java/com/google/firebase/firestore/remote/AbstractStream.java
=> Warn when stream is closing due to error, not debug.

firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
Porting from [iOS](https://github.com/firebase/firebase-ios-sdk/pull/5632).
=> Make removeSnapshotsInSyncListener run on AQ

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
This allows for appropriate handling of data collection flags as
well as enabling the ability to trigger app exception events for
any fatal event (Java or native).
=> Send app_exception events based on a marker file

encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/getters/GetterFactory.java
Reverts firebase/firebase-android-sdk#1627
=> Revert "Restore Java 8 support in encoders lib"

encoders/firebase-encoders-json/api.txt, encoders/firebase-encoders-json/src/json/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContext.java, encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/FieldDescriptor.java, encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/ObjectEncoderContext.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/EncodableProcessor.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/annotations/AnnotationBuilder.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/annotations/ToStringMethod.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/getters/AnnotationDescriptor.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/getters/AnnotationProperty.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/getters/Getter.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/getters/GetterFactory.java, encoders/firebase-encoders-processor/src/test/java/com/google/firebase/encoders/processor/EncodableProcessorTest.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedGenericsEncoder.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedMyClassEncoderWithExtraProperty.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedRecursiveGenericEncoder.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedSimpleClassEncoder.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedTypeWithListEncoder.java
This code was reverted from master and is now going to a dedicated feature branch.
=> Add `FieldDescriptor` support to DataEncoder.

encoders/firebase-decoders-json/firebase-decoders-json.gradle, encoders/firebase-decoders-json/src/json/java/com/google/firebase/decoders/json/CreationContextImpl.java, encoders/firebase-decoders-json/src/json/java/com/google/firebase/decoders/json/JsonDataDecoderBuilderContext.java, encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/json/JsonDataDecoderBuilderContextTest.java
- [] will be decoded as empty array.
=> support decode array token

firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
Reverts firebase/firebase-android-sdk#1619
=> Revert "Move Preconditions check to FirebaseInstallations constructor."

encoders/firebase-decoders-json/api.txt, encoders/firebase-decoders-json/src/json/java/com/google/firebase/decoders/json/JsonDataDecoderBuilderContext.java, encoders/firebase-decoders-json/src/json/java/com/google/firebase/decoders/json/ObjectDecoderContextImpl.java, encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/ObjectDecoderContext.java, encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/json/JsonDataDecoderBuilderContextTest.java
https://github.com/firebase/firebase-android-sdk/issues/1654
=> support inline decode

README.md, docs/README.md, docs/ktx/crashlytics.md
Adding crashlytics-ktx docs to firebaseopensource.com
Should be merged once the first version of `crashlytics-ktx` is released.
=> docs(crashlytics-ktx): add crashlytics-ktx to FOSDC

firebase-common/api.txt, firebase-common/gradle.properties, firebase-common/src/main/java/com/google/firebase/FirebaseApp.java, firebase-common/src/main/java/com/google/firebase/emulators/EmulatedServiceSettings.java, firebase-common/src/main/java/com/google/firebase/emulators/EmulatorSettings.java, firebase-common/src/main/java/com/google/firebase/emulators/FirebaseEmulator.java, firebase-database/CHANGELOG.md, firebase-database/api.txt, firebase-database/gradle.properties, firebase-database/src/main/java/com/google/firebase/database/FirebaseDatabase.java, firebase-firestore/CHANGELOG.md, firebase-firestore/api.txt, firebase-firestore/gradle.properties, firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java, firebase-functions/api.txt, firebase-functions/gradle.properties, firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.java
Reverts firebase/firebase-android-sdk#1712
=> Revert "Un-hide EmulatorSettings API"

firebase-database/ktx/src/main/kotlin/com/google/firebase/database/ktx/Database.kt, firebase-dynamic-links/ktx/src/main/kotlin/com/google/firebase/dynamiclinks/ktx/FirebaseDynamicLinks.kt, firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/Firestore.kt, firebase-functions/ktx/src/main/kotlin/com/google/firebase/functions/ktx/Functions.kt, firebase-inappmessaging-display/ktx/src/main/kotlin/com/google/firebase/inappmessaging/display/ktx/InAppMessagingDisplay.kt, firebase-inappmessaging/ktx/src/main/kotlin/com/google/firebase/inappmessaging/ktx/InAppMessaging.kt, firebase-storage/ktx/src/main/kotlin/com/google/firebase/storage/ktx/Storage.kt
Comprehensive list obtained by running:
```
for arg in $(./gradlew tasks --all | grep :ktx:ktlintMainSourceSetCheck | awk '{print $1}')
do
./gradlew -q $arg
done
```
=> Fix missing klint errors.

encoders/firebase-encoders-reflective/firebase-encoders-reflective.gradle, encoders/firebase-encoders-reflective/src/main/java/com/google/firebase/encoders/reflective/ReflectiveObjectEncoderProvider.java, encoders/firebase-encoders-reflective/src/test/java/com/google/firebase/encoders/reflective/ReflectiveObjectEncoderTest.java
The change also adds support for `@ExtraProperty`s and `@Ignore`.
=> Migrate reflective encoder to `FieldDescriptor`.

firebase-firestore/src/proto/google/firestore/v1/query.proto
Also updating comments to match updated comments on g3.
=> Add protos for != queries

firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
=> Handling AssertionError thrown by JsonReader causing Play Games app-crashes.

firebase-database/src/main/java/com/google/firebase/database/FirebaseDatabase.java, firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java, firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.java
Addressing @rachelsaunders comments on http://cl/328381521
=> Address reference doc review comments

firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/FirestoreChannel.java
See https://github.com/firebase/firebase-ios-sdk/pull/6264 for the equivalent change in the iOS repo.
=> Make the language reported via headers configurable

firebase-ml-modeldownloader/api.txt, firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/DownloadType.java, firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloader.java, firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloaderTest.java
As approved during API review.
=> Add FirebaseModelDownloader public API Headers

transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java, transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/AndroidClientInfo.java, transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctTransportBackendTest.java, transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/internal/LogRequestTest.java
=> Add support for Application build field in CCT Transport Backend.

firebase-config/bandwagoner/bandwagoner.gradle, firebase-config/bandwagoner/src/main/res/layout/api_fragment.xml
Update the device and use `match_parent` so the buttons are within the view in Espresso tests.
=> Update Test Lab device for RC Bandwagoner.

encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContext.java, encoders/firebase-encoders/api.txt, encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/ValueEncoderContext.java
Important for future protobuf support.
=> Add float support to ValueEncoderContext.

firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplay.java
=> Catch null on queryIntentServices to fix NPE

firebase-firestore/src/proto/google/firebase/firestore/proto/bundle.proto
This is based on https://github.com/googleapis/nodejs-firestore/blob/9cd53be4a7f37b8d1f61a1b8567fa8b7ccce0e3e/dev/protos/firestore/bundle.proto
=> Add Bundle Proto

firebase-firestore/src/test/resources/json/recovery_spec_test.json
This file seems to never have been added to the Android repo (it shows up as a warning in git). The tests themselves are ignored and shouldn't run.
=> Add missing recovery_spec_test.json

firebase-ml-modeldownloader/api.txt, firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/CustomModelDownloadConditions.java, firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloader.java, firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloaderTest.java
Can be used to track download progress.
=> Add public getModelDownloadId method 

firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/Target.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/Bundle.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/BundleCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/BundleMetadata.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/BundledDocumentMetadata.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/BundledQuery.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryBundleCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryPersistence.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/NamedQuery.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/Persistence.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteBundleCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLitePersistence.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/BundleCacheTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalSerializerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/MemoryBundleCacheTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLBundleCacheTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteBundleCacheTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
This adds the Bundle Cache + Schema changes + Tests (port from Web).
=> Add BundleCache

firebase-firestore/src/main/java/com/google/firebase/firestore/local/BundleCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/BundleMetadata.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/BundleSerializer.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryBundleCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteBundleCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/BundleCacheTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/BundleSerializerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalSerializerTest.java
This adds a JSON-to-Protobuf serializer that is used for Bundles. It used org.json for JSON decoding, which is part of the Android SDK (API Level 1).
The Value-decoding tests are inspired by the existing tests in RemoteSerializerTest.
=> JSON Decoder

firebase-common/src/main/java/com/google/firebase/storage/internal/ActivityLifecycleListener.java, firebase-firestore/src/main/java/com/google/firebase/firestore/LoadBundleTask.java, firebase-storage/src/main/java/com/google/firebase/storage/TaskListenerImpl.java
This removes the code change to firebase-common
=> Use ActivityLifecycleObserver for Firestore

firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java, firebase-firestore/src/test/resources/json/bundle_spec_test.json, firebase-firestore/src/test/resources/json/collection_spec_test.json, firebase-firestore/src/test/resources/json/existence_filter_spec_test.json, firebase-firestore/src/test/resources/json/limbo_spec_test.json, firebase-firestore/src/test/resources/json/limit_spec_test.json, firebase-firestore/src/test/resources/json/listen_spec_test.json, firebase-firestore/src/test/resources/json/offline_spec_test.json, firebase-firestore/src/test/resources/json/orderby_spec_test.json, firebase-firestore/src/test/resources/json/persistence_spec_test.json, firebase-firestore/src/test/resources/json/query_spec_test.json, firebase-firestore/src/test/resources/json/recovery_spec_test.json, firebase-firestore/src/test/resources/json/remote_store_spec_test.json, firebase-firestore/src/test/resources/json/resume_token_spec_test.json, firebase-firestore/src/test/resources/json/write_spec_test.json
This updates the Android Spec test runner to bring it in line with the Web runner. It ports the spec test changes from https://github.com/firebase/firebase-js-sdk/commit/6dffdf2eb1323ec9047af4ed78302a68f7dacce3#diff-5bfff912a6c5cd89226fd82cbec049b4a6d73169241bc4be3c43a809b1c20683R79
=> Update Spec tests with Bundle changes

firebase-perf/dev-app/dev-app.gradle, firebase-perf/e2e-app/e2e-app.gradle
Since we've recently me significant change (migrated source code from private to public repo). This should help us distinguish events on the backend.
=> Updating versions of our `dev-app` and `e2e-app` 

encoders/protoc-gen-firebase-encoders/protoc-gen-firebase-encoders.gradle, encoders/protoc-gen-firebase-encoders/src/main/kotlin/com/google/firebase/encoders/proto/codegen/Configuration.kt, encoders/protoc-gen-firebase-encoders/src/main/kotlin/com/google/firebase/encoders/proto/codegen/Main.kt, encoders/protoc-gen-firebase-encoders/src/main/kotlin/com/google/firebase/encoders/proto/codegen/Types.kt, encoders/protoc-gen-firebase-encoders/src/main/proto/config.proto, encoders/protoc-gen-firebase-encoders/src/test/kotlin/com/google/firebase/encoders/proto/codegen/ConfigTests.kt, encoders/protoc-gen-firebase-encoders/src/test/kotlin/com/google/firebase/encoders/proto/codegen/DriverTests.kt, encoders/protoc-gen-firebase-encoders/tests/code-gen-cfg.txtpb, encoders/protoc-gen-firebase-encoders/tests/tests.gradle
The intent is to have users of the plugin specify the config file via
plugin options.
=> Add CodeGenConfig to be used by the protoc plugin.

encoders/protoc-gen-firebase-encoders/protoc-gen-firebase-encoders.gradle, encoders/protoc-gen-firebase-encoders/src/main/kotlin/com/google/firebase/encoders/proto/codegen/CodeGenerator.kt, encoders/protoc-gen-firebase-encoders/src/main/kotlin/com/google/firebase/encoders/proto/codegen/Parsing.kt, encoders/protoc-gen-firebase-encoders/src/main/kotlin/com/google/firebase/encoders/proto/codegen/Types.kt, encoders/protoc-gen-firebase-encoders/src/test/kotlin/com/google/firebase/encoders/proto/codegen/ParsingTests.kt, encoders/protoc-gen-firebase-encoders/src/test/kotlin/com/google/firebase/encoders/proto/codegen/TypeTests.kt, encoders/protoc-gen-firebase-encoders/src/test/proto/cycle.proto, encoders/protoc-gen-firebase-encoders/src/test/proto/extensions.proto, encoders/protoc-gen-firebase-encoders/src/test/proto/simple.proto, encoders/protoc-gen-firebase-encoders/src/test/proto/types.proto, encoders/protoc-gen-firebase-encoders/tests/code-gen-cfg.txtpb, encoders/protoc-gen-firebase-encoders/tests/src/main/proto/test.proto
The parser processes input `FileDescriptorProto`s from protoc into a
type graph that is later fed into `CodeGenerator`.
=> Implement message parsing.

firebase-database/src/androidTest/java/com/google/firebase/database/DataTest.java, firebase-database/src/androidTest/java/com/google/firebase/database/EventTest.java, firebase-database/src/androidTest/java/com/google/firebase/database/FirebaseDatabaseTest.java, firebase-database/src/androidTest/java/com/google/firebase/database/InfoTest.java, firebase-database/src/androidTest/java/com/google/firebase/database/IntegrationTestHelpers.java, firebase-database/src/androidTest/java/com/google/firebase/database/OrderByTest.java, firebase-database/src/androidTest/java/com/google/firebase/database/OrderTest.java, firebase-database/src/androidTest/java/com/google/firebase/database/QueryTest.java, firebase-database/src/androidTest/java/com/google/firebase/database/RealtimeTest.java, firebase-database/src/androidTest/java/com/google/firebase/database/TransactionTest.java, firebase-database/src/main/java/com/google/firebase/database/core/RepoManager.java
=> Maybe Deflake RTDB tests

firebase-database/CHANGELOG.md, firebase-database/src/main/java/com/google/firebase/database/connection/PersistentConnectionImpl.java
Fixes https://github.com/firebase/firebase-android-sdk/issues/2385
This seems to only affect Android.
=> Don't go idle if there are outstanding gets()

alternative-settings.gradle, buildSrc/build.gradle, buildSrc/devsite_transform.sh, buildSrc/gms_transform.sh
Plus some fixes to the gradle settings file.
=> Add missing transformation file.

firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
=> Don't use Apache Ant in tests

firebase-perf/src/main/java/com/google/firebase/perf/gauges/GaugeModule.java, firebase-perf/src/main/java/com/google/firebase/perf/injection/components/FirebasePerformanceComponent.java, firebase-perf/src/main/java/com/google/firebase/perf/injection/modules/FirebasePerformanceModule.java, firebase-perf/src/main/java/com/google/firebase/perf/injection/modules/GaugeModule.java, firebase-perf/src/main/java/com/google/firebase/perf/internal/GaugeManager.java, firebase-perf/src/main/java/com/google/firebase/perf/internal/GaugeMetadataManager.java, firebase-perf/src/test/java/com/google/firebase/perf/internal/GaugeManagerTest.java, firebase-perf/src/test/java/com/google/firebase/perf/internal/GaugeMetadataManagerTest.java
Making `GaugeMetadataManager` class DI compatible.
=> Making GaugeMetadataManager class DI compatible.

firebase-database/src/main/java/com/google/firebase/database/Query.java
=> Update RTDB docs

firebase-storage/CHANGELOG.md, firebase-storage/src/main/java/com/google/firebase/storage/FileDownloadTask.java, firebase-storage/src/main/java/com/google/firebase/storage/StreamDownloadTask.java, firebase-storage/src/test/resources/activitylogs/emptyDownload_task.txt, firebase-storage/src/test/resources/activitylogs/emptyStreamDownload_background.txt, firebase-storage/src/test/resources/activitylogs/emptyStreamDownload_task.txt, firebase-storage/src/test/resources/activitylogs/fileDownloadCanceled_task.txt, firebase-storage/src/test/resources/activitylogs/fileDownloadResume_task.txt, firebase-storage/src/test/resources/activitylogs/fileDownload_task.txt, firebase-storage/src/test/resources/activitylogs/streamDownloadCanceled_task.txt, firebase-storage/src/test/resources/activitylogs/streamDownloadWithETagChange_background.txt, firebase-storage/src/test/resources/activitylogs/streamDownloadWithETagChange_task.txt, firebase-storage/src/test/resources/activitylogs/streamDownloadWithResumeAndCancel_background.txt, firebase-storage/src/test/resources/activitylogs/streamDownloadWithResumeAndCancel_task.txt, firebase-storage/src/test/resources/activitylogs/streamDownloadWithResume_background.txt, firebase-storage/src/test/resources/activitylogs/streamDownloadWithResume_task.txt, firebase-storage/src/test/resources/activitylogs/streamDownload_background.txt, firebase-storage/src/test/resources/activitylogs/streamDownload_task.txt, firebase-storage/src/testUtil/java/com/google/firebase/storage/TestDownloadHelper.java
Fixes https://github.com/firebase/firebase-android-sdk/issues/2288
=> Report the correct number of totalBytes for resumed downloads

tools/lint/src/main/kotlin/Annotations.kt, tools/lint/src/main/kotlin/DeferredApiDetector.kt, tools/lint/src/main/kotlin/ProviderAssignmentDetector.kt, tools/lint/src/test/kotlin/DeferredApiDetectorTests.kt, tools/lint/src/test/kotlin/ProviderAssignmentDetectorTests.kt
=> Allow provider assignment from `@DeferredApi` methods.

firebase-ml-modeldownloader/ktx/api.txt, firebase-ml-modeldownloader/ktx/gradle.properties, firebase-ml-modeldownloader/ktx/ktx.gradle, firebase-ml-modeldownloader/ktx/src/main/AndroidManifest.xml, firebase-ml-modeldownloader/ktx/src/main/kotlin/com/google/firebase/ml/modeldownloader/ktx/ModelDownloader.kt, firebase-ml-modeldownloader/ktx/src/test/kotlin/com/google/firebase/ml/modeldownloader/ktx/ModelDownloaderTests.kt, subprojects.cfg
This PR should create the Kotlin Extension Functions for the recently created `firebase-ml-modeldownloader` module.
```kotlin
// alternative to FirebaseModelDownloader.getInstance()
Firebase.modelDownloader 
// alternative to FirebaseModelDownloader.getInstance(FirebaseApp)
Firebase.modelDownloader(firebaseApp) 
// DSL Builder for CustomModelDownloadConditions
val customModelDownloadConditions = customModelDownloadConditions {
requireCharging()
requireWifi()
}
```
This PR should also create destructuring declarations for the `CustomModel` class. This allows us to replace:
```kotlin
Firebase.modelDownloader.getModel( ... )
.addOnSuccessListener { customModel ->
val modelFile = customModel.file
val fileSize = customModel.size
doSomething(modelFile, fileSize)
}
```
with:
```kotlin …
```
=> implement firebase-ml-modeldownloader-ktx

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
=> Cleanup Crashlytics javadocs formatting

ci/fireci/fireci/uploader.py, ci/fireci/fireciplugins/macrobenchmark.py, ci/fireci/setup.py
- change to measure percentiles instead of mean/median/stdev
=> Upload macrobenchmark results to the metric service.

firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerformance.java, firebase-perf/src/main/java/com/google/firebase/perf/metrics/NetworkRequestMetricBuilder.java, firebase-perf/src/main/java/com/google/firebase/perf/metrics/Trace.java, firebase-perf/src/main/java/com/google/firebase/perf/metrics/validator/FirebasePerfNetworkValidator.java, firebase-perf/src/main/java/com/google/firebase/perf/util/URLAllowlist.java
Summary
- The main purpose for this PR is to make trace, network, and gauge logging messages more obvious in the logcat ([Example in Step 4.4](https://firebase.google.com/docs/perf-mon/get-started-android#view-log-messages)).
- Update some logging messages with proper logging levels.
=> Update logging message with proper logging levels.

transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/ClientAnalyticsStore.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/ClientHealthMetricsStore.java
Client Analytics Store interface will be used as  a Persistent Layer
It is responsible for storing, updating, and retrieving client analytics data.
=> Defined Client Analytics Store interface.

transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/backends/BackendResponse.java
Add another network response status: INVALID_PAYLOAD.
- we will send this status back whenever the server responds with a code 400
=> Add INVALID_PAYLOAD into BackendResponse

transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/Uploader.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/UploaderTest.java
`recordLogEventDropped` for the reason of INVALID_PAYLOAD
=> Record logEvent dropped due to invalid payload

transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/Uploader.java
Wrap `recordLogEventDropped` into critical section to avoid race condition.
=> Wrap recordLogEventDropped into critical section

firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionRegistrar.java
- Move registration of LifecycleActivityCallbacks to registrar
- Add new constructor to FirebaseAppDistribution
=> FAD register LifecycleActivityCallbacks in Registrar 

firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateState.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateTaskImpl.java, firebase-app-distribution/src/main/res/values/strings.xml, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java
- Add implementation for updateApp for AABs 
- Create UpdateTaskImpl class to return in updateApp 
- Add unit tests
=> FAD Implement updateApp MVP for AABs

firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/Constants.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-app-distribution/src/main/res/values/strings.xml, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java
- Implement updateToLatestRelease 
- Add method to set exception for updateApp
=> FAD Implement updateToLatestRelease MVP 

firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
See go/firestore-composite-index
=> Add schema for field indexing

firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java
- Add release notes to update dialog if available 
- add tests for when release notes are empty 
- nit: change to more accurate test names for signInTester
=> FAD Add release notes to update dialog

firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateAppClient.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/UpdateAppClientTest.java
- create client class for updateApp logic 
- move relevant tests to UpdateAppClientTest
- add mockUpdateAppClient to FADtest
=> FAD refactor update logic into UpdateAppClient

firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/AppDistributionRelease.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/OnProgressListener.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateAppClient.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateProgress.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateStatus.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateTask.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateTaskImpl.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/UpdateAppClientTest.java
* Change UpdateToLatestRelease and UpdateApp to return Task<Void>
* Change String getBuildVersion() to long getVersionCode()
* Remove terminal states from UpdateStatus
* Add additional methods and support for OnProgressListeners in UpdateTaskImpl
=> Update API and add methods to UpdateTaskImpl

firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateApkClient.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateAppClient.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateTask.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateTaskImpl.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/UpdateApkClientTest.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/UpdateAppClientTest.java
- remove task completion source for updateApp
- refactor UpdateTaskImpl to have task and completion source created in constructor and implement setResult and setException
=> FAD refactor UpdateApp and UpdateTaskImpl

firebase-firestore/firebase-firestore.gradle, firebase-firestore/src/main/java/com/google/firebase/firestore/index/FirestoreIndexValueWriter.java, firebase-firestore/src/main/java/com/google/firebase/firestore/index/OrderedCodeReader.java, firebase-firestore/src/main/java/com/google/firebase/firestore/index/OrderedCodeWriter.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/FieldIndex.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/TargetIndexMatcher.java
This PR addresses comments from cl/392912920
=> Fix comments from Internal review

firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionNotificationsManager.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionTesterApiClient.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateApkClient.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateProgress.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateStatus.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateTaskImpl.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java
FAD Adding in changes asked by the API council.
=> Fad api changes

firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/CheckForNewReleaseClient.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionTesterApiClient.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/ReleaseIdentifierStorage.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateApkClient.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateAppClient.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/CheckForNewReleaseClientTest.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTesterApiClientTest.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/UpdateAppClientTest.java
Renaming a lot of methods, files, and variables to be more in line with other changes.
=> FAD Changing names to be more consistent with API council change request

appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/NetworkClient.java, appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/NetworkClientTest.java
Add `X-Android-Package` and `X-Android-Cert` headers to network calls.
[Google-internal bug: b/199533228]
=> Add X-Android-Package and X-Android-Cert headers.

firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionRegistrar.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/TesterSignInClient.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionLifecycleNotifier.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/TesterSignInClientTest.java
Adds a centralized, singleton class for activity lifecycle management.
This is the first PR in a series to migrate clients to the new lifecycle management design.
=> Add central place for activity lifecycle management; refactor signin

appcheck/firebase-appcheck-debug/src/main/java/com/google/firebase/appcheck/debug/internal/DebugAppCheckProvider.java, appcheck/firebase-appcheck-debug/src/test/java/com/google/firebase/appcheck/debug/internal/DebugAppCheckProviderTest.java, appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/internal/SafetyNetAppCheckProvider.java, appcheck/firebase-appcheck-safetynet/src/test/java/com/google/firebase/appcheck/safetynet/internal/SafetyNetAppCheckProviderTest.java, appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/NetworkClient.java, appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/RetryManager.java, appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/NetworkClientTest.java, appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/RetryManagerTest.java
Implement the App Check token exchange retry strategy described [here](https://docs.google.com/document/d/1cVFNq9Oy7q3GvnClcuFTJMjSXmm6SjsrSIb2CZ5ofX0/edit?usp=sharing&resourcekey=0-IHLxoWaWcYu6JURa5cuVDg).
[Google-internal bug: b/195583020]
=> Implement App Check token exchange retry strategy

firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/InstallApkClient.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateAppClient.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/InstallApkClientTests.java
Refactor InstallAPKClient to use the central lifecycle hooks
=> Refactor InstallApkClient to use the central lifecycle methods

firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/CheckForNewReleaseClient.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/CheckForNewReleaseClientTest.java
Do not prompt for update if the version code is lower than the installed version code
=> Handle lower version code

firebase-app-distribution/firebase-app-distribution.gradle, firebase-app-distribution/ktx/gradle.properties, firebase-app-distribution/ktx/ktx.gradle, firebase-app-distribution/ktx/src/androidTest/AndroidManifest.xml, firebase-app-distribution/ktx/src/androidTest/kotlin/com/google/firebase/app/distribution/ktx/FirebaseAppDistributionTests.kt, firebase-app-distribution/ktx/src/main/AndroidManifest.xml, firebase-app-distribution/ktx/src/main/kotlin/com/google/firebase/app/distribution/ktx/FirebaseAppDistribution.kt, subprojects.cfg
For our Kotlin users we wanted to have a wrapper that made their code look nicer.
=> Adding Kotlin wrapper to java api

firebase-database/src/test/java/com/google/firebase/database/MapperTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/util/MapperTest.java
=> Suppress Unicode warnings

firebase-database/CHANGELOG.md, firebase-database/src/main/java/com/google/firebase/database/connection/PersistentConnectionImpl.java
Fixes https://github.com/firebase/firebase-android-sdk/issues/3074
=> Fix assert in token refresh

firebase-crashlytics-ndk/src/main/jni/crashpad/crashpad_snapshot/Android.mk
Tested on multiple api levels, 32 bit and 64 bit arm devices, and x86 emulator.
=> Pulled in crashpad, and fixed the build.

firebase-common/src/main/java/com/google/firebase/FirebaseApp.java, firebase-common/src/main/java/com/google/firebase/FirebaseOptions.java, firebase-common/src/main/java/com/google/firebase/internal/ObfuscationUtils.java, firebase-common/src/main/java/com/google/firebase/monitoring/ComponentMonitoring.java, firebase-common/src/test/java/com/google/firebase/internal/ObfuscationUtilsTest.java
Additionally add obfuscation info to traces as numbers are vastly
different for obfuscated apps vs unobfuscated.
=> Add more detailed tracing.

firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/CheckForNewReleaseClient.java, firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/UpdateAabClient.java, firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/UpdateApkClient.java, firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/UpdateAabClientTest.java
* Change the name of executors to better describe their purpose
* Add clarifying comments
=> Clean up executors and add clarifying comments

firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
https://github.com/firebase/firebase-android-sdk/pull/3246/files/e86c06902b2da6aaa334d375d5e91a77907b35e3#diff-6015fff2a2587be54a006a54e5cf1b6cdcb8f225e1c6bac2263fcc69243d8da0
=> Simply RemoteEventTests

smoke-tests/build.gradle, smoke-tests/configure.gradle, smoke-tests/gradle.properties, smoke-tests/src/main/java/com/google/firebase/testing/BuildOnlyTest.java
- Upgrade dependency versions
- Replace jcenter with maven central repository
- Revive temporarily disabled Messaging test cases
=> Smoke test maintenance

encoders/firebase-encoders-proto/firebase-encoders-proto.gradle, encoders/firebase-encoders-proto/src/test/java/com/google/firebase/encoders/proto/WithCollectionsTests.java
This method have been added in guava 31, so we are also updating the dependency.
=> Use buildOrThrow instead of build for ImmutableMap.

firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexBackfiller.java
This shows how far the index has advanced.
=> Add Offset logline

firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
Ports new tests from https://github.com/firebase/firebase-js-sdk/pull/6008
=> Backport tests from Web

firebase-perf/CHANGELOG.md
=> Fireperf m112 changelog

appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/FirebaseAppCheckRegistrar.java, appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/FirebaseAppCheckRegistrarTest.java
App check as a heartbeat consumer since the e2e test for the app check backend works with android
=> App Check as a heartbeat Consumer since backend works now

firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/PendingDynamicLinkData.java
Java doc updates as per b/190099349
=> Java doc updates as per b/190099349

smoke-tests/build.gradle, smoke-tests/configure.gradle, smoke-tests/src/main/java/com/google/firebase/testing/BuildOnlyTest.java
- based on existing work from #3555
- support versioning for beta products via `enforcedPlatform`
=> Support App Distribution in smoke tests

firebase-firestore/src/main/java/com/google/firebase/firestore/core/Target.java
See https://github.com/firebase/firebase-js-sdk/pull/6075/files
=> Backport early exit from Web

firebase-perf/CHANGELOG.md, firebase-perf/gradle.properties
Remember to revert this before merging to master
=> Fireperf fragments eap: change version number

firebase-firestore/src/main/java/com/google/firebase/firestore/util/CustomClassMapper.java
Addresses https://github.com/firebase/firebase-android-sdk/issues/3611
=> Adding support for serializing URIs and URLs

firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteQueryEngineTest.java
The test should be in SQLiteIndexManagerTest as it only tests logic in getIndexType()
=> Move getIndexType() test

firebase-common/src/main/res/raw/keep.xml
=> Add keeps for strict resource shrinking.

firebase-common/src/main/res/raw/keep.xml
Removed as per discussion in https://issuetracker.google.com/issues/221423396
=> Remove shrinkMode attribute

firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt
Right now it doesn't update the UI properly after getting the response back.
=> Fix the appdistro test app check for update button

firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
=> Rename minBatchId to maxBatchId

firebase-messaging/src/test/java/com/google/firebase/messaging/DisplayNotificationRoboTest.java
Switch to using ShadowPackageManager.getInternalMutablePackageInfo instead.
=> Migrate away from deprecated ShadowPackageManager.getPackageInfoForTesting

smoke-tests/src/androidTest/backend/functions/functions/package-lock.json, smoke-tests/src/androidTest/backend/functions/functions/package.json
Note that these all pertain to `smoke-tests`. Addresses 6 "high severity" dependency alerts from **Dependabot**. Four of which are minor audit fixes, two are considered breaking changes.
Relevant open PRS: #3724 #3722 #2728 #2657 
Buganizer ticket: _232781764_
=> Dependabot High severity alerts

firebase-appdistribution-api/ktx/api.txt, firebase-appdistribution-api/ktx/src/androidTest/kotlin/com/google/firebase/app/distribution/ktx/FirebaseAppDistributionTests.kt, firebase-appdistribution-api/ktx/src/main/kotlin/com/google/firebase/appdistribution/ktx/FirebaseAppDistribution.kt
PR for [go/fire-app-distribution-destructure-ktx](http://go/fire-app-distribution-destructure-ktx)
I don't have permissions to assign reviews in this repo, so I'm tagging here:
@kaibolay please review
=> add destructuring declarations to Firebase App Distribution KTX

firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionException.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ErrorMessages.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClient.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterApiHttpClient.java, firebase-appdistribution/src/test/assets/testSimpleResponse.json, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClientTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TestUtils.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterApiHttpClientTest.java
Also refactors out low level API-specific HTTP and basic JSON parsing functionality into TesterApiHttpClient
=> Add in-app feedback requests to FirebaseAppDistributionTesterApiClient

firebase-appdistribution/firebase-appdistribution.gradle, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackSender.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClient.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ImageUtils.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ScreenshotTaker.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterApiHttpClient.java, firebase-appdistribution/src/main/res/layout/activity_feedback.xml, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FeedbackSenderTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClientTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ImageUtilsTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/NewReleaseFetcherTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ScreenshotTakerTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TestOnCompleteListener.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TestUtils.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterApiHttpClientTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterSignInManagerTest.java
In prototype UI, shows thumbnail of screenshot:
=> Take actual screenshots when giving feedback

firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
=> Patch background state checker.

firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionException.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ErrorMessages.java
Based on feedback from vlukanovich@
=> Update messaging around API_DISABLED status

firebase-annotations/src/main/java/com/google/firebase/annotations/PreviewApi.java
We want methods annotated with @PreviewApi to include it in their javadoc.
=> Make @PreviewApi a documented annotation.

firebase-database/src/androidTest/java/com/google/firebase/database/IntegrationTestHelpers.java, firebase-database/src/androidTest/java/com/google/firebase/database/QueryTest.java, firebase-database/src/main/java/com/google/firebase/database/core/Repo.java, firebase-database/src/main/java/com/google/firebase/database/core/SyncTree.java
Fix for related https://github.com/firebase/firebase-js-sdk/issues/6397
=> Fixed get() to propagate events to listeners

buildSrc/src/main/java/com/google/firebase/gradle/plugins/JavadocPlugin.java
Reverts firebase/firebase-android-sdk#3985
=> Revert "Update project.path var to new location."

firebase-appdistribution/firebase-appdistribution.gradle, firebase-appdistribution/src/androidTest/AndroidManifest.xml, firebase-appdistribution/src/androidTest/java/com/google/firebase/appdistribution/StrictModeTest.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/SignInStorage.java
alternative to #4106 which should produce same file contents
=> merge fad/next into fad/in-app-feedback

smoke-tests/src/androidTest/backend/functions/functions/package-lock.json
https://github.com/firebase/firebase-android-sdk/security/dependabot/18
=> Fix dependabot security alerts

ci/fireci/fireciplugins/fireperf.py
The perf gradle PR is 334 in the gradle repo.
b/246802885
=> Add gradle property to instrument Fireperf E2E test

firebase-appdistribution/firebase-appdistribution.gradle, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ImageUtils.java, firebase-appdistribution/src/main/res/drawable/card_background.xml, firebase-appdistribution/src/main/res/drawable/ic_baseline_arrow_back_24.xml, firebase-appdistribution/src/main/res/drawable/ic_baseline_send_24.xml, firebase-appdistribution/src/main/res/layout/activity_feedback.xml, firebase-appdistribution/src/main/res/values/strings.xml, firebase-appdistribution/src/main/res/values/themes.xml, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ImageUtilsTest.java
=> Update layout of Feedback activity.

firebase-firestore/src/test/java/com/google/firebase/firestore/core/FilterTest.java
=> Fix typo in or query test

firebase-functions/CHANGELOG.md, firebase-functions/firebase-functions.gradle
=> refactor(functions): update firebase-iid to 21.1.0

firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/AppDistroTestApplication.kt, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/ShakeDetectionFeedbackTrigger.kt
Renames it to be more aligned with the other triggers, adds javadocs, and reformats the file.
=> Clean up shake detection trigger example

docs/executors.md
Additionally fixed kotlin samples.
=> Add Direct Executor and SequentialExecutor docs

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionNotificationsManager.java, firebase-appdistribution/src/main/res/drawable/ic_baseline_rate_review_24.xml
=> Add icon for in-app feedback notifications

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
=> Fix handling of activity destruction based on configuration change

.github/workflows/make-bom.yml
Creates the bom and uploads it as an artifact. Original job performed testing, but @rlazo confirmed that testing should be executed somewhere else, so this job does not.
=> Add action to create bom

buildSrc/build.gradle.kts
=> Set jvm target for kotlin to jvm11 to match java.

firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/AppDistroTestApplication.kt, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/CustomNotificationFeedbackTrigger.kt, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/SecondActivity.kt, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/ShakeDetectionFeedbackTrigger.kt
didn't build without formatting first
=> ./gradlew :firebase-appdistribution:test-app:ktfmtFormat

buildSrc/src/main/java/com/google/firebase/gradle/plugins/Metalava.kt, firebase-annotations/api.txt, firebase-messaging/api.txt, firebase-storage/api.txt
Context for googlers b/262458570
=> Fix apiInformation check not warning of added methods/fields/classes

firebase-inappmessaging/CHANGELOG.md, firebase-inappmessaging/api.txt, firebase-inappmessaging/gradle.properties, firebase-inappmessaging/src/androidTest/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingFlowableTest.java, firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessaging.java, firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/DeveloperListenerManager.java, firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingTest.java
Added api for removing dismiss listener.
Motivational PR: https://github.com/firebase/firebase-android-sdk/pull/3980
Approved API Review: b/262402247
=> Added api for removing dismiss listener.

docs/make_release_notes.py
Fixes a conflict in header parsing with the iOS repo.
=> Move release notes script to Android repo

firebase-appdistribution/test-app/src/main/kotlin/com/googletest/firebase/appdistribution/testapp/MainActivity.kt
This is required now that we are targeting API level 33.
=> Request notification permissions in test app

firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
Based on the [DevRel plan](https://docs.google.com/document/d/169EFoj_dvSqxGw4gvpDFPW680vXHb78x00KfEo1gBIs/edit?resourcekey=0-2PfOZ3Q5Fa0M-xHJKGhACw#bookmark=kix.vrhn68invb9q).
=> Update infoText javadoc description

.github/workflows/create_releases.yml
This simplifies the action by relying on peter-evans/create-pull-request@v4 to create the commit and create the pull request.
=> Use the create pull request action to commit the changes

docs/make_release_notes.py
These changes complements the changes introduced in #4565
=> Read release name from release config file.

settings.gradle
Version catalogs are stable in gradle 7.5
=> Remove deprecated setting

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandler.java
=> Make FetchType header capitalized to match backend

appcheck/firebase-appcheck/ktx/src/androidTest/AndroidManifest.xml, buildSrc/build.gradle.kts, buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java, buildSrc/src/main/java/com/google/firebase/gradle/plugins/VendorPlugin.kt, buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/VendorTests.kt, firebase-appdistribution-api/ktx/src/androidTest/AndroidManifest.xml, firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle, firebase-crashlytics/ktx/src/androidTest/AndroidManifest.xml, firebase-firestore/firebase-firestore.gradle, firebase-firestore/src/androidTest/AndroidManifest.xml, firebase-functions/ktx/src/androidTest/AndroidManifest.xml, firebase-functions/src/androidTest/AndroidManifest.xml, firebase-inappmessaging/src/androidTest/AndroidManifest.xml, firebase-installations/src/androidTest/AndroidManifest.xml, firebase-messaging/src/androidTest/AndroidManifest.xml, transport/transport-runtime/transport-runtime.gradle
This reverts commit ffc5d33e693909e3ff3b45479a180c32db17c063.
=> Revert "Migrate vendor plugin to new transform api. (#4424)"

transport/transport-runtime/transport-runtime.gradle
[b/268106046](http://b/268106046)
=> disable device test on blueline-28 for transport-runtime

firebase-firestore/src/proto/google/firestore/v1/query.proto
=> Add proto for Sum and Avg

firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionProxy.java, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionStub.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionNotificationsManager.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ScreenshotTaker.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TakeScreenshotAndStartFeedbackActivity.java, firebase-appdistribution/src/main/res/layout/activity_feedback.xml, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionNotificationsManagerTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java, firebase-appdistribution/test-app/src/main/kotlin/com/googletest/firebase/appdistribution/testapp/CustomNotificationFeedbackTrigger.kt, firebase-appdistribution/test-app/src/main/kotlin/com/googletest/firebase/appdistribution/testapp/MainActivity.kt, firebase-appdistribution/test-app/src/main/kotlin/com/googletest/firebase/appdistribution/testapp/ScreenshotDetectionActivity.kt, firebase-appdistribution/test-app/src/main/kotlin/com/googletest/firebase/appdistribution/testapp/ScreenshotDetectionFeedbackTrigger.kt, firebase-appdistribution/test-app/src/main/kotlin/com/googletest/firebase/appdistribution/testapp/SecondActivity.kt, firebase-appdistribution/test-app/src/main/kotlin/com/googletest/firebase/appdistribution/testapp/ShakeDetectionFeedbackTrigger.kt, firebase-appdistribution/test-app/src/main/res/values/strings.xml
- Rename `infoText` -> `additionalFormText`
- Rename `infoTextResourceId` -> `additionalFormText` (already annotated with `@StringRes`)
- Small tweaks to a couple log messages
=> Changes from API review

firebase-inappmessaging-display/CHANGELOG.md, firebase-inappmessaging/CHANGELOG.md
Updating changelog to reflect the following PR(s):
https://github.com/firebase/firebase-android-sdk/pull/4691
https://github.com/firebase/firebase-android-sdk/pull/4588
=> Updating changelog for FIAM

firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigConstants.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
https://buganizer.corp.google.com/issues/268398841
Pass back server error if it is the 403 API enablement response.
=> Return Server produced error if Http status code is 403

firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
Based on feedback from @rachelsaunders.
=> Some App Distribution javadoc updates

firebase-config/src/main/java/com/google/firebase/remoteconfig/ConfigUpdateListener.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/ConfigUpdateListenerRegistration.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigException.java
Took a pass at revising the reference docs based on https://github.com/firebase/firebase-ios-sdk/pull/10060.
=> Update Realtime RC javadocs to align with iOS docs.

firebase-sessions/firebase-sessions.gradle.kts, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt
#no-changelog Integrate with Firebase Installations which will be used to receive FID and add it to the session events (Followup PR).
=> Integrate with FirebaseInstallations.

firebase-functions/src/androidTest/backend/functions/package.json
Node 12 is no longer supported, bumping to node 18
=> Update functions engine for testing.

firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/MainActivity.kt, firebase-sessions/test-app/test-app.gradle.kts
Needs to depend on Sessions because it's not eager.
=> Fix Firebase Sessions test app temporarily

firebase-storage/CHANGELOG.md, firebase-storage/firebase-storage.gradle, firebase-storage/src/main/java/com/google/firebase/storage/FirebaseStorageComponent.java, firebase-storage/src/main/java/com/google/firebase/storage/StorageRegistrar.java, firebase-storage/src/main/java/com/google/firebase/storage/StorageTaskScheduler.java, firebase-storage/src/main/java/com/google/firebase/storage/UploadTask.java, firebase-storage/src/main/java/com/google/firebase/storage/internal/SmartHandler.java, firebase-storage/src/test/java/com/google/firebase/storage/TestUtil.java, firebase-storage/src/testUtil/java/com/google/firebase/storage/ControllableSchedulerHelper.java
This reverts commit 55e77f01d0d38bee60d7cc94a700fc86bf471dcf.
=> Revert "Implement Android Executors for Storage (#4830)"

firebase-appdistribution-api/CHANGELOG.md, firebase-appdistribution/CHANGELOG.md, firebase-database/CHANGELOG.md, firebase-firestore/CHANGELOG.md
Previous PR fixing the didn't remove the old entry from the "Unreleased" section
=> Fix changelog files for several products

firebase-inappmessaging/CHANGELOG.md
=> Updating changelog

appcheck/firebase-appcheck/CHANGELOG.md
Equivalent change internally: [cl/529542160](http://cl/529542160)
=> typo: limted --> limited

firebase-common/src/androidTest/java/com/google/firebase/FirebaseAppTest.java
=> Prefer assertThat over assert in firebaseApp test

appcheck/firebase-appcheck-interop/CHANGELOG.md, encoders/firebase-decoders-json/CHANGELOG.md, encoders/firebase-encoders-json/CHANGELOG.md, encoders/firebase-encoders-processor/CHANGELOG.md, encoders/firebase-encoders-proto/CHANGELOG.md, encoders/firebase-encoders-reflective/CHANGELOG.md, encoders/firebase-encoders/CHANGELOG.md, encoders/protoc-gen-firebase-encoders/CHANGELOG.md, firebase-common/CHANGELOG.md, firebase-components/CHANGELOG.md, firebase-components/firebase-dynamic-module-support/CHANGELOG.md, firebase-database-collection/CHANGELOG.md, firebase-datatransport/CHANGELOG.md, firebase-installations-interop/CHANGELOG.md, protolite-well-known-types/CHANGELOG.md, transport/transport-api/CHANGELOG.md, transport/transport-backend-cct/CHANGELOG.md, transport/transport-runtime-testing/CHANGELOG.md, transport/transport-runtime/CHANGELOG.md
=> Add missing CHANGELOG.md files

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
Update real-time http methods to use Tasks for auth tokens and FID (future).
=> Refactor real-time RC to use tasks for auth token requests

.github/workflows/sessions-e2e.yml, firebase-sessions/gradle.properties, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt
Also update the e2e test to not use firebase-sessions branch.
=> Bump Firebase Sessions version

buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/BomGeneratorTask.java, buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/PomXmlWriter.java, buildSrc/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt
[b/285900964](https://b.corp.google.com/issues/285900964)
=> specify the bom dir as an output property of the BomGeneratorTask

firebase-inappmessaging-display/src/androidTest/AndroidManifest.xml
=> Make TestActivity exported for firebase-inappmessaging-display

.github/workflows/api-information.yml, .github/workflows/build-release-artifacts.yml, .github/workflows/build-src-check.yml, .github/workflows/changelog.yml, .github/workflows/check-head-dependencies.yml, .github/workflows/ci_tests.yml, .github/workflows/create_releases.yml, .github/workflows/diff-javadoc.yml, .github/workflows/fireci.yml, .github/workflows/fireperf-e2e.yml, .github/workflows/health-metrics.yml, .github/workflows/jekyll-gh-pages.yml, .github/workflows/make-bom.yml, .github/workflows/private-mirror-sync.yml, .github/workflows/release-note-changes.yml, .github/workflows/scorecards.yml, .github/workflows/semver-check.yml, .github/workflows/sessions-e2e.yml, .github/workflows/smoke-tests.yml, .github/workflows/update-cpp-sdk-on-release.yml, .github/workflows/validate-dependencies.yml
=> Update checkout action to version 3.5.3

firebase-appdistribution-api/gradle.properties, firebase-appdistribution/CHANGELOG.md, firebase-appdistribution/gradle.properties, firebase-inappmessaging-display/CHANGELOG.md, firebase-inappmessaging-display/gradle.properties, firebase-inappmessaging/CHANGELOG.md, firebase-inappmessaging/gradle.properties, firebase-installations/gradle.properties, firebase-messaging-directboot/gradle.properties, firebase-messaging/CHANGELOG.md, firebase-messaging/gradle.properties, firebase-ml-modeldownloader/CHANGELOG.md, firebase-ml-modeldownloader/gradle.properties, firebase-sessions/gradle.properties
=> Mergeback for m135

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/RolloutAssignment.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/UserMetadata.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java, firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReportTest.java
- Update CrashlyticsReport with new proto, followed the backend change: [cl/554467862](http://cl/554467862)
- Adding RolloutAssignmentList to UserMetadata
- Adding limits to parameter value for rollout assignment
#no-changelog
=> Update Crashlytics Report Proto with new Rollouts fields

firebase-datatransport/firebase-datatransport.gradle
Bump common and transport-* to their latest released versions
=> Update firebase-datatransport dependencies

firebase-inappmessaging-display/CHANGELOG.md, firebase-inappmessaging/CHANGELOG.md, firebase-inappmessaging/firebase-inappmessaging.gradle, firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingRegistrar.java, subprojects.cfg
[FIAM] Firelog to clearcut migration
=> [FIAM] Firelog to clearcut migration

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/metadata/RolloutAssignmentListTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransformTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/FileBackedNativeSessionFile.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/MetaDataStore.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/RolloutAssignment.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/RolloutAssignmentList.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/UserMetadata.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransform.java
Associated Rollouts with different types of events:
- Non-fatals
- Android fatals
- ANR
- NDK
Added comments below to mark the places where which part associate with with type of events
#no-changelog
=> Associate Rollouts with Fatal and non-fatals

firebase-crashlytics-ndk/CHANGELOG.md, firebase-crashlytics-ndk/gradle.properties, firebase-crashlytics/CHANGELOG.md, firebase-crashlytics/gradle.properties, firebase-datatransport/CHANGELOG.md, firebase-datatransport/gradle.properties, firebase-firestore/CHANGELOG.md, firebase-firestore/gradle.properties, firebase-perf/CHANGELOG.md, firebase-perf/gradle.properties, firebase-sessions/CHANGELOG.md, firebase-sessions/gradle.properties
=> Mergeback for M136

firebase-config/test-app/.gitignore, firebase-config/test-app/src/main/cpp/CMakeLists.txt, firebase-config/test-app/src/main/cpp/config.cpp, firebase-config/test-app/src/main/kotlin/com/google/firebase/crashlytics/OnDemandFatals.kt, firebase-config/test-app/src/main/kotlin/com/google/firebase/testing/config/MainActivity.kt, firebase-config/test-app/src/main/res/layout/activity_main.xml, firebase-config/test-app/src/main/res/values/strings.xml, firebase-config/test-app/test-app.gradle.kts
Adding more test cases for Crashlytics
=> adding more test cases

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigContainer.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/rollouts/RolloutsStateFactory.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/rollouts/RolloutsStateFactoryTest.java
Fixes a NPE parsing Rollouts metadata.
=> Reference ConfigContainer metadata for Rollouts constants.

firebase-config/test-app/src/main/kotlin/com/google/firebase/testing/config/MainActivity.kt
Primarily creating a PR to test the new `api: rollouts` label.
=> Add log message when activate completes in test app.

firebase-config-interop/gradle.properties, firebase-config/firebase-config.gradle, firebase-crashlytics/firebase-crashlytics.gradle
=> add version dependeny for RC interop

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleService.kt
Using the SessionGenerator to generate new sessions and create SessionDetails instead of directly creating UUID session ids in the service.
Also updated the boundClients queue to be a LinkedBlockingQueue to avoid ConcurrentModificationExceptions if a client binds while a message is being handled by the server.
=> Hooks up the SessionGenerator to the SessionLifecycleService

firebase-crashlytics/CHANGELOG.md, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/metadata/MetaDataStoreTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/UserMetadata.java
Fix Unity and Flutter on-demand user meta data behaviour. Cherry-picked from previous closed pr: https://github.com/firebase/firebase-android-sdk/pull/5275
=> User id fix

appcheck/firebase-appcheck-playintegrity/CHANGELOG.md, appcheck/firebase-appcheck-playintegrity/firebase-appcheck-playintegrity.gradle
Bump our Play Integrity API Library dependency version per the request of the Play Integrity team.
=> Bump Play Integrity API dependency.

firebase-common/src/main/java/com/google/firebase/logger/Logger.kt
Discussed in https://github.com/firebase/firebase-android-sdk/pull/5469#discussion_r1371862679
=> Make Logger a normal abstract class

firebase-sessions/test-app/test-app.gradle.kts
It looks like it's still failing but it's because the test app crashes successfully on test lab. But the dep problem is fixed.
=> Fix sessions test app build file

buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.kt, firebase-crashlytics/CHANGELOG.md, firebase-sessions/CHANGELOG.md, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/EventGDTLogger.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionDatastore.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionFirelogPublisher.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionGenerator.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleService.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleServiceBinder.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/RemoteSettings.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/RemoteSettingsFetcher.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/SessionsSettings.kt
Add change logs, restore commented out line, fix a few warnings. This is to prepare to merge to main line.
=> Clean up a few things before merging

firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigTests.kt, firebase-config/src/test/java/com/google/firebase/remoteconfig/TestConstructorUtil.kt, firebase-config/src/test/java/com/google/firebase/remoteconfig/ktx/RemoteConfigTests.kt
=> fix unit tests

firebase-datatransport/firebase-datatransport.gradle, transport/transport-api/gradle.properties, transport/transport-backend-cct/gradle.properties, transport/transport-runtime/gradle.properties
=> Bump transport versions

firebase-datatransport/firebase-datatransport.gradle, transport/transport-api/gradle.properties, transport/transport-backend-cct/gradle.properties, transport/transport-runtime/gradle.properties
=> Bump transport versions (#5535)

firebase-config-interop/CHANGELOG.md, firebase-config-interop/gradle.properties
=> Fix release config for config-interop (#5539)

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/Utils.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/UserMetadata.java
Rerun `./gradlew googleJavaFormat`  and fix unit tests
#no-changelog
=> fix formatting

firebase-firestore/CHANGELOG.md, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java
Fix: https://github.com/firebase/firebase-android-sdk/issues/5571
=> Replace Collection.emptyMap() with new HashMap()

firebase-crashlytics/CHANGELOG.md, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/ktx/FirebaseCrashlytics.kt
#5603
Added Deprecation annotation.
=> Added @Deprecated annotation on unused crashlytics from ktx api.

firebase-crashlytics/CHANGELOG.md, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/ktx/FirebaseCrashlytics.kt
Reverts firebase/firebase-android-sdk#5619
=> Revert "Added @Deprecated annotation on unused crashlytics from ktx api."

firebase-firestore/src/main/java/com/google/firebase/firestore/AggregateSource.java, firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
Apply the feedback to the count and aggregation API documentation as suggested in https://github.com/firebase/firebase-js-sdk/pull/6608. This is a port of https://github.com/firebase/firebase-js-sdk/pull/7933.
=> Firestore: Small Count API documentation improvements

appcheck/firebase-appcheck-safetynet/firebase-appcheck-safetynet.gradle, buildSrc/src/main/java/com/google/firebase/gradle/plugins/Metalava.kt, firebase-config/bandwagoner/bandwagoner.gradle, firebase-perf/dev-app/dev-app.gradle, firebase-perf/e2e-app/e2e-app.gradle
=> Misc build fixes

.github/workflows/ci_tests.yml, .github/workflows/config-e2e.yml, .github/workflows/fireperf-e2e.yml, .github/workflows/health-metrics.yml, .github/workflows/sessions-e2e.yml, .github/workflows/smoke-tests.yml
Pull request https://github.com/firebase/firebase-android-sdk/pull/5665 updated the `setup-gcloud` action, this PR updates
the `auth` action, which is also outdated.
=> Missing action upgrades

firebase-config/bandwagoner/src/main/java/com/googletest/firebase/remoteconfig/bandwagoner/MainActivity.java, firebase-config/bandwagoner/src/main/java/com/googletest/firebase/remoteconfig/bandwagoner/RealtimeFragment.java, firebase-config/bandwagoner/src/main/res/layout/realtime_fragment.xml
Merging an old branch from Realtime development since it's helpful to test realtime functionality today.
=> Add RealtimeFragment to RC test app.

firebase-config/firebase-config.gradle.kts
Config team confirmed this dependency can be pinned
=> Pin config interop

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHandler.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
Reverts #5688 
This reverts commit 46cccc9f459d76a12dba1b570ffe9b2f3c9f4a4d.
This was a clean revert created with `git revert 46cccc9f459d76a12dba1b570ffe9b2f3c9f4a4d`.
=> Revert "Disconnect from RC real-time server when app is backgrounded."

firebase-inappmessaging-display/CHANGELOG.md, firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/internal/FiamWindowManager.java, firebase-inappmessaging/CHANGELOG.md
Fix FIAM Bad token exception (b/330727156)
=> Fix: FIAM Bad token exception (b/330727156)

firebase-vertexai/firebase-vertexai.gradle.kts
This should prevent https://github.com/google/generative-ai-android/issues/69
=> Bump futures dependency

firebase-vertexai/firebase-vertexai.gradle.kts
Use a newer version of common, and don't publish javadocs (yet)
=> Update vertexai gradle build file

firebase-vertexai/gradle.properties, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/UsageMetadata.kt
Additionally:
- Right version for the SDK
- Address https://github.com/google/generative-ai-android/pull/104
=> Set the right apiClient value

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/RequestOptions.kt
They need to be hardcoded for now
=> Remove location and apiVersion from user visible configuration

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt
This is the equivalent of https://github.com/google/generative-ai-android/pull/115
Note that after we merge this PR it will be a breaking change from `alpha01` to the next version.
=> use the same parameter order as Google AI

firebase-vertexai/firebase-vertexai.gradle.kts
=> Update vertexai's common dependency

firebase-ml-modeldownloader/ml-data-collection-tests/ml-data-collection-tests.gradle
This fixes an issue with conflicting kotlin versions
=> Bump common dependency in ml-data-collection-tests

.github/workflows/api-information.yml, .github/workflows/build-release-artifacts.yml, .github/workflows/build-src-check.yml, .github/workflows/changelog.yml, .github/workflows/check-head-dependencies.yml, .github/workflows/ci_tests.yml, .github/workflows/config-e2e.yml, .github/workflows/copyright-check.yml, .github/workflows/create_releases.yml, .github/workflows/diff-javadoc.yml, .github/workflows/fireci.yml, .github/workflows/fireperf-e2e.yml, .github/workflows/health-metrics.yml, .github/workflows/jekyll-gh-pages.yml, .github/workflows/make-bom.yml, .github/workflows/post_release_cleanup.yml, .github/workflows/private-mirror-sync.yml, .github/workflows/release-note-changes.yml, .github/workflows/scorecards.yml, .github/workflows/semver-check.yml, .github/workflows/sessions-e2e.yml, .github/workflows/smoke-tests.yml, .github/workflows/update-cpp-sdk-on-release.yml, .github/workflows/validate-dependencies.yml, .github/workflows/version-check.yml
Node 16 is no longer supported
=> Update checkout action and java-setup version

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Content.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt
=> Add filedata support in vertex

firebase-dataconnect/firebase-dataconnect.gradle.kts
Based on https://github.com/firebase/firebase-android-sdk/pull/5933
=> firebase-dataconnect.gradle.kts: set previewMode = "alpha"

firebase-appdistribution-api/CHANGELOG.md, firebase-appdistribution/CHANGELOG.md
=> Update appdistribution* changelog entries

firebase-common/gradle.properties, firebase-components/gradle.properties, firebase-vertexai/gradle.properties
`versions` and `latestReleasedVersion` were outdated.
=> Update versions in common, components & vertexai

firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/FirebaseDataConnect.kt, firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/DataConnectGrpcClient.kt, firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/util/ProtoUtil.kt
Improve debug logging of GRPC requests and responses, especially to put the request metadata right with the request payload
=> Improve debug logging of GRPC requests and responses

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Exceptions.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt
These were the changes Rachel requested
=> Update Vertex docs in line with m149

firebase-crashlytics-ndk/CHANGELOG.md, firebase-crashlytics-ndk/gradle.properties, firebase-crashlytics/CHANGELOG.md, firebase-crashlytics/gradle.properties, firebase-sessions/gradle.properties, firebase-vertexai/gradle.properties
=> M149 mergeback

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Exceptions.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionDeclarations.kt
Per [b/352564349](https://b.corp.google.com/issues/352564349),
This fixes the non blocking comments Rachel left in the m150 Javadoc CL.
=> Address M150 Javadoc comments

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/CrashlyticsRegistrar.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/ExecutorUtils.java
Cherry-pick https://github.com/firebase/firebase-android-sdk/pull/6019, https://github.com/firebase/firebase-android-sdk/pull/6040 to main
#no-changelog
=> Crashlytics common executor

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
we are sending a task within a task for common worker which cause the async behavior, remove the re-submitting task for report finalization
=> fix finalize report behaviour

firebase-dataconnect/src/androidTest/kotlin/com/google/firebase/dataconnect/GrpcMetadataIntegrationTest.kt, firebase-dataconnect/src/androidTest/kotlin/com/google/firebase/dataconnect/testutil/FirebaseAppIdTestUtil.kt, firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/DataConnectGrpcMetadata.kt, firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/FirebaseDataConnectImpl.kt, firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/DataConnectGrpcMetadataUnitTest.kt
=> x-firebase-gmpid header added to data connect

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCaptureTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/IdManagerTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/metadata/MetaDataStoreTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/IdManager.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/Utils.java
Adjust time out and disk worker as discussed. This moves some things off the disk worker, but we plan to put them back after more refactoring.
=> Adjust time out and disk worker

firebase-dataconnect/androidTestutil/androidTestutil.gradle.kts, firebase-dataconnect/firebase-dataconnect.gradle.kts, firebase-dataconnect/testutil/testutil.gradle.kts
See comment https://github.com/firebase/firebase-android-sdk/pull/6290#discussion_r1771722559
=> Remove unnecessary excludes from gradle.kts files

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/APIController.kt
New wording more clearely describes the steps to take to solve the issue.
=> Update service disabled wording

buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/BomGeneratorTask.java
=> fix vertexAI in bom and add ktx artifact also

firebase-messaging/src/main/java/com/google/firebase/messaging/GmsRpc.java
The comment have been outdated since 2021
=> Remove outdated comment on GmsRpc

firebase-vertexai/gradle.properties
The changes include new API  (Civic integrity)
=> Minor bump vertex-ai version

.github/workflows/private-mirror-sync.yml
The action was defined as a push operation before
=> Make repo sync a pull operation

firebase-vertexai/README.md
The SDK was released as GA last year.
=> Remove preview notice from vertexai readme

firebase-dynamic-links/CHANGELOG.md
Replace the changed tag with deprecated for the last FDL release
=> Update fdl readme

firebase-functions/CHANGELOG.md
Changelog entry should be picked up for the next release
=> Add functions changelog

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleService.kt
Last PR auto merged when I resolved the comment, before pushing this commit.
=> Followup to #6699

firebase-ai/src/test/java/com/google/firebase/ai/DevAPIUnarySnapshotTests.kt, firebase-ai/src/test/java/com/google/firebase/ai/util/tests.kt, firebase-ai/update_responses.sh
Citation test still times out, but this address all other breakages.
=> [ai] Address most tests failures

firebase-vertexai/firebase-vertexai.gradle.kts
The release note name has been updated to use the correct value.
Context cl/761183261
=> [vertexai] Use correct name in release notes for vertexai

gradle/libs.versions.toml
I'm re-attempting this upgrade that previously failed in https://github.com/firebase/firebase-android-sdk/pull/7028 now that kotlin has been upgraded to 2.x in https://github.com/firebase/firebase-android-sdk/pull/7117
=> Upgrade app.cash.turbine:turbine from 1.2.0 to 1.2.1.

firebase-crashlytics-ndk/gradle.properties, firebase-sessions/gradle.properties
Bump the Sessions SDK major version
Also bump the Crashlytics NDK major version to keep aligned with the SDK
=> Bump ndk and aqs major versions

.gemini/config.yaml
An initial version of the configuration for the gemini bot in github.
=> [Infra] Add configuration for gemini bot

firebase-ai/CHANGELOG.md
Adding the PR number to the changelog entry helps track down changes when necessary.
=> [AI] Update changelog entries to include PR number
