firebase/firebase-android-sdk

firebase-firestore/CHANGELOG.md, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/OnlineStateTracker.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java, firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java, firebase-firestore/src/test/resources/json/offline_spec_test.json, firebase-firestore/src/test/resources/json/remote_store_spec_test.json
@wilhuff You have already reviewed this. I just moved it to this repo via "git diff" and "patch".  Sorry for the extra churn.
[Port of https://github.com/firebase/firebase-js-sdk/pull/1133]
1. Changed MAX_WATCH_STREAM_FAILURES to 1 per conversation with @wilhuff and
@jdimond.
2. Fixed a "race" where when a get() triggered a watch stream error, we'd
restart the stream, then get() would remove its listener, and so we had no
listener left once the watch stream was "opened". Without a listen to send
we'd be stuck in Offline state (even though we should be Unknown whenever
we have no listens to send), resulting in the next get() returning data
from cache without even attempting to reach the backend.
=> Offline get() improvements.

README.md, firebase-database/README.md, firebase-firestore/README.md, firebase-storage/README.md
Build/publish/test commands are common across the projects, so we can
just refer to them in the top level README rather than repeating them in
the sub-READMEs.
=> Adjust a few READMEs to eliminate some redundancy

.gitignore, ci/README.md, ci/fireci/.gitignore, ci/fireci/.style.yapf, ci/fireci/fireci/__init__.py, ci/fireci/fireci/commands.py, ci/fireci/fireci/emulator.py, ci/fireci/fireci/gradle.py, ci/fireci/fireci/internal.py, ci/fireci/fireci/main.py, ci/fireci/setup.py, ci/fireci/tests/__init__.py, ci/fireci/tests/artifact_handler_test.py, ci/fireci/tests/fileutil.py, ci/fireci/tests/gradle_test.py, ci/fireci/tests/integ_tests.py, ci/fireci/tests/scripts.py, ci/run.sh
The scripts are in the form of a Python CLI application that can be used
to run various tasks like:
* starting/stopping the Android emulator
* handling build artifacts
* running gradle tasks
* running test-apps
=> Adds Continuous Integration scripts to the repo.

firebase-database/src/main/AndroidManifest.xml
I'm not sure what changed so that now this is necessary, but I assume this change will resolve https://github.com/firebase/firebase-android-sdk/issues/18.  That said I haven't explicitly validated this as I'm not sure how.
cc/ @samtstern
=> Add INTERNET and ACCESS_NETWORK_STATE to database permissions.

buildSrc/build.gradle, root-project.gradle, test-apps/build.gradle
=> Add maven proxy configuration.

firebase-firestore/src/main/java/com/google/firebase/firestore/local/LruDelegate.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LruGarbageCollector.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryLruReferenceDelegate.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteLruReferenceDelegate.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LruGarbageCollectorTestCase.java
Requested renamed from https://github.com/firebase/firebase-js-sdk/pull/1224
=> removeQueries -> removeTargets

firebase-database/src/androidTest/java/com/google/firebase/database/TestHelpers.java, firebase-database/src/main/java/com/google/firebase/database/android/AndroidEventTarget.java
This allows me to run the following in a test app without crashes:
```
new Thread(new Runnable() {
@Override
public void run() {
try {
final DatabaseReference reference = FirebaseDatabase.getInstance().getReference();
reference.child("foo/test").setValue("done");
} catch (Throwable t) {
System.out.println(t);
}
}
}).start();
```
=> Allow initial call to .getReference() from any thread

firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryEagerReferenceDelegate.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryLruReferenceDelegate.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/ReferenceDelegate.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteLruReferenceDelegate.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LruGarbageCollectorTestCase.java
Doing some renaming that came up in the webclient review of part of the LRU port (https://github.com/firebase/firebase-js-sdk/pull/1224)
No functional changes.
=> Renaming from webclient review

firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryMutationQueue.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MutationQueue.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteMutationQueue.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/MutationQueueTestCase.java
This PR is a port of https://github.com/firebase/firebase-js-sdk/pull/1148 and changes removeMutationBatches to only remove a single batch.
=> Change removeMutationBatch to remove a single batch

firebase-firestore/CHANGELOG.md, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/UserDataConverter.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/PatchMutation.java
We currently drop empty objects when during set({merge: true}) since we only add leaf nodes to the field mask. We need to consider an empty object a leaf node.
Port of https://github.com/firebase/firebase-js-sdk/pull/1202
=> Don't drop empty objects during merge

firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryLruReferenceDelegate.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java
Previously, we weren't deleting our tracking of orphaned documents when we deleted the doc itself. I moved the deletion into the reference delegate, which is probably a better home anyways, and delete from the orphaned doc map at the same time so we no longer leak.
Caught while porting to web.
=> Don't leak orphaned docs when deleting

ci/fireci/fireci/emulator.py, ci/fireci/fireci/internal.py, ci/fireci/tests/emulator_test.py, ci/fireci/tests/fileutil.py, ci/fireci/tests/integ_tests.py, ci/fireci/tests/scripts.py
Emulator logs are stored in artifacts under test_emulator/ subdirectory.
=> Adds emulator launch/shutdown capabilities.

ci/fireci/fireci/__init__.py, ci/fireci/fireci/commands.py, ci/fireci/fireci/gradle.py, ci/fireci/fireci/plugins.py, ci/fireci/fireciplugins/__init__.py
The motivation is to be able to discover ci_command's on the PYTHONPATH
provided by packages outside of fireci.
=> Add plugin mechanism.

firebase-firestore/src/main/java/com/google/firebase/firestore/core/Transaction.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
This PR removes the notion of held write acks from LocalStore.
=> Remove held batch handling from LocalStore

firebase-firestore/src/main/java/com/google/firebase/firestore/core/Transaction.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLitePersistence.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
Port of https://github.com/firebase/firebase-js-sdk/pull/1149
=> Schema migration that drops held write acks

firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryMutationQueue.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MutationQueue.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteMutationQueue.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/MutationQueueTestCase.java
This PR drops `getHighestAcknowledgedBatchId` and `getAllMutationBatchesThroughBatchId`.
=> Remove no longer needed MutationBatch methods

firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/ReferenceSet.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
Fixes issue with GC that prevented local document removal for documents that had pending mutations.
Also renames applyBatchResult to applyWriteToRemoteDocuments to match Web.
=> Remove local references from reference delegate

firebase-firestore/CHANGELOG.md
As per https://firebase.google.com/support/release-notes/js
=> Held Write Acks Changelog entries

firebase-firestore/firebase-firestore.gradle
This avoids the classpath conflict when both guava and listenablefuture
libraries are present.
See https://groups.google.com/forum/#!topic/guava-announce/Km82fZG68Sw
for context.
=> Add dependency on empty version of listenablefuture.

firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
Port of https://github.com/firebase/firebase-ios-sdk/pull/1911, ensures that every remote document in the cache has a corresponding sentinel row in the `target_documents` table.
=> Add migration to add sequence numbers to documents

firebase-database-collection/firebase-database-collection.gradle, firebase-database/firebase-database.gradle, firebase-storage/firebase-storage.gradle, test-apps/database-test-app/build.gradle, test-apps/firestore-test-app/build.gradle, test-apps/firestore-test-app/lint.xml, test-apps/functions-test-app/build.gradle, test-apps/storage-test-app/build.gradle
Part 1 https://github.com/firebase/firebase-android-sdk/pull/63
=> Enabled linting part2

firebase-firestore/src/proto/google/firebase/firestore/proto/maybe_document.proto
See https://github.com/firebase/firebase-ios-sdk/pull/1948/
=> Backport Protobuf changes

firebase-firestore/CHANGELOG.md, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/POJOTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ServerTimestampTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentSnapshot.java
* Added `T get(..., Class<T>, ...)` overloads for extracting fields as a custom
class (POJO) type.
=> Implement POJO field reads.

firebase-firestore/CHANGELOG.md, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/POJOTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ServerTimestampTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/CollectionReference.java, firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentReference.java, firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentSnapshot.java, firebase-firestore/src/main/java/com/google/firebase/firestore/Transaction.java, firebase-firestore/src/main/java/com/google/firebase/firestore/UserDataConverter.java, firebase-firestore/src/main/java/com/google/firebase/firestore/WriteBatch.java, firebase-firestore/src/main/java/com/google/firebase/firestore/util/CustomClassMapper.java, firebase-firestore/src/test/java/com/google/firebase/firestore/model/FieldValueTest.java
All of our parsing code now accepts POJOs meaning you can pass them:
* As values in a Map<> passed to set().
* As values to a update() call.
* As elements in an array transform operation.
* As values in query field filters.
Also removed set(Map<>) overloads since they are now redundant with set(Object).
=> Allow passing POJOs as field values throughout API.

firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestoreSettings.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LruDelegate.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LruGarbageCollector.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryLruReferenceDelegate.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteLruReferenceDelegate.java
We had originally decided to only look at targets when assessing how much to run GC. However, based on running a write-heavy workload test, we need to include documents that ended up cached without being part of a target.
This is a port of a portion of https://github.com/firebase/firebase-ios-sdk/pull/1961
Note that merge base is into the LRU branch, not master.
Integration tests pass :)
=> Use orphaned docs as part of GC calculation

test-apps/build.gradle
This swaps the order of the repositories in the test-apps Gradle file. Specifically, jCenter() is swapped with google().
jCenter seems to be incompletely mirroring some Android artifacts. They host the pom files but not the actual jar or aar files. This confuses Gradle, leading to build errors. Placing google() first causes Gradle to check Google's repository first, which should always contain Android artifacts. As long as Google doesn't host only pom files for other dependencies, this shouldn't cause any issues.
=> Swap smoke test deps

firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
For consistency with other platforms and to prevent auto-commit.
=> Starting the Mutation Queue in a Transaction

firebase-firestore/src/main/java/com/google/firebase/firestore/QuerySnapshot.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/QueryListener.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/TargetIdGenerator.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/View.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/ViewSnapshot.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryMutationQueue.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MutationQueue.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteMutationQueue.java, firebase-firestore/src/test/java/com/google/firebase/firestore/QuerySnapshotTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/TestUtil.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryListenerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/TargetIdGeneratorTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/ViewSnapshotTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
This PR contains a port of the structural changes from the Multi-Tab PR (https://github.com/firebase/firebase-js-sdk/pull/1000)
It's might be worth discussing just getting rid of the TargetIdGenerator at this point...
=> Port structural changes from Multi-Tab

firebase-common/firebase-common.gradle, firebase-database/firebase-database.gradle, firebase-firestore/firebase-firestore.gradle, firebase-functions/firebase-functions.gradle, firebase-inappmessaging-display/firebase-inappmessaging-display.gradle, firebase-storage/firebase-storage.gradle, root-project.gradle
This avoids the dependency on Guava 25.1 which causes tests run through
Android Studio to fail. Fixes #108.
=> Downgrade google truth library to 0.40.

firebase-firestore/firebase-firestore.gradle, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/FirestoreCallCredentials.java
This mirrors cl/218434754, and prepares us for the finalization of the
CallCredentials API in a subsequent gRPC release.
(CallCredentials has previously been marked experimental and this is an
effort on the part of the gRPC team to finalize that API.)
=> Upgrade gRPC to 1.16.1 for compatibility with CallCredentials2

firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryMutationQueue.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/MutationBatch.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/MutationQueueTestCase.java
With held write acks gone, we no longer turn mutations into tombstones. This removes the code that handles this.
Port of https://github.com/firebase/firebase-js-sdk/pull/1354
=> Remove Mutation tombstones

firebase-database/src/main/java/com/google/firebase/database/tubesock/WebSocket.java, firebase-database/src/main/java/com/google/firebase/database/tubesock/WebSocketHandshake.java
We should
a) make sure our HTTP header logic is case insensitive
b) not NPE when a header is missing
This addresses https://buganizer.corp.google.com/issues/118593067
=> RTDB: Don't NPE when a header is missing

tools/errorprone/errorprone.gradle
The issue results in a missing `META-INF/services/com.google.errorprone.bugpatterns.BugChecker` file in the resulting binary which prevents the errorprone plugin from discovering the custom checks.
=> Fix errorprone annotation processor classpath

firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteLruReferenceDelegate.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLitePersistence.java
* Move as much work as possible out of the sqlite txn.
In particular, don't do anything that could throw in the finally block, as this will mask any exception thrown within the transaction itself.
* Use sqlite transaction listeners (rather than doing so manually)
Using sqlite's version allows us to not worry about getting the transaction semantics correct in the face of exceptions.
=> Fix handling of sqlite transactions

firebase-firestore/CHANGELOG.md, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/POJOTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ServerTimestampTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/CollectionReference.java, firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentReference.java, firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentSnapshot.java, firebase-firestore/src/main/java/com/google/firebase/firestore/Transaction.java, firebase-firestore/src/main/java/com/google/firebase/firestore/UserDataConverter.java, firebase-firestore/src/main/java/com/google/firebase/firestore/WriteBatch.java, firebase-firestore/src/main/java/com/google/firebase/firestore/util/CustomClassMapper.java, firebase-firestore/src/test/java/com/google/firebase/firestore/model/FieldValueTest.java
This reverts commit ddda9268537e096b978803df46d31b4541137d9a.
This makes master shippable again while we wait for API change approvals.
=> Revert "Better POJO Support for Document Fields"

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
Without this, it still fails, but:
a) not until serializing the query, and
b) the error is an internal error, and
c) the error message is quite cryptic and has nothing to do with the problem.
=> Forbid queries endAt an uncommitted server timestamp.

firebase-firestore/src/main/java/com/google/firebase/firestore/remote/Datastore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/util/FirestoreChannel.java
Without this, we get a potential resource leak when Firestore shuts
down. Currently, it only shuts down in tests, so this doesn't impact
production, however, with teh (soon-to-come) AndroiManagedChannel
change, the integration tests will fail, as the Android OS itself tracks
resources associated with AndroidManagedChannel and will terminate if
they're not properly cleaned up.
=> Add shutdown logic to the grpc channel

firebase-firestore/src/main/java/com/google/firebase/firestore/remote/Datastore.java
To work around dead connections where the OS doesn't actually close the
socket. This allows us to not have to wait for a tcp timeout to occur.
=> Add grpc keepalive timeout

firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
Adds guards for schema migrations so that they are safe to run multiple times.
=> Make schema migrations idempotent

firebase-common/src/main/java/com/google/firebase/FirebaseApp.java, firebase-common/src/test/java/com/google/firebase/DataCollectionDefaultDisabledTest.java, firebase-common/src/test/java/com/google/firebase/DataCollectionDefaultEnabledTest.java, firebase-common/src/test/java/com/google/firebase/DataCollectionTestUtil.java
Makes setting persistense scoped per FirebaseApp instance instead of
being scoped globally.
=> Fix automatic data collection(b/120600091).

firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestoreSettings.java
Note that merge base is the LRU branch.
Switches default value for the cache to `CACHE_SIZE_UNLIMITED`. Updates the comment on the method to indicate that it is default-disabled, but will be enabled in the future.
=> Switch default for LRU collection to disabled

firebase-common/src/main/java/com/google/firebase/components/AbstractComponentContainer.java, firebase-common/src/main/java/com/google/firebase/components/ComponentContainer.java, firebase-common/src/main/java/com/google/firebase/components/ComponentRuntime.java, firebase-common/src/main/java/com/google/firebase/components/CycleDetector.java, firebase-common/src/main/java/com/google/firebase/components/Lazy.java, firebase-common/src/main/java/com/google/firebase/components/RestrictedComponentContainer.java, firebase-common/src/test/java/com/google/firebase/components/ComponentRuntimeTest.java, firebase-common/src/test/java/com/google/firebase/components/CycleDetectorTest.java, firebase-common/src/test/java/com/google/firebase/components/LazyTest.java, firebase-common/src/test/java/com/google/firebase/components/RestrictedComponentContainerTest.java
The gist of the change is that it introduces support for Set-multibindings that enables components to declare a dependency on a Set<T> as well as to create components that contribute values to a Set<T>.
=> Add runtime support for Set-components

firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java, firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java
This is required for v1 and accepted in v1beta1.
Port of firebase/firebase-js-sdk@4cec9b1.
=> Include a trailing /documents on root resource paths

firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryMutationQueue.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MutationQueue.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteMutationQueue.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/MutationQueueTestCase.java
A straightforward port of https://github.com/firebase/firebase-ios-sdk/pull/2243.
=> Port "Stop persisting last acknowledged batch ID" from iOS

ci/fireci/fireci/commands.py, ci/fireci/fireci/emulator.py, ci/fireci/fireci/gradle.py, ci/fireci/fireci/internal.py, ci/fireci/fireci/stats.py, ci/fireci/setup.py
The change instruments fireci with opencensus stats backed by
Stackdriver Monitoring. Metrics collection is controlled via
"FIREBASE_ENABLE_METRICS" environment or the "--enable-metrics"
command line flag.
The change additionally propagates the stats Tag context to gradle for
future use.
=> Enable metrics collection for CI builds.

firebase-firestore/CHANGELOG.md, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/WriteBatchTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteMutationQueue.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/MutationQueueTestCase.java
This addresses #208.
While this works, I'm not yet sure this approach performs well enough to merge as-is. For example, we could make the two methods I changed to use direct load to use the inline method that others use.
I've sent this out to get feedback on this before I invest time in benchmarking.
=> Handle large write batches

fiamui-app/fiamui-app.gradle, firebase-common/firebase-common.gradle, firebase-database/firebase-database.gradle, firebase-firestore/firebase-firestore.gradle, firebase-functions/firebase-functions.gradle, firebase-inappmessaging-display/firebase-inappmessaging-display.gradle, firebase-storage/firebase-storage.gradle, protolite-well-known-types/protolite-well-known-types.gradle, root-project.gradle, sdkProperties.gradle, test-apps/build.gradle, test-apps/database-test-app/build.gradle, test-apps/firestore-test-app/build.gradle, test-apps/functions-test-app/build.gradle, test-apps/storage-test-app/build.gradle, tools/apksize/default.gradle
2 benefits:
* We build all sdks with the same build toolchain
* CI is faster as we don't have to download platforms v26 and v27
=> Unify android sdk version configuration.

buildSrc/build.gradle, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/metrics/DrainingBuildListener.java, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/metrics/MeasuringTaskExecutionListener.java, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/metrics/Metrics.java, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/metrics/MetricsPlugin.java, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/metrics/StackdriverMetrics.java, ci/fireci/fireci/gradle.py, ci/fireci/fireci/stats.py, root-project.gradle
Specifically we now report latency and success/failure of each
individual Gradle task.
=> Instrument Gradle build with metrics.

firebase-firestore/CHANGELOG.md, firebase-firestore/firebase-firestore.gradle, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLitePersistence.java
SQLite supports two methods of commiting; a rollback journal and a
write-ahead-log (WAL). By default, a rollback journal is used. However,
on Android 9 (P), the default changed slightly to a WAL-compatible mode:
https://source.android.com/devices/tech/perf/compatibility-wal. This
mode causes a WAL to be written to disk.
Our prior method of calculating the database size did not take the WAL
into account. In practice, this isn't too awful, as the contents of the
WAL would eventually be written back into the main database file, but in
the meantime, our calculation could be off by upwards of a few MB. This
commit changes the size calulation to ask sqlite rather than looking at
the size of the file on disk.
=> Adjust sqlite size calculation to account for WAL

firebase-database/firebase-database.gradle, firebase-storage/firebase-storage.gradle
Test results are available in the artifacts directory, so stdout logging
is no longer necessary.
=> Disable verbose stdout logging for storage and rtdb.

root-project.gradle
This commit will add a gradle task to run the instrumented unit test and generate a jacoco coverage report.
The command for the gradle task is `./gradlew :<firebase-project>:coverage` for specific sdk or `./gradlew coverage` for all sdks.
Generated html report and xml report reside in `build/reports/jacoco/coverage` under each sdk directory.
=> Add gradle task for generating JaCoCo coverage report for unit tests.

firebase-functions/proguard.txt, test-apps/functions-test-app/proguard-rules.pro
I'm not sure if this is the best way to implement this. But this was needed to make the warnings go away for the test app so that it would pass smoke tests.
=> Add okhttp3 settings to Functions proguard.

firebase-firestore/CHANGELOG.md, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryIndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryMutationQueue.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryPersistence.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/Persistence.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteMutationQueue.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLitePersistence.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/DocumentKey.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexManagerTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexedQueryEngineTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/MemoryIndexManagerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java, firebase-firestore/src/test/resources/json/query_spec_test.json
Port of https://github.com/firebase/firebase-js-sdk/pull/1440
=> Collection Group Queries

firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentReference.java, firebase-firestore/src/main/java/com/google/firebase/firestore/SetOptions.java
Since we no longer proguard our sdk, some internal methods can now
appear in IDE autocompletion lists. This PR reduces the visibility of
these methods so that this no longer occurs.
=> Reduce visibility of non-public portions of our api.

transport/transport-backend-cct/gradle.properties, transport/transport-backend-cct/preguard.txt, transport/transport-backend-cct/src/main/AndroidManifest.xml, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/BackendRegistry.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportFactoryImpl.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportRuntime.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportRuntimeModule.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/TransportRuntimeTest.java, transport/transport.gradle
* Enable proguarding of CCT backend. This reduces the size of the library to
53KB from 100KB.
* Properly declare INTERNET permission.
* Rename maven groupId to com.google.android.datatransport.
* Fix invalid `@Singleton` use.
* Runtime is not responsible for creating TransportFactory's.
=> Enable proguard of proto library, various fixes.

firebase-firestore/CHANGELOG.md, firebase-firestore/src/main/java/com/google/firebase/firestore/Blob.java, firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentReference.java, firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentSnapshot.java, firebase-firestore/src/main/java/com/google/firebase/firestore/FirestoreRegistrar.java, firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java, firebase-firestore/src/main/java/com/google/firebase/firestore/SetOptions.java, firebase-firestore/src/main/java/com/google/firebase/firestore/UserDataConverter.java, firebase-firestore/src/main/java/com/google/firebase/firestore/auth/package-info.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/package-info.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/package-info.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/package-info.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/package-info.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/value/package-info.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/package-info.java, firebase-firestore/src/main/java/com/google/firebase/firestore/util/package-info.java
Same as #266 and #270 but for Firestore.
I fixed a couple of places where we were missing the `@PublicApi` annotation. See cr/151329304 (internal) for reference.
Addresses #264
=> Add RestrictTo annotations to Firestore

firebase-database/CHANGELOG.md, firebase-database/src/main/java/com/google/firebase/database/core/utilities/encoding/CustomClassMapper.java, firebase-firestore/CHANGELOG.md, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/POJOTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/util/CustomClassMapper.java, firebase-firestore/src/test/java/com/google/firebase/firestore/util/MapperTest.java
This change adds custom error messages for BigDecimal, BigInteger, AtomicInteger, etc during serialization and deserialization. 
Note that we currently do throw errors as well.
- Deserialization:
Old:  "Unknown primitive type: class java.math.BigInteger"
New: "Could not deserialize object. Deserializing to BigInteger is not supported"
- Serialization: 
Old: "Invalid data. Unsupported type: java.math.BigInteger (found in field bigInteger)"
New: "Could not serialize object. BigInteger is not supported, please use int, long, float or double"
=> Reject non-standard Number classes during POJO serialization

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/POJOTest.java
Looks like #272 broke the Firestore Integration Tests, which I noticed in the failures for #277.
=> Fix Firestore POJO tests

firebase-database-collection/firebase-database-collection.gradle
In https://k8s-gubernator.appspot.com/build/android-ci/pr-logs/pull/firebase_firebase-android-sdk/277/connected-check-changed/1106453736609288192/ I see the following:
```
W0315 07:42:03.894] Execution failed for task ':firebase-database-collection:processDebugAndroidTestManifest'.
W0315 07:42:03.894] > Manifest merger failed : uses-sdk:minSdkVersion 9 cannot be smaller than version 14 declared in library [com.google.android.gms:play-services-base:16.0.1] /root/.gradle/caches/transforms-1/files-1.1/play-services-base-16.0.1.aar/23da706606c2023afc003c824e2c583b/AndroidManifest.xml as the library might be using APIs not available in 9
```
=> Bumping Database Collection Min SDK version to 14

firebase-storage/CHANGELOG.md, firebase-storage/firebase-storage.gradle, firebase-storage/src/main/java/com/google/firebase/storage/DeleteStorageTask.java, firebase-storage/src/main/java/com/google/firebase/storage/FileDownloadTask.java, firebase-storage/src/main/java/com/google/firebase/storage/FirebaseStorage.java, firebase-storage/src/main/java/com/google/firebase/storage/FirebaseStorageComponent.java, firebase-storage/src/main/java/com/google/firebase/storage/GetDownloadUrlTask.java, firebase-storage/src/main/java/com/google/firebase/storage/GetMetadataTask.java, firebase-storage/src/main/java/com/google/firebase/storage/StorageRegistrar.java, firebase-storage/src/main/java/com/google/firebase/storage/StreamDownloadTask.java, firebase-storage/src/main/java/com/google/firebase/storage/UpdateMetadataTask.java, firebase-storage/src/main/java/com/google/firebase/storage/UploadTask.java, firebase-storage/src/main/java/com/google/firebase/storage/internal/ExponentialBackoffSender.java, firebase-storage/src/main/java/com/google/firebase/storage/internal/Util.java, firebase-storage/src/test/java/com/google/firebase/storage/DeleteTest.java, firebase-storage/src/test/java/com/google/firebase/storage/DownloadTest.java, firebase-storage/src/test/java/com/google/firebase/storage/MetadataTest.java, firebase-storage/src/test/java/com/google/firebase/storage/PathingTest.java, firebase-storage/src/test/java/com/google/firebase/storage/StorageReferenceTest.java, firebase-storage/src/test/java/com/google/firebase/storage/TestUtil.java, firebase-storage/src/test/java/com/google/firebase/storage/UploadTest.java, tools/errorprone/src/main/java/com/google/firebase/errorprone/ComponentsAppGetCheck.java
This definitely falls under the umbrella "I don't know what I am doing". But here we go...
This follows the pattern in Firestore to register the component for Firebase Storage. It changes FirebaseStorage to only ever work with a single app, but keeps the option to get different instances for different storage buckets.
I also added `getInstanceImpl` as a valid name for the FirebaseApp.get() call, as I didn't want to add yet another `getInstance()` overload (which would result in an ambiguous null cast).
So what does everyone think? :)
=> Firebase Storage Component Registration

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/metrics/Metrics.java, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/metrics/MetricsPlugin.java
The change only exports metrics for "public" gradle tasks. The reason
for doing this is that we are hitting maximim quota limit of active
timeseries, which causes failure to upload metrics.
=> Reduce the number of metrics exported to stackdriver.

transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/GoogleTransportBackend.java, transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/GoogleTransportBackendTest.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/BackendRequest.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportFactoryImpl.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportImpl.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/ImmediateScheduler.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/TransportRuntimeTest.java
The PR changes the signature of `send()` to take `BackendRequest` as
parameter. This allows us to evolve the API in a backwards compatible
way in the furure.
prerequisite for b/128916710, b/129045832
=> Future-proof TransportBackend.

.opensource/project.json, docs/README.md, docs/ktx/common.md, docs/ktx/firestore.md
Main changes:
* Move the main page for this repo on firebaseopensource.com to be `docs/README.md` so we can present a less-technical overview.
* Add a new folder `docs` with subpages
* Add links to the main and KTX reference docs
cc @ashwinraghav @vkryachko we will need to actually fill out the content on KTX
=> Restructure docs for KTX

docs/README.md
Clicking on the "firebase-common" or the "firebase-firestore" links from the [firebase-android-sdk page](https://firebaseopensource.com/projects/firebase/firebase-android-sdk/) would redirect the user to GitHub to be able to see these pages.
Now, clicking on these links shows the respective pages, but still inside firebaseopensource.com (not redirecting to GitHub).
=> docs: fix ktx docs urls for firebaseopensource.com

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/GenerateCoveragePercentsTask.groovy, root-project.gradle, tools/apksize/apksize.gradle
Parse xml coverage reports. Extracts numbers and uploads to database.
Tested locally with below command:
```
./gradlew uploadCoverageMeasurements -Pdatabase_config=<path-to-database-config-file>
```
Note:
- Requires a new entry in Prow config to be enabled on CI.
- Needs some refactoring once we have a better idea on how to consolidate measurement collecting and uploading for different products on different platforms.
=> WIP: Calculate coverage measurements and upload to database.

smoke-tests/build.gradle, smoke-tests/src/database/AndroidManifest.xml, smoke-tests/src/database/java/com/google/firebase/testing/database/DatabaseTest.java, smoke-tests/src/storage/AndroidManifest.xml, smoke-tests/src/storage/java/com/google/firebase/testing/storage/StorageTest.java
This pull request adds new smoke tests for Database and Storage in a similar fashion as #319 did for Firestore.
=> Add new smoke tests for Storage and Database.

transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctTransportBackendTest.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/EventInternal.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/SendRequest.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportContext.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportFactoryImpl.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportImpl.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportRuntime.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/DefaultScheduler.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/ImmediateScheduler.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/Scheduler.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/AlarmManagerScheduler.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoScheduler.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/WorkScheduler.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/EventStore.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/PersistedEvent.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStore.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/TransportRuntimeTest.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoSchedulerTest.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/InMemoryEventStore.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/InMemoryEventStoreTest.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStoreTest.java
TransportContext generalizes the grouping of events that was previously
done by "backend". This is not sufficient as we'd want to start grouping
events by additional dimensions like: priority, api_key, etc.
The change is mostly forward-looking as it will allow us to simplify
storage upgrades as we implement more dimensions, priority being the
main one. And it boils down to modifying the table structure by:
* Rename the `backends` table to `transport_contexts`.
* Change its primary key from `backend_name` to auto increment integer.
* Change `events` foreign key to the new pk of `transport_contexts`.
* `events` no longer have `priority`.
=> Adds the concept of TransportContext.

.idea/copyright/Apache_2___Google.xml, firebase-datatransport/firebase-datatransport.gradle, firebase-datatransport/gradle.properties, firebase-datatransport/src/main/AndroidManifest.xml, firebase-datatransport/src/main/java/com/google/firebase/datatransport/TransportRegistrar.java, firebase-datatransport/src/main/java/com/google/firebase/datatransport/package-info.java, firebase-datatransport/src/test/java/com/google/firebase/datatransport/TransportRegistrationTest.java, subprojects.cfg
The library registers a `TransportFactory` as a component for other SDKs
to use.
=> Add firebase-datatransport library.

transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportRuntimeModule.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/EventStore.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/MaxStorageSize.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStore.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/InMemoryEventStore.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStoreTest.java
New events are dropped until old ones are discarded.
=> Add a limit on the maximum amount of storage the `events` database uses.

buildSrc/build.gradle, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/GenerateLicensesTask.groovy, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/LicenseResolver.groovy, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/LicenseResolverPlugin.groovy, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/ProjectLicense.groovy, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/ThirdPartyLicensesExtension.groovy, buildSrc/src/test/groovy/com/google/firebase/gradle/plugins/license/LicenseResolverPluginSpec.groovy
The implementation relied on an oss gradle plugin. The plugin had
several issues:
* Did not respect project level dependencies
* Did not respect some gradle configurations that propagate to the pom,
like runtimeOnly
* Had resolution issues where the order of task execution would affect
the outcome of the license report
* Failed the build for projects that have debug buildType disabled.
=> Re-implement 3p license inference implementation.

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationPlugin.groovy, firebase-functions/firebase-functions.gradle, gradle/googleServices.gradle, root-project.gradle
They are identical to "release" and not used by either our release or
smoke tests tooling.
=> Disable "debug" buildType in all android subprojects.

fiamui-app/src/main/AndroidManifest.xml, firebase-common-ktx/src/main/AndroidManifest.xml, firebase-database/src/main/AndroidManifest.xml, firebase-datatransport/src/main/AndroidManifest.xml, firebase-firestore-ktx/src/main/AndroidManifest.xml, firebase-firestore/src/main/AndroidManifest.xml, firebase-functions/src/main/AndroidManifest.xml, firebase-inappmessaging-display/src/main/AndroidManifest.xml, firebase-storage/src/main/AndroidManifest.xml, root-project.gradle, subprojects.cfg, tools/lint/lint.gradle, tools/lint/src/main/kotlin/LintChecks.kt, tools/lint/src/test/kotlin/LintChecksTest.kt, transport/transport-runtime/src/main/AndroidManifest.xml
The intent is to make sure teams don't forget to explicitly set the
attribute on Android components.
=> Add `android:exported` manifest lint check.

firebase-storage/src/main/java/com/google/firebase/storage/GetDownloadUrlTask.java, firebase-storage/src/main/java/com/google/firebase/storage/GetMetadataTask.java
This PR removes two `@PublicApi` annotations that annotate package-private classes.
=> Storage: Remove PublicApi from package-private classes

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/coverage/GenerateMeasurementsTask.groovy, buildSrc/src/test/groovy/com/google/firebase/gradle/plugins/measurement/apksize/ApkSizeJsonBuilderTest.groovy, buildSrc/src/test/groovy/com/google/firebase/gradle/plugins/measurement/apksize/ApkSizeTableBuilderTest.groovy, buildSrc/src/test/groovy/com/google/firebase/gradle/plugins/measurement/apksize/ApkSizeTestProject.groovy, tools/measurement/apksize/apksize.gradle, tools/measurement/coverage/coverage.gradle
- Rename coverage gradle tasks.
- Assign apk size gradle tasks into a new category "ApkSize"
to make them discoverable via `./gradlew tasks`.
- Misc clean up.
=> Metrics Collection Refactoring (2)

firebase-common/src/androidTest/java/com/google/firebase/FirebaseAppTest.java, firebase-common/src/main/java/com/google/firebase/FirebaseApp.java, firebase-common/src/main/java/com/google/firebase/internal/DataCollectionConfigStorage.java
The problem was that we were checking for direct boot with a call to
`Context#isDeviceProtectedStorage()` which would always return false as we
never requested a "device protected storage" context. The correct way to
detect direct boot mode is via `UserManager#isUserUnlocked()`.
Additionally the change switches data collection configuration
to use "direct boot" safe storage. It is fine from a security
perspective as we don't store any sensitive information in the config.
=> Fix direct boot mode handling (b/116149732).

firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
The error for a misconfigured default app should at least be a warning.
=> Changing error message for missing google-services from DEBUG to WARN

fiamui-app/src/main/AndroidManifest.xml
When exported is set to false, I get the following error:
04-18 11:58:55.151 1872-4043/system_process W/ActivityManager: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.example.firebase.fiamui/.MainActivity } from null (pid=10983, uid=2000) not exported from uid 10085
=> fiamui: Fix PermissionDenial in sample app

transport/transport-runtime/src/androidTest/aidl/com/google/android/datatransport/runtime/ITestRemoteLockRpc.aidl, transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/SynchronizationComponent.java, transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/MultiProcessSynchronizationGuardTest.java, transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/RemoteLockRpc.java, transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/TestService.java, transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/persistence/TestEventStoreModule.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportRuntimeComponent.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/DefaultScheduler.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/Uploader.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/EventStore.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/EventStoreConfig.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStore.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/synchronization/SynchronizationGuard.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/UploaderTest.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/InMemoryEventStore.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStoreTest.java
Lock timeout is no longer part of the interface and instead is an
implementation detail of SqliteEventStore.
=> Simplified synchronization guard interface.

firebase-firestore/CHANGELOG.md, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
Fixes: https://github.com/firebase/firebase-android-sdk/issues/370
When we migrate schemas with large datasets, we need to split our operations into multiple batches. Otherwise, we can exceed SQLite's CursorWindow.
This PR splits the three operations that potentially iterate through large datasets into batches. I have added tests that verify that the batching works, but I was not able to reproduce the original issue using the unit test. 
With this PR, I have been able to successfully migrate a schema in a test app that stored 10,000 documents. Without it, this migration fails with:
```
Caused by: java.lang.RuntimeException: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=15935, totalRows=4065
at …
```
=> Firestore: Split schema migrations into batches

smoke-tests/settings.gradle
Gradle 5 needs this file to distinguish project boundaries. We have no settings at the moment, so this file is blank.
=> Add settings.gradle to prep for Gradle 5

firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
context: b/70222712
Web SDK change: https://github.com/firebase/firebase-js-sdk/pull/1715
=> Adding documentation for WriteBatch size limit

root-project.gradle
Build variant of 'debug' was disabled in PR #312. Changed class
file lookup location in coverage calculation to be build type agnostic.
=> Fix issue for coverage report generation.

README.md, firebase-firestore/README.md
* The current link for `google-java-format` points to the IntelliJ site, which does not contain configuration information for setting up and enabling the plugin. The Github repo contains detailed setup instructions and links to other useful plugins as well.
* Importing the project for the first time and building in Android Studio causes the .xml files in `.idea/runConfigurations` to be deleted. Those files allow running Firestore tests from within Android Studio. Adding a message inside the Firestore package to point that out.
=> Update documentation for Code Formatting plugin and Firestore testing

tools/measurement/apksize/sdks.csv
Gradle is now building both the release and aggressive variants, so we need to accommodate that.
=> Update APK Size Tool to use release builds.

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/UploadMeasurementsTask.groovy, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/coverage/GenerateMeasurementsTask.groovy
Log the shell command executed for uploading metrics.
=> Discard coverage info if sdk name not defined in mappings.

smoke-tests/build.gradle, smoke-tests/src/combined/AndroidManifest.xml, smoke-tests/src/combined/java/com/google/firebase/testing/combined/AllTests.java
This adds a new build flavor to the smoke tests. The combined flavor includes the other flavors enabling us to test with a single executable and verify they build together. The individual variants can still be used to test products individually.
=> Add combined flavor to smoke tests

firebase-firestore/src/androidTest/AndroidManifest.xml
Without this, the integration tests fail within google3.
=> Add ACCESS_NETWORK_STATE to androidTest build.

subprojects.cfg
This fixes our release pipeline, which fails to pick up maven group id otherwise
=> Explicitly add `transport` to enabled projects

smoke-tests/README.md, smoke-tests/build.gradle, smoke-tests/configure.gradle
This change adds support to use a Bill of Materials to run the smoke tests. The Bill of Materials contains the versions of the Firebase libraries that should be used.
=> Add support for Bill of Materials to smoke tests.

firebase-firestore/src/main/java/com/google/firebase/Timestamp.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/value/TimestampValue.java, firebase-firestore/src/test/java/com/google/firebase/TimestampTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/UserDataConverterTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/model/FieldValueTest.java
Reorganize to make things clearer:
* Split out the tests that are really exercising the `UserDataConverter` into a `UserDataConverterTest`.
* Move the Timestamp tests that are unrelated to `FieldValue` into `TimestampTest`
Also fix nullability annotations on `Timestamp`.
=> Clean up FieldValueTests

firebase-common/proguard.txt
Component registrars are only referenced from metadata attributes in manifest
files, which can lead to them getting stripped by Proguard otherwise, resulting
in component lookup failures at runtime.
=> Keep all component registrars

firebase-functions/src/androidTest/backend/functions/package.json
Functions package.json must specify the engine.
https://firebase.google.com/docs/functions/manage-functions#set_nodejs_version
=> Add missing engine param in package.json (functions/tests)

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/LicenseResolverPlugin.groovy
Instead rely on the type of the task.
=> Decouple license resolver from bundle task name.

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/publish/Publisher.groovy, buildSrc/src/test/groovy/com/google/firebase/gradle/plugins/publish/PublishingPluginSpec.groovy
Namely:
* Exclude multidex from POMs
* Set dependency scope to compile
* Properly set dependency type(jar, aar) based on resolved artifact name
=> Properly handle pom dependencies.

smoke-tests/build.gradle
This change allows the smoke tests to pull Bill of Materials files from
the local Maven repository used by the main Firebase project.
=> Enable importing Bill of Materials from local Maven.

firebase-storage/src/main/java/com/google/firebase/storage/CancellableTask.java, firebase-storage/src/main/java/com/google/firebase/storage/ControllableTask.java, firebase-storage/src/main/java/com/google/firebase/storage/OnPausedListener.java, firebase-storage/src/main/java/com/google/firebase/storage/OnProgressListener.java, firebase-storage/src/main/java/com/google/firebase/storage/StorageException.java, firebase-storage/src/main/java/com/google/firebase/storage/StorageTask.java, firebase-storage/src/main/java/com/google/firebase/storage/StorageTaskManager.java, firebase-storage/src/main/java/com/google/firebase/storage/TaskListenerImpl.java, firebase-storage/src/main/java/com/google/firebase/storage/network/ResumableUploadCancelRequest.java, firebase-storage/src/test/java/com/google/firebase/storage/UploadTest.java
This fixes all Google3 Lint errors in this code:
Field name is CONSTANT_CASE, but field is not static and final
http://go/errorprone/bugpattern/ConstantField
Type Parameter TListenerType must be a single letter with an optional numeric suffix, or an UpperCamelCase name followed by the letter 'T'.
http://go/java-style#s5.2.8-type-variable-names
In Google Style, unlike Android Style, field names with special prefixes like mName and sName are not used.  Google3 Android code must follow Google Style.
http://go/errorprone/bugpattern/FieldPrefixes
Overloads of '*' are not grouped together; found ungrouped overloads on line(s): 800
http://go/java-style#s3.4.2.1-overloads-never-split
=> Storage Copybara: Fixing lint errors

firebase-storage/src/main/java/com/google/firebase/storage/internal/AdaptiveStreamBuffer.java
Fixes:
A summary fragment is required; consider using the value of the @return block as a summary fragment instead.
http://go/java-style#s7.2-summary-fragment
A block tag (@param, @return, @throws, @deprecated) has an empty description. Block tags without descriptions don't add much value for future readers of the code; consider removing the tag entirely or adding a description.
http://go/java-style#s7.1.3-javadoc-block-tags
=> Storage Copybara: Fix Javadoc

firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctionsException.java
When throwing `new HttpsError('not-found')` in a cloud function (ie: [without specifying `message` parameter](https://firebase.google.com/docs/reference/functions/functions.https.HttpsError)), `error.opt("message")` will be just an empty string, so:
- `error.opt("message") instanceof String` is `true`
- `details` will be assigned to `""`.
- `new FirebaseFunctionsException(description, code, details)` will be called with this empty string
- it will throws a `Detail message must not be empty` exception.
With this change,  `details` will be equal to whatever `code.name()` returns when the cloud function sends an empty string as a message. In the case of `HttpsError('not-found')`, it will be `NOT_FOUND`.
=> Ignore empty message string in FirebaseFunctionsException

tools/measurement/apksize/apksize.gradle, tools/measurement/coverage/coverage.gradle
Fix failing task `:tools:measurement:apksize:preFirestoreAggressiveBuild`.
Make coverage task depend on only firebase product check tasks.
The tasks dependency graph previously looks like:
```
:tools:measurement:coverage:uploadCoverageMeasurements
\--- :tools:measurement:coverage:generateCoverageMeasurements
+--- :fiamui-app:checkCoverage
|    \--- :fiamui-app:check ..>
+--- :firebase-common:checkCoverage
|    \--- :firebase-common:check ..>
+--- :firebase-database:checkCoverage
|    \--- :firebase-database:check ..>
+--- :firebase-database-collection:checkCoverage
|    \--- :firebase-database-collection:check ..>
+--- :firebase-datatransport:checkCoverage
|    \--- :firebase-datatransport:check ..>
+--- :firebase-firestore:checkCoverage
|    \--- :firebase-firestore:check ..>
+--- …
```
=> Fix for coverage collection.

firebase-storage/src/androidTest/java/com/google/firebase/storage/IntegrationTest.java, firebase-storage/src/test/java/com/google/firebase/storage/ListTest.java, firebase-storage/src/test/java/com/google/firebase/storage/RetryRule.java, firebase-storage/src/test/java/com/google/firebase/storage/network/NetworkLayerMock.java, firebase-storage/src/testUtil/java/com/google/firebase/storage/TestDownloadHelper.java, firebase-storage/src/testUtil/java/com/google/firebase/storage/TestUploadHelper.java
=> Copybara Storage: Fix Storage Lint

firebase-storage/src/test/java/com/google/firebase/storage/TestUtil.java, firebase-storage/src/test/java/com/google/firebase/storage/network/MockConnectionFactory.java
=> Storage Copybara: Fixing ErrorProne Warnings

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/RemoteLicenseFetcher.groovy
My fix in #484 changed the way the Apache license was handled, and all
whitespace was stripped from this popular license. Essentially, the
original code fetched it directly with the URL class while the other
licenses were fetched with Jsoup.
This commit restores this behavior. This has the unfortunate side-effect
of re-introducing boilerplate code, but it's the most cost-effective
solution for now.
=> Fix Apache license fetching.

firebase-common/ktx/src/test/kotlin/com/google/firebase/ktx/Tests.kt, firebase-common/src/androidTest/java/com/google/firebase/FirebaseAppTest.java, firebase-common/src/androidTest/java/com/google/firebase/FirebaseOptionsTest.java, firebase-common/src/test/java/com/google/firebase/components/ComponentRuntimeTest.java, firebase-common/src/test/java/com/google/firebase/components/ComponentTest.java, firebase-common/src/test/java/com/google/firebase/components/LazyTest.java, firebase-common/src/test/java/com/google/firebase/components/RestrictedComponentContainerTest.java, firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/FirestoreTests.kt, firebase-functions/ktx/src/test/kotlin/com/google/firebase/functions/ktx/FunctionsTests.kt, root-project.gradle, smoke-tests/build.gradle
They behave identically, and the old names are being removed.
This requires updating to Truth 0.44 or higher, so I've gone straight to 0.45.
=> Migrate from is(Not)SameAs to is(Not)SameInstanceAs.

firebase-storage/src/main/java/com/google/firebase/storage/StorageTaskManager.java
Fixes a couple of build warnings:
third_party/firebase/android/firebase_storage_api/src/com/google/firebase/storage/StorageTaskManager.java:75: warning: [rawtypes] found raw type: StorageTask
public void ensureRegistered(StorageTask targetTask) {
^
missing type arguments for generic class StorageTask<ResultT>
=> Add type arguments in StorageTaskManager

buildSrc/build.gradle, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/AffectedProjectFinder.groovy, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationPlugin.groovy, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/SmokeTestsPlugin.groovy, root-project.gradle
This effort replaces #494 by generating a list of artifacts instead of selectively publishing them. The `publishAllToBuildDir` task now produces an extra JSON file containing the names of all published artifacts. It also includes the artifacts that are affected by the most recent commit.
Our compatibility testing infrastructure will be able to use this listing to build two variants of the tests: one against head and the other against the latest release (except for the affected artifacts).
=> Output artifact list during local publishing.

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java, root-project.gradle
This fixes Android Studio issue, where it is impossible to run
integration tests in debug mode.
Additionally move build type configuration to FirebaseLibraryPlugin to
avoid projects.all configuration in gradle.
=> Set test type to release only in CI.

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/FieldPath.java
In particular, it *is* allowed to have slashes, etc in field paths, but you need to use FieldPath.of to do so.
=> Minor fix to error message to match the admin sdk.

smoke-tests/build.gradle
This change allows the smoke tests to clean all build variants created
by the infrastructure.
=> Added clean task to smoke tests.

firebase-firestore/ktx/ktx.gradle, firebase-firestore/ktx/src/test/java/com/google/firebase/firestore/TestAccessHelper.java, firebase-firestore/ktx/src/test/java/com/google/firebase/firestore/TestUtil.java, firebase-firestore/ktx/src/test/java/com/google/firebase/firestore/testutil/TestUtil.java
firebase-firestore-ktx currently has dependencies on `testUtil` and `roboUtil` from firebase-firestore. This causes Gradle build to fail when building firebase-firestore.
A temporary workaround is to give ktx its own copy of the files until the dependencies are resolved.
=> Copy firebase-firestore-ktx dependencies on firestore into its own subfolder

root-project.gradle
Code coverage can fail for local builds, becuase there are multiple
definitions for the same classes (debug and release). On CI, debug is
disabled. This change forces the coverage check to use on release
builds, thus making it compatible with both local and CI use cases.
This fixes the problem presented in #531.
=> Restrict coverage collection to release builds.

transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java, transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctTransportBackendTest.java
When the device is offline its active NetworkInfo is null, this causes
an NPE and fails to record events.
=> Fix offline transport handling.

smoke-tests/build.gradle, smoke-tests/configure.gradle, smoke-tests/src/combined/java/com/google/firebase/testing/combined/AllTests.java, smoke-tests/src/remoteConfig/java/com/google/firebase/testing/remoteconfig/RemoteConfigTest.java
This change boosts the default smoke test versions for local runs and adds three Remote Config tests to the smoke test suite.
=> Add Remote Config smoke tests.

smoke-tests/build.gradle, smoke-tests/configure.gradle
This commit generalizes the path to the parent repository which contains
the m2repository for the smoke tests.
=> Generalize parent repository logic.

firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
=> Backporting documentation changes

firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
FirebaseFirestore.java is causing check to fail due to formatting errors.
=> Fix FirebaseFirestore formatting.

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
Notes for @mikelehen:
- I'm not a huge fan of `validateAndCalculateReferenceValue`, but I'm not sure how else to refactor it without having almost identical code copied.
- The error messages for IN queries are now slightly off. What is the best way to customize messages for IN queries using documentIds? At this point, if we want different error messages, is it better to just have separate code blocks instead of trying to force the logic into a refactored `validateAndCalculateReferenceValue`?
=> Allow IN queries with arrays of documentIds

smoke-tests/build.gradle, smoke-tests/src/combined/java/com/google/firebase/testing/inappmessaging/InappMessagingTest.java
Inapp Messaging does not have an interface to trigger updates from the
device. As a result, this test simply verifies intialization and build
compatibility.
However, the latest release of Inapp Messaging is build incompatible
with the head state of AB Testing. As such, this test is disabled for
now.
=> Add Inapp Messaging smoke test.

smoke-tests/build.gradle, smoke-tests/gradle.properties, smoke-tests/infrastructure-rules.pro, smoke-tests/smoke-test-rules.pro, smoke-tests/src/androidTest/java/com/google/firebase/testing/common/SmokeTestSuite.java
This change adds the necessary proguard files and a configuration block
for release builds. However, this change does not yet enable testing
against the release build.
=> Add Proguard Files to Smoke Tests

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/FirebaseLibraryExtension.java, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/FirebaseStaticAnalysis.java, buildSrc/src/test/groovy/com/google/firebase/gradle/plugins/publish/PublishingPluginSpec.groovy, firebase-abt/firebase-abt.gradle, firebase-common/data-collection-tests/data-collection-tests.gradle, firebase-common/firebase-common.gradle, firebase-config/firebase-config.gradle, firebase-database/firebase-database.gradle, firebase-datatransport/firebase-datatransport.gradle, firebase-firestore/firebase-firestore.gradle, firebase-inappmessaging-display/firebase-inappmessaging-display.gradle, firebase-storage/firebase-storage.gradle, gradle.properties, protolite-well-known-types/protolite-well-known-types.gradle, root-project.gradle, tools/lint/lint.gradle, tools/lint/src/main/kotlin/CheckRegistry.kt, tools/lint/src/main/kotlin/KotlinInteropDetector.kt, tools/lint/src/main/kotlin/ManifestElementHasNoExportedAttributeDetector.kt, tools/lint/src/test/kotlin/ManifestTests.kt, transport/transport-api/transport-api.gradle, transport/transport-backend-cct/transport-backend-cct.gradle, transport/transport-runtime/transport-runtime.gradle
The checks are copied from the official lint checks, and modified to
only check public Firebase APIs, e.g. those that don't have @hide
javadoc tag in either of the following:
* The javadoc of the symbol
* The javadoc of the host class
* The javadoc of containing package-info.java
=> Add Kotlin Interop lint checks.

firebase-firestore/CHANGELOG.md, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ServerTimestampTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/TransactionTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/Transaction.java
- Standardize errors based on the spreadsheet.
- Remove local validation for document not found in transactions.
- Checking that the transaction hasn't been committed should be an assert.
=> Throw last failed attempt's error in failed transactions

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/GrpcCallProvider.java
This fixes the "Running on the wrong queue" assertion that is sometimes triggered when an integration test uses two Firestores (callees of [testCollectionWithDocs()](https://github.com/firebase/firebase-android-sdk/blob/70d4388d08ca08e608a38850716435ebe87cabed/firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java#L297)).
I am not 100% certain what leads to this behavior, but the problem is that https://github.com/grpc/grpc-java/blob/f3bf250a46571db3321fc3078b55e74280bdfd87/core/src/main/java/io/grpc/internal/DelayedClientTransport.java#L294 doesn't have the executor sets and then chooses the default executor, which seemingly can be from another instance.
=> Fix flaky integration tests

firebase-storage/src/test/java/com/google/firebase/storage/DependencyTest.java
This causes a CommonTypo validation failure in the Copybara CL 257313292
=> Fix typo in Storage test

firebase-storage/src/main/java/com/google/firebase/storage/StorageTaskManager.java, firebase-storage/src/test/java/com/google/firebase/storage/internal/MockSleeperHelper.java, firebase-storage/src/testUtil/java/com/google/firebase/storage/TestCommandHelper.java, firebase-storage/src/testUtil/java/com/google/firebase/storage/TestDownloadHelper.java, firebase-storage/src/testUtil/java/com/google/firebase/storage/TestUploadHelper.java, firebase-storage/src/testUtil/java/com/google/firebase/storage/network/MockInputStreamHelper.java
Continuing my quest to fix the violations reported in https://critique.corp.google.com/#review/257313292
=> Fix JavaStyle violations for Storage

firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java, firebase-storage/src/main/java/com/google/firebase/storage/StreamDownloadTask.java, firebase-storage/src/main/java/com/google/firebase/storage/network/NetworkRequest.java, firebase-storage/src/test/java/com/google/firebase/storage/DependencyTest.java, firebase-storage/src/test/java/com/google/firebase/storage/RetryRule.java, firebase-storage/src/test/java/com/google/firebase/storage/TestUtil.java, firebase-storage/src/test/java/com/google/firebase/storage/network/MockConnectionFactory.java
Fixes the warnings in the newest sync from https://critique.corp.google.com/#review/257313292
Skips suggestions that require API Level 19 (using UTF_8 from nio) and the suggested migration to go/truth.
=> Fixing more Storage code style issues

firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryMutationQueue.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryPersistence.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MutationQueue.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/RemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteMutationQueue.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLitePersistence.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/StatsCollector.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/AccumulatingStatsCollector.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/MemoryLocalStoreTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/PersistenceTestHelpers.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteLocalStoreTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteQueryCacheTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SQLiteSpecTest.java
This PR adds a pretty-bare bones way to export document read counts from the RemoteDocumentCache and the MutationQueue. I will use this in more thorough tests once we start optimizing our query execution.
The different ways to construct the Persistence layer are getting a little out of hand. I think a good follow up would be to add Builders for some of the classes here and address the overload overload.
=> Expose operation counts from Persistence layer

firebase-functions/src/main/java/com/google/firebase/functions/HttpsCallOptions.java
This commit resolves #604 by setting both the read and call timeouts.
The connect and write timeouts are left at their default values of 10
seconds.
=> Fix timeouts in Functions.

firebase-abt/firebase-abt.gradle, firebase-abt/src/main/java/com/google/firebase/abt/component/package-info.java, firebase-abt/src/main/java/com/google/firebase/abt/package-info.java, firebase-database/CHANGELOG.md, firebase-database/src/main/java/com/google/firebase/database/FirebaseDatabase.java, firebase-functions/src/main/java/com/google/firebase/functions/HttpsCallOptions.java
A/B Testing doesn't have user visible classes, so they should be  annotated with javadoc's @hide.
=> @Hide abt public classes

root-project.gradle
Files ignored are those class files within a "proto/" directory when generated. Generated files in other 
directories are still being counted.
=> Ignore some proto generated files from coverage.

firebase-firestore/CHANGELOG.md
Add changelog for https://github.com/firebase/firebase-android-sdk/pull/621.
https://github.com/firebase/firebase-android-sdk/pull/621 also fixed https://github.com/firebase/firebase-android-sdk/issues/155
=> Add CHANGELOG for latency-compensated query fix

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/AccessHelper.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java, firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/FirestoreMultiDbComponent.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/GrpcCallProvider.java, firebase-firestore/src/main/java/com/google/firebase/firestore/util/AsyncQueue.java, firebase-firestore/src/test/java/com/google/firebase/firestore/util/AsyncQueueTest.java, tools/errorprone/src/main/java/com/google/firebase/errorprone/ComponentsAppGetCheck.java
1. FirebaseApp delete calls firestore shutdown.
2. Deregister firestore when shutdown is called, new instance can then be registered.
3. Synchronize AsyncQueue.Executor scheduling. Also make it stop handling most of schedule requests once it is shutdown, only tasks originated from shutdown itself and clearPersistence can proceed.
=> Prepare `shutdown` to be a public api.

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/TransactionTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/Transaction.java
Porting over from [web](https://github.com/firebase/firebase-js-sdk/pull/1980).
=> Fix preconditions in transactions

smoke-tests/build.gradle, smoke-tests/runner.config
This change adds the new configuration, which will soon be used by the
runner. This imcreases flexibility by allowing GitHub changes to
immediately affect how the runner operates on CI.
Additionally, this change tweaks the build file to allow testing against
release builds. This will be live once the new runner is deployed.
=> Add new config file for smoke tests.

firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexFreeQueryEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexFreeQueryEngineTest.java
This is the fifth of six PR for "index-free" queries.
This PR adds a new Query Engine that uses the optimization of index-free queries and first loads the documents from the RemoteDocumentCache that the backend considers matching.
The Query Engine is not used/activated.
=> Index-Free (5/6): Add Index-Free Query Engine

transport/transport-backend-cct/gradle.properties, transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java, transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctTransportBackendTest.java, transport/transport-backend-cct/transport-backend-cct.gradle, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportRuntime.java
* Fix data race in initialize().
The issue is that we were not doing the double-checked locking properly,
which could manifest in instantiating multiple instances of
TransportRuntime due to concurrent calls to initialize().
* Set custom user-agent on requests to CCT.
=> Various updates to datatransport

firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java
The default timeout of 5 seconds is way too short. The network is not
guaranteed to be in a good state, and this may cause apps to crash
unexpectedly. This is the source of some flakiness in tests as well.
This change increases the timeout to 30 seconds. Updates are infrequent
and run in the background, so this should not be a problem.
Edit: The timeout is now changed to 60 seconds to match the iOS implementation.
=> Increase Remote Config's default timeout.

firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
I want to revert the schema change in https://github.com/firebase/firebase-android-sdk/pull/615 so that is not yet part of the release.
=> Revert "Add update_time to SQLRemoteDocumentCache schema"

firebase-common/src/main/AndroidManifest.xml
Firebase itself does not initialize in direct-boot mode and only does so
when the device is unlocked.
While this works most of the time, there are apps that initializeApp()
manually when in direct boot mode and this causes component discovery to
fail(b/138578076).
The change marks ComponentDiscoveryService as directBootAware so that
components are able to be discovered. Whether components are able to
function in direct boot mode is up to each SDK implementation and is
currently provided as best effort.
=> Make component discovery directBootAware

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/GrpcCallProvider.java
We no longer need the overrideChannelBuilder to connect to the emulator.
=> Remove overrideChannelBuilder

firebase-database/src/main/java/com/google/firebase/database/core/utilities/DefaultRunLoop.java
This PR updates the public facing error message that the RTDB shows when all else fails.
It special-cases NoClassDefFoundErrors as these are very common lately (due to the changes in Auth integration) and generally recommends GitHub over our email for any other issues.
=> Update RTDB Error message to point to GitHub

firebase-database/CHANGELOG.md, firebase-database/src/androidTest/java/com/google/firebase/database/DataTest.java, firebase-database/src/androidTest/java/com/google/firebase/database/FirebaseDatabaseTest.java, firebase-database/src/androidTest/java/com/google/firebase/database/RealtimeTest.java, firebase-database/src/main/java/com/google/firebase/database/core/utilities/ParsedUrl.java, firebase-database/src/main/java/com/google/firebase/database/core/utilities/Utilities.java, firebase-database/src/test/java/com/google/firebase/database/core/utilities/ParseUrlTest.java
We need to specify the namespace to connect to the Firestore Emulator from an Android Emulator.
With this change, a connection to the Emulator can be made by specifying a database URL such as "http://10.0.2.2:9000/?ns=foo". I ended up using Android URI parser over Java's since it has built in support for query param.
The new unit tests (some of them are old and moved from the integration test suite) pass with bold the old and the new parser.
Note that this PR drops the path segment encoding since I am no longer roundtripping through URL to get the database path.
=> Add support for /?ns= query param in Database URL

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/FirebaseLibraryExtension.java, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java, buildSrc/src/test/groovy/com/google/firebase/gradle/plugins/publish/PublishingPluginSpec.groovy, firebase-datatransport/firebase-datatransport.gradle, firebase-inappmessaging-display/firebase-inappmessaging-display.gradle, gradle.properties, protolite-well-known-types/protolite-well-known-types.gradle, transport/transport-api/src/main/java/com/google/android/datatransport/package-info.java, transport/transport-api/transport-api.gradle, transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/package-info.java, transport/transport-backend-cct/transport-backend-cct.gradle, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/backends/package-info.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/package-info.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/package-info.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/package-info.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/package-info.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/synchronization/package-info.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/time/package-info.java, transport/transport-runtime/transport-runtime.gradle
Teams can explicitly opt-out by either adding `@hide` to affected
packages or modifying `android.lintOptions`.
=> Remove custom DSL to disable kotlin checks.

firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryLruReferenceDelegate.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryData.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteLruReferenceDelegate.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LruGarbageCollectorTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/remote/MockDatastore.java, firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
Added the QueryData "with..." helper as suggested in https://github.com/firebase/firebase-android-sdk/pull/616
=> Add QueryData.with() helpers

firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryLruReferenceDelegate.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/RemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexedQueryEngineTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LruGarbageCollectorTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/RemoteDocumentCacheTestCase.java
This PR updates index-free queries to use readTime instead of updateTime, which allows us to pick up documents that matched a given query at the Query's snapshot version but were not part of the query's limit (see spec test: "Resumed limit queries use updated documents")
=> Index-Free: Using readTime instead of updateTime

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java, firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryMutationQueue.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MutationQueue.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteMutationQueue.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
Added 'waitForPendingWrites' to firestore.
=> awaitPendingWrites initial revision

firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexedQueryEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/RemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLitePersistence.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SimpleQueryEngine.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/RemoteDocumentCacheTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
This is the fourth of six PRs for "index-free" queries.
This PR adds the ability to `getAllDocumentsMatchingQuery()` to skip documents older than a given update time. This allows us to only scan for documents that have been modified since the Query's Target Mapping has been persisted.
=> Index-Free (4/6): Filter document queries by read time

firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
This PR makes sure we don't write documents to the RemoteDocumentCache that have a version of 0. This allows us to add an assert in the Index-Free query branch and also makes sure that we don't just persist NoDocuments because of RPC failures.
=> Don't persist manufactured documents

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/EventManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java
* Allow user to stop listening after shutdown
* EventManager.removeQueryListener should return void
* add missing check for callback existence in EventManager
=> Allow user to stop listening after shutdown + other minor fixes.

firebase-firestore/CHANGELOG.md, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/TransactionTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/TransactionRunner.java, firebase-firestore/src/main/java/com/google/firebase/firestore/util/AsyncQueue.java, firebase-firestore/src/main/java/com/google/firebase/firestore/util/ExponentialBackoff.java
Good call on recommending that I try and implement Android first before merging web. This has a been a painful, but educational experience.
A couple things about Android:
- The recursive method seemed like the only viable option here, since we cannot await backoffs in the same thread as the one calling it (something that I realized after a bit too much struggling). That being said, I still think the web approach is cleaner and more readable compared to Android. How do you feel about keeping the implementations different? I'm also not sure how I would port the whole `TaskCompletionSource` strategy used by Android for recursion over to web.
- The `skipDelaysForTimerIds` approach of web doesn't port over to Android b/c it relies on `runDelayedTasksUntil`, which blocks until the delay is …
=> Retrying transactions with backoff

firebase-firestore/ktx/src/test/java/com/google/firebase/firestore/TestUtil.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/QueryListener.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/View.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/ViewSnapshot.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalViewChanges.java, firebase-firestore/src/roboUtil/java/com/google/firebase/firestore/TestUtil.java, firebase-firestore/src/test/java/com/google/firebase/firestore/QuerySnapshotTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryListenerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/ViewSnapshotTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/ViewTest.java
Despite what we talked about offline, I still think we need to only advance the last limbo free snapshot version if the query is CURRENT. This is because we only calculate Limbo documents when we are in sync in the server. While we don't persist resume tokens for queries that aren't CURRENT, we do persist the remaining query data (including the lastLimboFreeSnapshot). We should not do that unless we are CURRENT.
=> Only advance the limbo free snapshot if query is synced

firebase-storage/CHANGELOG.md, firebase-storage/src/main/java/com/google/firebase/storage/StorageReference.java, firebase-storage/src/test/java/com/google/firebase/storage/ListTest.java, firebase-storage/src/test/resources/activitylogs/listAllFailed_network.txt, firebase-storage/src/test/resources/activitylogs/listAllFailed_task.txt, firebase-storage/src/test/resources/activitylogs/listSinglePageFailed_network.txt, firebase-storage/src/test/resources/activitylogs/listSinglePageFailed_task.txt, firebase-storage/src/testUtil/java/com/google/firebase/storage/TestCommandHelper.java, firebase-storage/test-app/src/main/java/com/example/storage/MainActivity.java, firebase-storage/test-app/test-app.gradle
Turns out that we didn't propagate backend errors for ListAll, instead the Task would just hang.
Fixes https://b.corp.google.com/issues/139533387
=> Propagate error for ListAll

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClientTest.java
UTF-8 characters are not being parsed correctly on fetches from the backend. Explicitly specifying the Character set resolves this issue.
Unit tests added as well to prevent a recurrence of this issue.
=> Fix issue with UTF8 strings in RC SDK 19.0.0

firebase-database-collection/src/main/java/com/google/firebase/database/collection/ImmutableSortedMap.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/remote/RemoteStoreTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexFreeQueryEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexedQueryEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SimpleQueryEngine.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexFreeQueryEngineTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexedQueryEngineTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/MemoryLocalStoreTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteLocalStoreTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/spec/QueryEvent.java, firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
This is the last PR with index-free logic. It, however, doesn't turn it on yet (and is still against the indexfree-master branch).
There are a fair bit of comments in the code to explain how it all works. The only other thing worth pointing out is that I updated the LocalStoreTests to run parameterized with different query engine, which changed some of the plumbing during the test setup.
I verified that the Spec tests pass with the IndexFreeQueryEngine, but also left those running against the SimpleQueryEngine to match the code in production.
=> Add Index-Free query engine

firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
This PR removes the unused `limboTargets` param and updates the test `testThrowsAwayDocumentsWithUnknownTargetIDsImmediately` to actually return `null` from `getQueryDataForTarget` for the inactive target.
=> Remove unused parameter from LocalStore tests

docs/README.md, docs/ktx/functions.md
I do realize the functions-ktx library hasn't been released yet, so maybe this should only be merged after its release.
=> feat: add docs for functions-ktx

firebase-firestore/api.txt
This should remove the additional messages for every Firestore PR. InstanceRegistry was never officially part of our public API.
=> Update API text file

firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
I blame this one on @mikelehen 
The basic thought process behind is that we don't need to backfill any read times. When a user upgrades, none of the QueryData will have a lastLimboFreeSnapshot version set. Once we have a lastLimboFreeSnapshot, we know that the target mapping can be relied upon. Any changes since the target mapping will have a read time.
Thoughts? Fears?
=> Index-free: Use different SQL for non-index free queries

firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
If we don't want to backfill the read time, we need to ensure that all documents written after any last limbo free snapshot version need to already have a read time. Since that is not the case if a user downgrades, we should clear all limbo free snapshot versions when the user upgrades again.
=> Index-free: Drop last limbo free snapshot if re-upgraded

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/apksize/ApkSizeJsonBuilder.groovy, buildSrc/src/test/groovy/com/google/firebase/gradle/plugins/measurement/apksize/ApkSizeJsonBuilderTest.groovy
This PR is part of the effort of migrating apk size measurement database to the same one used by ios/android project health metrics.
New tables have been created with a different name (with the prefix of "Android"). This change accommodates to the table name change on the database server side. The PR that switches the database to upload is [here](https://team-review.git.corp.google.com/c/firebase-android-core/test-infra/+/537770). These two PRs will need to be submitted together.
Records in the old database/table will later be migrated to the new database/table manually.
=> Migrate apk size table to metrics database.

firebase-config/api.txt, firebase-config/gradle.properties, firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
Synchronous setDefaults methods should be marked as deprecated, there are two of them and [one](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java#L543) is already marked as deprecated. This PR adds the deprecated annotation to the other one.
=> Add missing deprecation annotation to synchronous setDefaults method

transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java, transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctTransportBackendTest.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/retries/Function.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/retries/Retries.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/retries/RetryStrategy.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/retries/package-info.java
Redirects are followed up to 4 times(after initial request).
=> Add http redirect support to the cct transport backend.

firebase-common/lint-baseline.xml, firebase-common/src/main/AndroidManifest.xml
This attr had to be removed in https://github.com/firebase/firebase-android-sdk/pull/728 because a bug in the tooling that has been fixed now.
=> Re-add tools:targetApi to firebase-common AndroidManifest.

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/GrpcCallProvider.java
Reverts the part of firebase/firebase-android-sdk#678 that is still used in Google3.
=> Revert "Remove overrideChannelBuilder"

firebase-storage/api.txt, firebase-storage/src/androidTest/java/com/google/firebase/storage/IntegrationTest.java, firebase-storage/src/main/java/com/google/firebase/storage/ListResult.java, firebase-storage/src/main/java/com/google/firebase/storage/StorageException.java, firebase-storage/src/main/java/com/google/firebase/storage/StorageMetadata.java, firebase-storage/src/main/java/com/google/firebase/storage/StorageReference.java, firebase-storage/src/main/java/com/google/firebase/storage/UpdateMetadataTask.java, firebase-storage/src/main/java/com/google/firebase/storage/UploadTask.java, firebase-storage/src/main/java/com/google/firebase/storage/internal/Slashes.java, firebase-storage/src/main/java/com/google/firebase/storage/network/GetNetworkRequest.java, firebase-storage/src/main/java/com/google/firebase/storage/network/ListNetworkRequest.java, firebase-storage/src/main/java/com/google/firebase/storage/network/NetworkRequest.java, firebase-storage/src/main/java/com/google/firebase/storage/network/ResumableUploadStartRequest.java
- Use `getReference()` helper in all Integration test.
- Use `Uri.encode()` since it doesn't throw exceptions (and follows the existing encoding of spaces to %20 everywhere)
- Remove unnecessary parenthesis
- Remove JSONException that is never thrown
- Stop using deprecated FirebaseException constructor, instead we pass in the detailed message
=> Random code cleanup for Storage

firebase-database/CHANGELOG.md, firebase-database/src/main/java/com/google/firebase/database/tubesock/WebSocket.java
This seems to be the minimal fix to not crash apps when Tubesock encounters any exception.
I'm torn on whether we should port this back to https://github.com/FirebaseExtended/TubeSock since I am not 100% confident in our release pipeline over in that repo.
Fixes: https://github.com/firebase/firebase-android-sdk/issues/672
=> Don't crash app on WebSocket error

transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportContext.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/TransportContextTest.java
A recent PR introed a regression where calling `withPriority` would not
preserve the `extras` value. This change addresses that issue.
=> Fix `TransportContext#withPriority(Priority)`.

firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java
Ports the fix from firebase/firebase-ios-sdk#3752.
=> Avoid double-counting key sizes in memory LRU GC

transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/backends/BackendRegistryModule.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/backends/CreationContextFactory.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/backends/MetadataBackendRegistry.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/backends/BackendRegistryTest.java
Since the `backendName` property was introduced to `CreationContext`, it
can no longer be a singleton, but rather needs to vary based on the
requested `backendName`.
Additionally the change makes BackendRegistry more testable.
=> Fix CreationContext propagation to TransportFactories.

firebase-storage/CHANGELOG.md, firebase-storage/src/androidTest/java/com/google/firebase/storage/IntegrationTest.java, firebase-storage/src/main/java/com/google/firebase/storage/GetDownloadUrlTask.java, firebase-storage/src/main/java/com/google/firebase/storage/UploadTask.java, firebase-storage/src/main/java/com/google/firebase/storage/internal/Slashes.java, firebase-storage/src/main/java/com/google/firebase/storage/network/GetNetworkRequest.java, firebase-storage/src/main/java/com/google/firebase/storage/network/ListNetworkRequest.java, firebase-storage/src/main/java/com/google/firebase/storage/network/NetworkRequest.java, firebase-storage/src/main/java/com/google/firebase/storage/network/ResumableUploadByteRequest.java, firebase-storage/src/main/java/com/google/firebase/storage/network/ResumableUploadCancelRequest.java, firebase-storage/src/main/java/com/google/firebase/storage/network/ResumableUploadQueryRequest.java, firebase-storage/src/main/java/com/google/firebase/storage/network/ResumableUploadStartRequest.java, firebase-storage/src/test/java/com/google/firebase/storage/UploadTest.java, firebase-storage/src/test/resources/activitylogs/uploadWithUnicode_network.txt, firebase-storage/src/test/resources/activitylogs/uploadWithUnicode_task.txt, firebase-storage/src/testUtil/java/com/google/firebase/storage/TestUploadHelper.java, firebase-storage/test-app/src/main/java/com/example/storage/MainActivity.java
Fixes b/139750197
This PR makes sure that we always encode query parameters and always use the decoded path if we process them further.
=> Don't double escape list references

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/SmokeTestsPlugin.groovy
This change replaces the names of the artifact sets produced by the `assembleAllForSmokeTests` task. This is to better integrate with the upcoming changes to the smoke test runner.
=> [Smoke-tests] Switch artifact set names.

firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
This removes the sophisticated logic to determine whether we need to persist query data in `releaseQuery()` as LRU GC bumps the sequence number and always persists the query when the reference is removed.
=> Don't double save Query Data

firebase-firestore/ktx/src/test/java/com/google/firebase/firestore/TestUtil.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/QueryListener.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/View.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/ViewSnapshot.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalViewChanges.java, firebase-firestore/src/roboUtil/java/com/google/firebase/firestore/TestUtil.java, firebase-firestore/src/test/java/com/google/firebase/firestore/QuerySnapshotTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryListenerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/ViewSnapshotTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/ViewTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
`synced` is always `!fromCache`, so we don't need it.
=> Remove newly redundant synced flag

smoke-tests/runner.config
This change updates the smoke tests to use the latest release of Firebase.
=> [Smoke-tests] Update latest release.

firebase-firestore/src/test/resources/json/persistence_spec_test.json
I think I ported this over before, but it's being copied over when I generate the spec test json. I think it may be due to Andy's shutdown work on web.
=> Port over clearPersistence spec test changes

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/EventManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/QueryListener.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/EventManagerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java, firebase-firestore/src/test/resources/json/listen_spec_test.json
Porting from [web](https://github.com/firebase/firebase-js-sdk/pull/2100).
=> Adding onSnapshotsInSync (not public)

firebase-database/CHANGELOG.md, firebase-database/src/main/java/com/google/firebase/database/core/utilities/encoding/CustomClassMapper.java, firebase-database/src/test/java/com/google/firebase/database/MapperTest.java
CustomClassMapper can now handle GenericTypeIndicators with wildcards, instead of strictly requiring the type specified.
=> Add support for wildcards on the CustomClassMapper.

firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
This reverts commit a011927f9dde549ad6d1195e8e168675d40d741a.
=> Revert "Simplify IndexFree tests (#790)"

firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexFreeQueryEngine.java
This reverts commit 7c942114520307b18b5c8d7ddc6d6818662b000b.
=> Revert "Add logging for query mode (#776)"

smoke-tests/runner.config
This change sets the bill of materials version to RELEASE. The runner
has been updated to fetch the latest release from GMaven when this is
set.
=> [Smoke-tests] Enable automated release workflow.

firebase-firestore/CHANGELOG.md, firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java
This PR removes the assert that causes a crash for one of our customers: 
```
Caused by: java.lang.AssertionError: INTERNAL ASSERTION FAILED: Cannot add document to the RemoteDocumentCache with a read time of zero
at com.google.firebase.firestore.g.b.a(com.google.firebase:firebase-firestore@@21.1.0:46)
at com.google.firebase.firestore.g.b.a(com.google.firebase:firebase-firestore@@21.1.0:31)
```
This is the first step in fixing this issue. As a follow up, we have to fix the underlying root cause and clean up all affected data.
=> Remove Index-Free assert

firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
If there is a chance that a limbo resolution fails for a document that no longer exists, we could get into a state where we write a document into the RemoteDocumentCache with a snapshot version of zero. By re-ordering the statements, we make sure this does not happen
=> Change the order of checks in applyRemoteEvent()

firebase-firestore/CHANGELOG.md, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteLruReferenceDelegate.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LruGarbageCollectorTestCase.java
This applies the same fix as https://github.com/firebase/firebase-android-sdk/pull/374 to orphan document removal. I used the same batch size since both operations just read document kets.
Fixes https://github.com/firebase/firebase-android-sdk/issues/706
=> Split orphaned document GC into batches

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/apksize/ApkSizeTableBuilder.groovy, buildSrc/src/test/groovy/com/google/firebase/gradle/plugins/measurement/apksize/ApkSizeTableBuilderTest.groovy
The table now shows sizes right aligned and with thousand-delimiters for easier reading.
For example
```
|--------------------        APK Sizes        ------------------|
|---    project    ---|--  build type   --|--  size in bytes  --|
|firestore            |aggressive         |              902,019|
|database             |aggressive         |              421,788|
|functions            |aggressive         |              550,057|
|inappmessagingdisplay|aggressive         |            1,714,661|
|storage              |aggressive         |              341,995|
|config               |aggressive         |              390,261|
```
=> Better format the table generated by generateApkSizeMeasurements

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/aarsize/AarSizeJsonBuilder.groovy, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/aarsize/AarSizeTableBuilder.groovy, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/aarsize/GenerateMeasurementsTask.groovy, tools/measurement/apksize/apksize.gradle, tools/measurement/apksize/default.gradle, tools/measurement/apksize/sdks_ignore.csv
The new task `generateAarSizeMeasurements` generates either a table or a JSON report with the size, in bytes, of the release AAR generated by each subproject. It follows the same logic, and has the same flags, as `generateApkSizeMeasurements`.
=> Implement AAR size measurement.

root-project.gradle
Among other updates, it fixes the API variant.getJavaCompile() obsolete warning. For more info about the changes see the CHANGELOG https://github.com/google/protobuf-gradle-plugin/releases
=> Update protobuf plugin to the latest version.

firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexFreeQueryEngine.java
This ports the documentation and the internal changes to IndexFreeQueryEngine from the Web port.
=> Update IndexFreeQueryEngine with changes from Web

firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexFreeQueryEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexedQueryEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryResult.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SimpleQueryEngine.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/CountingQueryEngine.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexFreeQueryEngineTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
From Index-Free feedback on Web (https://github.com/firebase/firebase-js-sdk/pull/2169)
=> Backport executeQuery() API changes

transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/SchedulingModule.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/AlarmManagerScheduler.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/AlarmManagerSchedulerTest.java
AlarmManager expects time to be specified as milliseconds since epoch, instead of the ms since when invoked.
=> Fix AlarmManagerScheduler timestamp computation.

firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
There is no timeout for HttpsURLConnection. Rayo mentioned other FIS SDKs  timeout after 10s.
=> Enabling FIS network call timeout.

firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
On Android, when one of the values passed into `setDefaults*(Map<String, Object>)` is of type `byte[]`, the code calls `toString()` on the byte array, which returns a specially-formatted string representation of the array such as `"[B@4df982e"` for the byte array `{0x06,0x00,0x00,0x06,0x07,0x03}`.
Later on, when getByteArray is called, it returns a byte array containing the string representation that was passed in (e.g. the bytes of the string `"[B@4df982e"`) rather than the bytes of the original byte array that was passed in.
=> Fix ByteArray issue with setDefaults and setDefaultsAsync

firebase-config/bandwagoner/src/main/java/com/googletest/firebase/remoteconfig/bandwagoner/MainApplication.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java
1. Fix Strict Mode Violation
2. Explicitly turn strict mode on in Firebase Remote Config's Android test app.
We received a user report of [Strict Mode](https://developer.android.com/reference/android/os/StrictMode) issues with the Remote Config SDK since 19.0.0.
The stacktrace (see below) is very similar to a known issue that was fixed in the [OkHttp repo](https://github.com/square/okhttp/pull/24/files). My assumption is that Android's okhttp implementation hasn't picked up this fix yet.
To ensure we catch similar issues early on in the future, this PR also turns on Strict Mode in Remote Config's test app.
```
Caused by: java.lang.Throwable: Explicit termination method 'end' not called
at dalvik.system.CloseGuard.open(CloseGuard.java:221)
at …
```
=> Fix Remote Config Strict Mode Violation that might be caused by Android okhttp implementation

transport/transport-backend-cct/transport-backend-cct.gradle, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStore.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStoreTest.java
Instead returning the same context multiple times that is equal to the
number of pending events for that context.
=> Fix getActiveContexts to return unique contexts.

firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
This PR re-adds the asserts we reverted out in v21.10.1 and drops the last limbo free Snapshot Version for any query data that has been written with v21.10.1.
=> Index-Free: Drop last limbo free snapshot version for schema v9

smoke-tests/src/main/AndroidManifest.xml, smoke-tests/src/main/java/com/google/firebase/testing/BuildOnlyTest.java, smoke-tests/src/main/java/com/google/firebase/testing/DatabaseTest.java, smoke-tests/src/main/java/com/google/firebase/testing/DynamicLinksTest.java, smoke-tests/src/main/java/com/google/firebase/testing/FirestoreTest.java, smoke-tests/src/main/java/com/google/firebase/testing/FunctionsTest.java, smoke-tests/src/main/java/com/google/firebase/testing/RemoteConfigTest.java, smoke-tests/src/main/java/com/google/firebase/testing/StorageTest.java, smoke-tests/src/main/java/com/google/firebase/testing/TestSuite.java
This changes places all of the tests into a single package. There is no
reason to separate them and have one file per package.
This change also renames AllTests to TestSuite, as that better
identifies its purpose.
=> [Smoke-tests] Move tests into a single package.

smoke-tests/local-runner.config
Thsi change adds a modified version of the config file that is suitable
for local runs of the smoke tests.
=> [Smoke-tests] Add local config file.

firebase-installations-interop/api.txt, firebase-installations-interop/src/main/java/com/google/firebase/installations/InstallationTokenResult.java, firebase-installations/src/androidTest/java/com/google/firebase/installations/FirebaseInstallationsInstrumentedTest.java, firebase-installations/src/androidTest/java/com/google/firebase/installations/FisAndroidTestConstants.java, firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java, firebase-installations/src/main/java/com/google/firebase/installations/GetAuthTokenListener.java, firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
Updating getAuthToken to return creation timestamp along with authToken and
expiration timestamp.
=> Updating getAuthToken to return creation timestamp

firebase-installations/api.txt, firebase-installations/src/androidTest/java/com/google/firebase/installations/FirebaseInstallationsInstrumentedTest.java, firebase-installations/src/androidTest/java/com/google/firebase/installations/FisAndroidTestConstants.java, firebase-installations/src/androidTest/java/com/google/firebase/installations/local/PersistedInstallationEntrySubject.java, firebase-installations/src/androidTest/java/com/google/firebase/installations/local/PersistedInstallationTest.java, firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java, firebase-installations/src/main/java/com/google/firebase/installations/GetAuthTokenListener.java, firebase-installations/src/main/java/com/google/firebase/installations/GetIdListener.java, firebase-installations/src/main/java/com/google/firebase/installations/StateListener.java, firebase-installations/src/main/java/com/google/firebase/installations/Utils.java, firebase-installations/src/main/java/com/google/firebase/installations/local/PersistedInstallation.java, firebase-installations/src/main/java/com/google/firebase/installations/local/PersistedInstallationEntry.java
https://github.com/firebase/firebase-android-sdk/pull/888#discussion_r332817606
=> Addressing Rayo's comment: Rename PersistedFidEntry to PersistedInstallationEntry.

firebase-firestore/src/main/java/com/google/firebase/firestore/model/Document.java
=> Fix race condition when fieldValueCache is null

firebase-firestore/CHANGELOG.md, firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
If the credentials change listeners fires twice before we enqueue the client initialization on the AsyncQueue, `syncEngine` will be null in the credentials callback. This PR re-orders our initialization to make sure that the first thing we execute on the client is always `FirestoreClient.initialize()`.
Fixes https://github.com/firebase/firebase-android-sdk/issues/875
=> Fix race in credentialsProvider.setChangeListener

firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplay.java
#482 mentions a memory leak because we store a new instance of a class but don't clear it. It seems we don't need to store it at all. So let's not do that then.
=> Attempt to fix memory leak referenced in #482

docs/ktx/remote-config.md, firebase-config/api.txt, firebase-config/ktx/ktx.gradle, firebase-config/ktx/src/main/kotlin/com/google/firebase/remoteconfig/ktx/RemoteConfig.kt, firebase-config/ktx/src/test/kotlin/com/google/firebase/remoteconfig/ktx/RemoteConfigTests.kt, firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigSettings.java
Add Kotlin Extensions:
1. Building `FirebaseRemoteConfigSettings` objects 
```kotlin
val configSettings = remoteConfigSettings {
setMinimumFetchIntervalInSeconds(3600)
setFetchTimeoutInSeconds(60)
}
```
2. Setting Config Settings on a FirebaseRemoteConfig object
```kotlin
remoteConfig.setConfigSettingsAsync {
setMinimumFetchIntervalInSeconds(3600)
setFetchTimeoutInSeconds(60)
}
```
=> feat: add builder ktx for FirebaseRemoteConfigSettings

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClientTest.java
Modify ConfigFetchHttpClient so that metrics will be logged in Fetch even when the backend doesn't have an update.
=> Modify ConfigFetchHttpClient to log all successful Fetch calls.

firebase-installations/api.txt, firebase-installations/src/androidTest/java/com/google/firebase/installations/FirebaseInstallationsInstrumentedTest.java, firebase-installations/src/androidTest/java/com/google/firebase/installations/FisAndroidTestConstants.java, firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java, firebase-installations/src/main/java/com/google/firebase/installations/local/IidStore.java, firebase-installations/src/main/java/com/google/firebase/installations/local/PersistedInstallation.java
Reading iid from "com.google.android.gms.appid" shared pref
=> Reuse existing Iid as Fid

firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigRegistrar.java
This was added primarily as a performance boost, but we should be able to get the same performance benefit in most cases by just eagerly initializing only in the default app.
=> Switch Config to only eagerly initialize in default app

firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/Target.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryQueryCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryData.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteQueryCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/WatchChangeAggregator.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalSerializerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LruGarbageCollectorTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/QueryCacheTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteQueryCacheTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/remote/MockDatastore.java, firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
First PR to implement limitToLast on Android.
Corresponding JS PR: https://github.com/firebase/firebase-js-sdk/pull/2254
Future PR will be:
[2/3] Make SyncEngine able to handle Query/Target Mapping.
[3/3] Implement limitToLast
=> [1/3] Split Query and Target and make RemoteStore and LocalStore work with Targets

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/UploadMeasurementsTask.groovy, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/coverage/GenerateMeasurementsTask.groovy
Groovy classes are public by default, and fields/methods that are internal should be either private or marked as @internal. This PR addresses warnings from the groovy compiler.
=> Fix modifiers to address warnings

firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
Makes SyncEngine creates and maintains a potential 1:N mapping between Target and Query.
Tests for this has to be in the limitToLast PR because we need it to create those mappings.
=> [2/3] Make SyncEngine able to work with both Query and Target

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/View.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexFreeQueryEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/ViewTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexFreeQueryEngineTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
This PR implements limitToLast and adds unit and integration tests to test limitToLast and mirror queries.
We still have one more PR to do, which is make spec test work with both query and target and add a spec tests where backend rejects mirror queries.
=> [2.9/3] Implement limitToLast and add unit/integration tests.

firebase-config/bandwagoner/bandwagoner.gradle, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java
Previously, the Remote Config SDK would directly `put` a String Map of GA User Properties as value in the Fetch Request JSONObject. This is undocumented behavior as `JSONObject#put` doesn't accept a `Map` as a value: https://developer.android.com/reference/org/json/JSONObject.html#put(java.lang.String,%20java.lang.Object)
This was resulting in issues with API 19 and below https://github.com/firebase/firebase-android-sdk/issues/973
The solution is to create a JSONObject out of the Map (https://developer.android.com/reference/org/json/JSONObject.html#JSONObject(java.util.Map)), before passing that into the `put`.
As Integration tests were only run on API Level 26, this issue was not previously caught. As such, as part of this PR, we ensure that Integration Tests are run on API Level 16 as …
=> Pass User Properties to RC Fetch Request as a JSONObject

encoders/firebase-encoders/api.txt, encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/ObjectEncoderContext.java, encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/ValueEncoderContext.java, encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/json/JsonDataEncoderBuilder.java, encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContext.java, encoders/firebase-encoders/src/test/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContextTest.java
* primitive longs
* Enums with ability to register custom encoders if desired
* All java.lang.Number subclasses
Note that longs and all Numbers are represented as numeric values, not
strings. While this could be a problem when parsed with a JavaScript parser,
it is not an issue for us since JS is not involved on the client or the
server.
=> Add encoding support multiple types

encoders/firebase-encoders/api.txt, encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/config/Configurator.java, encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/config/EncoderConfig.java, encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/json/JsonDataEncoderBuilder.java, encoders/firebase-encoders/src/test/java/com/google/firebase/encoders/json/JsonDataEncoderBuilderTests.java
This allows clients to configure DataEncoders in a way that does not
couple them to a particular output format, e.g. json.
This mechanism will be used for auto-generated encoders in the future.
=> Add polymorphic encoder registration support.

encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/annotations/Encodable.java, encoders/firebase-encoders-processor/firebase-encoders-processor.gradle, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/EncodableProcessor.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/Encoder.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/Names.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/TypeTraversal.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/TypeVisitor.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/VisitResult.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/getters/Getter.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/getters/GetterFactory.java, encoders/firebase-encoders-processor/src/test/java/com/google/firebase/encoders/processor/EncodableProcessorTest.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedGenericsEncoder.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedRecursiveGenericEncoder.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedSimpleClassEncoder.java, encoders/firebase-encoders-processor/test-support/src/main/java/com, encoders/firebase-encoders-processor/test-support/test-support.gradle, root-project.gradle, subprojects.cfg
Supported features:
* Codegen is based on public java-bean style getters, fields are not encoded
directly
* Full support for generics
* Supports `java.util.Optional` via `value.getOrElse(null)`
* Fields can be marked as `@Encodable.Ignore` to skip them during encoding
* Fields can be marked as `@Encodable.Field(name="foo")` for custom encoded name
=> Adds code generation via `@Encodable` annotation.

encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/annotations/Encodable.java, encoders/firebase-encoders-processor/firebase-encoders-processor.gradle, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/EncodableProcessor.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/Encoder.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/Names.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/TypeTraversal.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/TypeVisitor.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/VisitResult.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/getters/Getter.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/getters/GetterFactory.java, encoders/firebase-encoders-processor/src/test/java/com/google/firebase/encoders/processor/EncodableProcessorTest.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedGenericsEncoder.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedRecursiveGenericEncoder.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedSimpleClassEncoder.java, encoders/firebase-encoders-processor/test-support/src/main/java/com, encoders/firebase-encoders-processor/test-support/test-support.gradle, root-project.gradle, subprojects.cfg
Supported features:
* Codegen is based on public java-bean style getters, fields are not encoded
directly
* Full support for generics
* Supports `java.util.Optional` via `value.getOrElse(null)`
* Fields can be marked as `@Encodable.Ignore` to skip them during encoding
* Fields can be marked as `@Encodable.Field(name="foo")` for custom encoded name
=> Adds code generation via `@Encodable` annotation. (#1029)

encoders/firebase-encoders-json/api.txt, encoders/firebase-encoders-json/src/json/java/com/google/firebase/encoders/json/JsonDataEncoderBuilder.java, encoders/firebase-encoders-json/src/test/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContextTest.java
Instead of throwing an error, we allow encoders to override previously registered ones.
=> Allow encoder registration override.

firebase-config/api.txt, firebase-firestore/api.txt, firebase-inappmessaging-display/api.txt, protolite-well-known-types/api.txt
=> Fix api files.

encoders/firebase-encoders-json/api.txt, encoders/firebase-encoders-json/src/json/java/com/google/firebase/encoders/json/JsonDataEncoderBuilder.java, encoders/firebase-encoders-json/src/json/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContext.java, encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/annotations/Encodable.java, encoders/firebase-encoders-reflective/api.txt, encoders/firebase-encoders-reflective/firebase-encoders-reflective.gradle, encoders/firebase-encoders-reflective/src/main/AndroidManifest.xml, encoders/firebase-encoders-reflective/src/main/java/com/google/firebase/encoders/reflective/ObjectEncoderProvider.java, encoders/firebase-encoders-reflective/src/main/java/com/google/firebase/encoders/reflective/ReflectiveObjectEncoder.java, encoders/firebase-encoders-reflective/src/main/java/com/google/firebase/encoders/reflective/ReflectiveObjectEncoderProvider.java, encoders/firebase-encoders-reflective/src/test/java/com/google/firebase/encoders/reflective/ReflectiveObjectEncoderTest.java, subprojects.cfg
The change introduces the concept of a "fallback" encoder that is used
for any type that does not have an explicitly registered encoder.
The reflective encoder itself is currently implemented in terms of
public getters and does not look at class fields, this can be made
configurable in the future.
=> Initial implementation of reflective encoder.

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/device/FirebaseTestServer.groovy
FTL tests started from local will upload artifacts/logs to the new
bucket. This avoids clutter in the bucket "android-ci".
=> Change the default FTL bucket to "fireescape-ftl-test-results".

firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
Fixed version number to identify Firebase Installations Android SDK in order to enable Instance-ID migration auth.
=> Fixed version number to identify Firebase Installations SDK

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/TransactionTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/Transaction.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/VerifyMutation.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java, firebase-firestore/src/proto/google/firestore/v1/write.proto, firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Port from [JS](https://github.com/firebase/firebase-js-sdk/pull/2436).
=> Add verify support

README.md, firebase-crashlytics-ndk/README.md
Add more detailed notes about how to set up the build environment
for Crashlytics NDK.
=> Update Crashlytics NDK README

firebase-config/ktx/ktx.gradle, firebase-config/ktx/src/test/kotlin/com/google/firebase/remoteconfig/TestConstructorUtil.kt, firebase-config/ktx/src/test/kotlin/com/google/firebase/remoteconfig/ktx/RemoteConfigTests.kt, firebase-config/src/androidTest/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigIntegrationTest.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandler.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/FakeInstanceIdResult.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigComponentTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandlerTest.java
Remote Config requires an IID token to evaluate certain conditions, but does not currently wait for the token from `FirebaseInstanceId#getToken()` before fetching. This returns the default condition value in some cases (ex. percentage conditions) rather than the evaluated result for an app instance.
This change replaces the use of the deprecated `#getToken()` with `#getInstanceId()`, which returns an async `Task` we can wait to complete before fetching, without otherwise blocking.
=> Get the IID token before fetching Remote Config.

firebase-firestore/src/main/java/com/google/firebase/firestore/UserDataConverter.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/Document.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/PatchMutation.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/TransformMutation.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/value/ObjectValue.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java, firebase-firestore/src/test/java/com/google/firebase/firestore/model/FieldValueTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/model/MutationTest.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
This PR is meant to pave the way for a mutable ObjectValue that is based on a Value.Builder. It proves that we only need `set()` and `delete()` (and not `equals()` and `compareTo()`) on the mutable type since most parts of the code still deal with immutable ObjectValues.
This is meant for an feature branch until we finish the Proto conversion as ObjectValue.Builder().set() is somewhat inefficient for nested field updates.
=> Add an ObjectValue builder

firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigSettings.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigMetadataClient.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigComponentTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigMetadataClientTest.java
At the moment, `FirebaseRemoteConfigSettings#FetchTimeoutInSeconds` is used only to set the HTTP Connection timeout, and there's no way for a developer to set the Read timeout (Definitions in http://stackoverflow.com/q/3069382)
To match RC iOS behavior, we use the FetchTimeout value for both the Connection and Read timeouts.
=> Use FetchTimeout value in Remote Config Connection and Read Timeouts

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
As I was porting arrayContainsAny, I noticed that I never included `docG` when instantiating the collection.
=> Fix typo in test

encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/getters/GetterFactory.java, encoders/firebase-encoders-processor/src/test/java/com/google/firebase/encoders/processor/EncodableProcessorTest.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedGenericsEncoderWithUnknownType.java
Until now it was possible to annotate non-generic classes with
`@Encodable`, while their properties could be generic with fully bound
type variables.
This change makes it possible to generate encoders for generic classes
with generic properties, but with a compiler warning.
Example:
```java
@Encodable
public class GenericClass<T, U> {
public T getT(); // warning generated
public U getU(); // warning generated
}
```
=> Add support for fully generic classes.

firebase-firestore/ktx/src/test/java/com/google/firebase/firestore/testutil/TestUtil.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/Document.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/PatchMutation.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/SetMutation.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/TransformMutation.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LruGarbageCollectorTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/model/DocumentTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/model/MutationTest.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
This basically reverts #561 since it will no longer be needed when all FieldValues expose the full Proto interface. It also brings back the old signature to the Document constructor.
=> Simplify Document

encoders/firebase-encoders-json/api.txt, encoders/firebase-encoders-json/src/json/java/com/google/firebase/encoders/json/JsonDataEncoderBuilder.java, encoders/firebase-encoders-json/src/json/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContext.java, encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/DataEncoder.java, encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/Encoder.java, encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/EncodingException.java, encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/ObjectEncoderContext.java, encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/ValueEncoderContext.java, encoders/firebase-encoders-json/src/test/java/com/google/firebase/encoders/json/JsonDataEncoderBuilderTests.java, encoders/firebase-encoders-json/src/test/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContextTest.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/EncodableProcessor.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedGenericsEncoder.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedGenericsEncoderWithUnknownType.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedRecursiveGenericEncoder.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedSimpleClassEncoder.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedTypeWithListEncoder.java, encoders/firebase-encoders-reflective/api.txt, encoders/firebase-encoders-reflective/src/main/java/com/google/firebase/encoders/reflective/ReflectiveObjectEncoder.java, encoders/firebase-encoders-reflective/src/main/java/com/google/firebase/encoders/reflective/ReflectiveObjectEncoderProvider.java, encoders/firebase-encoders-reflective/src/test/java/com/google/firebase/encoders/reflective/ReflectiveObjectEncoderTest.java, transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/AndroidClientInfoEncoder.java, transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/BatchedLogRequestEncoder.java, transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/ClientInfoEncoder.java, transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/LogEventEncoder.java, transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/LogRequestEncoder.java, transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/NetworkConnectionInfoEncoder.java, transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/internal/LogRequestTest.java
An error encoding a message is more likely to be unrecoverable than the other way around. Making EncoderException unchecked would reflect this case, instead of forcing teams to use the catch-log-rethrow pattern.
For reference, GSON does something similar
https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/JsonParseException.html
> This exception is a RuntimeException because it is exposed to the client. Using a RuntimeException avoids bad coding practices on the client side where they catch the exception and do nothing. It is often the case that you want to blow up if there is a parsing error (i.e. often clients do not know how to recover from a JsonParseException.
=> Make EncoderException a RuntimeException

firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java
There is a risk in the Protobuf FieldValue rewrite, so let's add a test to make sure we don't break the IDs.
=> Add test to verify canonical IDs are stable

firebase-firestore/src/main/java/com/google/firebase/firestore/model/value/ProtoValues.java, firebase-firestore/src/test/java/com/google/firebase/firestore/model/FieldValueTest.java
Adds a new format for canonical IDs of field values that is meant to be verifiable and stable.
=> Add explicit FieldValue canonicalization

codecov.yml
Mark as failures if the coverage drop is over a threshold.
=> Change coverage build status configuration.

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java
This test fails in my FieldValue rewrite when not run under the debugger.
I believe the failure is expected when the WatchStream acknowledges the Write before the WriteStream does. I see three snapshots:
```
isFromCache:true, hasPendingWrites:true
offlineCallbackDone.setResult()
Watch updates arrives
isFromCache:false, hasPendingWrites:true
We now try to set the result for `offlineCallbackDone` again, which raises an exception.
Write updates arrives
isFromCache:false, hasPendingWrites:false
onlineCallbackDone.setResult()
```
I believe a similar failure occurs today if the order is switched:
```
isFromCache:true, hasPendingWrites:true
offlineCallbackDone.setResult()
Write updates arrives
isFromCache:true, hasPendingWrites:false
onlineCallbackDone.setResult()
isFromCache:false, …
```
=> Fix queriesCannotBeSortedByAnUncommittedServerTimestamp test

firebase-firestore/CHANGELOG.md
Changelog PRs are the most fun.
=> Changelog for FieldValue change

firebase-crashlytics/firebase-crashlytics.gradle, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/ImmutableList.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/package-info.java, firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReportTest.java
New data model is an AutoValue data class representing the
hierarchical Crashlytics report data structure, to be used for
passing report data to the new Transport API. It is serialized
via the firebase-encoders-json `@Encodable` annotation.
=> Add new CrashlyticsReport data model

.idea/runConfigurations/Firestore_Unit_Tests.xml, firebase-firestore/firebase-firestore.gradle
Somewhat counterintuitively, robolectric has a dependency on protobuf-java, and occasionally our tests will all fail with messages about unable to find methods like `makeImmutable()` on our messages. This only happens with Android Studio's JUnit runner, not in Gradle.
We don't use any features that require this, so just exclude that dependency.
Also fix the runner definition to actually find tests.
=> Fix unit test running from within Android Studio

codecov.yml
- Change commit status for FirebaseCommon coverage to be informational.
- Change the syntax "default: off" to "default:". The former one seems no longer valid.
- Remove the table for affected files, which often contains noise.
=> Adjust coverage report format.

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/core/CrashlyticsControllerTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/BatteryStateTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCaptureTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/core/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/core/CrashlyticsCore.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/AppData.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/BatteryState.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCapture.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java
Handles capturing appropriate data from the underlying OS, build
information, and exception information and constructing
CrashlyticsReport and Event objects from it.
Moved AppData and BatteryState utility classes into the "internal"
package, since it was necessary to make them public anyway.
=> Add Crashlytics data capture class

firebase-database-collection/src/main/java/com/google/firebase/database/collection/ImmutableSortedSet.java, firebase-firestore/CHANGELOG.md, firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java
This is a port of https://github.com/firebase/firebase-js-sdk/pull/2624, to fix a performance regression.
=> Add unionWith to SortedSet.

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/send/DataTransportCrashlyticsReportSenderTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/send/DataTransportCrashlyticsReportSender.java
Rather than taking a callback in the constructor of the report
sender, just have the sendReport method return a task and let the
caller handle looping over multiple reports.
=> Return task from sendReport call

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/core/CrashlyticsCore.java
Previously, this could be overridden by end users, but the
override has been removed, rendering this prefix superfluous.
=> Remove D/FirebaseCrashlytics prefix from logs

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/FirebaseCrashlyticsReportManagerTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsLifecycleEvents.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/FirebaseCrashlyticsReportManager.java
Handles the interaction between Crashlytics lifecycle events and
crash reports (capture, persistence, and sending).
=> Add FirebaseCrashlyticsReportManager

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/FirebaseCrashlyticsReportManagerTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/FirebaseCrashlyticsReportManager.java
Also fix flaky test by passing a "same thread" executor
=> Pass executor into Crashlytics report manager

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/FirebaseCrashlyticsReportManagerTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistenceTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/FirebaseCrashlyticsReportManager.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
Replaces the concept of fatal/nonfatal in the persistence layer
with a persistence-specific concept of normal/high priority events.
This will be used to implement keeping a maximum number of logged
exceptions per session, without leaking information about specific
event types into the persistence layer.
=> Cap events-per-session in Crashlytics persistence

firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java, firebase-installations/src/main/java/com/google/firebase/installations/Utils.java, firebase-installations/src/test/java/com/google/firebase/installations/FirebaseInstallationsTest.java
FIS SDK is not aware of the real system time due to the "current time" was set once when the calendar instance got initialized (at app launches in our case). This bug makes FIS SDK not being able to fetch new AuthToken on time which causes 1M+ authentication fails on VerifyToken RPC call.
Note: this is a quick fix. Some affected tests removed should be brought back when @ankitaj224  is back to work.
=> Quick Fix: FIS SDK "current time" doesn't get update.

firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/internal/ShortDynamicLinkImpl.java
- Fix crash in Kotlin b/c `warnings` is null
- Add `toString` method to warnings to make printing them out easier
=> Fix ShortDynamicLinkImpl bugs

firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/internal/ShortDynamicLinkImpl.java, firebase-installations/src/main/java/com/google/firebase/installations/CrossProcessLock.java, firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
If the CrossProcessLock fails due to disk issues it will fail instead of throwing an exception.
As this should only happen due to issues like disk full or messed up permissions the FirebaseInstallations code will log and ignore any failure to get the log and move forward.
=> Make CrossProcessLock resilient to disk issues

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCapture.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java
Null values in these fields mean the data was missing, which in
the case of these fields, is a valid state.
- battery level
- background
- UUID
=> Make appropriate optional fields nullable

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClientTest.java
[`Locale#toLanguageTag`](https://developer.android.com/reference/java/util/Locale#toLanguageTag()) is preferred to [`Locale#toString`](https://developer.android.com/reference/java/util/Locale#toString()) for interchange purposes.
The Firebase backends expect a BCP-47 encoded language tag, which is produced by `Locale#toLanguageTag`, and not in all cases by `Locale#toString`.
=> Use Locale#toLanguageTag to properly encode IETF BCP 47 language tags.

firebase-crashlytics-ndk/src/main/AndroidManifest.xml, firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/CrashlyticsNdkRegistrar.java
Update to reflect new Firebase Crashlytics package name
=> Fix package name in Crashlytics NDK manifest

firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
Youtube observed this error on some devices when rolling out a new version. b/150526702
We were not able to reproduce this Exception, but found implementations of (Http)URLConnection that might return NULL for #getOutputStream.
The new code is preventing NPE and following the default error scenario that a connection to the FIS server API can not be established.
=> Catching NPE and throwing IOE instead.

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransformTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistenceTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCapture.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransform.java, firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReportTest.java
Enum value which should always be set to "3" for the Android SDK.
=> Add 'generator type' to CrashlyticsReport

firebase-crashlytics-ndk/firebase-crashlytics-ndk-proguard.txt, firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle, firebase-crashlytics-ndk/proguard.txt
Obfuscated apps which use Crashlytics NDK could experience a crash
on launch if the FirebaseCrashlytics class has been obfuscated. This
commit adds a proguard rule that gets packaged with the Crashlytics
NDK AAR, which prevents obfuscation of FirebaseCrashlytics.
=> Add proguard.txt for firebase-crashlytics-ndk

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/AnalyticsConnectorReceiver.java
We can infer the customer is on an outdated version of FA
if we cannot attach a listener with the "clx" origin. If
that is the case, use the old "crash" origin and write a
logcat warning with a nudge to upgrade.
=> Nudge customers to update if on an old Firebase Analytics

firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
- Include the file name in the error message of a failed spec test.
- Add log message for total test count in SpecTestCase.
=> Small logging improvements for spec tests.

firebase-firestore/src/main/java/com/google/firebase/firestore/UserDataWriter.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/Values.java
Port of https://github.com/firebase/firebase-js-sdk/pull/2766/commits/985d51491f0b5322f0c1139cb0f5f59d4ad7dc49
This PR has two versions: One without enums, and one with enums. Not sure how strongly we feel about avoiding them.
=> Backport ServerTimestamp type order changes

encoders/firebase-encoders-json/gradle.properties, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransformTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/BytesBackedNativeSessionFile.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsLifecycleEvents.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsUncaughtExceptionHandler.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/DataTransportState.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/FileBackedNativeSessionFile.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/MetaDataStore.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/UserMetadata.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/log/LogFileManager.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransform.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/report/ReportUploader.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/report/model/CreateReportRequest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/report/network/NativeCreateReportSpiCall.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/send/DataTransportCrashlyticsReportSender.java
Ensure data written to disk is cleaned up properly when
read/write/serialization errors occur.
=> Clean up error handling for report persistence

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/MetricsReportUploader.java
The branch information is used by the binary size dashboard.
This was written before coverage upload in `fireci` is implemented. I'll move this part of the logic to `fireci` as well when I get a chance. Right now, I want to make the data flow for dashboard work first.
=> Include branch information in metrics uploading.

firebase-installations/customer-lint-checks/customer-lint-checks.gradle, firebase-installations/customer-lint-checks/src/main/java/com/google/firebase/installations/lint/Checks.kt, firebase-installations/customer-lint-checks/src/main/java/com/google/firebase/installations/lint/IncompatibleIidVersionDetector.kt, firebase-installations/customer-lint-checks/src/test/java/com/google/firebase/installations/lint/VersionTests.kt
AGP 3.6 introduced a breaking change to lint-api making the check fail.
The change switch to use reflection to support both versions of the api.
Additionally the change makes the check failures more developer friendly
to make sure this check does not cause failures in upcoming AGP
versions.
Versions tested: 3.2 through 4.1.0-alpha04
Fixes #1407
=> Support AGP 3.6+ in the iid compatibility check.

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
No longer necessary due to backend upgrades
=> Remove organization ID from DataTransport payloads

firebase-database/CHANGELOG.md, firebase-database/api.txt, firebase-database/src/main/java/com/google/firebase/database/ServerValue.java
As per API proposal: go/servervalue-increment-api
=> Make ServerValue.increment() public

firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java, firebase-firestore/src/test/resources/json/collection_spec_test.json, firebase-firestore/src/test/resources/json/existence_filter_spec_test.json, firebase-firestore/src/test/resources/json/limbo_spec_test.json, firebase-firestore/src/test/resources/json/limit_spec_test.json, firebase-firestore/src/test/resources/json/listen_spec_test.json, firebase-firestore/src/test/resources/json/offline_spec_test.json, firebase-firestore/src/test/resources/json/orderby_spec_test.json, firebase-firestore/src/test/resources/json/persistence_spec_test.json, firebase-firestore/src/test/resources/json/query_spec_test.json, firebase-firestore/src/test/resources/json/remote_store_spec_test.json, firebase-firestore/src/test/resources/json/resume_token_spec_test.json, firebase-firestore/src/test/resources/json/write_spec_test.json
This change picks up changes to the spec tests, especially https://github.com/firebase/firebase-js-sdk/pull/2790, which renamed the "limboDocs" key in the JSON objects to "activeLimboDocs".
=> Update spec tests from changes in the firebase-js-sdk respository

firebase-firestore/src/main/java/com/google/firebase/firestore/remote/WatchChangeAggregator.java
Porting from [web](https://github.com/firebase/firebase-js-sdk/pull/2847).
=> Only iterate across active targets in WatchChangeAggregator

transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java, transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/LogResponse.java, transport/transport-backend-cct/transport-backend-cct.gradle
* Use a BufferedWriter which drastically speeds up json encoding, as the
encoder makes a lot of one-character writes so not buffering them
leads to significant uft-8 encoding overhead.
* Encode directly into the connection as opposed to an intermediate
byte array.
* Switch to try-with-resources for better resource safety
=> Optimize output stream encoding.

firebase-installations/API_KEY_RESTRICTIONS.md
Updated according to Stackoverflow question and latest MSA / developer outreach emails.
=> Update and improved instructions to fix API restrictions problem for FIS

firebase-firestore/CHANGELOG.md, firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java, firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java, firebase-firestore/src/test/resources/json/limbo_spec_test.json
This is a port of https://github.com/firebase/firebase-js-sdk/pull/2790 to Android.
The following description was copied from that PR and pasted here for your convenience:
This change was motivated by the following bug report: https://github.com/firebase/firebase-js-sdk/issues/2683.  In summary, the issue was that when a large number of documents went into limbo (in this case 15,000 documents) then this would cause 15,000 document listens, which would result in "resource-exhausted" errors.  The client would then back off for a bit but would try the listens again, which would again result in "resource-exhausted" errors.  And the cycle would continue.  Worst of all, the customer was being billed for all of these reads that had no beneficial effects for the clients.
In order to avoid this …
=> Implement limbo resolution listen throttling.

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/TransactionTest.java
Porting from [web](https://github.com/firebase/firebase-js-sdk/pull/2888).
=> Fix flaky transaction tests

firebase-crashlytics/firebase-crashlytics.gradle
- Exclude firebase-components because it is depended-upon locally.
=> Bump crashlytics to use the latest version of IID

transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStoreTest.java, transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/persistence/SpyEventStoreModule.java, transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/persistence/TestEventStoreModule.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/EventStoreConfig.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/EventStoreModule.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStore.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManager.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStoreTest.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManagerTest.java, transport/transport-runtime/transport-runtime.gradle
Large payloads are stored in a separate table as 80KB chunks of data keyed
by (sequence_num,event_id).
The motivation for the change is to avoid the Android SQLite
implementation limitation, that uses `CursorWindow`s of a limited size
that is unknown at runtime and vendors can change arbitrarily, hence the
conservative choice of 80KB instead of 2048KB that is present in AOSP
source code.
The way it manifests is that it is possible to write rows in the the db
that is impossible to read back as an exception gets thrown.
An altertative approach that was considered was to store file paths in
the DB and store blobs in the file-system. But that would introduce more
complexity to the storage system:
* Loss of ACID semantics, i.e. if we fail to commit we may fail to
delete the underlying file.
* …
=> Add large payload support to datatransport.

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/send/DataTransportCrashlyticsReportSenderTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/send/DataTransportCrashlyticsReportSender.java
DataTransport SDK will support larger payloads going forward, and
we will continue to iterate on more precise changes to reduce
payload sizes in the future.
DO NOT MERGE until DataTransport SDK upgrades are shipped: https://github.com/firebase/firebase-android-sdk/pull/1431
=> Remove hard limit on Crashlytics payload size

build.gradle, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ClosureUtil.java, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java, buildSrc/src/test/groovy/com/google/firebase/gradle/plugins/license/LicenseResolverPluginSpec.groovy, buildSrc/src/test/groovy/com/google/firebase/gradle/plugins/publish/PublishingPluginSpec.groovy, firebase-abt/firebase-abt.gradle, firebase-config/bandwagoner/bandwagoner.gradle, firebase-config/firebase-config.gradle, firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle, firebase-crashlytics/firebase-crashlytics.gradle, firebase-database/src/main/java/com/google/firebase/database/tubesock/WebSocket.java, firebase-firestore/firebase-firestore.gradle, firebase-firestore/ktx/ktx.gradle, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/AndroidConnectivityMonitor.java, firebase-functions/ktx/ktx.gradle, firebase-inappmessaging-display/firebase-inappmessaging-display.gradle, firebase-inappmessaging-display/ktx/ktx.gradle, firebase-inappmessaging/firebase-inappmessaging.gradle, firebase-storage/src/main/java/com/google/firebase/storage/network/NetworkRequest.java, sdkProperties.gradle, smoke-tests/build.gradle, transport/transport-api/transport-api.gradle, transport/transport-backend-cct/transport-backend-cct.gradle, transport/transport-runtime/transport-runtime.gradle
This change mostly addresses: https://github.com/robolectric/robolectric/issues/5456
=> Upgrade robolectric and target api 29.

README.md, build.gradle, firebase-abt/src/main/java/com/google/firebase/abt/FirebaseABTesting.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigConstants.java, gradle/errorProne.gradle
The motivation is that errorprone produces different bytecode than javac
this confuses retrolambda's desugaring where it fails to correctly
desugar try-with-resources.
To enable errorprone one needs to run:
```
./gradlew :mylib:mytask withErrorProne
```
=> Enable errorprone only by request.

firebase-common/firebase-common.gradle, transport/transport-api/proguard.txt, transport/transport-api/transport-api.gradle, transport/transport-backend-cct/proguard.txt, transport/transport-backend-cct/transport-backend-cct.gradle, transport/transport-runtime/proguard.txt, transport/transport-runtime/transport-runtime.gradle
=> Fix `@AutoValue`-related proguard issues.

firebase-inappmessaging/api.txt, firebase-inappmessaging/gradle.properties, firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessaging.java, firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/DataCollectionHelper.java, firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/SharedPreferencesUtils.java, firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingTest.java, firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/DataCollectionHelperTest.java, firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/SharedPreferencesUtilsTest.java
The new apis will be named as the existing setters are named and have a nullable Boolean.
The non-tri state api's is planned to be removed in the next breaking change release.
=> Add new version of setAutomaticDataCollectionEnabled api

transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/SafeLoggingExecutor.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/SafeLoggingExecutorTest.java
This is achieved by protecting the executor thread by a catch all. This
makes sure that failures are logged to logcat but do not cause the
underlying thread to crash itself.
Mitigates #1436 until a more detailed repro is provided.
=> Datatransport failures should not crash the app.

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
This is not a behavior change; it just clarifies the existing behavior in the javadoc.
=> Add clarifying javadoc to FirebaseCrashlytics#setCrashlyticsCollectionEnabled

firebase-firestore/src/main/java/com/google/firebase/firestore/core/ComponentProvider.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/MemoryComponentProvider.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/SQLiteComponentProvider.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/GarbageCollectionScheduler.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LruGarbageCollector.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/PersistenceTestHelpers.java, firebase-firestore/src/test/java/com/google/firebase/firestore/remote/MockDatastore.java, firebase-firestore/src/test/java/com/google/firebase/firestore/spec/MemorySpecTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SQLiteSpecTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
Ports the component provider from Web: https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/src/core/component_provider.ts
It also updates `FirestoreClient` and `SpecTestRunner` to use the new component provider. Note that the initialization in `FirestoreClient` is slightly different as there is no memory-only build, so we can decide much later which component provider to use.
=> Port ComponentProvider

docs/ktx/database.md, firebase-database/ktx/api.txt, firebase-database/ktx/src/main/kotlin/com/google/firebase/database/ktx/Database.kt, firebase-database/ktx/src/test/kotlin/com/google/firebase/database/DataSnapshotUtil.kt, firebase-database/ktx/src/test/kotlin/com/google/firebase/database/ktx/DatabaseTests.kt
This allows developers to use `mutableData.getValue<Post>()` instead of `mutableData.getValue(Post::class.java)` in Transactions.
=> feat(database-ktx): add reified function getValue() to MutableData

ci/fireci/fireci/uploader.py
This pull request addresses these two issues:
* Currently the metrics report is labeled with the commit hash from environment variable [`PULL_PULL_SHA`](https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#job-environment-variables). However, that is the hash of the PR head commit, but not the merge commit produced by [merging the PR head commit into the master branch](https://pantheon.corp.google.com/storage/browser/_details/android-ci/pr-logs/pull/firebase_firebase-android-sdk/1517/fireci/1255657197736562691/clone-log.txt?project=fireescape-c4819), which all the CI tests actually run against.
* Currently the `base_commit` is using the commit hash from `PULL_BASE_SHA`, which is not necessarily the most recent master commit at the time of test on CI. That misleads the metrics …
=> Use correct commit hashes when uploading metric reports.

ci/fireci/fireci/uploader.py
`capture_output` seems available only after python 3.7, but our CI is running 3.6.
https://docs.python.org/3.6/library/subprocess.html
=> Fix python subprocess call.

buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/AffectedProjectFinder.java, buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationPlugin.java
Regression introduced during java migration of build logic (#1516).
Essentially diff detection is missing required arguments `HEAD@{0} HEAD@{1}`
=> Fix "changed" tasks.

firebase-inappmessaging-display/firebase-inappmessaging-display.gradle, firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplay.java, firebase-inappmessaging-display/src/test/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplayTest.java, firebase-inappmessaging/api.txt, firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessaging.java, firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/DeveloperListenerManager.java, subprojects.cfg
Fixes: https://github.com/firebase/firebase-android-sdk/issues/1410
Fixes: https://github.com/firebase/firebase-android-sdk/issues/1092
=> Fix FIAM Display lifecycle interactions

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexedQueryEngineTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/model/ValuesTest.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/ComparatorTester.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Applying a bunch of G3 ErrorProne suggestions.
=> Add missing test annotation and ErrorProne suggestions.

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
Improves reliability of sending crash reports at crash time in the
case that the process would exit before Crashlytics has received
the asynchronous callback from DataTransport.
=> Wait for DataTransport callback task at crash time

transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManager.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManagerMigrationTest.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManagerTest.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/StateSimulations.java
#1548 evidences issues that we have with our Schema Manager when customers go back and forth between versions (here on referred to as Version Fluidity) Thanks @rafikhan .
These are our options:
1) We can either take Firestore's stand of being lossless when customers migrate back and forth between versions.
2) We can take a systematic cleanup approach that deletes *all* state when clients are migrated to older versions. 
We are leaning towards option 2
1. Given Firestore' s approach to preserve state, the advice from the API council was to take a similar approach.
2. Deleting old data might make in intractable to use Firelog for some use cases going foward. 
Design considerations
We have modified migrations (history), which is typically a red flag. However since we have modeled db creation …
=> Make schemas back and forth compatible

firebase-crashlytics-ndk/src/main/jni/Application.mk, firebase-crashlytics-ndk/src/main/jni/libcrashlytics/include/crashlytics/external/crashlytics.h, firebase-crashlytics-ndk/src/main/jni/libcrashlytics/include/crashlytics/handler/maps.h, firebase-crashlytics-ndk/src/main/jni/libcrashlytics/src/external/api.cpp
Remove unnecessary API implementation functions.
Fix warnings.
=> Fix a multiple-definition linker error in the native API.

encoders/firebase-decoders-json/api.txt, encoders/firebase-decoders-json/firebase-decoders-json.gradle, encoders/firebase-decoders-json/gradle.properties, encoders/firebase-decoders-json/src/main/AndroidManifest.xml, encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/Safe.java, encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/TypeToken.java, encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/TypeTokenContainer.java, encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/TypeTokenTest.java, subprojects.cfg
Initial Implementation of TypeToken for Decoder:
TypeToken will be used to represent types supported by the library in a type-safe manner.
=> inital implementation of typeToken for decoder

encoders/firebase-decoders-json/api.txt, encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/TypeToken.java, encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/TypeTokenContainer.java, encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/TypeTokenTest.java
- Changed `TypeTokenContainer` from an interface to a class.
- Changed field `typeArguments` of type `TypeTokenContainer` in non-generic `ClassToken` from null to an empty instance. 
- Changed `TypeToken` to throw an exception when a non-supported type `<? super Foo>` is passed to create a `TypeToken`, instead of throwing an exception only when trying to get the type arguments from it.
=> Changed TypeTokenContainer from interface to class

buildSrc/src/main/java/com/google/firebase/gradle/plugins/publish/Publisher.java
Removing them during iteration mutates the node list making us skip the
dep immediately following the removed dep.
=> Remove pom deps after iteration.

encoders/firebase-encoders-json/api.txt, encoders/firebase-encoders-json/src/json/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContext.java, encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/FieldDescriptor.java, encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/ObjectEncoderContext.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/EncodableProcessor.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/annotations/AnnotationBuilder.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/annotations/ToStringMethod.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/getters/AnnotationDescriptor.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/getters/AnnotationProperty.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/getters/Getter.java, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/getters/GetterFactory.java, encoders/firebase-encoders-processor/src/test/java/com/google/firebase/encoders/processor/EncodableProcessorTest.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedGenericsEncoder.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedMyClassEncoderWithExtraProperty.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedRecursiveGenericEncoder.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedSimpleClassEncoder.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedTypeWithListEncoder.java
The change updates `ObjectEncoderContext` with new overloads that use
`FieldDescriptors` and deprecates that ones that take `String` field names.
Additionally updates codegen logic in `firebase-encoder-processor` to
infer and use `FieldDescriptors`.
=> Add `FieldDescriptor` support to DataEncoder.

firebase-crashlytics/ktx/api.txt, firebase-crashlytics/ktx/build.gradle, firebase-crashlytics/ktx/gradle.properties, firebase-crashlytics/ktx/src/main/AndroidManifest.xml, firebase-crashlytics/ktx/src/main/kotlin/com/google/firebase/crashlytics/ktx/FirebaseCrashlytics.kt, firebase-crashlytics/ktx/src/main/kotlin/com/google/firebase/crashlytics/ktx/KeyValueBuilder.kt, firebase-crashlytics/ktx/src/test/java/com/google/firebase/crashlytics/ktx/CrashlyticsTests.kt, subprojects.cfg
Adding Kotlin Extensions for the new Crashlytics SDK :)
Not only this allows to use `Firebase.crashlytics`, but also setting custom keys:
```kotlin
Firebase.crashlytics.setCustomKeys(
"str_key" to "hello",
"bool_key" to true,
"int_key" to 1,
"long_key" to 1L,
"float_key" to 1.0f,
"double_key" to 1.0
)
```
=> feat: Implement firebase-crashlytics-ktx

firebase-firestore/CHANGELOG.md, firebase-firestore/src/main/java/com/google/firebase/firestore/auth/FirebaseAuthCredentialsProvider.java
Port of https://github.com/firebase/firebase-js-sdk/pull/3184
=> Refetch token if attempt was invalidated

firebase-inappmessaging-display/ktx/ktx.gradle
This makes fiam-ktx symbols available for developers without having them
to directly depend on both fiam-ktx and fiamd-ktx.
=> Have fiamd-ktx depend on fiam-ktx.

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
The user ID file will be missing if no user ID was set, so check
if it exists before trying to read from it to avoid unnecessary
error logging.
Fixes one of the prevalent issues in
https://github.com/firebase/firebase-android-sdk/issues/1559
=> Check for user ID file before trying to read it

encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/getters/GetterFactory.java
Reverts firebase/firebase-android-sdk#1649, as it was merged in the wrong order.
=> Revert "Revert "Restore Java 8 support in encoders lib""

transport/transport-runtime/transport-runtime.gradle
This is compatible with the way it's done in all other projects.
https://github.com/firebase/firebase-android-sdk/search?p=1&q=targetCompatibility&unscoped_q=targetCompatibility
=> Use the javaversion constant instead of string.

encoders/firebase-decoders-json/api.txt, encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/TypeToken.java, encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/TypeTokenTest.java
Move the `rawType` to `TypeToken` level instead of only inside `ClassToken` so that `ArrayToken` will also be able to get its raw type, which enables us to decode arrays of object.
Geting `Class<?>` type from `GenericArrayType` is not straightforward and hard, we will not support `GenericArrayType` for now.
=> Move `rawType` to `TypeToken`

firebase-functions/src/androidTest/java/com/google/firebase/functions/CallTest.java, firebase-functions/src/androidTest/java/com/google/firebase/functions/FirebaseFunctionsTest.java, firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.java, firebase-functions/src/main/java/com/google/firebase/functions/FunctionsMultiResourceComponent.java, firebase-functions/src/main/java/com/google/firebase/functions/FunctionsRegistrar.java
Follow up to #1672 but for `FirebaseFunctions`
=> Functions unified emulator settings

firebase-inappmessaging-display/api.txt, firebase-inappmessaging/api.txt
After the CI fix implemented in #1692 , the build in new PRs is failing because the current `api.txt` files from `in-app-messaging` and `in-app-messaging-display` are outdated:
```
> Task :firebase-inappmessaging:apiInformation FAILED
Aborting: Your changes have resulted in differences in the signature file
for the public API.
The changes may be compatible, but the signature file needs to be updated.
Diffs:
--- /home/prow/go/src/github.com/firebase/firebase-android-sdk/firebase-inappmessaging/api.txt	2020-06-22 16:47:15.984360721 +0000
+++ /home/prow/go/src/github.com/firebase/firebase-android-sdk/build/apiinfo/firebase-inappmessaging_api.txt	2020-06-22 16:52:35.872100325 +0000
@@ -18,7 +18,7 @@
method public void setAutomaticDataCollectionEnabled(boolean);
method public void …
```
=> chore(fiam + fiamd): re-generate api.txt files

transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java
- In cases where there is bad connection, the current behavior deletes the cached reports because they are caught as an `IOException`. They appear to be encoding errors, when in reality it's an error opening the `OutputStream` that is the connection.
- This changes it so that when the `IOException` is due to connection problems, we retry the upload instead of deleting it. 
This is where we transform status numbers into success, fatal, and transient errors: [CctTransportBackend.java](https://github.com/firebase/firebase-android-sdk/blob/master/transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java#L329-L356)
- 400-level errors (except 404) are treated as fatal errors, which are deleted
- 500-level errors are treated as transient errors, …
=> Retry GoogleDataTransport Connection Errors

transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStore.java
The current retry logic will delete an event after 10 retries,
which will only take ~17 minutes for high priority events.
If a device is on a bad network for that period of time, we could
relatively easily lose these events.
Increasing this to 16 will extend this timeframe to ~18 hours,
giving more opportunity for a retry to occur when the device has
a better network connection.
=> Increase number of retries before deleting events

firebase-database/src/main/java/com/google/firebase/database/FirebaseDatabase.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/AccessHelper.java, firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestoreSettings.java, firebase-firestore/src/test/java/com/google/firebase/firestore/FirebaseFirestoreTest.java
Follow up to #1672 but for `FirebaseFirestore`
Note:
- This now throws an `IlegalStateException` if the developer tries to set the host through the `EmulatedServiceSettings` as well as `FirebaseFirestoreSettings`.  The settings method already throws unchecked exceptions so I thought this was the correct behavior, but I could convert it to a warning.
=> Unified emulator settings for Firestore

firebase-common/api.txt, firebase-common/gradle.properties, firebase-common/src/main/java/com/google/firebase/FirebaseApp.java, firebase-common/src/main/java/com/google/firebase/emulators/EmulatedServiceSettings.java, firebase-common/src/main/java/com/google/firebase/emulators/EmulatorSettings.java, firebase-common/src/main/java/com/google/firebase/emulators/FirebaseEmulator.java, firebase-database/CHANGELOG.md, firebase-database/api.txt, firebase-database/gradle.properties, firebase-database/src/main/java/com/google/firebase/database/FirebaseDatabase.java, firebase-firestore/CHANGELOG.md, firebase-firestore/api.txt, firebase-firestore/gradle.properties, firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java, firebase-functions/api.txt, firebase-functions/gradle.properties, firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.java
Follow up to #1672 #1688 #1690
Questions:
=> Un-hide EmulatorSettings API

firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java, firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
Reported by Google Duo dog-fooding : b/158637349
=> Fixing NPE and correcting corresponding annotations.

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/Utils.java
It's possible that the task was not successful, was canceled or timed
out which should be checked before returning. Existing callers of this
method catch Exception so new exception types being thrown are safe.
=> check various task states before returning

firebase-database/ktx/src/test/kotlin/com/google/firebase/database/ktx/DatabaseTests.kt, firebase-dynamic-links/ktx/src/test/kotlin/com/google/firebase/dynamiclinks/ktx/DynamicLinksTests.kt, firebase-functions/ktx/src/androidTest/kotlin/com/google/firebase/functions/ktx/CallTests.kt, firebase-inappmessaging-display/ktx/src/test/kotlin/com/google/firebase/inappmessaging/display/ktx/InAppMessagingDisplayTests.kt, firebase-inappmessaging/ktx/src/test/kotlin/com/google/firebase/inappmessagging/ktx/InAppMessaggingTests.kt, firebase-storage/ktx/src/test/kotlin/com/google/firebase/storage/ktx/StorageTest.kt
=> Klint test fixes.

firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
Without the parenthesis, the link is broken.
=> Add missing parenthesis to link.

firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java, firebase-installations/src/main/java/com/google/firebase/installations/GetIdListener.java
Revert "Completing getId call with the disk reads on the caller thread."
This reverts commit f0ff299
=> Revert caching fid & disk read on caller thread.

buildSrc/src/main/java/com/google/firebase/gradle/plugins/Dokka.java, buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java, firebase-common/firebase-common.gradle, kotlindoc/package-lists/firebase/package-list
Specifically allows SDKs to declare dependencies via `javadocClasspath`
configuration for the dokka run to make `{@link}` tags render properly.
Depends on https://android-review.googlesource.com/c/platform/external/dokka/+/1365296
for rendering to work correctly.
=> Improve kotlindoc rendering.

apk-size/app/default.gradle
Android Gradle Plugin does not guarantee that debug build produces reproducible artifacts.
I cannot verify whether `debuggable = true/false` affects indeterminism as I was not able to reproduce indeterministic debug builds locally. Therefore, I'm disabling the debug build all together.
=> Disable debug build for apk size measurements.

firebase-crashlytics-ndk/src/main/jni/libcrashlytics/include/crashlytics/detail/memory/allocate.h, firebase-crashlytics-ndk/src/main/jni/libcrashlytics/src/handler/install.cpp
Properly release the handler context using the allocator's release mechanics instead of `delete`.
=> Properly release storage on exit

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/DataCollectionArbiter.java
Keeps track of what the current state of data collection is, and
logs the current state and where it was read from every time the
state is checked.
Also adds @Nullable annotations to clarify internal method calls.
=> Add logging of data collection state

firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessagingService.java, firebase-messaging/src/main/java/com/google/firebase/messaging/MessagingAnalytics.java, firebase-messaging/src/test/java/com/google/firebase/messaging/MessagingAnalyticsRoboTest.java
If shouldUploadScionMetrics and w shouldUploadFirelogAnalytics both evaluate to true, logToScion is called twice for a single message.
=> Fix Double Logging of FCM

transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/SchedulerConfig.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/ScheduleDelayTest.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/SchedulerConfigTest.java
The effect of the change is that initial attempts with small delay
are spread out in time more, which increases the overall time that
events are stored.
=> Log-adjusted backoff logic.

firebase-common/src/main/AndroidManifest.xml, firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
Note that even though `FirebaseApp itself initializes, none of the other SDKs get initialized until the user unlocks the devices.
See #1766
=> Initialize Firebase in direct boot mode

.opensource/project.json
When /docs/ktx/crashlytics.md was created in #1620 , it wasn't added to .opensource/project.json, which is causing it to not be shown in the sidebar menu on [firebaseopensource.com](https://firebaseopensource.com/projects/firebase/firebase-android-sdk/)
cc @rlazo
=> docs: add ktx/crashlytics.md to .opensource/project.json

encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/EncodableProcessor.java
It's not needed for the documentation purposes as javadoc and dokka only run on source, not generated code.
=> Remove `@hide` javadoc from generated classes

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/FieldFilter.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/Filter.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/KeyFieldInFilter.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/KeyFieldNotInFilter.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/NotInFilter.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java, firebase-firestore/src/main/java/com/google/firebase/firestore/util/Util.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Porting from [web](https://github.com/firebase/firebase-js-sdk/pull/3557).
=> Add != and NOT_IN queries (not public)

buildSrc/build.gradle, buildSrc/src/main/java/com/google/firebase/gradle/plugins/VendorPlugin.kt, buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/VendorTests.kt, firebase-inappmessaging-display/firebase-inappmessaging-display.gradle, firebase-inappmessaging/firebase-inappmessaging.gradle, transport/transport-runtime/transport-runtime.gradle
The `VendorPlugin`(applied with `id 'firebase-vendor'`) adds a dedicated
`vendor` gradle configuration to the project, which can be used to
include the dependencies in the output library. Such dependencies are
are shaded under the library's package name to avoid symbol collisions.
Example use:
```kotlin
plugins {
id("com.android.library")
id("firebase-vendor")
}
android {
// ...
}
dependencies {
implementation("com.example:somelib:1.0")
// this will make this library available at compile time as well as
// will vendor it inside the produced aar under `com.mylib.com.example`.
vendor("com.example:libtovendor:1.0") {
// IMPORTANT: if the library (transitively) depends on any library
// that contains `javax` or `java` packages, it must be excluded here
// and added as a pom dependency below. …
```
=> Add dependency vendoring support.

firebase-database/CHANGELOG.md, firebase-database/src/androidTest/java/com/google/firebase/database/FirebaseDatabaseTest.java, firebase-database/src/main/java/com/google/firebase/database/FirebaseDatabase.java
Port of https://github.com/firebase/firebase-js-sdk/pull/3650
=> Infer database URL from Project ID

firebase-firestore/src/main/java/com/google/firebase/firestore/model/Values.java
Fixes #1906.
#1534's upgrade to the `protolite` library resulted in a change to the Protobuf `Value.equals()` method, which can cause delays. This PR replaces usages of Protobuf's `equal()` method with our own.
Tested on the repro app provided in the issue, and verified that the delays disappear with this PR.
=> Remove usages of Protobuf equals

firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java, firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallationsRegistrar.java, firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
Lazy initialization of heartbeat.
=> lazy initialization of heartbeat

firebase-database/src/main/java/com/google/firebase/database/FirebaseDatabase.java
This fixes a bug in https://github.com/firebase/firebase-android-sdk/pull/1898. In the original PR, the code path to infer the project ID was not invoked when using the default app.
=> Also infer Database URL for default App

encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/EncodableProcessor.java, encoders/firebase-encoders-processor/src/test/java/com/google/firebase/encoders/processor/EncodableProcessorTest.java
The issue arises when there is more than one auto-value class in a
given package, in which case only one "support" class is generated.
=> Fix auto-value codegen.

buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/AffectedProjectFinder.java
The issue is that the process can block on writing to stdout if the
amount of data written is bigger than default buffer size.
Hence not trying to read from the process until it finishes causes it to
block forever trying to write to its stdout.
=> Read stdout of the process before waiting for it to complete.

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/NotInFilter.java, firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java
`whereNotIn(path, Array(null))` always returns an empty list, which means that `NotInFilter.matches()` needs to also not match any documents if the filter's value contains `null`. 
Also added a null serialization test for notIn.
=> Fix NotInFilter matching

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java
Fix for b/168320959 / #1935. Built-in icons are always in the "android" package,
so we can't use the launcher icon's package name to locate string
resources. The best we can do is fall back to context.getPackageName().
=> Fix Crashlytics crash when using built in launcher icon

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsLifecycleEvents.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
Multi-process apps can have multiple instances, which can result
in one instance having stale state. Relying on the passed-in
session ID as the source of truth ensures the SRC is always
operating on the most recent open session.
=> Remove session ID tracking from session reporting coordinator.

firebase-firestore/CHANGELOG.md, firebase-firestore/api.txt, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/FieldFilter.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java
In addition to making these public, I also added NOT_IN to the `isInequality()` check. This means that queries using NOT_IN will be ordered by the field name, as is the case with inequality filters. Updated tests to reflect the change and made changed the inequality filter validation message to match the other SDKs.
=> Make != and NOT_in filters public

firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
The FirebaseInstallationsServiceClient wasn't calling `setDoOutput(true)` on the `generateAuthToken` method, which was confusing some SSL providers and causing requests to unceremoniously fail. There's a separate issue causing the task failure not to get correctly propagated back to the caller (in this case FCM), but for now this is an easy and correct-seeming fix.
=> Call `setDoOutput(true)` on auth POSTs

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
This should fix the test failures in Google3: https://g3c.corp.google.com/results/invocations/1dc2a7dd-1aed-422a-9ddd-282f208b6cd1/targets/%2F%2Fthird_party%2Ffirebase%2Fandroid%2Ffirebase_firestore%2Ftests%2Fintegration_tests:firestore/tests
=> Fix NotEquals tests to use deterministic document ordering

firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java, firebase-firestore/src/test/resources/json/listen_spec_test.json, firebase-firestore/src/test/resources/json/offline_spec_test.json, firebase-firestore/src/test/resources/json/write_spec_test.json
Port of https://github.com/firebase/firebase-js-sdk/pull/3821 (test only, since main bug fix is not applicable)
=> Import spec tests

firebase-firestore/src/main/java/com/google/firebase/firestore/remote/FirebaseClientGrpcMetadataProvider.java
Port of https://github.com/firebase/firebase-ios-sdk/pull/6592
=> Always send the user agent regardless of the heartbeat value

firebase-common/firebase-common.gradle, firebase-common/src/androidTest/java/com/google/firebase/FirebaseAppTest.java, firebase-common/src/androidTest/java/com/google/firebase/StrictModeTest.java, firebase-common/src/androidTest/java/com/google/firebase/components/EagerComponent.java, firebase-common/src/androidTest/java/com/google/firebase/components/EagerInDefaultAppComponent.java, firebase-common/src/androidTest/java/com/google/firebase/components/EagerSdkVerifierRegistrar.java, firebase-common/src/androidTest/java/com/google/firebase/components/InitializationTracker.java, firebase-common/src/androidTest/java/com/google/firebase/components/InitializingComponent.java, firebase-common/src/androidTest/java/com/google/firebase/components/LazyComponent.java, firebase-common/src/main/java/com/google/firebase/FirebaseApp.java, firebase-common/src/main/java/com/google/firebase/heartbeatinfo/DefaultHeartBeatInfo.java, firebase-common/src/test/java/com/google/firebase/heartbeatinfo/DefaultHeartBeatInfoTest.java, firebase-components/src/main/java/com/google/firebase/components/ComponentRuntime.java, firebase-components/src/test/java/com/google/firebase/components/ComponentRuntimeTest.java, firebase-installations/src/main/AndroidManifest.xml
see: b/128433971
* Makes HeartBeat storage lazy.
* Adds strict mode test for `FirebaseApp#initializeApp()`
* Removes auth and analytics tests, these should be part of product test suites
=> Make firebase-common StrictMode-compliant.

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/remote/FirebaseClientGrpcMetadataProviderTest.java
It was broken by https://github.com/firebase/firebase-android-sdk/pull/2012
=> Fix the heartbeat integration test in Firestore

transport/transport-api/proguard.txt, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/util/PriorityMapping.java
The enum's values are accessed via reflection, so aggressive Proguard
rules can cause it to be stripped out.
e.g., https://github.com/firebase/firebase-android-sdk/issues/1996
=> Fix reflection error in com.google.android.datatransport.Priority when using aggressive Proguard rules.

firebase-config/bandwagoner/src/main/java/com/googletest/firebase/remoteconfig/bandwagoner/ApiFragment.java
Displaying the token after a network call creates a race condition that sometimes replaces the contents of this field Espresso integration tests. Besides, it's more useful to have the token in a copy-able log than displayed in the app.
=> Log FIS auth token instead of displaying it in the RC test app.

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
In the case that event files are found but cannot be read or
parsed, we might write a session with no events. To mitigate this,
we will double-check to make sure we've parsed the events properly
before synthesizing a report file.
=> Double check for events after parsing report data

firebase-components/firebase-components.gradle, firebase-components/src/main/java/com/google/firebase/components/ComponentRuntime.java, firebase-components/src/main/java/com/google/firebase/components/Deferred.java, firebase-components/src/main/java/com/google/firebase/components/LazySet.java, firebase-components/src/test/java/com/google/firebase/components/ComponentRuntimeTest.java, firebase-components/src/test/java/com/google/firebase/components/DeferredTest.java, firebase-components/src/test/java/com/google/firebase/components/LazySetTest.java, firebase-functions/src/main/java/com/google/firebase/functions/FirebaseContextProvider.java
This is done in preparation for dynamic module loading support.
The gist of the change is to make:
* Missing optional dependencies backed by "empty" providers. That can be
mutated at runtime to start returning non-null values if dependencies
become available
* Set components backed by thread-safe `Set`s that can be extended with
newly loaded dependencies.
=> Make `ComponentRuntime` mutable.

firebase-firestore/CHANGELOG.md, firebase-firestore/api.txt, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FieldsTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java, firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentSnapshot.java, firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestoreSettings.java, firebase-firestore/src/main/java/com/google/firebase/firestore/UserDataWriter.java, firebase-firestore/src/test/java/com/google/firebase/firestore/UserDataWriterTest.java
Snapshot data will now always use Timestamp values. Use `Timestamp.toDate()` to convert to `java.util.Date` if required.
`timestampsInSnapshots` was deprecated in January 2019 and has defaulted to true since then.
Port of https://github.com/firebase/firebase-ios-sdk/pull/6622
=> Remove timestampInSnapshots Setting

firebase-common/src/main/java/com/google/firebase/FirebaseApp.java, firebase-components/src/main/java/com/google/firebase/components/ComponentDiscovery.java, firebase-components/src/main/java/com/google/firebase/components/ComponentRuntime.java, firebase-components/src/main/java/com/google/firebase/components/InvalidRegistrarException.java, firebase-components/src/main/java/com/google/firebase/components/LazySet.java, firebase-components/src/main/java/com/google/firebase/components/OptionalProvider.java, firebase-components/src/main/java/com/google/firebase/components/RestrictedComponentContainer.java, firebase-components/src/main/java/com/google/firebase/dynamicloading/ComponentLoader.java, firebase-components/src/main/java/com/google/firebase/dynamicloading/package-info.java, firebase-components/src/test/java/com/google/firebase/components/ComponentDiscoveryTest.java, firebase-components/src/test/java/com/google/firebase/components/ComponentRuntimeTest.java, firebase-components/src/test/java/com/google/firebase/components/OptionalProviderTest.java, firebase-components/src/test/java/com/google/firebase/components/RestrictedComponentContainerTest.java
* `ComponentRuntime` will now store any registrar names that failed to
load due to `ClassNotFoundException` for future use.
* `ComponentRuntime` will provide a new `ComponentLoader` component that
can be used by interested parties to trigger component discovery. This
will be used by the new "dynamic-module-support" sdk to trigger
discovery upon new module installation.
=> Add dynamic loading support to component discovery.

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/DataCollectionArbiterTest.java
Basic test for the setter and getter. The real benefit of this change
is catching any changes to the internal API that will break the Unity
plugin.
=> Add tests for Crashlytics DataCollectionArbiter

firebase-database/CHANGELOG.md, firebase-database/src/main/java/com/google/firebase/database/core/utilities/Utilities.java
In 19.4, we replaced Java `assert` statements with custom asserts to address lint warnings, as `assert` is disabled on Android. This however caused the clients to crash, which indicates that at least some of our asserts are problematic. We can safely revert to the previous state by only enabling these asserts in debug builds.
Fixes https://github.com/firebase/firebase-android-sdk/issues/2069
=> Enforce asserts only in debug builds

firebase-common/src/main/AndroidManifest.xml, firebase-components/firebase-dynamic-module-support/api.txt, firebase-components/firebase-dynamic-module-support/firebase-dynamic-module-support.gradle, firebase-components/firebase-dynamic-module-support/src/main/AndroidManifest.xml, firebase-components/firebase-dynamic-module-support/src/main/java/com/google/firebase/dynamicloading/DynamicLoadingRegistrar.java, firebase-components/firebase-dynamic-module-support/src/main/java/com/google/firebase/dynamicloading/DynamicLoadingSupport.java, firebase-components/firebase-dynamic-module-support/src/main/java/com/google/firebase/dynamicloading/package-info.java, subprojects.cfg
This SDK will be declared as a dependency in the developers' base bundle.
This ensures that:
* `firebase-common` ends up in the base bundle, which is required since it
exposes an exported android component, namely `FirebaseInitProvider`.
Failing to do so would result in the app crashing at start up while
trying to load the missing content provider.
* Upon install of new modules, an attempt is made to load
`ComponentRegistrars` that were previouly missing(if any). This makes
it possible for developers to start using newly loaded Firebase SDKs
immediately upon install.
=> Adds firebase-dynamic-module-support SDK.

firebase-installations/ktx/src/test/kotlin/com/google/firebase/installations/ktx/InstallationsTests.kt
This is a minor issue: it looks like there was a copy-paste error when writing the tests for firebase-installations-ktx.
cc: @vkryachko
=> test(installations-ktx): Functions --> Installations

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCaptureTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransformTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/AppData.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCapture.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransform.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/proto/SessionProtobufHelper.java
Crashlytics reports sent via DataTransport erroneously did not set the
development_platform field for Unity apps. This results in incorrect
internal metrics for Unity apps. b/171214452
=> Add development_platform for Unity crash reports

firebase-firestore/CHANGELOG.md, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java, firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/FieldFilter.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java
Porting from [web](https://github.com/firebase/firebase-js-sdk/pull/3960).
=> Allow null and NaN values in filters

firebase-components/src/main/java/com/google/firebase/components/LazySet.java, firebase-components/src/main/java/com/google/firebase/components/OptionalProvider.java
The race could result in us not updating the actualSet with the newly
aded provider.
=> Fix a race condition in LazySet.

buildSrc/src/main/java/com/google/firebase/gradle/plugins/Dokka.java
This makes such dependencies' symbols available during javadoc/dokka
runs.
=> Include runtimeOnly dependencies in javadocClasspath.

docs/ktx/dynamic-links.md
**DO NOT MERGE** before the next release (after 19.1.0) of dynamic-links-ktx.
This should document the new features added in #1753
=> docs(fdl-ktx): document the Kotlin destructuring declarations

firebase-functions/firebase-functions.gradle, firebase-functions/ktx/api.txt, firebase-functions/ktx/src/main/kotlin/com/google/firebase/functions/ktx/Functions.kt, firebase-functions/src/androidTest/java/com/google/firebase/functions/FirebaseFunctionsTest.java, firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.java, firebase-functions/src/main/java/com/google/firebase/functions/FunctionsMultiResourceComponent.java
[Googlers: see API review here](https://docs.google.com/document/d/1cSIcGCW2QR1OLHX4RDCVNhpBUolnG6tfNpJBR2pn1aM/edit#)
- Added new unit tests
- API reviewed
This change is in line with other similar changes for JS and iOS sdk:
[JS implemented](https://github.com/firebase/firebase-js-sdk/pull/3825)
[iOS implemented](https://github.com/firebase/firebase-ios-sdk/pull/6787)
=> Add custom domain support to callable functions

README.md, firebase-crashlytics-ndk/README.md
Firebase Crashlytics NDK no longer requires NDK r17c to build.
=> Remove special instructions for requiring NDK r17c.

firebase-database/src/androidTest/java/com/google/firebase/database/QueryTest.java, firebase-database/src/main/java/com/google/firebase/database/Query.java, firebase-database/src/main/java/com/google/firebase/database/connection/PersistentConnection.java, firebase-database/src/main/java/com/google/firebase/database/connection/PersistentConnectionImpl.java, firebase-database/src/main/java/com/google/firebase/database/core/Repo.java, firebase-database/src/main/java/com/google/firebase/database/core/SyncTree.java
Port of https://github.com/firebase/firebase-js-sdk/pull/3812
=> Query get API for RTDB

firebase-crashlytics-ndk/firebase-crashlytics-ndk-proguard.txt
Prevents aggressive stripping of native methods in the JniNativeApi class.
=> Add Proguard rule for Crashlytics NDK

ci/fireci/fireci/commands.py
Tested at https://github.com/firebase/firebase-android-sdk/pull/1831 
apiInformation task would still show failure status since we are doing exit(1) before posting the comment
=> Make Api Information task comment the diff on the PR

firebase-storage/CHANGELOG.md, firebase-storage/src/main/java/com/google/firebase/storage/FileDownloadTask.java
This fixes a crash in the Storage SDK that occurred when a file was deleted while being written to. By changing the IllegalStateException to an IOException, we no longer crash the app but instead expose the failure as a failed task.
Fixes https://github.com/firebase/firebase-android-sdk/issues/2211
=> Throw IOException for deleted files

firebase-database/CHANGELOG.md, firebase-database/src/main/java/com/google/firebase/database/tubesock/WebSocket.java
On some Pixel devices, `socket.close()` throws an NPE (might be related to https://github.com/google/conscrypt/issues/331).
Fixes b/164528104
=> Don't crash SDK is socket.close() fails

firebase-firestore/src/proto/google/firestore/v1/write.proto
Porting from [web](https://github.com/firebase/firebase-js-sdk/pull/4118).
=> Add update transforms proto

buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/device/FirebaseTestServer.java
b/174660554
Enabling Test Orchestrator to run each of app's instrumentation tests independently without accumulating shared states.
References:
- https://firebase.google.com/docs/test-lab/android/firebase-console#new_instrumentation_tests_with_orchestrator
- http://cloud/sdk/gcloud/reference/firebase/test/android/run#--use-orchestrator
=> Enabling Test Orchestrator 

firebase-ml-modeldownloader/api.txt, firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle, firebase-ml-modeldownloader/src/main/AndroidManifest.xml, firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/CustomModel.java, firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloader.java, firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloaderRegistrar.java, firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/CustomModelDownloadService.java, firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileDownloadService.java, firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileManager.java, firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/SharedPreferencesUtil.java, firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/CustomModelDownloadConditionsTest.java, firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/CustomModelTest.java, firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloaderTest.java, firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/TestOnCompleteListener.java, firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/CustomModelDownloadServiceTest.java, firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/ModelFileDownloadServiceTest.java, firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/ModelFileManagerTest.java, firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/SharedPreferencesUtilTest.java
…nconditional downloads at this time.
=> Adding get Model for local downloads

firebase-database/src/main/java/com/google/firebase/database/Query.java
This is a typo that slipped through in the original PR https://github.com/firebase/firebase-android-sdk/pull/2087
=> RTDB Query get method must be public

firebase-components/src/main/java/com/google/firebase/components/ComponentRuntime.java, firebase-components/src/test/java/com/google/firebase/components/threading/AnotherEagerComponent.java, firebase-components/src/test/java/com/google/firebase/components/threading/DeadlockTests.java, firebase-components/src/test/java/com/google/firebase/components/threading/EagerComponent.java
The deadlock was arising when components are initialized concurrently
from different threads all waiting for `Lazy.get` to resolve which would
never succeed.
=> Fix deadlock issue.

firebase-firestore/src/main/java/com/google/firebase/firestore/LoadBundleTask.java, firebase-firestore/src/main/java/com/google/firebase/firestore/LoadBundleTaskProgress.java, firebase-firestore/src/test/java/com/google/firebase/firestore/LoadBundleTaskTest.java
DO-NOT-SUBMIT (yet), because LoadBundleTask is still just a stub.
=> Reflection tests to verify LoadBundleTask implement all interface of Task

firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.java
See http://cl/347916042 for context
=> Update FirebaseFunctions JavaDoc

firebase-common/src/main/java/com/google/firebase/internal/ActivityLifecycleListener.java, firebase-firestore/src/main/java/com/google/firebase/firestore/LoadBundleTask.java, firebase-firestore/src/main/java/com/google/firebase/firestore/LoadBundleTaskProgress.java, firebase-firestore/src/main/java/com/google/firebase/firestore/OnProgressListener.java, firebase-firestore/src/test/java/com/google/firebase/firestore/LoadBundleTaskTest.java, firebase-storage/src/main/java/com/google/firebase/storage/StorageTask.java, firebase-storage/src/main/java/com/google/firebase/storage/TaskListenerImpl.java
This implements the logic for LoadBundleTask. It's basically a super advanced copy/paste job:
- It takes some API comments from the Web implementation (https://github.com/firebase/firebase-js-sdk/blob/master/packages/firebase/index.d.ts#L8374)
- It relies on the Android Task API whenever possible. For progress updates, the implementation is inspired by cs/piper///depot/google3/java/com/google/android/gmscore/integ/client/tasks/src/com/google/android/gms/tasks/TaskImpl.java
- Most Task API comments are copied from StorageTask (https://github.com/firebase/firebase-android-sdk/blob/master/firebase-storage/src/main/java/com/google/firebase/storage/StorageTask.java)
=> Implement LoadBundleTask

firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileDownloadService.java, firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/ModelFileDownloadServiceTest.java
Removes old download attempts from the download managers and resets the models in shared preferences.
=> Clean up/remove failed or completed download attempts.

firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
Fixes #2227
Tested:
I verified that com.google.googlequicksearchbox doesn't have the violation anymore in the e2e test.
Signed-off-by: Régis Décamps <regisd@google.com>
=> Set TrafficStats tag in FirebaseInstallationServiceClient.createFirebaseInstallation

firebase-inappmessaging-display/src/main/AndroidManifest.xml
Fixing issues related with package visibility changes for Android 11.
While targeting android 11, querying for activities or services which can handle intent returns 0 results. To support this querying in Android 11 and above we need to have the 'queries' tag mentioned in the manifest. Please see: https://developer.android.com/about/versions/11/privacy/package-visibility for details.
=> Fixing issues related with package visibility changes for Android 11.

firebase-database/src/main/java/com/google/firebase/database/Query.java, smoke-tests/build.gradle, smoke-tests/src/main/java/com/google/firebase/testing/PerformanceMonitoringTest.java
https://github.com/firebase/firebase-android-sdk/issues/2158
=> Restore fireperf smoke tests as #2158 is fixed.

firebase-database/api.txt, firebase-database/src/androidTest/java/com/google/firebase/database/QueryTest.java, firebase-database/src/androidTest/java/com/google/firebase/database/ValueExpectationHelper.java, firebase-database/src/main/java/com/google/firebase/database/Query.java, firebase-database/src/main/java/com/google/firebase/database/core/utilities/PushIdGenerator.java, firebase-database/src/test/java/com/google/firebase/database/PushIdGeneratorTest.java
go/rtdb-exclusive-query-filters
=> Implement `endBefore` for RTDB queries

firebase-inappmessaging-display/src/main/AndroidManifest.xml
Reverts firebase/firebase-android-sdk#2316 This is breaking our tests.
=> Revert "Fixing issues related with package visibility changes for Android 11."

firebase-database/src/main/java/com/google/firebase/database/snapshot/ChildKey.java
In order for `startAfter` and `endBefore` to have the correct ordering semantics, we need to return the objects `MAX_KEY` and `MIN_KEY`. Otherwise, the comparison function won't work properly in all cases:
https://github.com/firebase/firebase-android-sdk/blob/master/firebase-database/src/main/java/com/google/firebase/database/snapshot/ChildKey.java#L74-L76
=> Key comparison for RTDB queries should correctly handle boundary sentinels

firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/DeleteMutation.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/Mutation.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/MutationBatch.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/PatchMutation.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/SetMutation.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/VerifyMutation.java, firebase-firestore/src/test/java/com/google/firebase/firestore/model/MutationTest.java
Port from iOS https://github.com/firebase/firebase-ios-sdk/pull/7276
This likely needs to be ported to Web too (but I didn't check - just worked on this while verifying the iOS PR).
=> Remove unused baseDoc argument

firebase-firestore/src/main/java/com/google/firebase/firestore/util/ByteBufferInputStream.java, firebase-firestore/src/test/java/com/google/firebase/firestore/util/ByteBufferInputStreamTest.java
This will allow all three overloads for loadBundle() to use the same decoding logic.
See https://github.com/firebase/firebase-android-sdk/pull/2322 for how this all comes together.
=> Add ByteBufferInputStream

encoders/firebase-encoders-proto/src/main/java/com/google/firebase/encoders/proto/ProtobufDataEncoderContext.java, encoders/firebase-encoders-proto/src/main/java/com/google/firebase/encoders/proto/ProtobufValueEncoderContext.java, encoders/firebase-encoders-proto/src/test/java/com/google/firebase/encoders/proto/WithCollectionsTests.java
This change addresses the issue where repeated fields with ["default"](https://developers.google.com/protocol-buffers/docs/proto3#default)
values would not be encoded which would result in such values missing
when decoded back instead of being present as default values.
For example encoding [0,0] would incorrectly decode as [].
=> Fix repeated field encoding.

firebase-crashlytics-ndk/src/androidTest/java/com/google/firebase/crashlytics/ndk/CrashpadControllerTest.java, firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/CrashpadController.java, firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/FirebaseCrashlyticsNdk.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/network/DefaultSettingsSpiCallTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/CrashlyticsAnalyticsListener.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/BlockingAnalyticsEventLogger.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsUncaughtExceptionHandler.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/DataCollectionArbiter.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/IdManager.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/UserMetadata.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/FileStoreImpl.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/CachedSettingsIo.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/network/DefaultSettingsSpiCall.java
Made some log messages clearer and easier to understand, also
reduced noise by changing the log level on existing logs to:
E: Unexpected/error state, not recoverable. Crashlytics will not function.
W: Unexpected/error state, but recoverable.
D: SDK lifecycle logs ("what" is happening).
- Unix-style "no news is good news" logging, if something goes
wrong, it will appear in W or E logs.
V: Finer-grained logging ("how" things are happening).
- "Success" logs, as well as logging of internally-stored values
(e.g. current mapping file ID) are logged at this level.
Also modified a few logs to *only* print in an error case.
=> Clean up and clarify Crashlytics logging.

ci/fireci/fireciplugins/fireperf.py
Moving fireci plugin for fireperf end to end test from the release repo to the public repo.
=> Run fireperf e2e test from the public reepo.

README.md, docs/README.md
Preparing `firebase-perf` to be OSS ready. 
- Updating main README to include `firebase-perf`
- Updating [firebaseopensource](https://firebaseopensource.com/projects/firebase/firebase-android-sdk/) to include `firebase-perf`
**Note:** Merge only after `firebase-perf` have been Open Sourced.
=> Updating `firebase-perf` external documentation as part of Open Sourcing

transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStoreTest.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStore.java
=> Fixes a bug in transport context selection.

.opensource/project.json
This will remove the sidebar from this page:
https://firebaseopensource.com/projects/firebase/firebase-android-sdk/
Someone else can decide if we actually want to delete all the individual md files listed here:
https://github.com/firebase/firebase-android-sdk/tree/master/docs#kotlin-extensions
=> Remove KTX docs from firebaseopensource.com

firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalSerializerTest.java
Porting from [iOS](https://github.com/firebase/firebase-ios-sdk/pull/7276/files#diff-f6031b0454b2782196a25405bedaafd9083538172c176c17961c709f5118fb2fR338).
=> Iterate forward on local serializer mutation batch decoding

transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/TestWorkScheduler.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/AlarmManagerScheduler.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoScheduler.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/Uploader.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/WorkScheduler.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/AlarmManagerSchedulerTest.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoSchedulerTest.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/UploaderTest.java
As per https://developer.android.com/reference/android/app/job/JobScheduler#getAllPendingJobs() this also returns the jobs which we are currently running. This results in the job never being rescheduled if there are more pending events. This pr fixes it.
Also as per https://stackoverflow.com/questions/37059315/android-jobscheduler-if-you-schedule-the-same-job-with-periodic-time-does-it-s if you schedule the same job and the same job is running then its killed and the new job is scheduled.
=> update scheduling alogirthm to handle reschedules

firebase-common/firebase-common.gradle, firebase-config/firebase-config.gradle, firebase-database/firebase-database.gradle, firebase-dynamic-links/firebase-dynamic-links.gradle, firebase-firestore/firebase-firestore.gradle, firebase-functions/firebase-functions.gradle, firebase-installations/firebase-installations.gradle, firebase-messaging/firebase-messaging.gradle, firebase-segmentation/firebase-segmentation.gradle, firebase-storage/firebase-storage.gradle
This will allow us to remove some of the custom logic for generating javadocs we depend on.
=> Define javadoc-only dependencies in projects gradle files.

firebase-firestore/CHANGELOG.md, firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java, firebase-firestore/src/test/resources/json/limbo_spec_test.json
Fix a bug where enqueued limbo resolutions are left in the queue even after all targets that care about their resolutions are stopped. This erroneous behavior was reported in https://github.com/firebase/firebase-android-sdk/issues/2311 against the Android SDK, but the bug is also present in the Web and iOS SDKs. This PR is a port of the equivalent fix in the Web SDK: https://github.com/firebase/firebase-js-sdk/pull/4395. This bug was introduced when limbo resolution throttling was implemented almost a year ago (https://github.com/firebase/firebase-js-sdk/pull/2790).
=> Dequeue limbo resolutions when their respective queries are stopped

firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigConstants.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClientTest.java
Allow users to make conditions using build number like they can for iOS apps
Build version is an internal tracking version of an app, not shown to users (in gradle files, this is versionCode)
App version is the external released version of an app shown to users (in gradle files, this is versionName)
=> Add build number to Remote Config

firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/DeleteMutation.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/MutationResult.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/PatchMutation.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/SetMutation.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/model/MutationTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Gil asked that this should not be part of #2383, but I think it still makes sense as an indepedent simplification
=> Make TransformResult non-nullable

firebase-firestore/src/main/java/com/google/firebase/firestore/remote/AbstractStream.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java
Status#equals() uses reference equality. This will typically work for OK statuses, but will almost always fail for non-OK statuses. Status#isOk() or comparing Status#getCode() is preferred.
See cl/356819841 for additional context and motivation.
=> Replace gRPC Status#equals() with Status#isOk().

firebase-dynamic-links/api.txt, firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/PendingDynamicLinkData.java, firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/internal/DynamicLinkUTMParams.java, firebase-dynamic-links/src/test/java/com/google/firebase/dynamiclinks/PendingDynamicLinkDataTest.java, firebase-dynamic-links/src/test/java/com/google/firebase/dynamiclinks/internal/DynamicLinkUTMParamsTest.java
Add getUtmParameters api method to PendingDynamicLinkData.
This is new api method to provide utm parameters associated with a firebase dynamic link.
Approved api review doc : https://docs.google.com/document/d/1NDBjiuCQEs3vnaPGfYKK2cdvJMIsJqukRtrZf8wsWCk
iOS PR for the same : https://github.com/firebase/firebase-ios-sdk/pull/7505
=> Add getUtmParameters api method to PendingDynamicLinkData

firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigResolver.java, firebase-perf/src/main/java/com/google/firebase/perf/config/DeviceCacheManager.java, firebase-perf/src/main/java/com/google/firebase/perf/provider/FirebasePerfProvider.java, firebase-perf/src/test/java/com/google/firebase/perf/FirebasePerformanceTest.java, firebase-perf/src/test/java/com/google/firebase/perf/config/DeviceCacheManagerTest.java, firebase-perf/src/test/java/com/google/firebase/perf/internal/AppStateMonitorTest.java, firebase-perf/src/test/java/com/google/firebase/perf/metrics/TraceTest.java, firebase-perf/src/test/java/com/google/testing/timing/FakeDirectExecutorService.java
To address StrictMode violation in b/171411615.
=> Removing the isPerformanceMonitoringEnabled check in FirebasePerfProvider and moving the getSharedPreferences to a separate thread.

firebase-firestore/ktx/src/test/java/com/google/firebase/firestore/testutil/TestUtil.java, firebase-firestore/src/main/java/com/google/firebase/firestore/bundle/BundleLoader.java, firebase-firestore/src/main/java/com/google/firebase/firestore/bundle/BundleSerializer.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/Document.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/MutableDocument.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/MutationBatch.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/WatchChangeAggregator.java, firebase-firestore/src/test/java/com/google/firebase/firestore/bundle/BundleSerializerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LruGarbageCollectorTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/RemoteDocumentCacheTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/model/DocumentTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/model/MutableObjectValueTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/model/MutationTest.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Some small fixes to MutableDocuments that I noticed while porting to JS (more likely coming). I also added the often asked for factory functions since it helps with readability (otherwise the reader does not know what `new MutableDocument` means).
=> Post-Merge cleanup of MutableDocuments

smoke-tests/build.gradle, smoke-tests/src/main/java/com/google/firebase/testing/BuildOnlyTest.java
Reverts firebase/firebase-android-sdk#2453
Turns out this needs to wait until after official release of SDK.
=> Revert "smoke tests for ml modeldownloader"

firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
Also fixes an incremental build failure that occurs when overwriting the
libcrashlytics-trampoline.so.
=> Fix "Invalid File Descriptor" warnings when building crashlytics-ndk

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/BatteryStateTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/BatteryState.java
Handle exception when registering too many receivers in Crashlytics. This happens when getting the battery state, and it only affects some devices and some versions of Android.
Tested by unit tests, and manually by fudging with the emulator.
Fixes #2171
=> Handle exception when registering too many receivers in Crashlytics.

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java
Make the Crashlytics isEmulator check much more robust.
This is based on Flutter's isEmulator check for Android. This should also fix #2495.
=> Make the Crashlytics isEmulator check much more robust.

firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigResolver.java
Remote the debugging log message as that does not serve any information to the developer or us.
This is a fix for the bug b/176250560.
=> Cleanup the confusing log message

firebase-abt/src/main/java/com/google/firebase/abt/FirebaseABTesting.java, firebase-abt/src/main/java/com/google/firebase/abt/component/AbtComponent.java, firebase-abt/src/main/java/com/google/firebase/abt/component/AbtRegistrar.java, firebase-abt/src/test/java/com/google/firebase/abt/FirebaseABTestingTest.java, tools/lint/src/main/kotlin/ProviderAssignmentDetector.kt, tools/lint/src/test/kotlin/ProviderAssignmentDetectorTests.kt
Changes the dependency on analytics to an optional Provider.
=> Make ABT Dynamic-Module compliant.

firebase-perf/src/main/java/com/google/firebase/perf/session/PerfSession.java, firebase-perf/src/main/java/com/google/firebase/perf/transport/TransportManager.java
- Removed console logging in `PerfSession.create()`, which reduces the startup time by 15 ms (~25% of total startup time)
- Side effect: There will no logging for logging verbose/non-verbose session. However, the logging provides little value to developers and developers can easily add logging by themselves.
- Delay the initialization of `applicationInfoBuilder`, which reduces the startup time by 8 ms (~20% of total startup time)
- Side effect: None
=> Improve Fireperf SDK startup time.

firebase-perf/src/test/java/com/google/firebase/perf/FirebasePerformanceTestBase.java, firebase-perf/src/test/java/com/google/firebase/perf/application/AppStateMonitorTest.java, firebase-perf/src/test/java/com/google/firebase/perf/config/DeviceCacheManagerTest.java, firebase-perf/src/test/java/com/google/firebase/perf/metrics/AppStartTraceTest.java, firebase-perf/src/test/java/com/google/firebase/perf/metrics/HttpMetricTest.java, firebase-perf/src/test/java/com/google/firebase/perf/metrics/NetworkRequestMetricBuilderTest.java, firebase-perf/src/test/java/com/google/firebase/perf/metrics/TraceMetricBuilderTest.java, firebase-perf/src/test/java/com/google/firebase/perf/metrics/TraceTest.java, firebase-perf/src/test/java/com/google/firebase/perf/metrics/validator/FirebasePerfTraceValidatorTest.java, firebase-perf/src/test/java/com/google/firebase/perf/network/FirebasePerfHttpClientTest.java, firebase-perf/src/test/java/com/google/firebase/perf/network/FirebasePerfOkHttpClientTest.java, firebase-perf/src/test/java/com/google/firebase/perf/network/FirebasePerfUrlConnectionTest.java, firebase-perf/src/test/java/com/google/firebase/perf/network/InstrHttpInputStreamTest.java, firebase-perf/src/test/java/com/google/firebase/perf/network/InstrHttpOutputStreamTest.java, firebase-perf/src/test/java/com/google/firebase/perf/network/InstrHttpURLConnectionTest.java, firebase-perf/src/test/java/com/google/firebase/perf/network/InstrHttpsURLConnectionTest.java, firebase-perf/src/test/java/com/google/firebase/perf/network/InstrURLConnectionBaseTest.java, firebase-perf/src/test/java/com/google/firebase/perf/session/PerfSessionTest.java, firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/GaugeMetadataManagerTest.java, firebase-perf/src/test/java/com/google/firebase/perf/transport/RateLimiterTest.java, firebase-perf/src/test/java/com/google/testing/timing/FakeDirectExecutorService.java, firebase-perf/src/test/java/com/google/testing/timing/FakeScheduledExecutorService.java
- Refer b/177441811 for more details.
- This PR is only for updating test classes and not the source classes.
- Look at the class level variable names and if that looks good to you then just move on to other class. Reason being the rest of the changes in the class are most likely the name refactoring change which are automatically done by the AndroidRefactoring tool and thus I don't expect any issues there.
- Not necessarily but this is a good first step to build upon. There could be many different ways of declaring variable names but I chose the one which is easy to follow IMHO.
- Also there's so much more to improve on but I decided to just update class level variable names
=> Updating variable names from the test classes to follow Java's code convention (b/177441811)

firebase-config/firebase-config.gradle, firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
The personalization test was using the default namespace, and because another instance of config already existed in that namespace, the test instance was not being created. This caused the personalization test to try to use real objects instead of the mocks, including the direct executor. This PR fixes this and uses a provider to fake the interaction when Analytics is present and when it's not.
=> Fix personalization test and add check for optionalProvider.

firebase-common/src/main/AndroidManifest.xml, firebase-components/firebase-dynamic-module-support/src/main/AndroidManifest.xml
The removal is needed to satisfy the manifest merger when it merges
manifests across dynamic feature modules into the base app.
Since each Firebase SDK has a discovery service definition in its
manifest, placing them into a dynamic feature adds
`android:splitName="featureName"` to the discovery service. Subsequent
merge into the main app manifest causes a conflict since the splitName
is different in each feature.
Note that this change is also moving the dynamic module support
registrar definition to `firebase-dynamic-module-support` since having
an `android:remove` in `firebase-common` produces a warning when the app
does not use dynamic feature modules. To avoid this warning, the
manifest entry will now live in the dynamic module support sdk, since
it's only expected to be used if the …
=> Add a tools:remove rule to the discovery service definition.

firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
Test how changing the provider's returned value affects the tests.
=> Test Remote config personalization provider more dynamically.

alternative-root-project.gradle, build.gradle, smoke-tests/build.gradle
Going forward Firebase SDKs will ship Java 8 bytecode.
Safe to merge now, since this is happening in the next release.
=> Disable desugaring.

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/ProviderProxyNativeComponentTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CLSUUIDTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreInitializationTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCaptureTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/DataCollectionArbiterTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/IdManagerTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/IdManager.java
Querying for the Firebase Installation Id makes a network call and potentially registers
new information to Firebase servers, so we should not access it from Crashlytics when
the data collection flag is disabled. Instead, we cache a synthetic FID to use as long
as collection is disabled. This can result in over-counting unique users who have experienced
a crash, but it better aligns with the privacy goals of the data collection flag.
See internal doc go/crashlytics-fid for more details.
=>  Disable fetching of Firebase Installation Id when data collection is disabled

appcheck/firebase-appcheck-debug-testing/firebase-appcheck-debug-testing.gradle, appcheck/firebase-appcheck-debug-testing/src/androidTest/java/com/google/firebase/appcheck/debug/testing/FirebaseAppCheckTest.java
Re-enable App Check integration tests.
App Check integration tests were disabled in #2601, since the debug secret environment variable was not configured for the public repo.
=> Re-enable App Check integration tests

appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultAppCheckToken.java, appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/TokenRefreshManager.java, appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/TokenRefreshManagerTest.java
Update the default token refresh rate:
`refresh time = IAT + (0.5*TTL) + 5 min`
=> Update default token refresh rate

firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/ForegroundNotifier.java, firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/model/InAppMessage.java
Fixing following java doc issues: 
/home/prow/go/src/github.com/FirebasePrivate/firebase-android-release/oss/firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/ForegroundNotifier.java:66: lint 103: Unknown tag: @returns
DroidDoc took 3 sec. to write docs to /home/prow/go/src/github.com/FirebasePrivate/firebase-android-release/oss/firebase-inappmessaging/build/docs/javadoc
/home/prow/go/src/github.com/FirebasePrivate/firebase-android-release/oss/firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/model/InAppMessage.java:144: warning 101: Unresolved link/see tag "#getCampaignMetadata()#getCampaignId()" in com.google.firebase.inappmessaging.model.InAppMessage
/home/prow/go/src/github.com/FirebasePrivate/firebase-android-release/oss/firebase- …
=> Fixing FIAM Java doc issues

appcheck/firebase-appcheck-interop/firebase-appcheck-interop.gradle
Since the `firebase-appcheck-interop` SDK is only meant for use by internal clients of Firebase App Check, disable Javadoc generation for this SDK.
=> Do not publish Javadoc for the App Check interop library

ci/fireci/fireciplugins/macrobenchmark.py, macrobenchmark/config.yaml
Downgrade gradle wrapper version from 7.0 to 6.9 to speed up test apps assembly.
- [macrobenchmark run](https://android-ci.firebaseopensource.com/view/gcs/android-ci/pr-logs/pull/firebase_firebase-android-sdk/2650/macrobenchmark/1390903202219560964) with gradle 7.0 (total: 42m 23s)
- assembleAllForSmokeTests (10m 51s)
- assemble assembleAndroidTest (for all test apps, 5m 21s ~ 9m 46s)
- [macrobenchmark run](https://android-ci.firebaseopensource.com/view/gcs/android-ci/pr-logs/pull/firebase_firebase-android-sdk/2650/macrobenchmark/1391796275434754055) with gradle 6.9 (total: 36m50s)
- assembleAllForSmokeTests (8m 40s)
- assemble assembleAndroidTest (for all test apps, 4m 15s ~ 7m 13s)
=> Configure google-services.json for macrobenchmark tests.

smoke-tests/build.gradle, smoke-tests/src/main/java/com/google/firebase/testing/BuildOnlyTest.java
* Remove tests for `firebase-ml-vision`, as it is removed from the bom in the [most recent release](https://firebase.google.com/support/release-notes/android#2021-05-11)
* Restore tests for `firebase-perf`. The issue for which the test had to be disabled temporarily was fixed  in the [release](https://firebase.google.com/support/release-notes/android#performance_v19-0-11)
* Change tests for `firebase-appindexing` to call a new api as the older one is removed in the [most recent release](https://firebase.google.com/support/release-notes/android#app-indexing_v20-0-0)
=> Keep smoke tests up to date.

firebase-inappmessaging-display/firebase-inappmessaging-display.gradle, firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplayRegistrar.java
Removing FIAM Display SDK dependency on Analytics since its not used by FIAM Display SDK
Changes:
- Removed analytics dependency from FirebaseInAppMessagingDisplayRegistrar
- Removed analytics dependency from FirebaseInAppMessagingDisplay - Gradle
=> Removing FIAM Display SDK dependency on Analytics.

firebase-perf/src/main/java/com/google/firebase/perf/transport/RateLimiter.java, firebase-perf/src/main/java/com/google/firebase/perf/transport/TransportManager.java, firebase-perf/src/main/java/com/google/firebase/perf/util/Rate.java, firebase-perf/src/test/java/com/google/firebase/perf/transport/RateLimiterTest.java, firebase-perf/src/test/java/com/google/firebase/perf/util/RateTest.java
Fixed two bugs in the RateLimiter:
- Rate was represented by a long, which causes confusion around the units (per second vs per minute)
- the token replenishment behavior is wrong and keeps track of lastTimeTokenConsumed instead of lastTimeTokenReplenished, causing less tokens to be generated overtime
=> Fix fireperf RateLimiter replenishment behavior and unit alignment.

firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/CrashFilesManager.java, firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/CrashpadController.java, firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/NdkCrashFilesManager.java
Clean up old sessions in the NDK before initializing and after finalizing a session.
Tested manually with a test app.
=> Clean up old sessions in the NDK

firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/DatabaseId.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/DocumentKey.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/Values.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/Mutation.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/MutationBatch.java
This brings our Mutation-parsing logic in line with that of iOS (https://github.com/firebase/firebase-ios-sdk/pull/8124)
=> Simplify Mutations

firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
One task was incorrectly relying on `externalNativeBuildClean`,
which caused all native files to be rebuilt on every build,
regardless of if they were changed. That task dependency has
been removed, reducing incremental build times from 6m to ~13s.
=> Fix incremental builds for firebase-crashlytics-ndk

ci/fireci/fireciplugins/macrobenchmark.py, macrobenchmark/config.yaml, macrobenchmark/template/app/build.gradle.mustache, macrobenchmark/template/benchmark/build.gradle, macrobenchmark/template/benchmark/src/androidTest/java/com/google/firebase/benchmark/BenchmarkTest.kt.mustache, macrobenchmark/template/benchmark/src/androidTest/java/com/google/firebase/benchmark/Test.kt.mustache, macrobenchmark/template/benchmark/src/main/AndroidManifest.xml.mustache, macrobenchmark/template/build.gradle
Also update version for some dependencies.
=> Remove application-id from macrobenchmark config file.

transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/UploaderIntegrationTest.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/Uploader.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/UploaderTest.java
Instead of uploading one batch, the Uploader will now upload all pending events - this will get around a throughput issue that the uploader can experience.
=> Change Uploader's `logAndUpdateState` to upload all pending events

firebase-common/src/test/java/com/google/firebase/platforminfo/FirebasePlatformLoggingTest.java
Old tests expected a whitespace between elements, but didn't account for the case when it's at the end of the string.
=> Fix common tests to support patterns at end of string in useragent.

ci/fireci/fireciplugins/coverage.py
The `note` was the fourth parameter, but was made fifth in #2682.
=> Fix breakage of coverage PR report cause by #2682.

encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/annotations/AnnotationBuilder.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedAtMyAnnotation.java
The toString() implementation of enum constants in annotations changed in JDK-8164819, this makes the previous behaviour more explicit.
=> Update AnnotationBuilder to not rely on toString()

firebase-inappmessaging-display/firebase-inappmessaging-display.gradle, gradle.properties
Jetifier is no longer needed and is causing failures for the encoders
proto plugin.
=> Disable jetifier.

firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateMonitor.java, firebase-perf/src/test/java/com/google/firebase/perf/application/AppStateMonitorTest.java
This PR is to fix:
1. https://github.com/firebase/firebase-android-sdk/issues/2672 
2. Screen trace data not tracked for Android API levels 23 and below (b/191954905).
Summary of changes:
1. Replaced `frameMetricsAggregator.remove(activity)` with `frameMetricsAggregator.reset()` because `remove` does not clean the frame metrics, causes frame metrics for each activity is added on top of the data for all previous pages.
2. Removed [checks](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateMonitor.java#L405-L407) for hardware accelerated. The reason for adding this check is due to the crash by calling `frameMetricsAggregator.remove(activity)` (see b/133827763). However, this check will return false even if …
=> Fix inaccurate activity screen metrics.

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/TransactionTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/TransactionRunner.java
This PR standardizes transaction retry language to use "attempts" rather than "retries" as part of b/147440261
=> Standardize transaction retries to attempts

firebase-firestore/CHANGELOG.md, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/remote/RemoteStoreTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/AndroidConnectivityMonitor.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/OnlineStateTracker.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java
This is a follow up to https://github.com/firebase/firebase-android-sdk/pull/2693, which used Android's built-in BackgroundDetector to fast-forward network reconnects when an app entered the foreground. Unfortunately, the BackgroundDetector is pretty conservative and only fires if it knows for certain that the app was in the background and now is in the foreground. This leads to some suppressed notifications. This PR just hooks directly into the notification API and always raises the foreground notification.
Logs:
```
2021-06-25 13:30:40.601 4251-4665/com.google.firebase.example.fireeats I/Firestore: (23.0.2) [OnlineStateTracker]: Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: Status{code=UNAVAILABLE, description=Unable to resolve host foo, …
```
=> Use manual foreground detection to trigger network reconnect

appcheck/firebase-appcheck-debug-testing/src/androidTest/java/com/google/firebase/appcheck/debug/testing/FirebaseAppCheckTest.java, appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/FirebaseAppCheck.java, appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheck.java, appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultTokenRefresher.java, appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheckTest.java, appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/DefaultTokenRefresherTest.java, appcheck/firebase-appcheck/test-app/src/main/java/com/googletest/firebase/appcheck/MainActivity.java
Implement API for 3P developers to request a Firebase App Check token as well as observe changes to the token. This will enable developers to protect their own (non-Firebase) backends with the FAC token.
=> Implement GetAppCheckToken API

transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManager.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManagerMigrationTest.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/StateSimulations.java
Upgraded storage schema version to V5 from V4
**Changes in V5**  
- Added `log_event_dropped` table
- `log_event_dropped` table is used to persist the general metrics about dropped events
- Added `global_log_event_state` tables
- `global_log_event_state` contains a single global value "last_metrics_upload_ms", this value is only used to present the start time of collecting Client Analytics metrics. "last_metrics_upload_ms" will be reset to current_time if existing metrics were sent to the server successfully.
_Note: existing tests in `SchemaManagerMigrationTest` make sure storage scheme can downgrade and upgrade successfully._
=> Upgrade storage schema version to V5 and add log_event_dropped and time tables.

buildSrc/build.gradle
Gradle 5.6.4 expects the plugin to be version 1.2.9.
=> Upgrade kotlin dsl plugin

firebase-database/CHANGELOG.md, firebase-database/src/main/java/com/google/firebase/database/connection/PersistentConnectionImpl.java
In the case where `authToken == null` and `appCheckToken != null`, this would never call `restoreState`. This fixes that case by calling `sendAppCheckTokenHelper` (that function also handles the case where `appCheckToken == null`.
=> Restore state when appcheck is used without auth.

transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java, transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctTransportBackendTest.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/backends/TransportBackend.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/backends/UploadOptions.java
Extend `TransportBackend` interface to have a default method `shouldUploadClientHealthMetrics`
`shouldUploadClientHealthMetrics`  indicate whether data sent through `TransportBackend` with
`TransportContext` should be recorded as client health metrics and upload to Flg server.
=> Extend TransportBackend to have a default method

transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStoreTest.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStore.java
Before persisting the events to database, it firstly check if the storage limit has been reached
- if so, it will drop the events and make a call to `ClientHealthMetricsStore` to `recordLogEventDropped` for the reason of `CACHE_FULL`.
=> Record log event dropped due to cache full

firebase-app-distribution/firebase-app-distribution.gradle, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/AppDistributionRelease.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionException.java
Convert AppDistributionRelease to AutoValue and add constructors to Exception type
=> Update AppDistributionRelease and FirebaseAppDistributionException

transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStoreTest.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStore.java
Before old events are deleted, we will make a call to `ClientHealthMetricsStore` to `recordLogEventDropped` for the reason of `MESSAGE_TOO_OLD`.
=> Record logevent dropped due to too old

transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/persistence/SpyEventStoreModule.java, transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/persistence/TestEventStoreModule.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/Uploader.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/EventStoreModule.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/TransportRuntimeTest.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/UploaderTest.java
It will be used to record log event dropped when network response is `INVLIAD_PAYLOAD` and `FATAK_ERROR`
=> Inject ClientHealthMetricsStore into Uploader

firebase-database/src/main/java/com/google/firebase/database/connection/PersistentConnectionImpl.java
We should also make sure pending requests are completed with an error, but I'll save that for another PR.
=> Log a warning if the RTDB connection is forcefully killed.

firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplay.java, firebase-inappmessaging-display/src/test/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplayTest.java, firebase-inappmessaging/src/testData/inappmessaging/testutil/TestData.java
Currently, FIAM uses Custom Tabs to open every action URI and results in errors for deep links.
Refering to [iOS SDK's implementation](https://github.com/firebase/firebase-ios-sdk/blob/b41a1273368e8af2af26d1dfcb135fc2307b94b3/FirebaseInAppMessaging/Sources/Runtime/FIRIAMActionURLFollower.m#L107-L129), which checks whether URI schems is http/https, I implemented a similar logic in this PR.
Not pretty sure if my test change is sufficient as this is my first time to contribute to the project. 
So please let me know if there's anything missing.
=> Use custom tab only for web actions

transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/Uploader.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/TransportRuntimeTest.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/UploaderTest.java
Added an additional `EventInteral` to `BackEndRequest` to send `ClientMetrics`
=> Include ClientMetrics into BachedLogRequest

firebase-perf/src/test/java/com/google/firebase/perf/FirebasePerformanceTest.java
This PR will unblock #2788.
`check-changed` should be passing based on the test result from #2813, which is based on #2788.
Context:
The failure examples could be found [here](https://storage.googleapis.com/android-ci/pr-logs/pull/firebase_firebase-android-sdk/2788/check-changed/1412872199047483392/artifacts/firebase-perf_build_test-results/testReleaseUnitTest/TEST-com.google.firebase.perf.FirebasePerformanceTest.xml)
=> Fix flaky tests in FirebasePerformanceTest.java

firebase-app-distribution/firebase-app-distribution.gradle, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionException.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionRegistrar.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionTesterApiClient.java, firebase-app-distribution/src/test/assets/testReleaseResponse.json, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTesterApiClientTest.java
- Implement checkForUpdate MVP (currently compares build versions, will be changed for code hashes)
- Added FirebaseAppDistributionTesterApiClient to handle calls to ListTesterAppInstallationReleasesAction endpoint 
- Add unit tests for checkForUpdate and Client
=> FAD implement checkForUpdate MVP and TesterApiClient 

firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionTesterApiClient.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/internal/AppDistributionReleaseInternal.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/internal/ReleaseIdentificationUtils.java, firebase-app-distribution/src/test/assets/testAabReleaseResponse.json, firebase-app-distribution/src/test/assets/testApkReleaseResponse.json, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTesterApiClientTest.java
* Added release identification for AABs
* Added new AppDistributionReleaseInternal class that represents the response from the server
* refactored some tests
=> Adding AppDistributionReleaseInternal and AAB release identification

firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/FirebaseDynamicLinks.java
Duplicated word:
> App Links launches **launches** the app
=> Fix typo in FirebaseDynamicLinks.java

firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/Constants.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionException.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionTesterApiClient.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTesterApiClientTest.java
Adding API error handling and better error messages
=> FAD API error handling

firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandler.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigComponentTest.java
Creating the ConfigFetchHandler for a non-default firebase application marks the provider as null which caused a NullPointerException
```
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object com.google.firebase.inject.Provider.get()' on a null object reference
at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.getUserProperties(ConfigFetchHandler.java:501)
at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackend(ConfigFetchHandler.java:311)
at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackendAndCacheResponse(ConfigFetchHandler.java:278)
at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.lambda$fetchIfCacheExpiredAndNotThrottled$1$ConfigFetchHandler(ConfigFetchHandler.java:215)
at …
```
=> Add a null check on AnalyticsConnector provider

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/KeysMap.java
Exception would be caught & logged when making rapid calls to setCustomKeys.
Updated KeysMap#getKeys() to return a defensive copy of keys, and
reduced overhead inside the synchronized blocks when updating keys.
Internal bug b/194422907, Github issue #2840
=> Fixed ConcurrentModificationException from setCustomKeys

firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/Constants.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/TesterSignInClient.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateStatus.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java
Standardizing how we spell canceled in our SDK codebase
=> Standardize spelling of canceled

firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/SignInStorage.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java
- Add sign in persistence through SignInStorage class using SharedPreferences 
- Implement isTesterSignedIn and signOutTester
- Fix tests affected by persistence 
- Add signIn checks in updateToLatestRelease, updateApp, and checkForUpdate 
- Add unit tests
=> FAD Add SignIn persistence to SDK 

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/KeysMap.java
This fixes an error introduced in #2851 (not yet shipped), as the
method is used to sanitize user ids, which should remain null
if they are not set.
=> Fixed KeysMap#sanitizeAttribute to preserve null values

firebase-firestore/firebase-firestore.gradle, firebase-firestore/src/main/java/com/google/firebase/firestore/local/Persistence.java
We are starting with development for Firestore's long awaited indexing support. This PR adds a environment variable that controls whether indexing is enabled in the final build. It is meant to replace the hard-coded flag as we do not want to accidentally change it to true and check it in to master.
=> Add environment flag to control indexing

firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/CheckForUpdateClient.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/TaskUtils.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/CheckForUpdateClientTest.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/TestOnCompleteListener.java
* Refactoring checkForUpdate client to use onSuccessTask instead of task completion source to prevent race conditions
* Adding unit tests to validated task response
PAIR: @rachaprince
=> Check For Update Refactor and tests

encoders/firebase-encoders-processor/firebase-encoders-processor.gradle, encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/EncodableProcessor.java
This change will cause the string representation to use qualified names e.g. @com.google.Foo(value = com.google.Bar.BAZ). The latest versions of javac no longer use qualified names in the implementation of AnnotationValue#toString, so you get something like @Foo(value = Bar.BAZ).
This change is important primarily for code that uses the toString() representation in generated source code, since simple names may fail to compile unless additional imports are added. It is still worth considering for code that uses the string representation in diagnostics or assertion messages, since it makes it clearer which type is being referred to.
=> Migrate AnnotationValue#toString to auto-common's AnnotationValues.toString

firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateApkClient.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateStatus.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/UpdateApkClientTest.java
- Add back terminal states for UpdateStatus
- made the updateTaskImpl passed in to the updateApk method a class variable (cachedUpdateTask) inside updateApkClient since it is reused a lot and setInstallationResult would not be able to access it otherwise 
- Set terminal states in updateProgress in updateApkClient 
- Update APK tests to test for correct status being set
=> FAD reintroduce terminal states to UpdateStatus 

buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/device/FirebaseTestLabExtension.java, buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/device/FirebaseTestServer.java, firebase-firestore/firebase-firestore.gradle
This change seems to be required to get the conformance tests to pass - see https://github.com/firebase/firebase-android-sdk/pull/2861
=> Increase connected check timeout for Firestore to 30m

firebase-firestore/src/main/java/com/google/firebase/firestore/index/DirectionalIndexByteEncoder.java, firebase-firestore/src/main/java/com/google/firebase/firestore/index/FirestoreIndexValueWriter.java, firebase-firestore/src/main/java/com/google/firebase/firestore/index/IntMath.java, firebase-firestore/src/main/java/com/google/firebase/firestore/index/OrderedCodeReader.java, firebase-firestore/src/main/java/com/google/firebase/firestore/index/OrderedCodeWriter.java, firebase-firestore/src/main/java/com/google/firebase/firestore/index/package-info.java
This adds the Index Encoding code that the backend uses to encode field values to index entries. Datastore-only features are removed and otherwise unused methods were removed.
=> Add Index Encoding code from backend

firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionException.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/ReleaseUtils.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateApkClient.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateAppClient.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateTaskImpl.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/UpdateApkClientTest.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/UpdateAppClientTest.java
Making sure we don't use the same cached update task in the `UpdateAppClient` and the `UpdateApkClient` to avoid cross-class synchronization issues
=> Fix update app synchronization issues

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/DefaultSettingsControllerTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/DataCollectionArbiter.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/Utils.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsController.java
This resolves a concurrency issue in Crashlytics when racing two tasks on a background thread before the application is initialized. The race util would create a task on the main application thread, regardless of the executor. Since the application was not initialized yet, the race never completed. Now the race util has an overloaded method to accept the executor to avoid this problem.
Tested manually on a real device that was experiencing this issue.
=> Plumb the executor through waitForDataCollectionPermission in Crashlytics

firebase-perf/src/main/java/com/google/firebase/perf/metrics/validator/FirebasePerfTraceValidator.java, firebase-perf/src/test/java/com/google/firebase/perf/metrics/validator/FirebasePerfTraceValidatorTest.java
This is to fix a part of b/197734449, where we "found validation failures due to screen traces having 0 or undefined number of total frames" being generated and sent to the backend. 
This PR adds a validation in the SDK that drops screen traces from being sent to the backend when there is no totalFrames metrics or when the metrics is <= 0. 
The exact cause of why zero frames are being recorded is unknown, I suspect it had something to do with us not calling FrameMetricsAggregator.remove(activity), which was removed due to not having good check for hardware acceleration ([context](https://github.com/firebase/firebase-android-sdk/pull/2736)). That could be investigated more in the future, b/150558546 may be useful, just putting that down as a record.
=> Add validation for checking if a Screen Trace has non-positive totalFrames

firebase-functions/src/androidTest/java/com/google/firebase/functions/FirebaseContextProviderTest.java, firebase-functions/src/androidTest/java/com/google/firebase/functions/TestInternalAppCheckTokenProvider.java, firebase-functions/src/main/java/com/google/firebase/functions/FirebaseContextProvider.java
If `AppCheckTokenResult` contains an error, do not send the placeholder token to backend requests.
See FirebaseExtended/flutterfire#6794 for more details.
=> Don't send placeholder FAC token to Cloud Functions 

firebase-firestore/firebase-firestore.gradle, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
We can remove `index_value` from the composite key since every `index_id` should correspond to a single `index_value`.
=> Remove index_value from primary key of index_entries

firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
Reverting #2960.
If there is an ARRAY_CONTAINS index, there will be multiple different index values for a given index_id, since each item in the array is added as a different index_value for the same index_id.
=> Revert removal of index_value

firebase-firestore/firebase-firestore.gradle, firebase-firestore/src/main/java/com/google/firebase/firestore/core/Target.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/TargetTest.java
This adds functionality to `Target` to compute boundaries for Index scans. 
See how this is used in the prototype: https://github.com/firebase/firebase-android-sdk/pull/2654/files#diff-979270768a3e2798683bf7702f4e84ade098aa967d60d90c9c741d41fc64754dR191 Note that the prototype uses multiple methods instead of the API in this PR.
=> Add Index Bounds to Queries

firebase-firestore/CHANGELOG.md, firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestoreSettings.java, firebase-firestore/src/test/java/com/google/firebase/firestore/FirebaseFirestoreSettingsTest.java
Fix a bug where the "copy constructor" for `FirebaseFirestoreSettings.Builder` forgot to copy the `cacheSizeBytes` field.
The problematic code is:
https://github.com/firebase/firebase-android-sdk/blob/e41b233118beb9f06cd330f4f1239f880df3eb84/firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestoreSettings.java#L55-L60
=> Fix bug where `cacheSizeBytes` was sometimes not initialized correctly in `FirebaseFirestoreSettings`

firebase-firestore/src/main/java/com/google/firebase/firestore/remote/Datastore.java, firebase-firestore/src/test/java/com/google/firebase/firestore/remote/MockDatastore.java
The teardown of the GRPC channel takes almost one second, and we don't use it at all during the Spec Test run. This change changes the runtime from 2:30 minutes to 8 seconds for me.
=> Speed up SpecTest

firebase-perf/src/main/java/com/google/firebase/perf/config/RemoteConfigManager.java, firebase-perf/src/test/java/com/google/firebase/perf/config/RemoteConfigManagerTest.java
**Rationale**:
This is required to ensure that a remote notification does not trigger multiple config fetches from remote config at the same time. Internal bug reference: b/187985523
iOS version of the same change https://github.com/firebase/firebase-ios-sdk/pull/8593
=> Fireperf: create a random delay before initiating a remote config fetch. 

firebase-firestore/src/main/java/com/google/firebase/firestore/core/Bound.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/FieldFilter.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/Target.java, firebase-firestore/src/main/java/com/google/firebase/firestore/index/IndexByteEncoder.java, firebase-firestore/src/main/java/com/google/firebase/firestore/index/IndexEntry.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexBackfiller.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryIndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/DocumentKey.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/FieldIndex.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/TargetTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexManagerTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexBackfillerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
This PR adds the code that is needed to add documents to the Index and to run queries against the Index.
Couple changes from previous PRs:
- The schema now uses collection_groups and no longer collection_ids. This was true before but it also now reflected in the names.
- Since we use collection groups, the schema actually needs to contain the relative path of the document rather than just the document ID.
=> Index Evaluation

firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java, firebase-firestore/src/main/java/com/google/firebase/firestore/bundle/BundleSerializer.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/Bound.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/Target.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java, firebase-firestore/src/test/java/com/google/firebase/firestore/bundle/BundleSerializerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/TargetTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
This is supposed to reduce confusion as to what `before` means for startAt() and endAt().
=> Change Bound's before to inclusive

firebase-firestore/src/main/java/com/google/firebase/firestore/model/MutableDocument.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/DeleteMutation.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/FieldMask.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/Mutation.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/PatchMutation.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/SetMutation.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/VerifyMutation.java, firebase-firestore/src/test/java/com/google/firebase/firestore/model/MutationTest.java
This PR:
- Removes FieldMask
- Re-uses testing logic for `verifyRoundTrip`
- Uncovers versioning issue in overlay
=> Remove FieldMask

firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/FieldIndex.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/TargetIndexMatcher.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
Incremental PR to add storing and retrieving last update time from FieldIndex. Also renamed collectionId to collectionGroup on fieldIndex.
=> add update time to FieldIndex

firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/CheckForNewReleaseClient.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionTesterApiClient.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/CheckForNewReleaseClientTest.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTesterApiClientTest.java
API requests have to contain additional “X-Android-Package”, “X-Android-Cert” headers for Android-application restricted keys
=> Add headers to support Android-application restricted API keys

firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/DeleteMutation.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/Mutation.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/PatchMutation.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/SetMutation.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/model/MutationTest.java
I have been thinking more about our mutation code. I don't actually think there are any user visible mutations changes if a latency-compensated delete keeps the current version and has "localMutations" set. The only changes I see are in the local store tests, but the integration tests are unchanged.
Let me know if you can think of any problems.
This would further simplify https://github.com/firebase/firebase-android-sdk/pull/2962
=> Remove special handling in Mutations

firebase-crashlytics-ndk/src/androidTest/java/com/google/firebase/crashlytics/ndk/FirebaseCrashlyticsNdkTest.java, firebase-crashlytics-ndk/src/main/AndroidManifest.xml, firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/CrashlyticsNdkRegistrar.java, firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/FirebaseCrashlyticsNdk.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/CrashlyticsNativeComponentDeferredProxyTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/CrashlyticsNativeComponent.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/CrashlyticsNativeComponentDeferredProxy.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/unity/ResourceUnityVersionProvider.java
Some app development platforms, including Unity, will overwrite our
NDK signal handler if it is installed too quickly upon app launch.
This change prevents our signal handler from being immediately installed,
instead waiting for FirebaseCrashlyticsNdk#installSignalHander().
=> Enable deferred installation of Crashlytics NDK signal handler.

firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/FirebaseDynamicLinks.java, firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/internal/FirebaseDynamicLinksImpl.java, firebase-dynamic-links/src/test/java/com/google/firebase/dynamiclinks/internal/FirebaseDynamicLinksImplTest.java
Changing the @NonNull to @Nullable for `Intent` argument in getDynamicLink(intent) method.
The intent parameter should be the intent that launched the application, or can be null if the intent does not include the dynamic link. A non-null intent is necessary only when the app is launched directly using the dynamic link, such as when using App Links.
Changes:
- Changed the annotation from  @NonNull to @Nullable.
- Modified getDynamicLink(Intent) method to handle null intents.
- Added test with null intent.
Related issue: https://github.com/firebase/firebase-android-sdk/issues/2336
=> FDL getDynamicLink(Intent) method to accept null intent.

firebase-firestore/src/main/java/com/google/firebase/firestore/core/OrderBy.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/Target.java, firebase-firestore/src/main/java/com/google/firebase/firestore/index/IndexEntry.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexBackfiller.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/FieldIndex.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/TargetTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexBackfillerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
This PR adds `limit()` support to our query engine. Unfortunately, this means that we have to enforce ordering as we need to filter the "best n" matches directly in the database layer. 
This again changes our indexing format. This test is a good example as to why:
```
@Test
public void testLimitAppliesOrdering() {
indexManager.addFieldIndex(
new FieldIndex("coll")
.withAddedField(field("value"), FieldIndex.Segment.Kind.ORDERED)
.withAddedField(field("value"), FieldIndex.Segment.Kind.CONTAINS));
addDoc("coll/doc1", map("value", Arrays.asList(1, "foo")));
addDoc("coll/doc2", map("value", Arrays.asList(3, "foo")));
addDoc("coll/doc3", map("value", Arrays.asList(2, "foo")));
Query query =
query("coll")
.filter(filter("value", "array-contains", "foo"))
.orderBy(orderBy("value")) …
```
=> Add ordering to Index implementation

firebase-perf/src/main/java/com/google/firebase/perf/metrics/AppStartTrace.java, firebase-perf/src/test/java/com/google/firebase/perf/metrics/AppStartTraceTest.java
Summary:
- This PR moves the [app start trace build logic](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-perf/src/main/java/com/google/firebase/perf/metrics/AppStartTrace.java#L203-L233) into another thread. 
- The rest of the PR is about formatting old code.
This effort will cut down the trace build time during app startup from ~30ms to a few ms.
=> Move app start trace build logic into a non-main thread.

firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/FirebaseCrashlyticsNdk.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/CrashlyticsNativeComponent.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/CrashlyticsNativeComponentDeferredProxy.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsUncaughtExceptionHandler.java
Our backend expects at most one fatal event per session. In some cases,
such as Unity, the native signal handler may cause an uncaught exception
to be thrown, after we have recorded the NDK crash. If this happens,
Crashlytics should ignore the uncaught exception and send the NDK
crash information as the fatal event.
=> Don't send fatal uncaught exception if an NDK crash exists

firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerformance.java
The PR will cut down the cost of generateDashboardURL and save ~10ms if debug log is disabled.
=> Check if debug log is enabled before generate dashboard URL

firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/TesterSignInClient.java, firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionLifecycleNotifier.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/TesterSignInClientTest.java
- Removes executor option in the lifecycle notifier because this causes callbacks to execute in an unexpected order
- Sets a succesful signin result when SignInResultAction is created
=> Fixes some bugs with the new state managment

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/remote/RemoteStoreTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/ComponentProvider.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/MemoryComponentProvider.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/SQLiteComponentProvider.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/DefaultQueryEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexBackfiller.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexedQueryEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryIndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryMutationQueue.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryPersistence.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/Persistence.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/RemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteMutationQueue.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLitePersistence.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/CountingQueryEngine.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexManagerTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexedQueryEngineTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LruGarbageCollectorTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/QueryEngineTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/RemoteDocumentCacheTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexBackfillerTest.java
This PR changes the IndexManager to use the signed in User for documents with mutations. 
It requires a bunch of changes:
- IndexManager is now user-scoped and gets replaced when the user changes.
- IndexBackfiller and RemoteDocumentCache have setters to replace the IndexManager under the hood
- Misc cleanup that I tried to describe via comments.
=> User-scoped indices

firebase-app-distribution/api.txt, firebase-app-distribution/ktx/api.txt, firebase-app-distribution/ktx/src/androidTest/kotlin/com/google/firebase/app/distribution/ktx/FirebaseAppDistributionTests.kt, firebase-app-distribution/ktx/src/main/kotlin/com/google/firebase/app/distribution/ktx/FirebaseAppDistribution.kt
All sdks have an api.txt files that include methods that users will be interacting with both on java and in kotlin.
=> Adding in api.txt files to ktx and app distribution directories 

transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/TestDestination.java, transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/UploaderIntegrationTest.java, transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/UploaderTestRuntimeComponent.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/Uploader.java
The issue was that we were never resetting counters after a successful
metrics upload. This resulted in ever increasing counter values that did
not represent reality.
=> Fix metrics counter reporting.

firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryIndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/FieldIndex.java, firebase-firestore/src/main/java/com/google/firebase/firestore/util/Util.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexBackfillerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexingEnabledSQLiteLocalStoreTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/OverlayEnabledSQLiteLocalStoreTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/model/FieldIndexTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/util/UtilTest.java
This PR diffs the index configuration that the user provides with the currently active definition and removes indexes that are no longer used
=> Add ability to delete indexes

firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/CustomModelDownloadService.java, firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/CustomModelDownloadServiceTest.java
Details are provided in this issue description
https://github.com/firebase/firebase-android-sdk/issues/2647
The changes here are at parity with the changes shown below and follow the same pattern:
https://github.com/firebase/firebase-android-sdk/blob/ac3276ce7d5f5181b1c419731495eb88a98537af/firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java#L246
There is one caveat that in the referenced **google-play-services-basement-17.4.0** the method below is deprecated, but to keep parity of the pattern with the rest of the codebase I have continued to use it here too. 
`AndroidUtilsLight.getPackageCertificateHashBytes`
Was able to export library to mavenLocal() and test it in this simple app
https://github.com/kabeer-uber/firebase-ml-bug-2647
changes …
=> Support for API key restrictions in FirebaseModelDownloader

firebase-messaging/firebase-messaging.gradle, firebase-messaging/src/test/AndroidManifest.xml, firebase-messaging/src/test/java/com/google/firebase/iid/FirebaseInstanceIdWithFcmReceiverRoboTest.java, firebase-messaging/src/test/java/com/google/firebase/messaging/CommonNotificationBuilderRoboTest.java, firebase-messaging/src/test/java/com/google/firebase/messaging/DisplayNotificationRoboTest.java, firebase-messaging/src/test/java/com/google/firebase/messaging/FirebaseMessagingRoboTest.java, firebase-messaging/src/test/java/com/google/firebase/messaging/FirebaseMessagingServiceRoboTest.java, firebase-messaging/src/test/java/com/google/firebase/messaging/MessagingAnalyticsRoboTest.java, firebase-messaging/src/test/java/com/google/firebase/messaging/WakeLockHolderRoboTest.java
* Removed @Ignore for all tests that were disabled in the move to GitHub.* Updated robolectric version to include notification delegate support. Also updated createNotificationInfo_withInvalidEventTime and WakeLockHolderRoboTest tests to pass with the updated robolectric version.
* Limited tests using minSdk/maxSdk to sdk instead to fix OutOfMemoryErrors that seem to be due to running the tests on too many API levels. It could also be due to a specific platform level causing issues.
* Updated androidx.core version to include NotificationCompat.getVisibility() to replace CommonNotificationBuilderRoboTest usage of Notification.visibility.
* Added MyTestActivity to the test AndroidManifest.xml to enable FirebaseMessagingServiceRoboTest's use of the Activity.
=> Fix messaging tests disabled in the move to GitHub.

firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/FieldIndex.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/TargetTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexBackfillerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexingEnabledSQLiteLocalStoreTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/model/FieldIndexTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/model/TargetIndexMatcherTest.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
This changes FIeldIndex to be an AutoValue with the goal to make it easier to extend and add new properties.
=> Make FieldIndex an AutoValue

firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
This PR makes it so that all index entries are scoped to a user, which removes shared index entries for documents that are not mutated. For apps that use multiple users this means that we will keep more index entries, but in the general case it means that we keep one less (instead of keeping the unmodified value + the modified value for single user indices, we now just keep one).
This means that each index now has a different backfill state per user. If a new user signs in, we need to start backfill from zero. We likely need an additional data structure for that.
=> Remove shared index entries

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/MetaDataStore.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
This fixes a bug caught in post-commit validation of PR #3143. The
bug never shipped.
Before the earlier refactor, the user id was serialized in two different
files on disk: one as a raw id and the other in JSON. In the refactor,
this was inadvertedly consolidated to one file path. The result is that
when generating a Crashlytics report, the SDK expects a plain text user id
in the file, and instead sends up the entire JSON blob as the user id.
A follow-on refactor is already underway which will elliminate the need
for the redundant file. Until that change is ready, we'll return to
using distinct file paths for the two files.
=> Fix Crashlytics user id serialization bug

firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexBackfiller.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexedQueryEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryIndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/RemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/FieldIndex.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/CountingQueryEngine.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexBackfillerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexingEnabledSQLiteLocalStoreTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/RemoteDocumentCacheTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/model/FieldIndexTest.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
This PR moves the "how updated is the index?" state from the index table to a per-user table and adds a sequence number. This allows the backfiller to process all index entries independently for each user.
=> Store per-user state for indexes

firebase-installations/firebase-installations.gradle, firebase-installations/src/androidTest/java/com/google/firebase/installations/StrictModeTest.java, integ-testing/src/main/java/com/google/firebase/testing/integ/MultipleViolationsException.java, integ-testing/src/main/java/com/google/firebase/testing/integ/StrictModeRule.java
It has special meaning in JUnit which results in only the first failure
being printed as test failure.
Also added an example strict mode test to FIS(disabled since there are
violations).
=> Don't use JUnit's MultipleViolationsException.

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/IndexingTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexBackfiller.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexBackfillerTest.java
Some changes I made during debugging.
=> Random changes for Indexing

firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistribution.java, firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/InstallApkClient.java, firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/TesterSignInClient.java, firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/UpdateApkClient.java
Makes our synchronization patterns more consistent by:
- guarding mutable fields with either a synchronization block or method
- if the object is written asynchronously by our codebase, we use a synchronized block to prevent memory inconsistencies after the calling method returns. 
-avoiding the use of synchronized blocks within synchronized methods, because this increases the chances of deadlock
=> Guard mutable fields with synchronization blocks or methods

firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java
We do not need to store the readTime as a separate value. We can just store it with the document.
=> Simplify MemoryRemoteDocumentCache

firebase-firestore/src/test/java/com/google/firebase/firestore/local/RemoteDocumentCacheTestCase.java
Small PR that extracts common data elements from the tests and adds a new test case to test that we omit results from subcollections.
=> Clean up RemoteDocumentCacheTestCase

.github/workflows/update-cpp-sdk-on-release.yml
Updated version of the script requires the Python "requests" module, which needs to be explicitly installed.
=> Update Python dependencies before running trigger_workflow script.

firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/CrashlyticsNdkRegistrar.java, firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/CrashpadController.java, firebase-crashlytics/src/androidTest/assets/flutter_assets/NOTICES.Z, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/CrashlyticsNativeComponentDeferredProxyTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/DevelopmentPlatformProviderTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreInitializationTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCaptureTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/DevelopmentPlatformProvider.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/AppData.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCapture.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/StaticSessionData.java, firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerRobolectricTest.java
Set DevelopmentPlatform info for Flutter apps
Also made DevelopmentPlatform delay the initialization when possible to avoid an additional file operation during start up.
=> Set DevelopmentPlatform info for Flutter apps

firebase-messaging/src/main/java/com/google/firebase/messaging/MessagingAnalytics.java, firebase-messaging/src/test/java/com/google/firebase/messaging/MessagingAnalyticsRoboTest.java
* Added getting the default FirebaseApp instance before logging to Scion and not continuing if it throws IllegalStateException because it hasn't been initialized. This prevents throwing IllegalStateException when trying to log to Scion if the default FirebaseApp has not been initialized.
=> Check for default FirebaseApp before logging to Scion.

firebase-perf/dev-app/dev-app.gradle, firebase-perf/dev-app/src/main/AndroidManifest.xml, firebase-perf/dev-app/src/main/java/com/googletest/firebase/perf/testapp/FragmentActivity.java, firebase-perf/dev-app/src/main/java/com/googletest/firebase/perf/testapp/ListAdapter.java, firebase-perf/dev-app/src/main/java/com/googletest/firebase/perf/testapp/PerfTestActivity.java, firebase-perf/dev-app/src/main/java/com/googletest/firebase/perf/testapp/SharedViewModel.java, firebase-perf/dev-app/src/main/java/com/googletest/firebase/perf/testapp/ui/dashboard/DashboardFragment.java, firebase-perf/dev-app/src/main/java/com/googletest/firebase/perf/testapp/ui/dashboard/DashboardViewModel.java, firebase-perf/dev-app/src/main/java/com/googletest/firebase/perf/testapp/ui/home/HomeFragment.java, firebase-perf/dev-app/src/main/java/com/googletest/firebase/perf/testapp/ui/home/HomeViewModel.java, firebase-perf/dev-app/src/main/java/com/googletest/firebase/perf/testapp/ui/notifications/NotificationsFragment.java, firebase-perf/dev-app/src/main/java/com/googletest/firebase/perf/testapp/ui/notifications/NotificationsViewModel.java, firebase-perf/dev-app/src/main/res/drawable/ic_dashboard_black_24dp.xml, firebase-perf/dev-app/src/main/res/drawable/ic_home_black_24dp.xml, firebase-perf/dev-app/src/main/res/drawable/ic_notifications_black_24dp.xml, firebase-perf/dev-app/src/main/res/layout/activity_fragment.xml, firebase-perf/dev-app/src/main/res/layout/fragment_dashboard.xml, firebase-perf/dev-app/src/main/res/layout/fragment_home.xml, firebase-perf/dev-app/src/main/res/layout/fragment_notifications.xml, firebase-perf/dev-app/src/main/res/layout/main_activity.xml, firebase-perf/dev-app/src/main/res/layout/number_list_item.xml, firebase-perf/dev-app/src/main/res/menu/bottom_nav_menu.xml, firebase-perf/dev-app/src/main/res/menu/menu.xml, firebase-perf/dev-app/src/main/res/navigation/mobile_navigation.xml, firebase-perf/dev-app/src/main/res/values/dimens.xml, firebase-perf/dev-app/src/main/res/values/strings.xml
b/208271486: while working on Fragment performance measurement, we need an activity with multiple fragments to test on, in the dev-app.
This adds a button to the main activity that starts a new `FragmentActivity` which uses `Navigation` component with 3 fragments. 
There are also preliminary listeners added to the `FragmentActivity.onCreate()` that we could possibly utilize in our performance measurements, namely `getSupportFragmentManager().registerFragmentLifecycleCallbacks(...)` and `Navigation.findNavController(...).addOnDestinationChangedListener(...)`.
Filter by keyword "Fragment" in logcat and navigate around to see the behaviour of each lifecycle callback. 
Navigation component uses something called `NavHostFragment` as a container to swap different fragments into the view. But …
=> Fireperf: create an activity with fragments in `dev-app` for testing

firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java, firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallationsRegistrar.java, firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
This pr adds the HEARTBEAT_HEADER into the http call.
=> Set fis as an unloader

buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/tagging/GitClient.java, buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/tagging/ShellExecutor.java, buildSrc/src/test/kotlin/com/google/firebase/gradle/bomgenerator/tagging/GitClientTest.kt
Verified in the fake release `MFake`: https://github.com/FirebasePrivate/firebase-android-sdk/pull/412.
The tag `MFake` was successfully created and uploaded to `FirebasePrivate/firebase-android-sdk`. 
https://prow-gob.gcpnode.com/view/gcs/fireescape/pr-logs/pull/FirebasePrivate_firebase-android-sdk/412/make-bom/1469548790112325632/#1:build-log.txt%3A207
=> [test-infra] Fix release tagging implementation

firebase-perf/src/main/java/com/google/firebase/perf/transport/TransportManager.java
Speculative fix for issue #3084. NullPointerException is encountered specifically on Android version 8.1.0, this is due to String.format inserted with Double values.
The proposed fix is to use DecimalFormat to format the values before being inserted in String.format
=> String format with decimal issue in Android 8.1.0

firebase-app-distribution/api.txt, firebase-app-distribution/ktx/api.txt, firebase-app-distribution/ktx/src/androidTest/kotlin/com/google/firebase/app/distribution/ktx/FirebaseAppDistributionTests.kt, firebase-app-distribution/ktx/src/main/kotlin/com/google/firebase/app/distribution/ktx/FirebaseAppDistribution.kt, firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistribution.java
Remove support for multiple instances of the sdk. Only support the default Firebase app
=> Remove support for multiple sdk instances in Firebase App Distribution

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
This will fix the issue with Unity metadata being excluded in some cases.
=> Include internal keys even if no custom keys were set.

firebase-firestore/src/main/java/com/google/firebase/firestore/SetOptions.java
Addresses firebase/firebase-admin-node#987
=> docs: improve documentation for merge behavior

firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/internal/InstallActivity.java
The bug in question would occur when a user would update the app and not close the app after updating and opening it using the system dialog that occurs after an update. When they would try to update again the update would fail and the task would hang.
=> Adding clear task flag to fix update app bug

firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/ApkUpdater.java, firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/AppIconSource.java, firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistributionNotificationsManager.java, firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/ApkUpdaterTest.java, firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/AppIconSourceTest.java, firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/FirebaseAppDistributionNotificationsManagerTest.java, firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/FirebaseAppDistributionTest.java
This should also make `UpdateApkTest` less flaky.
=> Refactor notification tests to be more focused to the classes under test

firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/AabUpdater.java, firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/ApkUpdater.java, firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistributionTesterApiClient.java, firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/HttpsUrlConnectionFactory.java, firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/internal/InstallActivity.java, firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/AabUpdaterTest.java, firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/ApkUpdaterTest.java, firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/NewReleaseFetcherTest.java
- Makes error messages and statuses more relevant and specific
- Catches some additional error cases and removes some unnecessary ones
- Replaces all instances of [log-and-(re)throw](http://go/java-practices/exceptions#log_rethrow), instead setting exception causes
- Injects `HttpsUrlConnectionFactory` to avoid mocking package private class methods
- Replaces `Thread.sleep` in tests with `ExecutorServiceawaitTermination()` to speed up tests
- Adds a couple TODO's I will follow up on
=> Improve error handling around downloading and installing

firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/NewReleaseFetcher.java, firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/ReleaseIdentificationUtils.java, firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/TaskUtils.java, firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/internal/LogWrapper.java, firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/NewReleaseFetcherTest.java
- Cleans up top level Task-based error handling, using `TaskUtils.runAsyncInTask`
- Isolates Long parsing error handling into one place
- Improves messaging around getting IAS artifact IDs, APK hashes, package info
=> Clean up error handling in NewReleaseFetcher

firebase-firestore/CHANGELOG.md, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java, firebase-firestore/src/test/resources/json/existence_filter_spec_test.json, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
This fixes a problem where the SDK receives an existence filter mismatch and clears the mapping of documents to targets, but does not receive another snapshot that also clears the snapshot version (i.e. the device went in the background and did was not able to actually process a re-run of the query).
The change that this PR makes is that we always reset the lastLimboFreeSnapshot version to 0 if we get a target mismatch.
Fixes https://github.com/firebase/firebase-android-sdk/issues/3249
=> Clear the lastLimboFreeSnapshot version on existence filter mismatch

firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/AabUpdaterTest.java, firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/FirebaseAppDistributionTest.java, firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/TestUtils.java
Refactors tests using the assertTaskFailure method
Creates a shared TestUtils class
=> DRY up the FirebaseAppDistributionTest class with assertTaskFailure

firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java
Follows logic pattern established by: https://github.com/firebase/firebase-android-sdk/pull/3057/files
When an app rotates, the activity is destroyed. We close any open dialogs to prevent hanging references to the destroyed activity, and cancel the task.  If we wanted to avoid cancelling the task, we'd need to pull work to would need to store the state of the dialog / task, close it, and then reopen it .
=> Cancel task if activity is destroyed while sign in task is rotating

firebase-app-distribution-stub/api.txt, firebase-app-distribution-stub/firebase-app-distribution-stub.gradle, firebase-app-distribution-stub/gradle.properties, firebase-app-distribution-stub/ktx/api.txt, firebase-app-distribution-stub/ktx/gradle.properties, firebase-app-distribution-stub/ktx/ktx.gradle, firebase-app-distribution-stub/ktx/src/androidTest/AndroidManifest.xml, firebase-app-distribution-stub/ktx/src/androidTest/kotlin/com/google/firebase/app/distribution/ktx/FirebaseAppDistributionTests.kt, firebase-app-distribution-stub/ktx/src/main/AndroidManifest.xml, firebase-app-distribution-stub/ktx/src/main/kotlin/com/google/firebase/app/distribution/ktx/FirebaseAppDistribution.kt, firebase-app-distribution-stub/src/main/AndroidManifest.xml, firebase-app-distribution-stub/src/main/java/com/google/firebase/appdistribution/AppDistributionRelease.java, firebase-app-distribution-stub/src/main/java/com/google/firebase/appdistribution/BinaryType.java, firebase-app-distribution-stub/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-app-distribution-stub/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionException.java, firebase-app-distribution-stub/src/main/java/com/google/firebase/appdistribution/OnProgressListener.java, firebase-app-distribution-stub/src/main/java/com/google/firebase/appdistribution/UpdateProgress.java, firebase-app-distribution-stub/src/main/java/com/google/firebase/appdistribution/UpdateStatus.java, firebase-app-distribution-stub/src/main/java/com/google/firebase/appdistribution/UpdateTask.java, firebase-app-distribution-stub/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java, subprojects.cfg
This stubbed-out SDK will be shipped alongside firebase-app-distribution, and will enable customers to selectively compile against the stubbed out version when building for the Play store.
Follow-ups to this will include:
- Adding presubmit checks to make sure that the stub and main SDK have the same version number and api.txt
- Document the release process
=> Add firebase-app-distribution-stub SDK

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/DataCollectionArbiter.java
Proposed fix by DanielNovak for #3265.
TLDR: DiskReadViolation warning is being triggered when setting `setCrashlyticsCollectionEnabled`
The developer found that the issue is caused by `DataCollectionArbitrer.java` where it's using `commit()` instead of `apply()`.
Relevant code:
```
private static void storeDataCollectionValueInSharedPreferences(SharedPreferences sharedPreferences, Boolean enabled) {
Editor prefsEditor = sharedPreferences.edit();
if (enabled != null) {
prefsEditor.putBoolean("firebase_crashlytics_collection_enabled", enabled);
} else {
prefsEditor.remove("firebase_crashlytics_collection_enabled");
}
prefsEditor.commit();
}
```
The key difference of `commit` vs `apply` is that apply is asynchronous. Stack Overflow link [here](https://stackoverflow.com/a/5960732/14129564). …
=> issue_3265_disk_read_violation

firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
This makes the test match reality more as the target has synced keys when it hits the existence filter mismatch.
=> Improve testIgnoresTargetMappingAfterExistenceFilterMismatch

transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManager.java
Proposed fix for #3301. 
The `log_event_dropped` table was initially added on `SchemaManager.java` on 
- Firebase Crashlytics `18.2.4`
- datatransport:transport-runtime:`3.1.0`
EDIT: Proposed solution by mkocus is to use `DROP TABLE IF EXISTS` before the `CREATE TABLE` is called.
The `DROP_LOG_EVENT_DROPPED_SQL` is only called during `onDowngrade`, which means if somehow the migration fails half way, there is no way of continuing the migration, thus it's best to call `DROP_LOG_EVENT_DROPPED_SQL` whenever creating the table to ensure this table does not exist before upgrade.
=> Adding IF NOT EXISTS to CREATE log_event_dropped

firebase-firestore/src/main/java/com/google/firebase/firestore/local/DocumentOverlayCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryDocumentOverlayCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteDocumentOverlayCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/Overlay.java, firebase-firestore/src/main/java/com/google/firebase/firestore/util/Util.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/DocumentOverlayCacheTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteOverlayMigrationManagerTest.java
Splitting up https://github.com/firebase/firebase-android-sdk/pull/3323. This is the first PR.
=> Add Overlay class

firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/CountingQueryEngine.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
This updates the LocalStore tests to be able to verify how many overlays were processed. This will be used in the Mutation Backfill PR.
=> Update LocalStoreTestCase to validate overlays

firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexBackfiller.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsResult.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/RemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/FieldIndex.java, firebase-firestore/src/main/java/com/google/firebase/firestore/util/Util.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/CountingQueryEngine.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexBackfillerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexingEnabledSQLiteLocalStoreTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/RemoteDocumentCacheTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteOverlayMigrationManagerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCacheTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/model/FieldIndexTest.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
This is another version of https://github.com/firebase/firebase-android-sdk/pull/3202
It's a bit simpler:
- It moves all IndexOffset logic to IndexBackfiller
- It re-uses more code in the LocalDocumentsView
- It removes the latest read time from the offset, as we can just keep the offset at the current read time
I also added a new LocalStoreTestCase that verifies our query processing.
=> Backfill Mutations

firebase-crashlytics/firebase-crashlytics.gradle
Flame (Pixel 4) does not support API 30 any longer (1), so we need to use Redfin
(1) According to `gcloud firebase test android models list`
=> Change device model for testlab

firebase-installations/src/main/java/com/google/firebase/installations/local/PersistedInstallation.java
tries to solve https://github.com/firebase/firebase-android-sdk/issues/3313
the `dataFile` is initialized lazily from methods that are supposed to be already be called from a dedicated IO thread given they perform disk ops
=> Lazy initialize dataFile in PersistedInstallation

ci/fireci/fireciplugins/macrobenchmark.py
This is a follow up to #3343 which made the change for crashlytics.
=> Update macrobenchmark to use the right device

firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloader.java, firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/FirebaseMlLogger.java, firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileDownloadService.java, firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileManager.java
Proposed fix for #3321 by dev-gloomyfox.
TLDR: FirebaseModelDownloader instance creation fails when using a separate FirebaseApp instance. 
The proposed fix will overload the `getInstance` method of both `FirebaseMlLogger.java` & `ModelFileManager.java`. This method will have a parameter of `FirebaseApp`, and will be used in [FirebaseModelDownloader.java#L58](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloader.java#L58) & [ModelFileDownloadService.java#L88](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileDownloadService.java#L88). 
More details is explained by the …
=> issue_3321_seperate_firebaseapp

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/AabUpdater.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/ApkUpdater.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionLifecycleNotifier.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/TaskUtils.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/TesterSignInManager.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/AabUpdaterTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/ApkUpdaterTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionLifecycleNotifierTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/TestUtils.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/TesterSignInManagerTest.java
This allows the handler to be run _immediately_ after the foreground activity is resumed. When relying on a Task handler, you're actually enqueueing the handler to either the main thread queue or our own executor's queue, and there's no guarantee that the activity is still in the foreground when it's called. While a race condition should be rare, it's better to avoid it if possible.
An alternative would be to pass in a "direct executor" that runs the listener in the same thread that sets the result, but this approach enforces that approach so the caller doesn't have to remember to do that.
=> Replace getForegroundActivity with applyToForegroundActivity[Task]

firebase-firestore/CHANGELOG.md, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/FirestoreCallCredentials.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/GrpcCallProvider.java
This should fix/improve our flaky Android and Unity CI.
=> Don't deadlock during shutdown()

firebase-appdistribution-stub/firebase-appdistribution-stub.gradle
The stub does not have any dependencies on core Firebase classes, so removing these.
=> Remove unnecessary dependencies from App Distribution stub SDK

build.gradle
Fireperf has some flaky E2E tests due to failures in downloading dependencies from jcenter(), which was deprecated and unstable. This PR will let Fireperf to download dependencies from mavenCentral() at the first place.
Note: Currently, it is hard to remove jcenter() for all Firebase products as many tests/products still depend on it. Firebase core team will remove jcenter() for all products.
=> Move jcenter() to the end on repositories

firebase-firestore/src/main/java/com/google/firebase/firestore/bundle/BundleLoader.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/MutableDocument.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/WatchChangeAggregator.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteOverlayMigrationManagerTest.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Backporting some of the changes in https://github.com/firebase/firebase-js-sdk/pull/5925 that were not already part of Android.
=> Backport readTime changes

firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
Use consistent naming in IndexState and IndexEntries. This is not a breaking change if merged by Feb 1 as the schema went live in the same release: https://github.com/firebase/firebase-android-sdk/pull/3226
=> Rename document_name to document_key

firebase-common/src/main/java/com/google/firebase/heartbeatinfo/DefaultHeartBeatController.java, firebase-common/src/test/java/com/google/firebase/heartbeatinfo/DefaultHeartBeatControllerTest.java
Adding NO_WRAP and NO_PADDING  to the encoding so that new line character doesn't show up and it doesn't cause e2e tests to fail or smoke tests to fail.
=> fix ci failures

ci/fireci/fireciplugins/fireperf.py
I recently updated the folder structure of fireperf plugin in the gradle repo and this needs to be updated.
=> Update `performance-gradle` to `perf-plugin`

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/AppDistributionRelease.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/BinaryType.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionException.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/OnProgressListener.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/UpdateProgress.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/UpdateStatus.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/UpdateTask.java
Updates Java doc comments based on code review feedback on the auto generated java docs.
Once this merges into the main branch, the test release branch will automatically re-generate the zip file with the docs.
=> Edit java docs for Firebase App Distribution

README.md, firebase-common/src/test/java/com/google/firebase/heartbeatinfo/DefaultHeartBeatControllerTest.java, firebase-common/src/test/java/com/google/firebase/heartbeatinfo/HeartBeatInfoStorageTest.java
Fix heartbeat tests so that copybara passes gracefully
=> Fix heartbeat tests

firebase-perf/src/test/java/com/google/firebase/perf/session/PerfSessionTest.java
`shouldCollectGaugesAndEvents_perfMonDisabledAtRuntime_sessionNotVerbose` occasionally fails when it tries to programmatically set the config. This is likely due to the [ConfigResolver](https://github.com/firebase/firebase-android-sdk/blob/486da83a45ba9658c413c19aed3026e0f6e8ced4/firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigResolver.java#L187) trying to setValue before the [shared preferences is ready](https://github.com/firebase/firebase-android-sdk/blob/486da83a45ba9658c413c19aed3026e0f6e8ced4/firebase-perf/src/main/java/com/google/firebase/perf/config/DeviceCacheManager.java#L247).
This just forces the test to use a single threaded [FakeDirectExecutorService](https://github.com/firebase/firebase-android-sdk/blob/ac3276ce7d5f5181b1c419731495eb88a98537af/firebase-perf …
=> Fix flaky PerfSessionTest due to async access to SharedPrefs

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/AccessHelper.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
Not needed anymore since it was added to the public API
=> Remove AccessHelper.clearPersistence()

firebase-perf/src/main/java/com/google/firebase/perf/network/InstrURLConnectionBase.java, firebase-perf/src/test/java/com/google/firebase/perf/network/InstrURLConnectionBaseTest.java
This should remove the possibility of a null being passed to InstrHttpInputStream/InstrHttpOutputStream.
Fixes #3406
=> Adding null checks for instantiating InstrHttpInputStream/InstrHttpOutputStream

firebase-messaging/src/main/java/com/google/firebase/messaging/DisplayNotification.java, firebase-messaging/src/main/java/com/google/firebase/messaging/ImageDownload.java, firebase-messaging/src/test/java/com/google/firebase/messaging/DisplayNotificationChannelRoboTest.java, firebase-messaging/src/test/java/com/google/firebase/messaging/DisplayNotificationRoboTest.java, firebase-messaging/src/test/java/com/google/firebase/messaging/ImageDownloadRoboTest.java
- Switched to stopping an image download by canceling a Future to interrupt the download thread instead of trying to close the InputStream directly since the underlying library does not appear to be thread safe and can throw a variety of Exceptions when close is called on a different thread (https://github.com/firebase/firebase-android-sdk/issues/1830 for a previous issue).
=> Stop image download by canceling a Future.

firebase-firestore/src/main/java/com/google/firebase/firestore/index/IndexEntry.java, firebase-firestore/src/main/java/com/google/firebase/firestore/util/Util.java
The schema is `index_id, uid, array_value, directional_value, document_key`. Our internal order should match this.
=> Prefer arrayValue when sorting FieldIndex

firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateMonitor.java, firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateUpdateHandler.java, firebase-perf/src/test/java/com/google/firebase/perf/application/AppStateMonitorTest.java
b/204362742
`_fs` and `_bs` traces are using the next sessionId instead of the current sessionId because we call `updateAppState` ([line 176](https://github.com/firebase/firebase-android-sdk/pull/3122/files#diff-eb968bff71b0337966fe331ee130c0ad812d5fed5e8b15c7e676a565bb0074c5L176)) before sending `_fs` or `_bs` traces ([line 177](https://github.com/firebase/firebase-android-sdk/pull/3122/files#diff-eb968bff71b0337966fe331ee130c0ad812d5fed5e8b15c7e676a565bb0074c5L177)).  One of the callbacks of `updateAppState` is `SessionManager` which updates the sessionId, thus `_fs` and `_bs` uses the next session's sessionId. 
This fix simply changes the order of methods, delaying `updateAppState` until session trace is sent.
=> Fireperf: fix incorrect `sessionId`s for `_fs` and `_bs` traces

firebase-firestore/src/main/java/com/google/firebase/firestore/core/Target.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryIndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexBackfillerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
This reduces the number of times TargetIndexMatcher has to be invoked and hence reduces the number of reads from IndexedDB in the Web port.
=> Remove canServeFromIndex

firebase-firestore/src/main/java/com/google/firebase/firestore/core/Target.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/Values.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
This adds the ability to use inequality and equality filters on the same field.
=> Support > and != on the same field

firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
This reverts commit 26d09920f8c5beace35606445b502ff13ba38dc4.
=> Revert "Re-establish streams when App Check token expires. (#3328)"

firebase-firestore/src/test/java/com/google/firebase/firestore/local/DocumentOverlayCacheTestCase.java
This test was ported from https://github.com/firebase/firebase-ios-sdk/commit/cf04e6740bd371738cd62bed71498838a259e3db, part of https://github.com/firebase/firebase-ios-sdk/pull/9345.
=> DocumentOverlayCacheTestCase.testUpdateDocumentOverlay() added

transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManager.java
Proposed fix for #3459 by [danyalberton](https://github.com/danyalberton).
The DROP_GLOBAL_LOG_EVENT_STATE_SQL is only called during onDowngrade, which means if somehow the migration fails half way, there is no way of continuing the migration, thus it's best to call DROP_GLOBAL_LOG_EVENT_STATE_SQL whenever creating the table to ensure this table does not exist before upgrade.
=> call DROP_GLOBAL_LOG_EVENT_STATE_SQL before inserting during migration

firebase-firestore/CHANGELOG.md, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/WriteBatchTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
Fixes: https://github.com/firebase/firebase-android-sdk/issues/3490 and https://github.com/FirebaseExtended/flutterfire/issues/7988
=> Fix overlay recalculation bug with multiple batches

firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java, firebase-firestore/src/test/java/com/google/firebase/firestore/model/TargetIndexMatcherTest.java
This changes indexing to always specify an array_value as it is part of the primary key:
```
db.execSQL(
"CREATE TABLE index_entries ("
+ "index_id INTEGER, " // The index_id of the field index creating this entry
+ "uid TEXT, "
+ "array_value BLOB, " // index values for ArrayContains/ArrayContainsAny
+ "directional_value BLOB, " // index values for equality and inequalities
+ "document_key TEXT, "
+ "PRIMARY KEY (index_id, uid, array_value, directional_value, document_key))");
```
=> Always use array_valye

firebase-database/CHANGELOG.md, firebase-database/src/androidTest/java/com/google/firebase/database/QueryTest.java, firebase-database/src/main/java/com/google/firebase/database/connection/PersistentConnectionImpl.java, firebase-database/src/main/java/com/google/firebase/database/core/Repo.java
Addresses [b/221106730](http://b/221106730). Existing behavior is to throw a "Client is offline" exception when no local value is available. The reason we did this was so that we could fallback to disk cache when the server is unresponsive. 
However, if there is no local persisted value available, which could be the case when an app is just starting up, get will just give up. For consistency with our other operations, get should await a database connection in this case.
Since we want to "try" the server when a persisted value is available, and "await" the server when a persisted value is not available, we have to check for the persisted value before sending any requests to the server.
=> `Query.get` should wait for backend connection

firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateMonitor.java, firebase-perf/src/test/java/com/google/firebase/perf/application/AppStateMonitorTest.java
b/210055697
In multi-activity apps, when Activity 1 starts Activity 2, `FrameMetricsAggregator` does not work when `frameMetricsAggregator.add(activity2)` is called before `reset()` of activity1. That is the current behaviour because we use `onStart` and `onStop`. The order of these lifecycle callbacks are well defined in the activity lifecycle documentation, "[Coordinating activities](https://developer.android.com/guide/components/activities/activity-lifecycle#coordinating-activities)" section. 
Move the "stopping of screen traces" from `onActivityStopped` to `onActivityPostPaused`. According to the same [documentation](https://developer.android.com/guide/components/activities/activity-lifecycle#coordinating-activities), the order of these callbacks are well defined, and it is …
=> Fireperf: fix screen trace in multi-activity apps

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/TesterSignInManager.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/TesterSignInManagerTest.java
Changing the cancellation of the sign in task from onActivityStarted too onActivityResume. This is because in the original implementation if the user hit back before being redirected to the web the task would hang. This fix makes it so that if the user clicks back into the app at any point the task will be cancelled.
=> Fixing sign in cancellation bug

firebase-firestore/src/main/java/com/google/firebase/firestore/core/Target.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryIndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/TargetTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexBackfillerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
I am really struggling to understand why this was broken and not detected by the existing tests. I also wonder whether this is actually the right fix and could use a thorough set of eyes.
=> Support descending queries

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/FileStore.java
There is a problem with the file structure on some devices #3269. When we did the FileStore refactor, we turned a silent failure into a runtime exception, causing apps to crash on some of these devices. Although this does not fix the root problem, it reverts to the silent behaviour we had before. We still need to investigate the root cause of this.
=> Do not throw when FileStore cannot create a dir.

firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigResolver.java, firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigurationConstants.java, firebase-perf/src/test/java/com/google/firebase/perf/config/ConfigResolverTest.java, firebase-perf/src/test/java/com/google/firebase/perf/config/ConfigurationConstantsTest.java
A new flag is added for fragment trace sampling flag. This flag is fetched from remote config, but overridable from the manifest file.
=> Add fragment trace sampling rate config flag

firebase-appdistribution/CHANGELOG.md
Reference: http://cl/433250870
=> Update CHANGELOG from m112 release

firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryDocumentOverlayCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteDocumentOverlayCache.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/Mutation.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/MutationBatch.java, firebase-firestore/src/main/java/com/google/firebase/firestore/util/Preconditions.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/DocumentOverlayCacheTestCase.java, smoke-tests/build.gradle
The current implementations of `DocumentOverlayCache.saveOverlays()` checks that each value in the given `Map` is non-null, and if it is null it ignores it, as if the key/value pair wasn't even present in the map.
This PR changes the logic to _assume_ that none of the values in the `Map` are null and modifies the call sites to ensure that they avoid putting null values into the map.
This is a slightly cleaner implementation and makes the null behavior more explicit at the call site.
=> Change DocumentOverlayCache.saveOverlays() to require non-null values in the given Map

firebase-firestore/CHANGELOG.md, firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/CountingQueryEngine.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteLocalStoreTest.java
Just like with Index-Free queries, we can't use indexing for limit queries if one of the indexed values contains a non-indexed mutation. The test case should make this case obvious.
=> Don't use Indexes for outdated limit queries

firebase-messaging/src/main/java/com/google/firebase/messaging/FcmLifecycleCallbacks.java
https://github.com/firebase/firebase-android-sdk/issues/3538
* Added catching RuntimeException when trying to get the analytics data Bundle from the Activity Intent since it's possible that the extras could contain invalid or incorrectly formatted data that will throw an Exception when trying to get the Bundle.
=> Catch RuntimeException when getting analytics Bundle.

firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateMonitor.java, firebase-perf/src/main/java/com/google/firebase/perf/application/FragmentMonitor.java, firebase-perf/src/main/java/com/google/firebase/perf/application/FragmentStateMonitor.java
b/208271814
This PR doesn't include tests to unblock the other implementation tasks, tests will be added in another PR. 
EDIT: actually don't see a reason to test because these are just lifecycle callbacks, there's nothing in those callbacks so there's nothing to test.
=> Fireperf: fragment lifecycle callbacks

firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateMonitor.java, firebase-perf/src/test/java/com/google/firebase/perf/application/AppStateMonitorTest.java
followup to https://github.com/firebase/firebase-android-sdk/pull/3311
=> Fireperf: start screen trace in `onResume`

smoke-tests/build.gradle, smoke-tests/src/main/java/com/google/firebase/testing/BuildOnlyTest.java
Reverts firebase/firebase-android-sdk#3555
Because app-distro has not been included in the BoM, it is causing smoke test failures for some other products. This removes app-distribution from smoke test temporarily. We will add it back when the product is out of beta (and added to the BoM).
=> Revert "Add Firebase App Distribution to smoke tests"

appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultAppCheckToken.java, appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/DefaultAppCheckTokenTest.java, appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/StorageHelperTest.java
=> Fix refresh logic for App Check custom providers.

firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateMonitor.java, firebase-perf/src/main/java/com/google/firebase/perf/application/FragmentStateMonitor.java, firebase-perf/src/main/java/com/google/firebase/perf/util/Constants.java, firebase-perf/src/test/java/com/google/firebase/perf/application/FragmentStateMonitorTest.java
b/208271842
Currently there's a validation error:
> W/FirebasePerformance: non-positive totalFrames in screen trace _st_SupportRequestManagerFragment
W/FirebasePerformance: Invalid Trace:_st_SupportRequestManagerFragment
W/FirebasePerformance: Unable to process the PerfMetric (trace metric: _st_SupportRequestManagerFragment (duration: 118339.913ms)) due to missing or invalid values. See earlier log statements for additional information on the specific missing/invalid values.
This is due to no frame metrics for the "total_frames" validation check, because we have not implemented that yet.
=> Fireperf fragments: trace creation and adding custom attributes

smoke-tests/build.gradle
This reverts #3531 .
#3531 was a workaround for #3526 . Now that the issue was fixed, the workaround is no longer needed.
=> Revert "[firehorn] Workaround to make smoke-test pass. (#3531)"

firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateMonitor.java, firebase-perf/src/main/java/com/google/firebase/perf/application/FragmentStateMonitor.java, firebase-perf/src/main/java/com/google/firebase/perf/metrics/FrameMetricsCalculator.java, firebase-perf/src/main/java/com/google/firebase/perf/util/ScreenTraceUtil.java, firebase-perf/src/test/java/com/google/firebase/perf/application/FragmentStateMonitorTest.java, firebase-perf/src/test/java/com/google/firebase/perf/metrics/FrameMetricsCalculatorTest.java
The original PR with comments can be found #3584
=> Add frame metrics to fragment traces

firebase-appdistribution/firebase-appdistribution.gradle, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/ApkUpdater.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/ApkUpdaterTest.java
ApkUpdater class was missing some unit test coverage on classes such as downloadToDisk and updateApk where we were not testing some paths of success.
Added in testing to verify all of the notifications used in the ApkUpdater class. 
Test the happy path of the updateApk method going through download apk -> makeApkDownloadRequest -> downloadToDisk.
As well as testing the fail case of validateJarFile.
=> Adding unit tests to ApkUpdater class

firebase-messaging/src/main/java/com/google/firebase/messaging/CommonNotificationBuilder.java, firebase-messaging/src/test/java/com/google/firebase/messaging/CommonNotificationBuilderRoboTest.java
* Added createNotificationInfo() variant that allows specifying a calling Context to be used for creating PendingIntents and one Context that the notification is intended for (resources, package name, manifest data, etc.).
=> Add createNotificationInfo() that takes a calling and an app Context.

appcheck/firebase-appcheck-debug-testing/gradle.properties, appcheck/firebase-appcheck-debug/gradle.properties, appcheck/firebase-appcheck-interop/gradle.properties, appcheck/firebase-appcheck-safetynet/gradle.properties, appcheck/firebase-appcheck/gradle.properties
Correct the version listed in `gradle.properties` files to be version number of the upcoming App Check release.
=> Fix App Check version numbers in `gradle.properties`

appcheck/firebase-appcheck-playintegrity/src/main/java/com/google/firebase/appcheck/playintegrity/internal/GeneratePlayIntegrityChallengeRequest.java, appcheck/firebase-appcheck-playintegrity/src/main/java/com/google/firebase/appcheck/playintegrity/internal/GeneratePlayIntegrityChallengeResponse.java, appcheck/firebase-appcheck-playintegrity/src/main/java/com/google/firebase/appcheck/playintegrity/internal/PlayIntegrityAppCheckProvider.java, appcheck/firebase-appcheck-playintegrity/src/test/java/com/google/firebase/appcheck/playintegrity/internal/GeneratePlayIntegrityChallengeRequestTest.java, appcheck/firebase-appcheck-playintegrity/src/test/java/com/google/firebase/appcheck/playintegrity/internal/GeneratePlayIntegrityChallengeResponseTest.java, appcheck/firebase-appcheck-playintegrity/src/test/java/com/google/firebase/appcheck/playintegrity/internal/PlayIntegrityAppCheckProviderTest.java, appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/NetworkClient.java, appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/NetworkClientTest.java
Add Play Integrity attestation logic, which includes obtaining a challenge nonce from the App Check backend.
=> Implement Play Integrity attestation flow.

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/DevelopmentPlatformProviderTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/DevelopmentPlatformProvider.java
Check for a specific flutter asset file instead of listing the path.
This should fix issue #3605 caused by the fact that listing an asset path may be slow in some cases.
=> Check for a specific flutter asset file instead of listing the path

firebase-firestore/src/main/java/com/google/firebase/firestore/remote/Datastore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/FirestoreChannel.java
#no-changelog
For BatchGetDocuments, since the SDK knows the number of document paths in the requests, as soon as the SDK receives all the responses needed, it will fire user callback to save user's waiting time.
=> SDK support for logical termination in Firestore BatchGetDocuments

firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceFragmentScreenTracesTest.java, firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceScreenTracesTest.java
b/228604783
An attempt to fix the missing activity screen traces in e2e autopush. Instead of backgrounding, start another activity to trigger `sendScreenTrace`.
=> Fireperf: trigger `sendScreenTrace` by starting new activity in `FirebasePerformanceScreenTracesTest`

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/Utils.java
This fixes a bug where the exception handler never times out while waiting for settings that never come.
=> Timeout when blocking tasks on any thread.

firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
We need to return the least restrictive index type and not the first one we find
=> Return the minimum index type from all targets

appcheck/firebase-appcheck-debug-testing/gradle.properties, appcheck/firebase-appcheck-debug/gradle.properties, appcheck/firebase-appcheck-debug/src/test/java/com/google/firebase/appcheck/debug/internal/DebugAppCheckProviderTest.java, appcheck/firebase-appcheck-interop/gradle.properties, appcheck/firebase-appcheck-safetynet/gradle.properties, appcheck/firebase-appcheck-safetynet/src/test/java/com/google/firebase/appcheck/safetynet/internal/SafetyNetAppCheckProviderTest.java, appcheck/firebase-appcheck/gradle.properties, appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/AppCheckTokenResponse.java, appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultAppCheckToken.java, appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/NetworkClient.java, appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/AppCheckTokenResponseTest.java, appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/DefaultAppCheckTokenTest.java, appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/NetworkClientTest.java
Switch the App Check SDKs over to using the `v1` App Check APIs.
=> Update App Check SDKs to use `v1` API.

firebase-functions/api.txt, firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.java, firebase-functions/src/main/java/com/google/firebase/functions/HttpsCallableReference.java
Sorry for a late-coming urgent change; AFAICT nobody on the SDK team could staff these changes, so I'm trying to write the change for the top 3 SDKs before I/O freeze.
For context, see [go/cf3v2-crash-landing](http://go/cf3v2-crash-landing).
For API approval, see [go/callable-functions-custom-urls](http://go/callable-functions-custom-urls)
=> Add FirebaseFunctions.getHttpsCallableFromURL

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java
Fix for android for: https://github.com/firebase/firebase-js-sdk/issues/6134
=> Fix a bug with limitToLast and cursors

firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexBackfiller.java
This is a very minor refactor to simplify code:
- removes 2 lines of code.
- removes 1 private property.
- removes conditional evaluation on every execution.
- removes assignment on every execution.
- adds 1 parameter to private method.
There should be no side effects, since the IndexBackfiller never appears to start after a being stopped. If for some reason the IndexBackfiller should start again, there will simply be a larger delay in subsequent starts.
=> Minor refactor of IndexBackfiller to eliminate private property.

firebase-messaging/src/main/java/com/google/firebase/messaging/FcmLifecycleCallbacks.java
https://github.com/firebase/firebase-android-sdk/pull/3432
* Also included delaying checking for notification open logging on Android 7.1 (N MR1/25) to avoid Bundle unparceling race condition.
=> Log notification open after onActivityCreated() on Android 7.1.

firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateMonitor.java, firebase-perf/src/main/java/com/google/firebase/perf/application/FragmentStateMonitor.java, firebase-perf/src/main/java/com/google/firebase/perf/application/FrameMetricsRecorder.java, firebase-perf/src/main/java/com/google/firebase/perf/metrics/FrameMetricsCalculator.java, firebase-perf/src/test/java/com/google/firebase/perf/application/AppStateMonitorTest.java, firebase-perf/src/test/java/com/google/firebase/perf/application/FragmentStateMonitorTest.java, firebase-perf/src/test/java/com/google/firebase/perf/application/FrameMetricsRecorderTest.java
Make AppStateMonitor to not care about FrameMetricsAggregator. Instead make the AppStateMonitor depend on FrameMetricsRecorder (which abstracts FrameMetricsAggregator)
=> Abstract FrameMetricsAggregator to FrameMetricsRecorder class

firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceFragmentScreenTracesTest.java
The other test with `_st_FirebasePerfScreenTracesActivity` is not flaky and [relaunches the activity](https://github.com/firebase/firebase-android-sdk/blob/9ab121fbb8c21dd093483f8cf4a0a6d12c6f0cda/firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceScreenTracesTest.java#L56-L58) at the end of the test, so I am trying to relaunch the activity to ensure the screen trace is sent.
=> Attempt to fix flaky E2E screen trace by relaunching the activity.

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/FileStoreTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/FileStore.java
Update the Crashlytics file system to support multi-process apps more elegantly.
This new file system only works on Android 28 and above. Pre-28 will continue to use to the v1 file system.
Tested manually with SDK and NDK.
Pair with @mrichards
=> Update Crashlytics file system to support multi-process apps

firebase-messaging/src/main/java/com/google/firebase/messaging/MessagingAnalytics.java
Upgrade logging priority so that message delivered logs are reported from devices with increased background restrictions or network restrictions.
=> Upgrade Firelog priority from telemetry to data

firebase-messaging/src/main/java/com/google/firebase/messaging/MessagingAnalytics.java
After changing the priority to DEFAULT, it usually takes less than 1 hour to deliver the data.
=> Update comment of logToFirelog method

firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/View.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java, firebase-firestore/src/test/java/com/google/firebase/firestore/bundle/BundleSerializerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteLocalStoreTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteQueryEngineTest.java
This changes the query engine to also drop the limit on limit queries that need to be refilled. It also cleans up some of the Target.getLimit() logic that leads to repetitive code.
=> Re-run limit queries without limit if they need to be re-filled

firebase-appdistribution-api/api.txt, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionException.java
The constructors need to be public, because they are called from other packages (i.e. internal/impl).
But there is no reason for customers to create these exceptions themselves.
So having them show up in JavaDoc is confusing and not helpful.
=> Hides the constructors for FirebaseAppDistributionException.

firebase-appdistribution/firebase-appdistribution.gradle, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ErrorMessages.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClient.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/NewReleaseFetcher.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/AabUpdaterTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClientTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/NewReleaseFetcherTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TestUtils.java
Refactors the FID/FIS auth token fetching into the API client, since that will be needed by the feedback stuff.
=> Refactor FID logic into FirebaseAppDistributionTesterApiClient

firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceFragmentScreenTracesTest.java, firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceScreenTracesTest.java, firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceTest.java, firebase-perf/e2e-app/src/main/java/com/google/firebase/testing/fireperf/FirebasePerfActivity.java, firebase-perf/e2e-app/src/main/java/com/google/firebase/testing/fireperf/FirebasePerfScreenTracesActivity.java, firebase-perf/e2e-app/src/main/java/com/google/firebase/testing/fireperf/FireperfUtils.java, firebase-perf/e2e-app/src/main/java/com/google/firebase/testing/fireperf/NetworkRequestGenerator.java, firebase-perf/e2e-app/src/main/java/com/google/firebase/testing/fireperf/SlowListAdapter.java, firebase-perf/e2e-app/src/main/java/com/google/firebase/testing/fireperf/TraceGenerator.java
This PR addresses some problems with E2E test app setup:
1. Removes unnecessary `block` and `notify` (because `Espresso`/`ActivityScenario` methods like `onView` `onActivity` [already wait for main thread to be idle before running](https://g3doc.corp.google.com/java/com/google/android/apps/searchlite/g3doc/testing/deflake_playbook.md?cl=head#unnecessary-espressoonidle-before-onviewondata)) 
2. Removes semaphores (which had a race condition b/231739863), and use `Future` instead
3. Simplify `FirebasePerformanceTest.waitForBothTracesAndNetworkRequestsBatch` and `FireperfUtils` by a lot. Previous code had executors calling executors calling executors...only one is enough. Without this, `Future` is enough, which means no `Semaphore` or `CountDownLatch` needed. `Future` is a lot less …
=> Fireperf: significantly simplify android instrumentation tests

firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
Fixes #3760.
Adding null checker when updateFidListener is called.
=> Fixes NullPointerException at updateFidListener

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterApiHttpClient.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterApiHttpClientTest.java
This will be used to upload screenshots. An upload request is just a POST to a different host with some extra headers.
=> Add upload request to TesterApiHttpClient

transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/AlarmManagerScheduler.java
Fixes #3805.
As stated:
> Android 12 need to specify the [mutability flag](https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability) with every PendingIntent. This seems to be missing in the above two lines.
I added the condition to check for version `Build.VERSION_CODES.M` or higher, before setting the `PendingIntent.FLAG_IMMUTABLE` flag. 
This is the same condition checker for other files e.g. `FirebaseMessaging.java` [Line 502](https://github.com/firebase/firebase-android-sdk/blob/8e28b5b1bd38a4356a40e7546290ce857cdd1d0a/firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessaging.java#L502).
=> added pending intent mutability

firebase-appdistribution-api/api.txt, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/UpdateProgress.java, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionProxy.java, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionStub.java, firebase-appdistribution/firebase-appdistribution.gradle, firebase-appdistribution/src/main/AndroidManifest.xml, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ErrorMessages.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackSender.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClient.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ReleaseIdentifier.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ScreenshotTaker.java, firebase-appdistribution/src/main/res/layout/activity_feedback.xml, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FeedbackSenderTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterApiHttpClientTest.java
Adds `FeedbackSender` as a new Component, so that it can be accessed by the FeedbackActivity.
Screencast (submit fails because the upload URL mapping has not rolled out to GFE yet): https://screencast.googleplex.com/cast/NTQ2NDIyNjkzNzE3NjA2NHw0M2YwNjUxYS03Nw
=> Implement collectAndSendFeedback()

firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/QueryEngineTestCase.java
#no-changelog
Make Android SDK and iOS SDK consistent.
=> Change comments and test instances in QueryEngine

transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/logging/Logging.java
Previously #3728 which fixes #3716.
Initially, condition checker was for version (API < 24), but now will change to (API < 26).
[Android documentation](https://developer.android.com/reference/android/util/Log#isLoggable(java.lang.String,%20int)):
> `IllegalArgumentException` is thrown if the tag.length() > 23 for Nougat (7.0) and prior releases (API <= 25), there is no tag limit of concern after this API level.
=> Changing condition statement API version < 26 for log limit

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/AabUpdater.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionLifecycleNotifier.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterSignInManager.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/AabUpdaterTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ApkUpdaterTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionLifecycleNotifierTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TestUtils.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterSignInManagerTest.java
The old `applyToForegroundActivity()` which accepted a `void` callback, is now called `consumeForegroundActivity()`.
Also, adds `TestUtils.mockForegroundActivity()` for mocking all of these types of methods to return a given activity.
=> Add support for return values to applyToForegroundActivity()

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CommonUtilsTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCapture.java
Remove Android ID check heuristic from isEmulator check.
Tested with unit tests, the default emulators with Android Studio, and a physical device. There might be more heuristics we can replace this with if needed.
=> Remove Android ID check heuristic from isEmulator check.

firebase-perf/src/main/java/com/google/firebase/perf/logging/ConsoleUrlGenerator.java, firebase-perf/src/test/java/com/google/firebase/perf/logging/ConsoleUrlGeneratorTest.java
The Firebase console metrics page is getting deprecated.
=> Update IDE URL to troubleshooting page

transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java
There is a deadline mismatch between the client and the server. The client has a deadline of 40 seconds, and server has 2 minutes, causing the client to repeat requests (with backoff), until they are delivered. This will increase the client deadline to 130 seconds.
=> Increase the Data Transfer read timeout default to 130 seconds

firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileManager.java, firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/ModelFileManagerTest.java
As the issue https://github.com/firebase/firebase-android-sdk/issues/3864 details, this is an edge case I would like to fix and shouldn't occur in regular occurrence.
An alternative to this fix is to potentially change
CUSTOM_MODEL_ROOT_PATH = "com.google.firebase.ml.custom.models";
to something different than what [FirebaseModelManager](https://firebase.google.com/docs/reference/android/com/google/firebase/ml/common/modeldownload/FirebaseModelManager) was using.
=> Adding file path check to avoid NumberFormatException due to empt path

buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/ChangedModulesTask.kt
The task should return the module even if nothing depends on it since it
likely has tests of its own.
=> Support leaf modules in changed modules task.

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/TransactionTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalSerializerTest.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/ComparatorTester.java
Googlers see cl/457735855 from which this PR was ported.
=> Firestore: Add @CanIgnoreReturnValue annotations in tests

firebase-components/firebase-dynamic-module-support/firebase-dynamic-module-support.gradle
Move from monolithic to partitioned apis at https://developer.android.com/reference/com/google/android/play/core/release-notes#partitioned-apis
Fixes #3860
=> Fix dynamic module support bug https://github.com/firebase/firebase-android-sdk/issues/3860

firebase-firestore/src/main/java/com/google/firebase/firestore/core/CompositeFilter.java
We want a composite filter object to be immutable (the list of filters stored in a composite filter shouldn't change). We had marked the list as `final`, but we should also make sure getters are not able to modify the list.
To avoid adding Guava as a dependency, we're not going to use `ImmutableList`. Instead, we'll return `unmodifiableList` in the getters.
=> Use unmodifiableList for CompositeFilters.

firebase-firestore/src/proto/google/firestore/v1/query.proto
This is to reflect the latest proto updates (now in the [preview](https://github.com/googleapis/googleapis/blob/preview/google/firestore/v1/query.proto#L68-L72) branch)
=> Update the query protos.

.github/workflows/update-cpp-sdk-on-release.yml
To match the change done in the IOS repo
https://github.com/firebase/firebase-ios-sdk/pull/10009
=> Update name of file in CPP repo.

firebase-firestore/CHANGELOG.md, firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
=> Ensure Client exists

firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java, firebase-firestore/src/main/java/com/google/firebase/firestore/util/LogicUtils.java, firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java
We had used OPERATOR_UNSPECIFIED in place of the OR enum because the proto was
not ready. Now that the proto has been updated, we can remove those.
Also found an out-of-date TODO and removed it.
=> Remove usage of OPERATOR_UNSPECIFIED and use the real OR operator.
