firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/AabUpdater.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/AabUpdaterTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TestOnProgressListener.java
- Makes AabUpdater run async code on its own executor wherever possible to avoid going back and forth between the executor and the main thread, which makes testing difficult
- Add `TestOnProgressListener` which allows test to wait for a specified number of progress updates
=> Fix broken firebase-appdistribution test

firebase-appdistribution/test-app/README.md
This is to help with the error:
```
Project 'test-app' not found in project ':firebase-appdistribution'
```
=> Add instructions to enable `test-app` in subprojects.cfg

firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/AabUpdaterTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TestOnProgressListener.java
Based on comments in https://github.com/firebase/firebase-android-sdk/pull/3920
=> Some cleanup in AabUpdaterTest

firebase-appdistribution-api/api.txt, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionException.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ErrorMessages.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterApiDisabledErrorDetails.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterApiHttpClient.java, firebase-appdistribution/src/test/assets/apiDisabledBadLinkResponse.json, firebase-appdistribution/src/test/assets/apiDisabledResponse.json, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TestUtils.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterApiDisabledErrorDetailsTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterApiHttpClientTest.java
See [go/fad-sdk-auth-errors](http://go/fad-sdk-auth-errors) for more information.
=> Handle API disabled errors in firebase-appdistribution

firebase-appdistribution-api/api.txt, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionProxy.java, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionStub.java, firebase-appdistribution/src/main/AndroidManifest.xml, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackSender.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ImageUtils.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ScreenshotTaker.java, firebase-appdistribution/src/main/res/layout/activity_feedback.xml, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FeedbackSenderTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ImageUtilsTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ScreenshotTakerTest.java
This reverts commit 78d28880e0c3897fda8055e988127da67a122466, merging it into `fad-in-app-feedback`.
This will establish the new feature branch for developing the In-App Feedback feature.
=> Revert "Remove In-App Feedback functionality from firebase-appdistribution (#3926)

firebase-messaging/src/main/java/com/google/firebase/messaging/FcmBroadcastProcessor.java, firebase-messaging/src/main/java/com/google/firebase/messaging/WakeLockHolder.java, firebase-messaging/src/main/java/com/google/firebase/messaging/WithinAppServiceConnection.java, firebase-messaging/src/test/java/com/google/firebase/messaging/FcmBroadcastProcessorRoboTest.java, firebase-messaging/src/test/java/com/google/firebase/messaging/WakeLockHolderRoboTest.java, firebase-messaging/src/test/java/com/google/firebase/messaging/WithinAppServiceConnectionRoboTest.java
* Changed to finish the message broadcast as soon as the Intent is sent to the FirebaseMessagingService when binding to the Service. This should reduce the chance that the BroadcastReceiver ANRs in certain circumstances.
* Acquired a WakeLock when using bindService() to send an Intent to FirebaseMessagingService to prevent the device from sleeping while processing the Intent now that the broadcast is finished before the Service has finished handling it.
- Holding the WakeLock for up to 60 seconds for high priority messages to match the behavior for high priority messages when using startService().
- Holding the WakeLock for up to 9 seconds for normal priority messages to match the previous behavior where the broadcast was not forced to finish for 9 seconds.
=> Finish message broadcast after sending Intent to bound Service.

firebase-appdistribution-api/api.txt, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionProxy.java, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionStub.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt
Based on API council review feedback.
=> Rename collectAndSendFeedback to startFeedback

firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionException.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ErrorMessages.java
This merges https://github.com/firebase/firebase-android-sdk/pull/3934 into `master`, instead of the in-app feedback feature branch where it was accidentally merged.
=> Update messaging around API_DISABLED status

ci/README.md, ci/fireci/setup.cfg
Current numpy version does not support arm64 m1 macos. Support is added in 1.21.0.
=> Upgrade numpy version to 1.23.1

firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexBackfillerTest.java
=> Clean up code in IndexBackfiller

.github/workflows/ci_tests_experimental.yml
NDK r21 is no longer provided by default on GitHub Actions.
https://github.com/actions/virtual-environments/issues/5930
=> Install NDK r21 on GitHub Actions

firebase-components/src/main/java/com/google/firebase/components/Component.java, firebase-components/src/main/java/com/google/firebase/components/ComponentRegistrarProcessor.java, firebase-components/src/main/java/com/google/firebase/components/ComponentRuntime.java, firebase-components/src/test/java/com/google/firebase/components/ComponentRuntimeTest.java, firebase-components/src/test/java/com/google/firebase/components/ComponentTest.java
It allows augmenting/replacing components as they are requested from
ComponentRegistrars.
The motivation is to be able to measure initialization time of
certain components and at the same time not to introduce this
measurement logic directly to the components framework.
=> Add an extension point to ComponentRuntime.

firebase-appdistribution-api/api.txt, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionProxy.java, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionStub.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java, firebase-appdistribution/src/main/res/layout/activity_feedback.xml, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt, firebase-appdistribution/test-app/src/main/res/values/strings.xml
Based on [go/iaf-sdk-api-proposal](http://go/iaf-sdk-api-proposal)
Tested in test app:
=> Add info text argument to startFeedback

.github/workflows/private-mirror-sync.yml
The current setup of the workflow is not working:
https://github.com/firebase/firebase-android-sdk/actions/workflows/private-mirror-sync.yml
There are two problems:
- `actions/checkout` checks out a shallow copy of the code, which is not push-able
- the token supplied to `actions/checkout` can only be used for authentication with http but not with ssh
=> Fix sync job between OSS and private repository

buildSrc/src/main/java/com/google/firebase/gradle/plugins/VendorPlugin.kt, firebase-inappmessaging/src/androidTest/java/com/google/firebase/inappmessaging/TestApiClientModule.java, firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/ApiClient.java, firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/injection/modules/ApiClientModule.java, transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStoreTest.java, transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/persistence/SpyEventStoreModule.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/EventStoreModule.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStore.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManagerTest.java
1. Transform jar inputs in addition to directory inputs.
Future AGP will generate r_classes.jar instead of creating R classes in
a directory.
2. Replace Lazy with Provider to avoid vendoring issues.
It looks like AGP has stopped "transforming" test classes, so switching
to Provider instead of `dagger.Lazy` to avoid the problem. It's not an
issue since the injected classes are effectively singletons.
=> Fix vendoring plugin issues in future AGP versions

.github/workflows/api-information.yml
When configuring required status checks to pass in branch protection rules, the status checks are distinguished only by the job names, regardless of their workflow name. Therefore, individual job names need to be more self-explanatory.
=> Use more explanatory name for API information job

appcheck/firebase-appcheck/ktx/ktx.gradle, buildSrc/src/main/java/com/google/firebase/gradle/plugins/Dokka.java, buildSrc/src/main/java/com/google/firebase/gradle/plugins/publish/Publisher.java, firebase-appdistribution-api/ktx/ktx.gradle, firebase-common/firebase-common.gradle, firebase-config/ktx/ktx.gradle, firebase-crashlytics/ktx/ktx.gradle, firebase-database/ktx/ktx.gradle, firebase-dynamic-links/ktx/ktx.gradle, firebase-firestore/ktx/ktx.gradle, firebase-functions/ktx/ktx.gradle, firebase-inappmessaging-display/ktx/ktx.gradle, firebase-inappmessaging/ktx/ktx.gradle, firebase-installations/ktx/ktx.gradle, firebase-messaging/ktx/ktx.gradle, firebase-ml-modeldownloader/ktx/ktx.gradle, firebase-perf/ktx/ktx.gradle, firebase-storage/ktx/ktx.gradle
Additionally fix pom dependency type resolution.
=> Use the more common stdlib dep now that we ship java8 bytecode.

appcheck/firebase-appcheck/ktx/src/main/kotlin/com/google/firebase/appcheck/ktx/FirebaseAppCheck.kt
This PR should add the missing KtxRegistrar to appcheck-ktx
=> add FirebaseAppCheckKtxRegistrar to appcheck-ktx

smoke-tests/gradle.properties
Smoke tests have been occasionally failing due to:
```
FAILURE: Build failed with an exception.
* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
```
This pull request seems to fix the issue. With the change in this pull request, the above error does not appear in any of the 5 total runs of smoke tests (see attempt 1-5 of https://github.com/firebase/firebase-android-sdk/actions/runs/2905798357).
=> Prevent gradle daemon from crashing

appcheck/firebase-appcheck/ktx/src/main/kotlin/com/google/firebase/appcheck/ktx/FirebaseAppCheck.kt, build.gradle, buildSrc/build.gradle.kts, buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaGenerationTask.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java, buildSrc/src/main/java/com/google/firebase/gradle/plugins/FiresiteTransformTask.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/JavadocPlugin.java, buildSrc/src/main/java/com/google/firebase/gradle/plugins/KotlinUtils.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/ProjectUtils.kt, buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/PublishingPluginTests.kt, firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentId.java, firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessaging.java, firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/model/CampaignMetadata.java, subprojects.cfg
Our current Dokka implementation is old and was due for an upgrade. Thankfully, the folks over at AndroidX have been working on new tooling that integrates directly with Dokka- and provides translations for DevSite. This PR does not include the removal of any old systems, only the addition of the new ones. The java variant of our ref doc generations will remain the same until we are comfortable with the DackkaPlugin.
This PR comes with:
- Various javadoc fixes
- Additional utility methods for buildSrc
- `DackkaGenerationTask` for creating ref docs with dackka
- `FiresiteTransformTask` for translating Devsite output from dackka to Firesite ready output
- `DackkaPlugin` for managing everything dackka related, and providing default configurations
All functionality provided in this PR is …
=> Add a new plugin for Dackka

firebase-perf/src/main/java/com/google/firebase/perf/transport/RateLimiter.java, firebase-perf/src/test/java/com/google/firebase/perf/transport/RateLimiterTest.java
Blocking https://github.com/firebase/firebase-android-sdk/pull/4024.
b/243686627
TL;DR: don't use `@VisibleForTesting` method for real code, they break encapsulation. In this case, `Timer(long time)` is breaking logic too because it's mixing 2 different timebases together (time-since-epoch and time-since-VM-start). It's a bad method that should not exist even for tests.
However if we remove the above, there's a leftover problem from https://github.com/firebase/firebase-android-sdk/pull/2662:
Before https://github.com/firebase/firebase-android-sdk/pull/2662, say there are 0 tokens at first. We can call `rateLimiter.check()` after any amount of time, so something like 1.33 tokens can be generated, but we only use `long` for our `tokenCount`, so it will automatically round to 1, and record …
=> [Fireperf] Fix `RateLimiter` by avoiding manually setting time

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
Since [`URL#openConnection()`](https://docs.oracle.com/javase/7/docs/api/java/net/URL.html#openConnection()) only creates the connection object and doesn't open the connection, we were optimistically resetting the retries remaining before checking if the connection actually succeeded. (`connect()` or any downstream method like `getResponseCode()` must be called to open the connection.)
This change
* updates `beginRealtimeHttpStream()` to call `connect()` before resetting the retries
* and propagates the `IOException` thrown by `openConnection()` rather than checking if the connection object is `null` so we can collapse the two into one user-visible error about the realtime connection
Comparable iOS change: https://github.com/firebase/firebase-ios-sdk/pull/10143
=> Only reset retries when the realtime connection successfully opens.

firebase-messaging/src/main/java/com/google/firebase/messaging/CommonNotificationBuilder.java, firebase-messaging/src/main/java/com/google/firebase/messaging/FcmBroadcastProcessor.java
* Cleaned up some unused methods in CommonNotificationBuilder.
* Also changed to explicitly save the result of sendIntent() in FcmBroadcastProcessor but not use it since we're blocking on the result of the Task, and added a comment to that effect.
=> Clean up unused methods.

firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/DisplayCallbacksImpl.java, firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/ProtoStorageClient.java, firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/DisplayCallbacksImplTest.java
https://github.com/firebase/firebase-android-sdk/issues/3774
The Flag variable to check whether impressed or not was a static one and because of which when one FIAM message is marked as impressed, it was affecting other messages until the app restarts.
=> Fix: Cannot mark as impressed more than one message almost same time

firebase-installations/src/androidTest/java/com/google/firebase/installations/StrictModeTest.java, firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java, firebase-installations/src/test/java/com/google/firebase/installations/FirebaseInstallationsTest.java
This fix defers initialization of `IidStore` (which performs a disk read) with a `Lazy`, resolving strict mode violations, and re-enables the strict mode test.
=> Resolved strict mode violations in firebase-installations

firebase-perf/src/main/java/com/google/firebase/perf/metrics/AppStartTrace.java, firebase-perf/src/main/java/com/google/firebase/perf/util/Timer.java, firebase-perf/src/test/java/com/google/firebase/perf/metrics/AppStartTraceTest.java, firebase-perf/src/test/java/com/google/firebase/perf/util/TimerTest.java
b/243537606
Blocked by https://github.com/firebase/firebase-android-sdk/pull/4027
Change `Timer.java`'s timebase to `elapsedRealtime` for consistency with Android platform API. Platform APIs like `Process.startElapsedRealtime()` are in that timebase, so if we want to find duration between our timestamps and Android API's, then they must be the same timebase. 
Changed variable names and some Javadoc, because the old ones are incorrect and misleading. We aren **not** using different APIs for wallclock time (`timeInMicros`) and duration-calculating-time (`highResTime`) because duration-calculating-time is high-resolution. _We are separating them because wall-clock is **not monotonic**_. See the top of this doc https://developer.android.com/reference/android/os/SystemClock to learn more.
=> [Fireperf][AASA] change timebase to `elapsedRealtime`

firebase-perf/src/main/java/com/google/firebase/perf/util/FirstDrawDoneListener.java, firebase-perf/src/test/java/com/google/firebase/perf/util/FirstDrawDoneListenerTest.java
=> [Fireperf][AASA] `FirstDrawDoneListener`

buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/Metalava.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/ProjectUtils.kt
Per [b/243941807](b/243941807), this refactors the Dackka task to utilize Metalava generated stubs for Java sources, and use the standard sources for Kotlin.
This also adds a small extension method for Metalava, since we don't actually offer configuration of the output directory on stub generation.
=> Implement Metalava with Dackka

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/network/HttpGetRequest.java
Properly encode http params. This should resolve #4060 where special characters were not being encoded.
Should we consider using a typical http library instead of this custom built network package?
=> Properly encode http params.

buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaGenerationTask.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt
Otherwise no docs are produced for java sdks.
=> Make dackka task depend on docStubs task.

firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt, firebase-appdistribution/test-app/test-app.gradle
- Uses the recommended Kotlin syntax for accessing the FirebaseAppDistribution object
- Updates compile and target SDK versions to 31 to make a lint error go away
- Cleans up dependencies
=> Minor updates to the App Distribution test app.

buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/GradleUtils.kt
In accordance with [b/245753889](https://b.corp.google.com/issues/245753889), this adds support to the DackkaPlugin to generate Javadoc variants.
More specifically this:
- Removes the `deleteDackkaGeneratedJavaReferences` task
- Refactors `copyOutputToCommonDirectory` to two separate task
- Adds a new task to copy the Javadoc output via `copyJavaDocToCommonDirectory`
- Adds a new task to copy the Kotlindoc output via `copyKotlinDocToCommonDirectory`
- Adds an extension method to the `Copy` task in gradle for copying individual directories
- Fixes the `DackkaPlugin` documentation to reflect the new changes
Keep in mind that the current implementation in this pr requires the project setting `dackkaJavadoc` to be equal to `true`, otherwise Dackka won't copy the Javadoc output to the root …
=> Add Javadoc support to the DackkaPlugin

firebase-appdistribution/test-app/test-app.gradle
- `compileSdk`/`targetSdkVersion` from 31 to 33
- various dependencies to latest version
=> Update various versions

buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaGenerationTask.kt, kotlindoc/package-lists/kotlin/package-list
Per [b/246812330](https://b.corp.google.com/issues/246812330), this adds the Kotlin standard library to our precompiled package lists. This also resolves [b/246794289](https://b.corp.google.com/issues/246794289).
Previously, it seems we fetched the package list for the Kotlin stdlib online at build time. With `offlineMode` enabled now, that process doesn't occur. Instead of disabling the setting, we can just add the Kotlin stdlib package-list to our list of precompiled package-lists.
=> Add Kotlin stdlib to the precompiled package-lists 

firebase-appdistribution/firebase-appdistribution.gradle, firebase-appdistribution/src/androidTest/AndroidManifest.xml, firebase-appdistribution/src/androidTest/java/com/google/firebase/appdistribution/StrictModeTest.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/SignInStorage.java
* Adds integration tests in appdistribution for testing strict mode violations
* Defers access of shared preferences off of component initialization to not block during init
=> Resolve strict mode violations in firebase-appdistribution

firebase-appdistribution/firebase-appdistribution.gradle
`UsingOnClickInXml` did not work correctly when running with AGP 7.2.2,
=> update appcompat (1.3.0 -> 1.5.1) to fix lint

firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/GaugeManager.java, firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/GaugeMetadataManager.java, firebase-perf/src/main/proto/firebase/perf/v1/perf_metric.proto, firebase-perf/src/test/java/com/google/firebase/perf/metrics/validator/FirebasePerfGaugeManagerValidatorTest.java, firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/GaugeManagerTest.java, firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/GaugeMetadataManagerTest.java
getRunningAppProcesses() was also causing compliance issues with Tencent's appstore #4045
=> Removing getRunningAppProcesses since the process_name isn't used

buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/ProjectUtils.kt
This fixes: [b/246972998](https://b.corp.google.com/issues/246972998)
Removing `projectSpecificSources` was an over-sight, and led to `com.google.firebase.Timestamp` not being generated during doc generation. Adding the method back fixes this.
Additionally, I removed the `isKotlin` check for `excludedFiles` as it was redundant (since the method checks for a specific project, it would be ignored when needed as a by-product).
I also added an additional util method for `dependsOnAndMustRunAfter` and changed our `dependsOn(docStubs)` as such. We need `docStubs` to run _before_ `generateDackkaDocumentation`, and not having `mustRunAfter` was leading to not-so-fun gradle "optimizations".
And some restructuring for readability and consistency :')
=> Add projectSpecificSources back to the DackkaPlugin

buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/FiresiteTransformTask.kt
In an effort to make the DackkaPlugin tasks all cache compliant (per [b/243833009](https://b.corp.google.com/issues/243833009)), the only remaining task that was not already cache complaint was FiresiteTransform. This PR fixes that.
More specifically, we now copy the transformed files into a new directory labeled `dackkaTransformedFiles`, versus working on the same files that Dackka outputs. This allows gradle to check if the files have actually changed, and pass an `UP-TO-DATE-CHECK` as needed.
Build time has dropped from ~50 seconds to only ~15 seconds, that's a 333% decrease!
=> Make FiresiteTransform a Cacheable task

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
- Check http response status code before retrying. Http status codes being used to retry are:
Ok 200
Client Timeout 408
Bad Gateway 502
Unavailable 503
Gateway timeout 504
Similar to what Fetch uses to throttle requests:
[firebase-android-sdk/firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandler.java](https://github.com/firebase/firebase-android-sdk/blob/523730a3b4463160490170d9348818a5c403a2eb/firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandler.java#L390)
- Close error stream
=> Realtime RC - Check HTTP status before listening and retrying

firebase-appdistribution/firebase-appdistribution.gradle, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java, firebase-appdistribution/src/main/res/layout/activity_feedback.xml
AppCompat was updated in https://github.com/firebase/firebase-android-sdk/pull/4104
This requires a compileSdkVersion of 32. Without that the tests fail. Rather than increase compileSdkVersion, which requires our customers to do the same, let's just fix the lint error for now by removing the click handler.
=> Fix tests by downgrading AppCompat and fixing lint issue

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
`getText()` preserves styles, unlike `getString()`
After: 
Before:
=> Fix links in FeedbackActivity info text

buildSrc/src/main/java/com/google/firebase/gradle/plugins/ProjectUtils.kt
Per [b/248582256](https://b.corp.google.com/issues/248582256), this PR upgrades Dackka to 1.0.3
For the sake of keeping our dry run up-to-date, and since the Dackka team is constantly fixing bugs- an effort to keep the artifact up-to-date should be made.
Note: I've also added the 1.0.3 artifact to our maven bucket, so the DackkaPlugin can be ran successfully.
=> Upgrade Dackka to 1.0.3

kotlindoc/package-lists/firebase/package-list
In accordance with [b/248593457](https://b.corp.google.com/issues/248593457), this fixes the incorrect output from running Dackka on `appcheck-ktx`. The `package-summary` url was missing the expected `firebase.google.com` prefix for translation. Since the artifact is new, it wasn't included in the previous package list. This PR adds it to the file, and the docs compile as expected.
=> Fix appcheck-ktx doc generation

firebase-messaging/firebase-messaging.gradle, firebase-messaging/src/androidTest/AndroidManifest.xml, firebase-messaging/src/androidTest/java/com/google/firebase/messaging/StrictModeTest.java
Part of a larger effort to resolve and prevent strict mode violations for eager components.
=> Add strict mode testing in firebase-messaging

appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheck.java, appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheckTest.java
Resolve a StrictMode violation in App Check by moving the retrieval of the stored App Check token out of the initialization path.
=> Resolve StrictMode violation in App Check.

firebase-appdistribution-api/api.txt, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionProxy.java, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionStub.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackSender.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClient.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ImageUtils.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/LogWrapper.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ScreenshotTaker.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterApiHttpClient.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FeedbackSenderTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClientTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ImageUtilsTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ScreenshotTakerTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterApiHttpClientTest.java, firebase-appdistribution/test-app/src/main/AndroidManifest.xml, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/FeedbackTriggers.java, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/ScreenshotDetectionFeedbackTrigger.java, firebase-appdistribution/test-app/test-app.gradle
Also has some refactoring to, among other things, allow the passing of a screenshot URI to the `startFeedback()` API.
=> Add a screenshot-based trigger for in-app feedback

firebase-perf/dev-app/dev-app.gradle, firebase-perf/dev-app/src/main/AndroidManifest.xml, firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigResolver.java, firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigurationConstants.java, firebase-perf/src/main/java/com/google/firebase/perf/config/RemoteConfigManager.java, firebase-perf/src/main/java/com/google/firebase/perf/metrics/AppStartTrace.java, firebase-perf/src/test/java/com/google/firebase/perf/config/RemoteConfigManagerTest.java, firebase-perf/src/test/java/com/google/firebase/perf/metrics/AppStartTraceTest.java
b/245947422
b/243540978
During startup, when we want to decide to record this trace or not, we only check disk cache for RC flag because RC is not initialized yet. 
This RC flag will be saved to disk ONLY upon successful RC `fetchAndActivate()`. There's a problem with all other flags in that they are being saved to disk every time they are queried.
=> [Fireperf][AASA] send `_experiment_app_start_ttid` trace, controlled by RC flag

firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/AppDistroTestApplication.kt, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/SecondActivity.kt, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/ShakeForFeedback.kt, firebase-appdistribution/test-app/src/main/res/layout/activity_main.xml, firebase-appdistribution/test-app/src/main/res/layout/list_item.xml, firebase-appdistribution/test-app/src/main/res/menu/action_menu.xml, firebase-appdistribution/test-app/src/main/res/values/strings.xml
Also:
- Move the regular feedback button trigger to an action bar menu
- Clean up some of the UX code (removing unnecessary type params, making padding uniform)
- Turn ShakeForFeedback from a singleton class into an object
=> Add menu to test app for selecting feedback trigger

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/AppDistroTestApplication.kt, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/ScreenshotDetectionFeedbackTrigger.java
Also:
- Refactor screenshot trigger so it can be enabled application-wide, instead of per activity
- Put a guard in place on URI-based startActivity() methods to prevent callers from starting feedback multiple times simultaneously
=> Hook screenshot trigger to test app menu

firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ApkUpdaterTest.java
The test was asserting that the task is not complete, and then awaiting completion. However it's totally possible that it would have already completed by that assertion, which is probably why it failed randomly during a presubmit test on https://github.com/firebase/firebase-android-sdk/pull/4152.
=> Fix ApkUpdaterTest flake

buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/FiresiteTransformTask.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/GradleUtils.kt, buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/publishing.kt, firebase-abt/firebase-abt.gradle, firebase-components/firebase-components.gradle, firebase-components/firebase-dynamic-module-support/firebase-dynamic-module-support.gradle, firebase-database-collection/firebase-database-collection.gradle
In accordance with [b/247570655](https://b.corp.google.com/issues/247570655), this PR extends `FiresiteTransform` to offer configuration for the generated `_reference-head-tags.html` at the top of html files.
We would like to offer a unique ref html file for each set of docs (Java & Kotlin), for SEO purposes etc.,
To accomplish this, without drastically changing the behavior of `FiresiteTransform` - we now expose a task to separate the Java and Kotlin generated sets before transformation- and then combine them after the fact. This required a bit of overhead to accomplish, but will pay off in the long run whenever we decide to combine the output directory of Java and Kotlin generated sets.
To keep things as idiomatic as possible, I started defining the desired output directories at the …
=> Specify unique ref tags in Dackka output

appcheck/firebase-appcheck/firebase-appcheck.gradle, appcheck/firebase-appcheck/src/androidTest/java/AndroidManifest.xml, appcheck/firebase-appcheck/src/androidTest/java/com/google/firebase/appcheck/StrictModeTest.java, appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/StorageHelper.java
Adds tests for strict mode violations and moves shared preferences to a lazy.
=> Fix strict mode violations for appcheck

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CountTest.java
Enable the integration tests for COUNT that were added in https://github.com/firebase/firebase-android-sdk/pull/4130 now that the RunAggregationQuery RPC has been fully rolled out.
=> Enable COUNT integration tests, now that backend support has rolled out

buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaGenerationTask.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt
After investigating why AGP's Kotlin directories shared the same sources as the Java variant ([b/46984444](https://b.corp.google.com/issues/246984444)), it has become apparent that this separation does not have any benefit to us- and is intended behavior. Because of this, I've removed all referenced of the bug- and combined Java and Kotlin source set variables during Dackka generation.
=> Combine Java/Kotlin sources in Dackka Plugin

firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/NotificationFeedbackTrigger.kt
- Change notification importance/priority to LOW
- Set `requestPermissionLauncher` to null in onDestroy instead of onPause
- Don't show notification for `TakeScreenshotAndTriggerFeedbackActivity`
- Automatically reformat entire file to make this PR unreadable...
=> Small tweaks to notification feedback trigger

firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/ShakeForFeedback.kt
The current level, medium, is too high and difficult to trigger.
=> Turn down shake sensitivity

appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/SafetyNetAppCheckProviderFactory.java
[The SafetyNet Attestation API is being deprecated and replaced with the Play Integrity API](https://developer.android.com/training/safetynet/deprecation-timeline); as such, we will also be deprecating App Check's use of SafetyNet.
=> Deprecate App Check SafetyNet SDK

firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/NotificationFeedbackTrigger.kt, firebase-appdistribution/test-app/test-app.gradle
Currently the call to `notificationManager.notify()` is flagged because it is not guarded by a permissions check.
=> Fix compiler warnings about checking permissions

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandlerTest.java
Assign the few builder setter return values to satisfy `@CheckReturnValue` requirements for Google's build system. This avoids a dependency on `com.google.errorprone:error_prone_annotations` -- firebase-components already has error_prone (so we include it transitively) but we don't need the annotation extensively and can avoid maintaining/updating more dep versions.
This is a no-op change.
Internal: b/245979943#comment4
=> Assign ConfigContainer Builder return values.

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandler.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandlerTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClientTest.java
Revert NO_CHANGE bug fixes: https://github.com/firebase/firebase-android-sdk/pull/4181#pullrequestreview-1139673872. These fixes will be replaced with the changes proposed in go/realtime-rc-forward-compatibility.
=> remove NO_CHANGE bug fixes

firebase-perf/CHANGELOG.md, firebase-perf/ktx/api.txt, firebase-perf/ktx/src/main/kotlin/com/google/firebase/perf/ktx/Performance.kt
[go/firebase-perf-kotlin-api-addendum](http://goto.google.com/firebase-perf-kotlin-api-addendum)
Closes #2029
=> feat(perf-ktx): add trace(name, block) extension function

firebase-appdistribution-api/api.txt, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/InterruptionLevel.java, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionProxy.java, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionStub.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionNotificationsManager.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionNotificationsManagerTest.java, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt
A proposed change on top of: https://github.com/firebase/firebase-android-sdk/pull/4183
=> Add InterruptionLevel to notification trigger API

smoke-tests/build.gradle, smoke-tests/src/main/java/com/google/firebase/testing/BuildOnlyTest.java
App Indexing is deprecated starting BoM 31.0.0.
https://firebase.google.com/support/release-notes/android#bom_v31-0-0
=> Remove smoke test for app indexing

appcheck/firebase-appcheck-debug/src/test/java/com/google/firebase/appcheck/debug/internal/DebugAppCheckProviderTest.java, appcheck/firebase-appcheck-playintegrity/src/test/java/com/google/firebase/appcheck/playintegrity/internal/PlayIntegrityAppCheckProviderTest.java, appcheck/firebase-appcheck-safetynet/src/test/java/com/google/firebase/appcheck/safetynet/internal/SafetyNetAppCheckProviderTest.java, appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheckTest.java, appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/DefaultTokenRefresherTest.java, build.gradle, firebase-appdistribution-api/src/test/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionProxyTest.java, firebase-appdistribution/firebase-appdistribution.gradle, firebase-common/data-collection-tests/src/test/java/com/google/firebase/DataCollectionPostNDefaultDisabledTest.java, firebase-common/data-collection-tests/src/test/java/com/google/firebase/DataCollectionPreNDefaultDisabledTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigComponentTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandlerTest.java, firebase-crashlytics/firebase-crashlytics.gradle, firebase-database/firebase-database.gradle, firebase-firestore/firebase-firestore.gradle, firebase-firestore/ktx/ktx.gradle, firebase-inappmessaging-display/src/test/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplayTest.java, firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/InAppMessageStreamManagerTest.java, firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/MetricsLoggerClientTest.java, firebase-installations/src/test/java/com/google/firebase/installations/FirebaseInstallationsTest.java, firebase-messaging/firebase-messaging.gradle, firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/ModelFileDownloadServiceTest.java, firebase-perf/firebase-perf.gradle, firebase-perf/ktx/ktx.gradle, transport/transport-backend-cct/transport-backend-cct.gradle
Robolectric 4.9 was released today, see https://github.com/robolectric/robolectric/releases/tag/robolectric-4.9 for details.
=> Bump Robolectric to 4.9

firebase-appdistribution-api/api.txt, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/InterruptionLevel.java, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionProxy.java, firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionStub.java, firebase-appdistribution/src/main/AndroidManifest.xml, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ApkUpdater.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionLifecycleNotifier.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionNotificationsManager.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ScreenshotTaker.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TakeScreenshotAndStartFeedbackActivity.java, firebase-appdistribution/src/main/res/values/strings.xml, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ApkUpdaterTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionLifecycleNotifierTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionNotificationsManagerTest.java, firebase-appdistribution/test-app/src/main/AndroidManifest.xml, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/AppDistroTestApplication.kt, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/CustomNotificationFeedbackTrigger.kt, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/NotificationFeedbackTrigger.kt, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/SecondActivity.kt, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/ShakeForFeedback.kt, firebase-appdistribution/test-app/src/main/res/values/strings.xml, firebase-appdistribution/test-app/test-app.gradle
This adds a new API allowing developers to show a notification that, when tapped, will take a screenshot of the running application and open the feedback form. This way the developers don't need to add any new UI elements to their app to trigger feedback.
Other changes include:
- The lifecycle notifier now tracks the previous activity in addition to the current one, so that we can ignore our own empty activity when taking a screenshot after the notification is tapped.
- Adds the SDK-based notification trigger to the test app
=> Notification trigger API

.github/workflows/create_releases.yml
This implementation:
- Creates the base branch (name is based in user input)
- Creates the release branch (name is based in user input)
- Creates the release.cfg file in the release branch without adding any SDK (module) to it.
It can create the branches based on any existing branch of the repo.
=> Add "create release PR" github action

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CountTest.java
This verifies that the descriptive error message that occurs when the server does not have the required index has the URL that customers can follow to create the index.
=> Firestore: Add test that verifies count query error message when missing index

firebase-firestore/CHANGELOG.md, firebase-firestore/ktx/src/test/java/com/google/firebase/firestore/TestUtil.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/QueryListener.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/View.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/ViewSnapshot.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/TargetChange.java, firebase-firestore/src/roboUtil/java/com/google/firebase/firestore/TestUtil.java, firebase-firestore/src/test/java/com/google/firebase/firestore/QuerySnapshotTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryListenerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/ViewSnapshotTest.java, firebase-firestore/src/test/resources/json/listen_spec_test.json
Fix a bug where Firestore fails to return results from the local cache if the result set was empty.
This bug is due to the following logic in `QueryListener.java`:
https://github.com/firebase/firebase-android-sdk/blob/ae3bdb895e47b3d9a688dfbfe5ef3e94f2918c59/firebase-firestore/src/main/java/com/google/firebase/firestore/core/QueryListener.java#L143
which assumes that if the result set from the local cache is empty that there is no cached result; however, if the result set of the query is indeed empty then it should be returning that empty result set from the cache.
This fix improves the logic to use the presence of a hasCachedResults flag to indicate that the empty result set is cached data and should be raised to the client.
This bug fix is ported from …
=> Fix Firestore failing to return empty results from the local cache

firebase-database/firebase-database.gradle, firebase-database/src/test/java/com/google/firebase/database/PushIdGeneratorTest.java
firebase-database only uses `StringUtils#repeat` in test code, and it is easy to port repeat method to test file and remove plexus-utils from test dependency.
=> Remove plexus-utils from firebase-database's test dependency

firebase-functions/src/androidTest/java/com/google/firebase/functions/TestFirebaseInstanceIdInternal.java
The firebase-functions instrumentation tests broke after updating the firebase-iid version in #4225 . This PR should fix them.
=> test(functions): fix instrumentation tests

firebase-messaging/src/test/java/com/google/firebase/messaging/MessagingAnalyticsRoboTest.java
Properly reset SharedPreferences test state in between each test.
=> Fix flakiness in MessagingAnalyticsRoboTest.java

firebase-appdistribution/test-app/src/main/AndroidManifest.xml, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/AppDistroTestApplication.kt, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/CustomNotificationActivity.kt, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/CustomNotificationFeedbackTrigger.kt, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt, firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/ShakeDetectionFeedbackTrigger.kt, firebase-appdistribution/test-app/src/main/res/layout/activity_custom_notification.xml, firebase-appdistribution/test-app/src/main/res/values/strings.xml
=> Simplify custom notification trigger example and move to activity

firebase-firestore/CHANGELOG.md, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/TransactionTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/Transaction.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/TransactionRunner.java
This fix is ported from Web SDK https://github.com/firebase/firebase-js-sdk/pull/6550, and its follow-up PR https://github.com/firebase/firebase-js-sdk/pull/6729.
=> Fix FAILED_PRECONDITION when writing to a deleted document in a transaction

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java
- Do not send the screenshot if the checkbox is unchecked
- Disables the text input when sending feedback
=> Some tweaks to the FeedbackActivity

firebase-firestore/CHANGELOG.md, firebase-firestore/src/main/java/com/google/firebase/firestore/util/CustomClassMapper.java, firebase-firestore/src/test/java/com/google/firebase/firestore/util/MapperTest.java
#no-changelog
GenericTypeIndicator is used in firebase database (https://firebase.google.com/docs/reference/android/com/google/firebase/database/GenericTypeIndicator?hl=id) and not existing in Firestore. #222
=> Remove GenericTypeIndicator in error messages

firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
=> Early return in getDocumentsMatchingTarget

buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/FiresiteTransformTask.kt
Per [b/257073544](https://b.corp.google.com/issues/257073544), this PR adds a transform to `FiresiteTransform` that removes the leading `com.google` from our YAML files. This is fine for our kdoc files, but from the javadoc perspective it looks a bit odd as other internal tooling follows the same format (docs that are generated outside the scope of `DackkaPlugin`).
This also removes the old transform for removing the leading Firebase domain from links- as it's no longer needed (see #4258).
=> Add Dackka transform to remove leading groupId in Javadocs

appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/SafetyNetAppCheckProviderFactory.java
Remove the `@Deprecated` annotations added in #4187, as we are instead marking the SDK as deprecated in Android Studio.
The change in #4187 was never released, so it is not necessary to release with this update.
=> Remove `@Deprecated` annotations from App Check SafetyNet SDK

firebase-perf/CHANGELOG.md, firebase-perf/src/main/java/com/google/firebase/perf/application/FrameMetricsRecorder.java
Copy of https://github.com/firebase/firebase-android-sdk/pull/4184 due to CLA issues (Jeremy leaving).
Let's take a look at [Android's source code, in android.view.View](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/view/View.java;l=7381;drc=master?q=addFrameMetrics&ss=android%2Fplatform%2Fsuperproject).
The exception was thrown from `findFrameMetricsObserver`, inside `removeFrameMetricsListener`
Since this null check didn't exists, this triggers NPE when `mFrameMetricsObserver` is uninitialized. Jeremy found that [this was fixed in later Android versions](https://android.googlesource.com/platform/frameworks/base/+/140ff5ea8e2d99edc3fbe63a43239e459334c76b). Why then, is `mFrameMetricsObserver` uninitialized? It's because …
=> Fix `FrameMetrics` NPE

.github/workflows/build-release-artifacts.yml
This version of the workflow hardcodes the list of sdks to release to include Firestore only. Also, generated javadoc is not yet equivalent to what's generated by the regular release process.
=> Initial version of the build release artifacts workflow.

kotlindoc/package-lists/android/package-list
Per [b/257285420](https://b.corp.google.com/issues/257285420), this fixes the `@NonNull` and `@Nullable` annotation links in the Dackka output redirecting to a 404 page.
This occurred because those annotations were being provided by `androidx.annotation`, wheres we don't actually have any `androidx` package-list files for our external links during doc generation. Looking through the source, the only public API that even uses `androidx` seems to be pulling from the annotation artifact- so instead of creating a new file for it, I just added a reference to `androidx.annotation` below our already existing `android.annotation` in our package-list files.
=> Fix NonNull and Nullable annotation links

firebase-database/src/main/java/com/google/firebase/database/DataSnapshot.java, firebase-database/src/main/java/com/google/firebase/database/GenericTypeIndicator.java, firebase-database/src/main/java/com/google/firebase/database/MutableData.java, firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseMlException.java
Per [b/257286586](https://b.corp.google.com/issues/257286586), this PR fixes an issue where our docs were producing broken code elements.
This happens mainly because break elements are not supported by Dokka (see https://github.com/Kotlin/dokka/issues/2262). To fix this, we just replace the code elements with pre elements- which is what we should be doing anyhow.
Note that is only a concern for multi-line code elements. Those that are single lined are fine as is (although this PR does fix one or two that were not correctly whitespaced).
=> Fix broken code elements in docs

firebase-perf/src/main/java/com/google/firebase/perf/metrics/AppStartTrace.java, firebase-perf/src/main/java/com/google/firebase/perf/util/FirstDrawDoneListener.java, firebase-perf/src/main/java/com/google/firebase/perf/util/PreDrawListener.java, firebase-perf/src/main/java/com/google/firebase/perf/util/Timer.java, firebase-perf/src/test/java/com/google/firebase/perf/metrics/AppStartTraceTest.java, firebase-perf/src/test/java/com/google/firebase/perf/util/TimerTest.java
These experiments helps single out certain possibilities from the outliers we see in `_experiment_as_ttid`:
1. `SystemClock.uptimeMillis()` is another monotonic timebase, but excluding deep sleep. This helps single out if the app was entering deep sleep thus causing massive duration
2. `OnPreDraw` is what PRIMES uses for all of 1P Google, thus with lots of success. Just looking at onDraw there were many bugs and hoops the code has to deal with, and `onPreDraw` just looks more stable, so perhaps it can be a bug or something else there as well.
=> [Fireperf][AASA] Additional experiments for `_experiment_as_ttid`

firebase-database/src/main/java/com/google/firebase/database/DataSnapshot.java, firebase-database/src/main/java/com/google/firebase/database/DatabaseReference.java, firebase-database/src/main/java/com/google/firebase/database/MutableData.java
Per [b/257287954](https://b.corp.google.com/issues/257287954), this PR fixes `&lt;` and `&gt;` symbols breaking the doc output from Dackka.
This occurs because angle brackets are broken in Dackka (see [b/257276445](https://buganizer.corp.google.com/issues/257276445)). A workaround is to wrap them in `<code>` blocks. Although, looking through our existing source, it seems as though we oftentimes wrap types in code blocks anyhow- so this PR just wraps the entire type versus just wrapping the generic type (what's present in the angle brackets).
=> Fix &lt; and &gt; breaking the Javadoc output

buildSrc/src/main/java/com/google/firebase/gradle/plugins/FiresiteTransformTask.kt, firebase-firestore/src/main/java/com/google/firebase/Timestamp.java, firebase-perf/src/main/java/com/google/firebase/perf/metrics/Trace.java
Per [b/256180692](https://b.corp.google.com/issues/256180692), this PR fixes an issue where multiline `@see` blocks were leaking HTML into the final output for documentation.
This occurs due to an upstream issue with Dokka (see https://github.com/Kotlin/dokka/issues/2665), where line breaks inside of `@see` tags break the generated Javadoc. This *also* prevents hyperlinks from being utilized in `@see` blocks. Thankfully, this issue only occurs in two places throughout our codebase (at least on the public API, which is what matters for doc generation).
One instance was resolved by providing a direct reference to the object- as it just so happens to be present on our classpath (and as such, a hyperlink is not needed).
The remaining instance was solved in three ways:
1. We reduce the link to …
=> Fix multiline hyperlink renders

firebase-common/src/main/java/com/google/firebase/concurrent/ExecutorsRegistrar.java, firebase-common/src/main/java/com/google/firebase/concurrent/FirebaseExecutors.java, firebase-common/src/main/java/com/google/firebase/concurrent/SequentialExecutor.java, firebase-common/src/main/java/com/google/firebase/concurrent/package-info.java
Namely, SequentialExecutor and directExecutor.
=> Adds generally useful executors

firebase-common/src/main/java/com/google/firebase/concurrent/CustomThreadFactory.java, firebase-common/src/main/java/com/google/firebase/concurrent/ExecutorsRegistrar.java
Any violations would kill the app in debug builds of firebase-common, and log a warning in release builds. This is done to fail tests that incorrectly use executors while not affecting 3p apps in release builds.
Additionally correctly set thread priorities in an Android specific way.
=> Enable strict mode for executors.

buildSrc/src/main/java/com/google/firebase/gradle/NdkBinaryFixTask.kt, firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
Due to AGP upgrade the crashlytics-trampoline.so file stopped being included in the resulting AAR, this causes issues on devices with api 29+.
=> Fix ndk build.

buildSrc/src/main/java/com/google/firebase/gradle/MultiProjectReleasePlugin.java, buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt
Per [b/255992607](https://b.corp.google.com/issues/255992607), this replaces our old Javadoc generation through Doclava with our new implementation with Dackka- so that our release process now generates Javadocs through the `DackkaPlugin`.
For the sake of brevity (and ensuring everything works), this does not change any task names or even the general format of our release plugins. Especially since some of these plugins are very inter-tangled. This will be addressed in a future PR (probably in relation with my `firebase-library` refactor work coming up).
=> Replace Doclava with Dackka

transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/ForcedSender.java
Make ForcedSender.sendBlocking do nothing, instead of throw, when given a wrong Transport type.
This will make it easier to mock Transport in tests. This method is best-effort anyway, so doing nothing instead of throwing is fine.
=> Avoid throwing in ForcedSender.sendBlocking

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ReleaseIdentifier.java, firebase-appdistribution/src/main/res/values/strings.xml, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
Developers can use `adb shell setprop debug.firebase.appdistro.devmode true` to skip checking the release version (and skip actually submitting feedback - while keeping the UI).
=> Handle the case where we can't identify the release.

firebase-messaging/CHANGELOG.md, firebase-messaging/src/main/java/com/google/firebase/messaging/WakeLockHolder.java, firebase-messaging/src/test/java/com/google/firebase/messaging/WakeLockHolderRoboTest.java
https://github.com/firebase/firebase-android-sdk/issues/4315
* Released sendWakefulServiceIntent()'s WakeLock on the main thread instead of within WithinAppServiceConnection to prevent a deadlock trying to acquire the WakeLockHolder.syncObject.
=> Fix deadlock when handling simultaneous messages.

firebase-appdistribution/firebase-appdistribution.gradle, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/AabUpdater.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ApkUpdater.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClient.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/LogWrapper.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClientTest.java
Following [the guide](https://github.com/firebase/firebase-android-sdk/blob/e0cfdd60b8c7204805f78874892a03dccbe174af/docs/executors.md).
In all three cases we either block for network I/O or synchronization.
=> Use shared executors in App Distribution SDK

ci/fireci/fireciplugins/macrobenchmark/analyze/aggregator.py, ci/fireci/fireciplugins/macrobenchmark/analyze/analyzer.py, ci/fireci/fireciplugins/macrobenchmark/analyze/plotter.py, ci/fireci/fireciplugins/macrobenchmark/run/test_project.py, ci/fireci/setup.cfg
- Output more analysis results
- Close figure after saving to file
- Switch to `redfin` for more consistent results
=> Improve fireci CLI for macrobenchmark

buildSrc/src/main/java/com/google/firebase/gradle/plugins/VendorPlugin.kt, buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/VendorTests.kt, transport/transport-runtime/transport-runtime.gradle
This change removes parts of dagger that are not used by SDKs that vendor it in.
=> Enable dead code elimination for vendored deps.

build.gradle, encoders/protoc-gen-firebase-encoders/protoc-gen-firebase-encoders.gradle, encoders/protoc-gen-firebase-encoders/tests/tests.gradle, firebase-crashlytics/firebase-crashlytics.gradle, firebase-perf/ktx/ktx.gradle
Fix for #4371. 
Updating dependency to the latest patched version to avoid vulnerability issue.
- `com.google.protobuf:protobuf-java` from `3.17.3` to `3.21.9`
=> Changed protobuf-java to latest version 3.21.9

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionLifecycleNotifier.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ScreenshotTaker.java
Before: http://go/scrcast/NTM2MTE4NTkwMjgyMTM3NnxlMzFkZTdmNy0yYg
After: http://go/scrcast/NjE2MzAwNzY3NjYxMjYwOHwwNDg0N2I2Ny0wYw
=> Fix screenshot taking on platforms with hardware bitmaps

firebase-functions/CHANGELOG.md, firebase-functions/firebase-functions.gradle, firebase-functions/src/androidTest/java/com/google/firebase/functions/CallTest.java, firebase-functions/src/main/java/com/google/firebase/functions/FirebaseContextProvider.java, firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.java, firebase-functions/src/main/java/com/google/firebase/functions/FunctionsComponent.java, firebase-functions/src/main/java/com/google/firebase/functions/FunctionsMultiResourceComponent.java, firebase-functions/src/main/java/com/google/firebase/functions/FunctionsRegistrar.java, firebase-functions/src/main/java/com/google/firebase/functions/Serializer.java
This simplifies injection of firebase components so they don't have to be passed all the way from the registrar into classes that actually use components.
This change adds `+4.22 kB` to the size of the sdk, but is a small enough increase compared to the advantages it provides
=> Use dagger in functions.

firebase-crashlytics-ndk/README.md, firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
Set ndkVersion to 25.1.8937393 for Crashlytics NDK SDK.
We used to build with 21... but that is no longer required.
=> Set ndkVersion for Crashlytics NDK SDK.

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ScreenshotTaker.java
The continuation method needs to return a non-null `Task`. This change doesn't have any practical effect: either way no screenshot is captured and the feedback flow opens without a screenshot attached. But right now this prints an NPE and stack trace to the logs.
```
Failed to take screenshot for feedback
java.lang.NullPointerException: Continuation returned null
at com.google.android.gms.tasks.zzo.run(com.google.android.gms:play-services-tasks@@18.0.2:7)
at com.google.firebase.appdistribution.impl.FirebaseAppDistributionLifecycleNotifier$$ExternalSyntheticLambda5.execute(Unknown Source:0)
at com.google.android.gms.tasks.zzp.zzd(com.google.android.gms:play-services-tasks@@18.0.2:1)
at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.0.2:5)
at …
```
=> Fix 'Continuation returned null' error when there is no previous activity

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java, firebase-appdistribution/src/main/res/layout/activity_feedback.xml, firebase-appdistribution/src/main/res/values/themes.xml
http://go/scrcast/NjYyODI2NDQ3MTY5MTI2NHwzNmMzNDUxMC0wNA
=> Add spinner when sending feedback

firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHandler.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigComponentTest.java
* Allows the executor to be injected for testing. This came up testing https://github.com/firebase/firebase-android-sdk/pull/4339.
* Prepares Realtime to integrate with [Firebase Executors](https://github.com/firebase/firebase-android-sdk/blob/master/docs/executors.md).
=> Inject executor service for Realtime components.

buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/Coverage.java
Fixes the issue where JaCoCo cannot produce coverage files for certain kotlin packages.
See details:
- https://github.com/jacoco/jacoco/issues/1155
- https://youtrack.jetbrains.com/issue/KT-44757
=> Upgrade JaCoCo plugin version

.github/workflows/health-metrics.yml
The problem with `github.ref` was that when two consecutive commits are pushed to a feature branch (e.g. `master`) around the same time, the execution of health metrics test for the second commit will cancel the execution for the first one, and thus make the metrics measurement for the first commit unavailable.
=> Change concurrency group for health metrics test to "github.sha"

appcheck/firebase-appcheck/CHANGELOG.md, appcheck/firebase-appcheck/firebase-appcheck.gradle, appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/FirebaseAppCheckRegistrar.java, appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheck.java, appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultTokenRefresher.java, appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/TokenRefreshManager.java, appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/FirebaseAppCheckRegistrarTest.java, appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheckTest.java
=> Migrate `firebase-appcheck` to use standard executors provided by Firebase Common.

appcheck/firebase-appcheck-debug-testing/src/main/AndroidManifest.xml, appcheck/firebase-appcheck-debug-testing/src/main/java/com/google/firebase/appcheck/debug/testing/DebugAppCheckTestHelper.java, appcheck/firebase-appcheck-debug-testing/src/main/java/com/google/firebase/appcheck/debug/testing/DebugSecretProvider.java, appcheck/firebase-appcheck-debug-testing/src/main/java/com/google/firebase/appcheck/debug/testing/FirebaseAppCheckDebugTestingRegistrar.java, appcheck/firebase-appcheck-debug-testing/src/test/java/com/google/firebase/appcheck/debug/testing/DebugAppCheckTestHelperTest.java, appcheck/firebase-appcheck-debug-testing/src/test/java/com/google/firebase/appcheck/debug/testing/FirebaseAppCheckDebugTestingRegistrarTest.java, appcheck/firebase-appcheck-debug/src/main/java/com/google/firebase/appcheck/debug/DebugAppCheckProviderFactory.java, appcheck/firebase-appcheck-debug/src/main/java/com/google/firebase/appcheck/debug/FirebaseAppCheckDebugRegistrar.java, appcheck/firebase-appcheck-debug/src/main/java/com/google/firebase/appcheck/debug/InternalDebugSecretProvider.java, appcheck/firebase-appcheck-debug/src/main/java/com/google/firebase/appcheck/debug/internal/DebugAppCheckProvider.java, appcheck/firebase-appcheck-debug/src/test/java/com/google/firebase/appcheck/debug/FirebaseAppCheckDebugRegistrarTest.java, appcheck/firebase-appcheck-playintegrity/src/main/java/com/google/firebase/appcheck/playintegrity/FirebaseAppCheckPlayIntegrityRegistrar.java, appcheck/firebase-appcheck-playintegrity/src/main/java/com/google/firebase/appcheck/playintegrity/PlayIntegrityAppCheckProviderFactory.java, appcheck/firebase-appcheck-playintegrity/src/test/java/com/google/firebase/appcheck/playintegrity/FirebaseAppCheckPlayIntegrityRegistrarTest.java, appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/FirebaseAppCheckSafetyNetRegistrar.java, appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/SafetyNetAppCheckProviderFactory.java, appcheck/firebase-appcheck-safetynet/src/test/java/com/google/firebase/appcheck/safetynet/FirebaseAppCheckSafetyNetRegistrarTest.java
Integrate `SafetyNetAppCheckProvider`, `PlayIntegrityAppCheckProvider`, and `DebugAppCheckProvider` with Firebase Components. This is a prerequisite for migrating the `firebase-appcheck-safetynet`, `firebase-appcheck-playintegrity`, and the `firebase-appcheck-debug` SDKs to use go/firebase-android-executors.
Note: This PR involves a refactor in the logic for initializing a `DebugAppCheckProvider` with a debug secret obtained from `InstrumentationRegistry` arguments, in order to integrate `DebugAppCheckProvider` with Firebase Components.
=> Integrate `AppCheckProvider`s with Firebase Components.

appcheck/firebase-appcheck-debug-testing/CHANGELOG.md, appcheck/firebase-appcheck-debug/CHANGELOG.md, appcheck/firebase-appcheck-debug/firebase-appcheck-debug.gradle, appcheck/firebase-appcheck-debug/src/main/java/com/google/firebase/appcheck/debug/FirebaseAppCheckDebugRegistrar.java, appcheck/firebase-appcheck-debug/src/main/java/com/google/firebase/appcheck/debug/internal/DebugAppCheckProvider.java, appcheck/firebase-appcheck-debug/src/test/java/com/google/firebase/appcheck/debug/FirebaseAppCheckDebugRegistrarTest.java, appcheck/firebase-appcheck-debug/src/test/java/com/google/firebase/appcheck/debug/internal/DebugAppCheckProviderTest.java, appcheck/firebase-appcheck-playintegrity/CHANGELOG.md, appcheck/firebase-appcheck-playintegrity/firebase-appcheck-playintegrity.gradle, appcheck/firebase-appcheck-playintegrity/src/main/java/com/google/firebase/appcheck/playintegrity/FirebaseAppCheckPlayIntegrityRegistrar.java, appcheck/firebase-appcheck-playintegrity/src/main/java/com/google/firebase/appcheck/playintegrity/internal/PlayIntegrityAppCheckProvider.java, appcheck/firebase-appcheck-playintegrity/src/test/java/com/google/firebase/appcheck/playintegrity/FirebaseAppCheckPlayIntegrityRegistrarTest.java, appcheck/firebase-appcheck-playintegrity/src/test/java/com/google/firebase/appcheck/playintegrity/internal/PlayIntegrityAppCheckProviderTest.java, appcheck/firebase-appcheck-safetynet/CHANGELOG.md, appcheck/firebase-appcheck-safetynet/firebase-appcheck-safetynet.gradle, appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/FirebaseAppCheckSafetyNetRegistrar.java, appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/internal/SafetyNetAppCheckProvider.java, appcheck/firebase-appcheck-safetynet/src/test/java/com/google/firebase/appcheck/safetynet/FirebaseAppCheckSafetyNetRegistrarTest.java, appcheck/firebase-appcheck-safetynet/src/test/java/com/google/firebase/appcheck/safetynet/internal/SafetyNetAppCheckProviderTest.java, appcheck/firebase-appcheck/CHANGELOG.md
#4431 migrated the base `firebase-appcheck` SDK to go/firebase-android-executors. This PR migrates the remaining App Check SDKs (`firebase-appcheck-safetynet`, `firebase-appcheck-playintegrity`, `firebase-appcheck-debug`).
=> Migrate remaining App Check SDKs to go/firebase-android-executors.

firebase-appdistribution-api/firebase-appdistribution-api.gradle, firebase-appdistribution/firebase-appdistribution.gradle
This has never actually been used. Built and tested locally.
=> Remove unused jetbrains annotations dependencies

.github/workflows/diff-javadoc.yml, buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/ChangedModulesTask.kt
Adds a workflow to diff javadoc in PRs. The workflow will add one collapsed comment and edit it on new commits, showing a git styled diff in github markdown for each file changed.
=> Add Diff Javadoc workflow

.github/workflows/build-src-check.yml, .github/workflows/create_releases.yml, .github/workflows/diff-javadoc.yml, .github/workflows/merge-to-main.yml, .github/workflows/update-cpp-sdk-on-release.yml
Currently we use third party actions in a handful of places, and tags are targeted. This could hypothetically become an attack vector, so tags are replaced with the commits we're currently using. Of note, third party actions from `ruby/` `actions/` `github/` `google/` and `google-github-actions/` are considered trustworthy to target via tag.
=> Secure external Github Actions

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/AabUpdater.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ApkInstaller.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ApkUpdater.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/AppIconSource.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionNotificationsManager.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClient.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ImageUtils.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/InstallActivity.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/LogWrapper.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/NewReleaseFetcher.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ReleaseIdentifier.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/SignInResultActivity.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TakeScreenshotAndStartFeedbackActivity.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TaskUtils.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterApiHttpClient.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterSignInManager.java
- make `LogWrapper` static
- ensure `TAG` is passed uniformly
=> clean up logging

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java, firebase-appdistribution/src/main/res/values/strings.xml
- removed unused strings
- extracted hard-coded strings
- added `translation_description`
=> prepare for translation

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackSender.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionLifecycleNotifier.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ScreenshotTaker.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionNotificationsManagerTest.java
- Update expected string in unit test
- Guard protected member reference with synchronized block
- Add TODO and suppress explicit executor lint errors
=> Fix errors after rebase on fad/next

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ScreenshotTaker.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/SignInStorage.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TaskUtils.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterSignInManager.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TestUtils.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterSignInManagerTest.java
Followup from https://github.com/firebase/firebase-android-sdk/pull/4350
Creating a SharedPreferences object can touch storage, so we should do so only on a background thread.
=> Move SharedPreferences usage to background thread

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ApkUpdater.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ApkUpdaterTest.java
It was caching a Task so that `downloadApk` could only create one task even if called multiple times in a row. But that can't happen because it's only called from `updateApk`, and that method is already caching a Task to avoid multiple simultaneous calls.
Also, it was self-managing a `TaskCompletionSource` when `TaskUtils.runAsyncInTask` can manage it instead.
=> Clean up ApkUpdater

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
Neither task, either to set the cached release to null or to set the signed it status to false, can ever fail. And the order does not matter. So just kick them off so they can occur as quickly as possible. It's especially important for these changes to occur ASAP since `signOutTester()` returns immediately, and ideally we want the state to reflect that call immediately so the developer sees consistent behavior from the API.
Also adds a new test.
=> Do not wait to store state when signing out

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/SignInStorage.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterSignInManager.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterSignInManagerTest.java
- Speed up typical reads and writes by only using the background executor in SignInStorage to initialize the SharedPreferences object, not protect all references
- Do not complete the Task returned by signInTester until the tester sign in status is updated
- Use an actual SignInStorage instance in TesterSignInManagerTest
=> Clean up sign in state management

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/SignInStorage.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
There was an edge case where, if the first thing you did when opening the app was to call `signOutTester`, calling `isTesterSignedIn` immediately afterwords would return `true`. This makes a few tweaks which should prevent this from happening in any reasonable scenario:
- Sets the sign in status in storage immediately when `signOutTester()` is called
- Stores SharedPreferences even when `getSignInStatusBlocking()` is called
Also adds some more tests to cover the failure mode, and some general test cleanup.
=> Make isTesterSignedIn more reliable

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ApkInstaller.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TaskCompletionSourceCache.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TaskUtils.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/UpdateTaskImpl.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ApkInstallerTests.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
Uses a `TaskCompletionSourceCache`, which allows caching tasks which can then be resolved later in a thread-safe manner.
=> Remove synchronized blocks from ApkInstaller

firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ApkUpdaterTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TestUtils.java
- The latch's name made it seem like it was a mock
- Inlining more of the setup makes it more readable
=> Improve readability of a test in ApkUpdaterTest

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TaskCompletionSourceCache.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/UpdateTaskCache.java
- The `Task<Void>` returned by the `setValue()`, `setException()`, etc. methods were not actually being resolved. They weren't being used yet but will be in a followup change.
- Adds `TaskCompletionSourceCache.isOngoing()` which will support a followup change
- Fleshes out the javadocs
=> Some improvements to the task caches

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TaskCompletionSourceCache.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterSignInManager.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/UpdateTaskCache.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterSignInManagerTest.java
Also moves to `@LightweightExecutor` now that there are no more blocking operations.
=> Remove synchronized blocks from TesterSignInManager

firebase-appdistribution/CHANGELOG.md, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/UpdateTaskImpl.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/UpdateTaskImplTest.java
This is a bug that we should probably fix, even though the typical customer use case is to add only one listener. [The API ](https://firebase.google.com/docs/reference/android/com/google/firebase/appdistribution/UpdateTask#addOnProgressListener(com.google.firebase.appdistribution.OnProgressListener)) definitely seems like it's meant to support multiple listeners.
=> Support multiple progress listeners on an UpdateTask

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionLifecycleNotifier.java
We were including some code inside `synchronized` blocks that did not need the lock.
=> Focus some synchronized blocks in lifecycle notifier

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/AabUpdater.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ApkInstaller.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ApkUpdater.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionLifecycleNotifier.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterSignInManager.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ApkUpdaterTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionLifecycleNotifierTest.java
This will make it easier to reason about what runs on what thread.
=> Always call foreground activity callbacks on the UI thread

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ScreenshotTaker.java
```
StrictMode policy violation: android.os.strictmode.UnbufferedIoViolation
at android.os.StrictMode$AndroidBlockGuardPolicy.onUnbufferedIO(StrictMode.java:1647)
at libcore.io.IoTracker.trackIo(IoTracker.java:35)
at libcore.io.IoTracker.trackIo(IoTracker.java:45)
at java.io.FileOutputStream.write(FileOutputStream.java:398)
at android.graphics.Bitmap.nativeCompress(Native Method)
at android.graphics.Bitmap.compress(Bitmap.java:1445)
at com.google.firebase.appdistribution.impl.ScreenshotTaker.writeToFile(ScreenshotTaker.java:147)
at com.google.firebase.appdistribution.impl.ScreenshotTaker.lambda$takeScreenshot$0$com-google-firebase-appdistribution-impl-ScreenshotTaker(ScreenshotTaker.java:69)
at com.google.firebase.appdistribution.impl.ScreenshotTaker$$ExternalSyntheticLambda1.then(Unknown …
```
=> Use BufferedOutputStream to prevent StrictMode violations

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ApkUpdater.java
```
StrictMode policy violation: android.os.strictmode.DiskReadViolation
at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1658)
at libcore.io.BlockGuardOs.stat(BlockGuardOs.java:419)
at libcore.io.ForwardingOs.stat(ForwardingOs.java:846)
at android.app.ActivityThread$AndroidOs.stat(ActivityThread.java:7798)
at java.io.UnixFileSystem.getLength(UnixFileSystem.java:298)
at java.io.File.length(File.java:968)
at com.google.firebase.appdistribution.impl.ApkUpdater.lambda$installApk$5$com-google-firebase-appdistribution-impl-ApkUpdater(ApkUpdater.java:101)
at com.google.firebase.appdistribution.impl.ApkUpdater$$ExternalSyntheticLambda1.onFailure(Unknown Source:6)
at com.google.android.gms.tasks.zzk.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
at …
```
=> Read file length on background thread to avoid StrictMode violation

firebase-perf/dev-app/dev-app.gradle, firebase-perf/firebase-perf.gradle, firebase-perf/src/main/java/com/google/firebase/perf/metrics/AppStartTrace.java, firebase-perf/src/main/java/com/google/firebase/perf/util/PreDrawListener.java, firebase-perf/src/main/java/com/google/firebase/perf/util/Timer.java, firebase-perf/src/test/java/com/google/firebase/perf/metrics/AppStartTraceTest.java, firebase-perf/src/test/java/com/google/firebase/perf/util/TimerTest.java
This PR is the 3rd iteration of experiments for Android App Start Alignment. 
The changes from the 2nd iteration are the following:
1. removed `uptimeMillis`
2. reprioritized trace/subtraces (default trace is now `preDraw + post`)
3. (fixed) real background detection
4. added `preDraw + postAtFrontOfQueue` subtrace
5. added `procStart-to-classLoad` subtrace
6. added `firstForeground` subtrace
7. added `firstBackground` subtrace
`procStart-to-classLoad` and `firstForegound` can be used to experiment thresholds for filtering out non-detectable backgrounding and interruptions.
`firstBackground` can be used to filter detected backgrounding for all 3 different methodologies (preDraw, preDrawFoQ, onDrawFoQ)
=> [Fireperf][AASA] Experiment time-to-initial-display 3

firebase-crashlytics/src/androidTest/assets/firebase_settings_collect_build_ids.json, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CommonUtilsTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreInitializationTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCaptureTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransformTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistenceTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/SettingsV3JsonTransformTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/TestSettings.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/AppData.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/BuildIdInfo.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCapture.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransform.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/DefaultSettingsJsonTransform.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/Settings.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsJsonConstants.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsV3JsonTransform.java, firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerRobolectricTest.java
Reads the resource file containing the list of build ids and their associated library name and architecture.  Writes the payload into the report.
=> Adds support to read the build ids

firebase-firestore/firebase-firestore.gradle
Without it, it's generated as a symbol, causing the build to break.
=> Wrap target backend property in double quotes

buildSrc/src/main/java/com/google/firebase/gradle/plugins/publish/PublishingPlugin.java
This enables the plugin to read the list of projects to be released from a configuration file, besides getting them from the CLI.
=> Extend publishing plugin to support release configFiles.

.github/workflows/build-release-artifacts.yml
The action was using a dummy configuration that only created release artifacts for Firestore.
=> Use file-based release configuration for the build release action.

firebase-config/api.txt, firebase-config/src/main/java/com/google/firebase/remoteconfig/ConfigUpdate.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
`updatedKeys` better describes this value and we use "key"/"keys" consistently throughout the SDKs.
=> Rename updatedParams to updatedKeys in ConfigUpdate.

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
=> Use an executor for Realtime HTTP onSuccess task.

firebase-abt/CHANGELOG.md, firebase-abt/src/main/java/com/google/firebase/abt/FirebaseABTesting.java, firebase-abt/src/test/java/com/google/firebase/abt/FirebaseABTestingTest.java
Considering experiments changed if either `experiment id` or `variant id` changes aligns with how the [A/B testing SDK for iOS behaves](https://github.com/firebase/firebase-ios-sdk/blob/eb30b6fdd809cbfe3a9eb7f3ccf1dd46326bef2d/FirebaseABTesting/Sources/ABTConditionalUserPropertyController.m#L261).
=> Report updated experiments if either experiment id or variant id changes.

firebase-abt/CHANGELOG.md, firebase-abt/src/main/java/com/google/firebase/abt/FirebaseABTesting.java, firebase-abt/src/test/java/com/google/firebase/abt/FirebaseABTestingTest.java, firebase-firestore/src/proto/google/firestore/v1/bloom_filter.proto, firebase-firestore/src/proto/google/firestore/v1/firestore.proto, firebase-firestore/src/proto/google/firestore/v1/write.proto
Add bloom filter to protos.
Ported from web SDK: https://github.com/firebase/firebase-js-sdk/pull/6780/files
=> Update protos to include bloom filter

docs/make_release_notes.py
Beyond that change, we are also making some extra format changes to better suit our usecase.
=> Update make_release_notes to generate based on the release config

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
Fixes b/257069716. Populate using `BuildConfig` as we do in the [Fetch request](https://github.com/firebase/firebase-android-sdk/blob/994c4b60e60f00b21a2357f7c488d512b1d506ae/firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java#L344).
=> Replace Android version with SDK version in the Realtime stream request.

firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHandler.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
Fixes bug for bug/261868622.
The source of the problem was that we when the app was going from the foreground to background, we would interrupt the thread running the Http Stream to signal to the client that we didn't want anymore connection retries.
The fix is to add update the background state change flow and not use the thread interruption anymore
=> Realtime RC 1P Bug Fix: Remove thread interruption logic

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigContainer.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigContainerTest.java
For parity with iOS, which needs to persist active ABT metadata before it can perform the diff. See b/263139421.
=> Don't diff experiment metadata to determine updated keys.

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/UpdateTaskImpl.java
These annotations are unnecessary since https://github.com/firebase/firebase-android-sdk/pull/4394
=> Remove now-unnecessary lint suppression

firebase-appdistribution/firebase-appdistribution.gradle, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/AabUpdater.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ApkInstaller.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ApkUpdater.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionLifecycleNotifier.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ScreenshotTaker.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/SignInStorage.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterSignInManager.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionLifecycleNotifierTest.java
- Use the project-wide dagger version
- Mark classes as `@Singleton` if there should only be one instance present in the app
- Ensure the singleton `FirebaseAppDistributionLifecycleNotifier` is only registered with the application once
=> Some cleanup in App Distro's Dagger usage

firebase-appdistribution/test-app/README.md
We support build flavors in `test-app.gradle` so there is no longer just a `appDistributionUploadDebug` task. Instead, there are `appDistributionUploadBetaDebug` and `appDistributionUploadProdDebug` debug tasks.
=> Update test app readme

firebase-appdistribution/src/main/res/drawable/btn_disabled_stroked.xml, firebase-appdistribution/src/main/res/drawable/btn_stroked.xml, firebase-appdistribution/src/main/res/drawable/btn_stroked_background.xml, firebase-appdistribution/src/main/res/drawable/card_background.xml, firebase-appdistribution/src/main/res/layout/activity_feedback.xml, firebase-appdistribution/src/main/res/values/themes.xml
=> Style gallery button for uploading custom screenshots

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
**Problem:**  Bug that occurs when app goes from foreground -> background -> foreground causing the app to freezes due to a deadlock. This happens b/c beginRealtimeHttpStream is synchronized and blocking, when the app goes from background -> foreground it tries to restart the stream and calls makeRealtimeHttpConnection. Since beginRealtimeHttpStream is blocking, the call to makeRealtimeHttpConnection is blocked until the connection is finished after 5 min 
due to the synchronization from the first method.
**Solution:** Make beginRealtimeHttpStream not synchronized by moving the "GuardedBy" variable to other, synchronized methods.
=> Realtime RC Bug Patch: Fixes deadlock issue that caused app to freeze when transitioning from background to foreground

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigContainer.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigContainerTest.java
`ConfigContainer.copyOf` does not make a true "copy". The `other` `ConfigContainer` should not be modified between fetching and activating, since this produces an inaccurate activated config.
=> Make a deep copy of the other config before modifying it to compute changes.

firebase-crashlytics/CHANGELOG.md, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/send/ReportQueue.java
This exception gets thrown sometimes when Crashlytics attempts to do a forced send at a bad time (#4496). Since the forced send is best effort anyway, it is safe to just fail in this case and let the regular scheduled send happen on the next launch.
=> Catch SQLException when doing best effort forced send in Crashlytics.

firebase-crashlytics/CHANGELOG.md
Previous commit to add build ids for Native ANRs on pre-Android 12 versions: https://github.com/firebase/firebase-android-sdk/pull/4444
=> Add change log entry missing from previous commit

buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/tagging/ShellExecutor.java, buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java, buildSrc/src/main/java/com/google/firebase/gradle/plugins/GitSubmodulePlugin.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/GradleUtils.kt
Per [b/267779128](https://b.corp.google.com/issues/267779128),
This adds a new Plugin called `GitSubmodulePlugin`. It's a light weight plugin that facilitates interaction with Git Submodules from Gradle. 
Our current release action is broken ([b/267188389](https://b.corp.google.com/issues/267188389)), because we have SDKs with submodules- but never actually pull the submodules as apart of our build process. We _could_ get away with just a quick little hacky task to fix this, but I opted for a Plugin instead. Primarily to take advantage of the following benefits:
- Better build times through native Gradle plugin improvements
- More modular implementation, should any other SDKs start using Git Submodules
- Further establishment of plugin design principles in Gradle/Kotlin
- Easier to …
=> Implement the GitSubmodulePlugin

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackSender.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackTrigger.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClient.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TakeScreenshotAndStartFeedbackActivity.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterApiHttpClient.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FeedbackSenderTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClientTest.java
Pipe through feedback trigger to API client calls and pass it as a header in call to create feedback
=> Pass feedback trigger type to create feedback call

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackSender.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClient.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FeedbackSenderTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClientTest.java
Note to self: confirm which endpoint is actually recording the metric before changing the client 🤦🏿‍♂️
=> Pass trigger header on commit feedback call

build.gradle
Bumps google-services from 4.3.3 to 4.3.15.
updated-dependencies:
- dependency-name: com.google.gms:google-services
dependency-type: direct:production
update-type: version-update:semver-patch
Signed-off-by: dependabot[bot] <support@github.com>
=> Bump google-services from 4.3.3 to 4.3.15

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java
Not storing the state causes a crash when trying to restore it in `onCreate()`.
=> Store feedback trigger state on screen rotation

appcheck/firebase-appcheck-debug-testing/CHANGELOG.md, appcheck/firebase-appcheck-debug/CHANGELOG.md, appcheck/firebase-appcheck-playintegrity/CHANGELOG.md, appcheck/firebase-appcheck-safetynet/CHANGELOG.md, appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/SafetyNetAppCheckProviderFactory.java, appcheck/firebase-appcheck/CHANGELOG.md
Per discussion, add deprecation tags to the App Check SafetyNet SDK.
=> Add deprecation tagging to `SafetyNetAppCheckProviderFactory`.

firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplay.java
Crash fix: [Attempt to invoke virtual method 'com.google.firebase.inappmessaging.model.MessageType kb.i.c()'](https://github.com/firebase/firebase-android-sdk/issues/4214#top)
https://github.com/firebase/firebase-android-sdk/issues/4214
- Added a null check to avoid the crash.
=> Fiam crash fix

firebase-sessions/api.txt, firebase-sessions/firebase-sessions.gradle.kts, firebase-sessions/gradle.properties, firebase-sessions/src/androidTest/kotlin/com/google/firebase/sessions/FirebaseSessionsTests.kt, firebase-sessions/src/main/AndroidManifest.xml, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/FirebaseSessionsTest.kt, subprojects.cfg
Initial commit for Firebase Sessions SDK
- Setup subproject, including test structure with a place holder api
- Source code and gradle build files are all in Kotlin
- Set min sdk level to 16, which is what Crashlytics and Fireperf are
=> Initial commit for Firebase Sessions SDK

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
ported from https://github.com/firebase/firebase-js-sdk/pull/7045
=> Add integration test for bloom filter

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
- Remove exceptions that users can't do anything about and that don't break Realtime
- Remote duplicate test and update test to not rely on exception
=> Remove irrelevant exceptions and update tests

firebase-sessions/firebase-sessions.gradle.kts, firebase-sessions/src/androidTest/kotlin/com/google/firebase/sessions/FirebaseSessionsTests.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionInitiator.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/WallClock.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionInitiatorTest.kt
Use `kotlin.time.Duration` instead of `Long` for time intervals.
`kotlin.time.Duration` is safe to use with min api level 16. It is `java.time.Duration` that requres api level 26. We still can't use `java.time.Instant` because of our min api level, but I avoided it by making everything `Duration`s.
Also switched to using `SystemClock.elapsedRealtime()` which is *"the time since the system was booted, and include deep sleep. This clock is guaranteed to be monotonic, and continues to tick even when the CPU is in power saving modes, so is the recommend basis for general purpose interval timing."*
Fixed the copyright format on Kotlin files so it shows collapsed by default in AS.
=> Use kotlin.time.Duration instead of Long for time intervals

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionGenerator.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionGeneratorTest.kt
Adds a SessionGenerator that rotates the Session ID and index.
#no-changelog
=> Add SessionGenerator to generate the Session ID

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigContainer.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigContainerTest.java
Fixes a bug reading from the cache after upgrading to this version.
* Before upgrading, the cached config does not contain `template_version_number_key`.
* After upgrading, calling `containerJson.getLong(TEMPLATE_VERSION_NUMBER_KEY)` throws a `JSONException`, which is [caught](https://github.com/firebase/firebase-android-sdk/blob/dfe71a9b2b1067dbee7b8b6f204e07b68d45c549/firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigStorageClient.java#L106) (since it's expected the cache may not have been written yet) and [a default value is returned](https://github.com/firebase/firebase-android-sdk/blob/dfe71a9b2b1067dbee7b8b6f204e07b68d45c549/firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigGetParameterHandler.java#L233-L247).
To repro:
1. Run …
=> Default template_version_number_key to 0 when it is not cached.

firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java, firebase-firestore/src/test/resources/json/bundle_spec_test.json, firebase-firestore/src/test/resources/json/existence_filter_spec_test.json, firebase-firestore/src/test/resources/json/limbo_spec_test.json, firebase-firestore/src/test/resources/json/limit_spec_test.json, firebase-firestore/src/test/resources/json/recovery_spec_test.json
#no-changelog
Port from https://github.com/firebase/firebase-js-sdk/pull/7113
=> Validate query purpose in spec tests

encoders/firebase-encoders-json/firebase-encoders-json.gradle, encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContext.java, encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/json/NumberedEnum.kt, encoders/firebase-encoders-json/src/test/java/com/google/firebase/encoders/json/DummyEnum.kt, encoders/firebase-encoders-json/src/test/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContextTest.java
Add NumberedEnum interface.
This is useful for when we want enums to have explicit numbers, and serialize as the number, instead of the enum name.
This is in Kotlin so we can take advantage of the nice syntax to override it in the primary ctor of an enum class.
=> Add NumberedEnum interface

encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/json/NumberedEnum.kt
Make `NumberedEnum` public, not internal. This is needed to use it in other Firebase libraries.
=> Make NumberedEnum public, not internal

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java
As noted in the comment, if there's an invalidation message and no listeners, ignore the message and close the realtime stream connection. The next time the realtime connection is opened, the client will receive the same invalidation message and call any registered listeners.
In effect, this stops listening when the last listener is removed. This works around `URLConnection.disconnect()` being called in `ConfigAutoFetch` rather than `ConfigRealtimeHttpClient`. Since the connection is cleaned up in `ConfigAutoFetch`, terminating it early in `ConfigRealtimeHttpClient` involves significant refactoring to avoid calling multiple connection lifecycle methods twice.
=> Ignore invalidations and stop listening when there are no listeners.

firebase-appdistribution/firebase-appdistribution.gradle, firebase-appdistribution/test-app/test-app.gradle
I think these were missed in https://github.com/firebase/firebase-android-sdk/pull/4697
=> Make more app distro deps static

firebase-sessions/firebase-sessions.gradle.kts, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvent.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventTest.kt
Add JSON encoder for `SessionEvent`s.
Also moved the logic to construct a Session Start event out of the data class, this is to make the data class cleaner and easier to read.
=> Add JSON encoder for SessionEvents

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/send/ReportQueue.java
This will avoid blocking the main thread for regular crashes, and help avoid ANRs.
No change log: This is part of "* [changed] Improved crash reporting reliability for crashes that occur early in the app's
lifecycle."
=> Only attempt to flush reports for start up crashes

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryPurpose.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteEvent.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/WatchChangeAggregator.java, firebase-firestore/src/test/resources/json/bundle_spec_test.json, firebase-firestore/src/test/resources/json/existence_filter_spec_test.json, firebase-firestore/src/test/resources/json/limbo_spec_test.json, firebase-firestore/src/test/resources/json/limit_spec_test.json, firebase-firestore/src/test/resources/json/offline_spec_test.json, firebase-firestore/src/test/resources/json/recovery_spec_test.json
Port from Web: https://github.com/firebase/firebase-js-sdk/pull/7107
=> Add new goog-listen-tag for bloom filter

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionGenerator.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionGeneratorTest.kt
This is more Kotlin idiomatic. Also made some properties val instead of var, I think this is cleaner.
=> Use the private setter pattern on SessionGenerator.currentSession

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
This is a port of https://github.com/firebase/firebase-js-sdk/pull/7134
=> Firestore: QueryTest.java: add a test that resumes a query with existence filter

firebase-sessions/firebase-sessions.gradle.kts, firebase-sessions/src/androidTest/kotlin/com/google/firebase/sessions/FirebaseSessionsTests.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionCoordinator.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvent.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionCoordinatorTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeFirebaseInstallations.kt
Populate `firebaseInstallationId` field in session data.
Add `SessionCoordinator` class and plumb in a `CoroutineDispatcher`.
Setup coroutines including testing.
=> Populate firebaseInstallationId field in session

firebase-config/src/main/java/com/google/firebase/remoteconfig/ConfigUpdate.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/ConfigUpdateListener.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigClientException.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigServerException.java
=> Improve real-time reference docs.

firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
Fixes instrumentation tests for crashlytics-ndk
=> Use >API30 for crashlytics ndk device testing

firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalSerializerTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteEventTest.java, firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java, firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestTargetMetadataProvider.java
=> Improve bloom filter application test coverage

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/ApplicationInfo.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvent.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/ApplicationInfoTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionCoordinatorTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeFirebaseApp.kt
=> Package session start event's application information.

buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt
Include Kotlin directories in the Dackka plugin.
The `generateDackkaDocumentation` task was not outputting anything on `firebase-sessions` because it was ignoring the `main/kotlin/` src dir, it only looked at `main/java/` before. This was causing some workflows to fail on every PR since sessions is entirely written in Kotlin.
=> Include Kotlin directories in the Dackka plugin

firebase-sessions/firebase-sessions.gradle.kts, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/EventGDTLogger.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsEarly.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionCoordinator.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/EventGDTLoggerTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionCoordinatorTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeEventGDTLogger.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeProvider.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeTransportFactory.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/TestSessionEventData.kt
- Adds a dependency on data-transport
- Adds TestSessionEventData.kt to store Session Event objects used for testing
#no-changelog
=> Integrate firebase-sessions with GoogleDataTransport

.github/workflows/ci_tests.yml, firebase-sessions/test-app/test-app.gradle.kts
Add the integration test's google-services.json file to unit tests so unit tests can use the google services plugin too.
=> Add the integration test's google-services.json file to unit tests

firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/FirestoreTests.kt
Add a unit test for Firestore's `@PropertyName` annotation on Kotlin data class properties. This test both (a) verifies that the annotation actually works and (b) showcases how to use the property in Kotlin, which can easily trip up users (e.g. https://github.com/firebase/firebase-android-sdk/issues/4822).
=> Firestore: add a Kotlin unit test for PropertyName

.github/workflows/fireperf-e2e.yml
Removing Jeremy and Leo from the Fireperf e2e test assignee list.
=> Removing former team members from the Fireperf e2e assignee list

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionInitiator.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/LocalOverrideSettings.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/SessionsSettings.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/SettingsProvider.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/LocalOverrideSettingsTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionInitiatorTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionsSettingsTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeFirebaseApp.kt
Implement local overrides for configs from the application's manifest file.
=> Implement local manifest override configs

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/EventGDTLogger.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionCoordinator.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvent.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/EventGDTLoggerTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionCoordinatorTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/TestSessionEventData.kt
- Also updates logging to log the Encoded Session Event instead of the data object (only in debug mode) so that we can catch encoding issues
TODO (in a follow up)
- Make sure we're setting the time correctly
- Fill in Device Name
=> Fix encoding for Session Events

firebase-perf/CHANGELOG.md, firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigResolver.java, firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigurationConstants.java, firebase-perf/src/main/java/com/google/firebase/perf/config/DeviceCacheManager.java, firebase-perf/src/main/java/com/google/firebase/perf/config/RemoteConfigManager.java, firebase-perf/src/main/java/com/google/firebase/perf/transport/RateLimiter.java, firebase-perf/src/main/java/com/google/firebase/perf/util/Constants.java, firebase-perf/src/main/java/com/google/firebase/perf/util/ImmutableBundle.java, firebase-perf/src/test/java/com/google/firebase/perf/config/ConfigResolverTest.java, firebase-perf/src/test/java/com/google/firebase/perf/config/ConfigurationConstantsTest.java, firebase-perf/src/test/java/com/google/firebase/perf/config/DeviceCacheManagerTest.java, firebase-perf/src/test/java/com/google/firebase/perf/config/RemoteConfigManagerTest.java, firebase-perf/src/test/java/com/google/firebase/perf/session/PerfSessionTest.java, firebase-perf/src/test/java/com/google/firebase/perf/transport/RateLimiterTest.java, firebase-perf/src/test/java/com/google/firebase/perf/util/ImmutableBundleTest.java
RC Flags are stored as Double and our SDK loses precision when converting back to Float. This causes sampling rates to not behave as expected.
=> Changing Fireperf's SDK Floats to Doubles

appcheck/firebase-appcheck/CHANGELOG.md, appcheck/firebase-appcheck/api.txt, appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/FirebaseAppCheck.java, appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheck.java, appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheckTest.java, appcheck/firebase-appcheck/test-app/src/main/java/com/googletest/firebase/appcheck/MainActivity.java, appcheck/firebase-appcheck/test-app/src/main/res/layout/activity_main.xml, appcheck/firebase-appcheck/test-app/src/main/res/values/strings.xml
Add an API for obtaining limited-use App Check tokens as per go/fac-1-use-client-sdk.
=> Implement limited-use App Check tokens.

.github/workflows/sessions-e2e.yml
This workflow will still checkout firebase-sessions and run the test on that branch. But for it to run every 4 hours, we need to merge it into master.
=> Merge sessions-e2e.yml from firebase-sessions so it can run on schedule

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/WallClock.kt
Follow up from https://github.com/firebase/firebase-android-sdk/pull/4870#discussion_r1162805177
=> Move currentTimeUs into WallClock

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/ApplicationInfoTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/EventGDTLoggerTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/LocalOverrideSettingsTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionCoordinatorTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionInitiatorTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionsSettingsTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeFirebaseApp.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/TestSessionEventData.kt
Populate sampling rate in session event.
I also refactored the fake firebase app a bit to make it easier to access it multiple times inside one test.
And I am playing with a way to use the test data but override 1 value nested a bit deep into the data class.
=> Populate sampling rate in session event

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/ApplicationInfoTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/TestSessionEventData.kt
I assume this needs to be consistent with the Crashlytics Device Model: https://github.com/firebase/firebase-android-sdk/blob/master/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCapture.java#L220
=> Fill in device_model field for AQS

firebase-sessions/firebase-sessions.gradle.kts, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/LocalOverrideSettings.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/RemoteSettings.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/SessionsSettings.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/SettingsCache.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SettingsCacheTest.kt
Pending: Implement remote config fetching capability and updating the caches with the fetched value.
=> Introduce remote config cache for storing configs fetched remotely.

buildSrc/src/main/java/com/google/firebase/gradle/plugins/BaseFirebaseLibraryPlugin.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/PomValidator.kt
Per [b/279212956](https://b.corp.google.com/issues/279212956),
This takes advantage of the new extension methods provided in the recently merged #4879, and refactors the `PomValidator` task to take advantage of them.
Additionally, this fixes [b/279212781](https://b.corp.google.com/issues/279212781) - providing documentation for the `PomValidator` task.
=> Refactor PomValidator

firebase-firestore/src/main/java/com/google/firebase/firestore/AggregateQuerySnapshot.java, firebase-firestore/src/test/java/com/google/firebase/firestore/AggregateQuerySnapshotTest.java
See https://github.com/firebase/firebase-cpp-sdk/pull/1283
=> Firestore: Internal method AggregateQuerySnapshot.createWithCount() added for CPP SDK

firebase-config/src/main/java/com/google/firebase/remoteconfig/ConfigUpdateListener.java
Docs generation drops the `@link` its own class.
=> Change ConfigUpdateListener docs link to code reference.

buildSrc/src/main/java/com/google/firebase/gradle/plugins/BaseFirebaseLibraryPlugin.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/KotlinUtils.kt
Per [b/280087461](https://b.corp.google.com/issues/280087461),
This fixes an issue where some dependencies were being marked as `jar` when they should've been marked as `aar`. This occurred due to the fact that we were comparing based on artifact names (which include the version) instead of the maven name (just the groupId and artifactId).
=> Fix pom dependencies

firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigClientException.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigException.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigInfo.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigServerException.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigSettings.java
* Use "Remote Config" instead of "FRC"
* Remove many `@author` tags (all can be removed, starting with documented classes). This doesn't show up in the docs, but we typically don't use it in the Firebase repo.
* Use platform-specific link for https://firebase.google.com/docs/remote-config/get-started?platform=android#add-real-time-listener
* Document `getCode()` in `FirebaseRemoteConfigException`
* Add various `@code` and `@link` references
* Remote Config Servers -> Remote Config Server (singular)
Internal b/274648602
=> Fix various issues and inconsistencies in the Remote Config ref docs.

firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
=> Lowercase "server(s)" in Remote Config docs.

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/ApplicationInfo.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/ApplicationInfoTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeFirebaseApp.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/TestSessionEventData.kt
Got the field from Crashlytics here: https://github.com/firebase/firebase-android-sdk/blob/master/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCapture.java#L201
no-changelog
=> Add os_version, app_build_version, device_manufacturer for Sessions #11222

contributor-docs/components/executors.md
Per [b/281574448](https://b.corp.google.com/issues/281574448),
This fixes a few small typos and formatting issues that were overlooked in the previous PR that updated the executor docs :')
=> Clean up Executor docs

firebase-common/src/main/java/com/google/firebase/FirebaseApp.java, firebase-common/src/main/java/com/google/firebase/heartbeatinfo/HeartBeatInfoStorage.java, firebase-common/src/test/java/com/google/firebase/heartbeatinfo/HeartBeatInfoStorageTest.java
Only take all heartbeats until today.. Donot send heartbeats of today and don't delete them as well
=> update heartbeat to provide support for c++ sdks

appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/FirebaseAppCheck.java, firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.java
Javadoc fixes in App Check and Functions.
=> Javadoc fixes

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionGenerator.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionGeneratorTest.kt
Immediately call the callback if Sessions generated a session before the subscriber subscribed. iOS does this too. This will fix the `FirebaseSessionsTest` when having multiple subscribers in the test app.
=> Fix behaviour with multiple subscribers

firebase-crashlytics/ktx/ktx.gradle, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreInitializationTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistenceTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsAppQualitySessionsSubscriber.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransform.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
Add and populate appQualitySessionId in Crashlytics reports. This works by saving the latest AQS session id to disk on every event, which is slightly different than iOS which saves it on every session change. The JVM can save to disk in the exception handler, so it's ok to do it this way for Android. Then when a report is finalized, take the most recent AQS session id for that Crashlytics session and include it in the report.
=> Add and populate appQualitySessionId in Crashlytics reports

firebase-storage/CHANGELOG.md
Use the lib name instead of the a var.
=> Update CHANGELOG.md for storage

firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigurationConstants.java, firebase-perf/src/main/java/com/google/firebase/perf/config/RemoteConfigManager.java, firebase-perf/src/test/java/com/google/firebase/perf/config/ConfigResolverTest.java, firebase-perf/src/test/java/com/google/firebase/perf/config/ConfigurationConstantsTest.java
Make default sampling rates for when RC fetch failed 1/1000 typical default.
=> Make default sampling rates for when RC fetch failed 1/1000 typical

firebase-crashlytics/ktx/ktx.gradle, firebase-crashlytics/ktx/src/androidTest/AndroidManifest.xml, firebase-crashlytics/ktx/src/androidTest/kotlin/com/google/firebase/crashlytics/ktx/CrashlyticsTests.kt, firebase-crashlytics/ktx/src/main/kotlin/com/google/firebase/crashlytics/ktx/FirebaseCrashlytics.kt, health-metrics/apk-size/app/default.gradle
This is needed because we upped the target sdk and firebase-crashlytics-ktx had been using some deprecated apis.
=> Fix firebase-crashlytics-ktx instrumented tests

firebase-firestore/src/test/resources/json/existence_filter_spec_test.json, firebase-firestore/src/test/resources/json/limbo_spec_test.json, firebase-firestore/src/test/resources/json/listen_spec_test.json
Sync spec tests with changes from https://github.com/firebase/firebase-js-sdk/pull/7372: "Remove the no-ios tag from bloom filter spec tests".
The changes in this PR have no effect on this SDK, but serves to keep the spec tests in sync for easier updating in the future.
#no-changelog
=> Firestore Spec Tests: Port JS PR 7372 (remove no-ios tag from bloom filter tests)

firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/SignInStorage.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterSignInManager.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterSignInManagerTest.java
In dev mode, instead of just always having the tester be signed in, actually allow the developer to use `signInTester()`, `signOutTester()`, `isTesterSignedIn()`, etc., but just skip the actual sign in flow. This will be a more realistic way to text the SDK out using dev mode. Expands on https://github.com/firebase/firebase-android-sdk/pull/5078.
Stores the sign in state separately from non-dev mode, so that they don't sign in during dev mode and then try to use the SDK for real after setting dev mode to false.
=> Store dev mode sign in state separately

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/RemoteSettings.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/RemoteSettingsFetcher.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/RemoteSettingsTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionsSettingsTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SettingsCacheTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/api/FirebaseSessionsDependenciesTest.kt
This will fix an issue with slow start up on slow network. There are still some caveats, for example cold launch will behave similar to Perf. I will address these in another PR.
=> Make remote settings fetch non-blocking

.github/workflows/create_releases.yml, buildSrc/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/ReleaseGenerator.kt
add json release config
add PR link parsing
remove intentionally skipped commits from all searched
=> Release generator improvements

firebase-appdistribution/CHANGELOG.md, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/DevModeDetector.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/NewReleaseFetcher.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ReleaseIdentifier.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/SignInStorage.java, firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterSignInManager.java, firebase-appdistribution/src/main/res/values/strings.xml, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/NewReleaseFetcherTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ReleaseIdentifierTest.java, firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterSignInManagerTest.java
The docs say that dev mode allows you to test in-app feedback without actually distributing your app. However that's not true because you still have to sign into the SDK.
This expands dev mode to allow testing the SDK in a signed in state without actually signing in:
- `signInTester()` skips opening the browser and immediately marks the tester as signed in
- Sign in state is managed using a separate key in app storage
Also, this expands dev mode to cover the in-app update functionality as well. It simply disables the check for new release and prints a log message instead.
=> Do not require sign in to use developer mode

firebase-messaging/CHANGELOG.md, firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessaging.java
* Marked send as deprecated since upstream messaging is deprecated.
=> Deprecate send.

firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerfEarly.java
Have Perf report data collection disabled to Sessions until the metadata issue is resolved. This is to prevent Sessions from thinking Perf data collection is enabled when it was disabled in metadata.
=> Have Perf report data collection disabled to Sessions

firebase-appdistribution-api/CHANGELOG.md
Copies the CHANGELOG from https://github.com/firebase/firebase-android-sdk/pull/5078 since we want to keep `firebase-appdistribution` and `firebase-appdistribution-api` to stay on the same version and include the same release notes for new changes.
=> Update App Distro API CHANGELOG.md

firebase-firestore/src/main/java/com/google/firebase/firestore/core/View.java
Remove a useless invocation of compareTo() whose result was being ignored. It appears that this useless compareTo() call was accidentally left behind from some previous refactor. Comparing it to the JS and iOS implementations, https://github.com/firebase/firebase-js-sdk/blob/aea4a4471306b089a02b207d2df285dfc71666c7/packages/firestore/src/core/view.ts#L295-L300 and https://github.com/firebase/firebase-ios-sdk/blob/876b9624e490cfc9451250d1a02eb959f6746927/Firestore/core/src/core/view.cc#L266-L275, respectively, it appears that the desired logic omits this useless compareTo() call.
This "bug" was detected by static analysis of https://errorprone.info/bugpattern/CheckReturnValue in google3 (Googlers see cl/544688630 and cl/544704978).
=> Firestore: remove unused compareTo() computation

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
Add test `bloomFilterShouldCorrectlyEncodeComplexUnicodeCharacters()` to `QueryTest.java`. This test verifies that the bloom filter correctly encodes document paths that contain special Unicode characters, like combining characters and characters above 0xFFFF (i.e. characters outside of the BMP, basic multilingual plane).
Googlers see b/289234093 for details.
This is a port of https://github.com/firebase/firebase-js-sdk/pull/7412
=> Firestore: add test bloomFilterShouldCorrectlyEncodeComplexUnicodeCharacters() to QueryTest.java

firebase-messaging/CHANGELOG.md, firebase-messaging/src/main/java/com/google/firebase/messaging/EnhancedIntentService.java, firebase-messaging/src/main/java/com/google/firebase/messaging/FcmBroadcastProcessor.java, firebase-messaging/src/main/java/com/google/firebase/messaging/WithinAppServiceConnection.java, firebase-messaging/src/test/java/com/google/firebase/messaging/FcmBroadcastProcessorRoboTest.java, firebase-messaging/src/test/java/com/google/firebase/messaging/WithinAppServiceConnectionRoboTest.java
* Changed to finish a background broadcast after the message has been handled, subject to a timeout. This keeps the `FirebaseMessagingService`'s process in an active state while it is handling an FCM message, up to the 20 seconds allowed.
* Removed acquiring a WakeLock for background broadcasts as one is held for the app until the broadcast is finished.
=> Finish background FCM broadcasts after handling the message.

firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessaging.java
* Removed deprecated class documentation about upstream messaging.
* Updated send deprecation wording to "FCM upstream messaging" to align with the standard naming.
* Fixed spelling error.
=> Clean up documentation.

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/remote/TestingHooksUtil.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/BloomFilter.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/TestingHooks.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/WatchChangeAggregator.java
Modify the test `bloomFilterShouldCorrectlyEncodeComplexUnicodeCharacters()` in `QueryTest.java`, that was added by the recent PR https://github.com/firebase/firebase-android-sdk/pull/5135, to directly check the bloom filter for containing the document paths with complex Unicode characters. Previously, it was indirectly checking this via the other properties of the existence filter. As a result, the "retry" logic was removed, since it doesn't matter if there is a false positive.
To add the ability to directly interrogate the bloom filter, the testing hooks needed to be augmented to expose the  `BloomFilter`, projectId, and databaseId.
This is a port of https://github.com/firebase/firebase-js-sdk/pull/7413
=> Firestore: Update test bloomFilterShouldCorrectlyEncodeComplexUnicodeCharacters() in QueryTest.java

firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
This is to address comment in cl/545750836.
=> Clarify multi db documentation

buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/GradleUtils.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/VersionBumpTask.kt
Per [b/274794264](https://b.corp.google.com/issues/274794264),
This connects the `PostReleasePlugin` plugin with releasing libraries, such that tasks like `VersionBumpTask` can be executed from the root directory- while only applying to releasing libraries.
=> Connect PostReleasePlugin with PublishingPlugin

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
This is a port of https://github.com/firebase/firebase-js-sdk/pull/7415
=> Firestore: QueryTest.java: Use a WriteBatch to delete documents rather than a transaction

firebase-firestore/api.txt, firebase-firestore/src/main/java/com/google/firebase/firestore/MemoryEagerGcSettings.java, firebase-firestore/src/main/java/com/google/firebase/firestore/MemoryLruGcSettings.java
Return type of MemoryLruGcSettings$Builder.setSizeBytes() should be the Builder itself, not void.
=> Fix return type of Builder.set

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
The Firestore emulator does not (as of July 14, 2023) send an existence filter when a query is resumed by clients. As a result the client fails to delete documents that were deleted since the query was last run. The emulator will soon be fixed to send the existence filter (Googlers see b/270731363).
There are two bloom filter integration tests, the first of which tried to do as much as it could when running against the emulator and completing successfully if it got that far. That test, though, didn't really validate anything and by it passing it incorrectly implied that the bloom filter logic was validated. This test is now completely skipped when running against the Firestore emulator, which also makes the test simpler and easier to maintain.
These two bloom filter integration tests also …
=> Firestore: Disable bloom filter integration tests when using Firestore emulator

firebase-firestore/src/main/java/com/google/firebase/firestore/remote/TestingHooks.java, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/WatchChangeAggregator.java
Port some small code changes from https://github.com/firebase/firebase-js-sdk/pull/7474 to be consistent with the web sdk.
=> Firestore: Bloom filter minor code cleanup for consistency with web sdk

smoke-tests/build.gradle
It doesn't import the main build file, thus cannot find the variable.
=> Use actual version for androidx.core.test inside smoke-tests

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
Use a different Firestore instance instead of a `WriteBatch` to avoid affecting the local cache in `QueryTest.java`.
I had originally thought that `WriteBatch` sidestepped the local cache, just like a transaction did; however, that turned out to be incorrect and using a `WriteBatch` nullified the test cases that were modified to use it. This is a follow-up to https://github.com/firebase/firebase-android-sdk/pull/5167.
This PR was ported from https://github.com/firebase/firebase-js-sdk/pull/7486.
=> Firestore: QueryTest.java: use a different Firestore instance instead of a WriteBatch

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/RemoteSettingsFetcher.kt
The crashing in #5024, reveals that the stacktrace points to `RemoteSettingsFetcher$doConfigFetch`. The issue is due to the `openConnection()`.  I'm guessing that this is somewhat being triggered when the user has VPN or unstable internet connection. Including this inside the try catch should resolve the issue.
```
Fatal Exception: java.lang.SecurityException: Unknown calling package name 'xxx'.
at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
at android.os.Parcel.createException(Parcel.java:2995)
at android.os.Parcel.readException(Parcel.java:2978)
at android.os.Parcel.readException(Parcel.java:2920)
at com.google.android.gms.common.internal.zzac.getService(zzac.java:31)
at com.google.android.gms.common.internal.BaseGmsClient.getRemoteService(BaseGmsClient.java:109)
at …
```
=> Mitigation for issue 5024

.github/workflows/ci_tests.yml, .github/workflows/update-cpp-sdk-on-release.yml
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> ci: Migrate set-output to GITHUB_OUTPUT

firebase-inappmessaging-display/firebase-inappmessaging-display.gradle, firebase-inappmessaging-display/lint-baseline.xml, firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle, firebase-ml-modeldownloader/lint-baseline.xml
If we bump the SDK to 33 for all sub-projects, there are some new lint rules will be reported by lint. This PR adds necessary lint-base files to track current potential lint warnings and we can bump SDK to 33 direct without lint errors after this PR lands.
=> Add lint-base files for some sub-projects

firebase-sessions/CHANGELOG.md, firebase-sessions/gradle.properties, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/LocalOverrideSettings.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/ApplicationInfoTest.kt
Fix NPE when no version name is set. This will make it easier for apps to have Android tests while including the Sessions SDK. Also removed references to ApplicationInfoFlags to make it easier to minify apps with older api levels.
When the version name is unset, use the version code.
=> Fix NPE when no version name is set

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/metadata/MetaDataStoreTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/metadata/RolloutAssignmentListTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/MetaDataStore.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/RolloutAssignment.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/RolloutAssignmentList.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/UserMetadata.java
Create a `RolloutAssignment` model for storing the instance at UserMetadata in memory.
Implemented serialization and  de-serialization from json to data model and vice-versa (this is used for file read and write).
`RolloutAssignment` will not become a part of the proto in CrashlyticsReport because we might later port it to Interop SDK so both RC and Crash can leverage on.
#no-changelog
=> Store rollouts state in cache

buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/GmavenHelper.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/semver/GmavenCopier.kt
During the m134 release we were releasing firebase-sessions for the first time and due to which the semver test was broken. Hence the if conditions were added. These if conditions were not being evaluated correctly since it dependend on a malleable state of things. So now it's moved to checking in Gmaven itself if the project exists instead of depending on a malleable state which keeps being updated by the gradle tasks.
=> Fix semver check

README.md, buildSrc/README.md, buildSrc/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt, firebase-firestore/README.md, firebase-perf/README.md
Per [b/294577585](https://b.corp.google.com/issues/294577585),
This updates any references to our previous release commands to now represent the new process; including the removal of the barebones `publishAll`.
Additionally, this fixes the following:
- [b/294577524](https://b.corp.google.com/issues/294577524) -> Add a default name for releases when using commands
- [b/294578506](https://b.corp.google.com/issues/294578506) -> Add a link to our contributor documentation in our buildSrc README
=> Update release commands in README files

buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.kt
This PR enables GradleMetadataPublishing, which is necessary to properly resolve Kotlin Multiplatform artifacts.
Fixes: #5176
=> Enable gradle metadata publishing

firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceFragmentScreenTracesTest.java, firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceScreenTracesTest.java, firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceTest.java
This should fix the flaky TAP tests that expect traces to be sent.
=> Add a 40 second sleep at the end of each Fireperf e2e test to ensure that events are sent before the app exits.

.github/workflows/version-check.yml, buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseJavaLibraryPlugin.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/GmavenHelper.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/GmavenVersionChecker.kt, firebase-messaging/gradle.properties, protolite-well-known-types/gradle.properties, transport/transport-backend-cct/gradle.properties, transport/transport-runtime/gradle.properties
=> Add GMaven Version test

firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceFragmentScreenTracesTest.java, firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceScreenTracesTest.java, firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceTest.java
Also, update the sleep to 40s (Forgot to push in the last PR)
=> Fix missing throw Exception in test for Thread.sleep().

firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigConstants.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigContainer.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigContainerTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandlerTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClientTest.java
- Parse rollout_metadata out of fetch response in `extractConfigs` method
- Add field in ConfigContainer for rollout_metadata to be saved
- Add unit tests for fetching/activating configs with rollout_metadata
=> Feature Rollouts RC Fetch Integration

firebase-config/firebase-config.gradle, firebase-config/ktx/src/test/kotlin/com/google/firebase/remoteconfig/TestConstructorUtil.kt, firebase-config/ktx/src/test/kotlin/com/google/firebase/remoteconfig/ktx/RemoteConfigTests.kt, firebase-config/src/androidTest/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigIntegrationTest.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigRegistrar.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigContainer.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigMetadataClient.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/rollouts/RolloutsStateSubscriptionsHandler.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigComponentTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/rollouts/RolloutsStateSubscriptionsHandlerTest.java
PR 1 of 3 implementing the pub/sub pattern in RC.
PRs: 
1. **This PR: Add dependency with stubbed implementation.**
2. [Implement publish and subscribe.](https://github.com/firebase/firebase-android-sdk/pull/5280)
3. [Implement getActiveRolloutsState.](https://github.com/firebase/firebase-android-sdk/pull/5281)
=> Add RC Interop to RC SDK with a stubbed implementation.

firebase-crashlytics/firebase-crashlytics.gradle, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/CrashlyticsRemoteConfigListenerTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/RemoteConfigDeferredProxyTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreInitializationTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/CrashlyticsRegistrar.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/CrashlyticsRemoteConfigListener.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/RemoteConfigDeferredProxy.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/RolloutAssignment.java
Integrate RC interop with Crashlytics SDK:
1. Adding Crashlytics subscriber for RC interop
2. Adding Deferred Proxy  for RC interop
3. Unit tests
=> Integrate interop with Crashlytics sdk

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/metadata/MetaDataStoreTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/UserMetadata.java
For on-demand fatal, we will need to close the previous session and open a new session during app life cycle. We need to port over the previous UserMetadata state (including user id, custom keys etc) for the new session.
Decide to merge to master later as a part of feature rollouts project.
Original PR: https://github.com/firebase/firebase-android-sdk/pull/5275
=> Feature rollouts user id fix

buildSrc/src/main/java/com/google/firebase/gradle/plugins/BaseFirebaseLibraryPlugin.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/KotlinUtils.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/PostReleasePlugin.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/UpdatePinnedDependenciesTask.kt, buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/FirebaseTestController.kt, buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/PublishingPluginTests.kt, buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/UpdatePinnedDependenciesTests.kt, buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/publishing.kt
Per [b/292140435](https://b.corp.google.com/issues/292140435),
This implements a task to handle conversion of project level dependencies to pinned dependencies post release. Relevant documentation explaining everything is added as well.
The following is also fixed by this PR:
- [b/296419486](https://b.corp.google.com/issues/296419486) - Connect `updatePinnedDependencies` task with `PostReleasePlugin`
- [b/296419551](https://b.corp.google.com/issues/296419551) - Implement a `postReleaseCleanup` task
- [b/296419351](https://b.corp.google.com/issues/296419351) - Add tests for the `updatePinnedDependencies` task
- [b/296420102](https://b.corp.google.com/issues/296420102) - Implement a common test interface for dynamically created projects
- …
=> Finish PostReleasePlugin

sdkProperties.gradle
We need to update AXT core and AndroidX ext JUnit version to ensure using proper AXT dependency that export necessary Activities for higher target SDKs.
This CL also disables lint for some sub-projets and anyone can remove it and fix warnings.
=> Update target to SDK 33

firebase-firestore/CHANGELOG.md
During auto rebase, the change log entry of auto creation cache index was put inside the previous release cycle by mistake.
=> Fix Changelog Error

firebase-crashlytics/firebase-crashlytics.gradle, firebase-inappmessaging/firebase-inappmessaging.gradle
Per [b/299481147](https://b.corp.google.com/issues/299481147),
This updates some project level deps that should've been updated after M136, and will fix the error state occurring in M137.
=> Update project level deps from M136

firebase-crashlytics-ndk/CHANGELOG.md
Per [b/299509129](https://b.corp.google.com/issues/299509129),
This adds a changelog entry to `firebase-crashlytics-ndk` that should've been added with #5274, as `firebase-crashlytics` is in the same library group.
=> Add missing changelog entry to firebase-crashlytics-ndk

firebase-firestore/gradle.properties
Per [b/299650417](https://b.corp.google.com/issues/299650417),
This bumps `firebase-firestore` by a minor version, as should've been done by the deprecation of a public method in #5256.
=> Minor bump for firestore

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java, firebase-firestore/src/test/resources/json/existence_filter_spec_test.json
ported from: https://github.com/firebase/firebase-js-sdk/pull/7457
=> Add test cases for existence filter with updated, removed, added documents

firebase-crashlytics/CHANGELOG.md, firebase-firestore/CHANGELOG.md, firebase-inappmessaging-display/CHANGELOG.md, firebase-inappmessaging/CHANGELOG.md
Per [b/300474851](https://b.corp.google.com/issues/300474851),
This updates the `CHANGELOG.md` files that were changed during the release note review for M137; as such to stay in alignment with our goal of keeping the `CHANGELOG.md` files at master in sync with the release notes.
=> Update CHANGELOG entries according to CL review for m137

firebase-components/gradle.properties, firebase-crashlytics-ndk/CHANGELOG.md, firebase-crashlytics-ndk/gradle.properties, firebase-crashlytics/CHANGELOG.md, firebase-crashlytics/gradle.properties, firebase-firestore/CHANGELOG.md, firebase-firestore/gradle.properties, firebase-inappmessaging-display/CHANGELOG.md, firebase-inappmessaging-display/gradle.properties, firebase-inappmessaging/CHANGELOG.md, firebase-inappmessaging/gradle.properties
Per [b/300503321](https://b.corp.google.com/issues/300503321),
This does all the post release clean up tasks for m137 (the release that just went out).
=> m137 mergeback

firebase-config/test-app/test-app.gradle.kts
Fixes ~Attempting to fix~ instrumentation tests failing with the message:
```
Execution failed for task ':firebase-config:test-app:dexBuilderDebugAndroidTest'.
> Could not resolve all files for configuration ':firebase-config:test-app:debugRuntimeClasspath'.
> Failed to transform classes.jar (project :firebase-installations) to match attributes {artifactType=android-asm-instrumented-jars, asm-transformed-variant=debug, com.android.build.api.attributes.AgpVersionAttr=7.4.2, com.android.build.api.attributes.BuildTypeAttr=debug, com.android.build.gradle.internal.attributes.VariantAttr=debug, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
```
`./gradlew :firebase-config:test-app:dexBuilderDebugAndroidTest` passes when run locally before and after (wasn't able to repro the …
=> [Test App] Use versioned deps for Installations.

buildSrc/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt
Addressess pending comments from PR #5297
=> Use constants for library group task name

firebase-components/CHANGELOG.md, firebase-components/gradle.properties, firebase-crashlytics-ndk/CHANGELOG.md, firebase-crashlytics-ndk/gradle.properties, firebase-crashlytics/CHANGELOG.md, firebase-crashlytics/gradle.properties, firebase-firestore/CHANGELOG.md, firebase-firestore/gradle.properties, firebase-inappmessaging-display/CHANGELOG.md, firebase-inappmessaging-display/gradle.properties, firebase-inappmessaging/CHANGELOG.md, firebase-inappmessaging/gradle.properties
Per [b/300682723](https://b.corp.google.com/issues/300682723),
This does all the post release clean up tasks for m137_1 (the hotfix that just went out).
=> m137_1 mergeback

.github/workflows/sessions-e2e.yml, firebase-sessions/firebase-sessions.gradle.kts, firebase-sessions/test-app/src/main/AndroidManifest.xml, firebase-sessions/test-app/test-app.gradle.kts
Add `useReleasedVersions` property to the sessions e2e test app. Also updated dep versions, and configured test lab to be more consistent. This is so the e2e test app can run on released versions in the scheduled workflow, but default to using the project level deps during local development.
=> Add useReleasedVersions property to sessions e2e test app

.github/workflows/post_release_cleanup.yml
Per [b/301961341](https://b.corp.google.com/issues/301961341),
This creates a workflow that can be invoked to automatically create a mergeback branch *and* run the `postReleaseCleanup` task for after a release.
The workflow is ran from the release branch, but the PR is created for `master`. I will update the release manual to reflect this as well after it's merged and I've tested it.
The `name` input is purely used for naming the mergeback branch PR and such.
=> Create post release plugin workflow

.github/workflows/post_release_cleanup.yml
Per [b/302184829](https://b.corp.google.com/issues/302184829),
This configures the newly added [post release cleanup workflow](https://github.com/firebase/firebase-android-sdk/blob/master/.github/workflows/post_release_cleanup.yml) to add `NO_RELEASE_CHANGE` to the PR's body by default.
=> Automatically add NO_RELEASE_CHANGE to mergeback

firebase-components/src/main/java/com/google/firebase/components/Qualified.java
Add `@NonNull` annotation to `qualified` and `unqualified`. This is to fix a warning in Kotlin code that uses these static methods with nice syntax.
=> Add NonNull annotation to qualified and unqualified

appcheck/firebase-appcheck/CHANGELOG.md, appcheck/firebase-appcheck/firebase-appcheck.gradle, appcheck/firebase-appcheck/test-app/src/main/AndroidManifest.xml, appcheck/firebase-appcheck/test-app/test-app.gradle
Additionally, we are explicitly marking firebase-appcheck/test-app activity as exported, and removing direct dependencies it has with common and components.
=> Declare firebase-common dependency as api in firebase-appcheck

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionDatastore.kt
Avoid changing the api surface. Having `val`s at the file level causes Kotlin to generate a public class with the filenameKt which adds a public class to the public api surface: "The public api surface has changed for the subproject firebase-sessions: error: Added class com.google.firebase.sessions.SessionDatastoreKt [AddedClass]". So we have to put them in a class or companion object.
=> Avoid changing api surface

firebase-messaging/CHANGELOG.md, firebase-messaging/src/main/AndroidManifest.xml
* Added metadata to FirebaseInstanceIdReceiver to signal that it finishes background broadcasts after the message has been handled.
=> Add FINISHED_AFTER_HANDLED metadata to FirebaseInstanceIdReceiver.

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionGenerator.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/TimeProvider.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionGeneratorTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionInitiatorTest.kt
Make `SessionGenerator` injectable. Also made `WallClock` an object to avoid needing to pass it around. Moved `collectEvents` out of SessionGenerator since it will need to be handled in the service.
=> Make SessionGenerator injectable

appcheck/firebase-appcheck-playintegrity/CHANGELOG.md, appcheck/firebase-appcheck/CHANGELOG.md, appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheck.java, appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/NetworkClient.java, appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/RetryManager.java, appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/NetworkClientTest.java, appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/RetryManagerTest.java
Changes:
- Successful `GeneratePlayIntegrityChallenge` call should not reset `RetryManager` backoff
- Cache in-flight App Check token fetching tasks
- Update `403` errors to throttle with exponential backoff rather than a flat one-day period (to match [iOS](https://github.com/firebase/firebase-ios-sdk/blob/f3a14c249e001b3c894bb943ecc3973f50e60a49/FirebaseAppCheck/Sources/Core/Backoff/FIRAppCheckBackoffWrapper.m#L264-L268))
=> Fix client-side throttling for Play Integrity flows

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionFirelogPublisher.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionGenerator.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/SessionsSettings.kt
This will make it safe to call `Firebase.app` any time from anywhere in this SDK.
=> Only support the default Firebase app

.github/workflows/ci_tests.yml, firebase-common/src/main/java/com/google/firebase/ktx/Firebase.kt, firebase-firestore/README.md, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CompositeIndexQueryTest.java
Add guidance to ReadMe File
Add message for terraform workflow to ignore "index already exists" error message.
=> Add composite index testing guidance to ReadMe

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionFirelogPublisher.kt, firebase-sessions/src/test/AndroidManifest.xml, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeFirelogPublisher.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeSessionDatastore.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FirebaseSessionsFakeRegistrar.kt
Adds fake implementations for the newly added interfaces and creates a fake registrar installing our fake implementations.
=> Sessions fake registrar

appcheck/firebase-appcheck-debug-testing/gradle.properties, appcheck/firebase-appcheck-debug/gradle.properties, appcheck/firebase-appcheck-interop/gradle.properties, appcheck/firebase-appcheck-playintegrity/gradle.properties, appcheck/firebase-appcheck/gradle.properties, buildSrc/src/main/java/com/google/firebase/gradle/plugins/PostReleasePlugin.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/VersionBumpTask.kt, firebase-config/gradle.properties, firebase-crashlytics-ndk/gradle.properties, firebase-crashlytics/gradle.properties, firebase-database/gradle.properties, firebase-dynamic-links/gradle.properties, firebase-firestore/gradle.properties, firebase-functions/gradle.properties, firebase-inappmessaging-display/gradle.properties, firebase-inappmessaging/gradle.properties, firebase-installations-interop/gradle.properties, firebase-installations/gradle.properties, firebase-messaging-directboot/gradle.properties, firebase-messaging/gradle.properties, firebase-ml-modeldownloader/gradle.properties, firebase-perf/gradle.properties, firebase-sessions/gradle.properties, firebase-storage/gradle.properties
Per [b/306709509](https://b.corp.google.com/issues/306709509),
This fixes an oversight in which we were not updating the `latestReleasedVersion` during our version bumps. 
Additionally, this fixes the following:
- [b/306713770](https://b.corp.google.com/issues/306713770) -> Update the `latestReleasedVersion` for libraries where it's invalid
- [b/300682493](https://b.corp.google.com/issues/300682493) -> Add condition to `moveUnreleasedChanges` task for changelog file existence
=> Update latestReleasedVersion on version bump

firebase-common/src/main/java/com/google/firebase/logger/Logger.kt, firebase-common/src/main/java/com/google/firebase/logger/package-info.java
Add a common Firebase logging interface to make logging more consistent and make testing easier. With this we could make tests that assert specific things were logged, for example, Sessions could assert an event was logged.
=> Add common Firebase logging interface

firebase-crashlytics/CHANGELOG.md, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CommonUtilsTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistenceTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/ProcessDetailsProvider.kt, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCapture.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/ProcessDetailsProvider.kt, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransform.java
Add process details to Crashlytics java and anr events. NDK events will be handled later after we upgrade crashpad. Also fixed a bug in detecting background processes.
The proto change was made in internal cl/574516195
=> Add process details to Crashlytics events

firebase-firestore/firestore_collection_group_index_config.tf, firebase-firestore/firestore_composite_index_config.tf, firebase-firestore/main.tf, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/AggregationTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CompositeIndexQueryTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/CompositeIndexTestHelper.java
=> Move sum&avg composite index tests to compositeIndexQueryTest.java

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionsActivityLifecycleCallbacks.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionsActivityLifecycleCallbacksTest.kt
Keep track of pending foreground before settings fetched to catch the first session in cold start with no settings cache.
=> Keep track of pending foreground before settings fetched

firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/FirstFragment.kt, firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/SecondActivity.kt, firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/TestApplication.kt, firebase-sessions/test-app/test-app.gradle.kts
Use the latest release bom in the sessions test app instead of trying to figure out released versions.
Also removed direct references to Sessions subscribers from the test app because it will make the e2e test workflow fail after this feature merges to main line but before the release. After the release, we can put that back in.
=> Use the latest release bom in the sessions test app

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvent.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/TestSessionEventData.kt
We identified a bug where the backend protobuf is not in agreement with the structure of the message being sent. This causes the entire message to be dropped. Making this work will require a bit of refactoring.
Revert this for now to be safe and add it back in a subsequent PR.
=> Remove process-details for now.

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt
We need this since we changed how Crashlytics and Perf will depend on Sessions. Before they got an instance of FirebaseSessions but now they don't.
=> Set eagerInDefaultApp for Firebase Sessions

firebase-sessions/test-app/multidex-config.pro, firebase-sessions/test-app/src/androidTest/AndroidManifest.xml, firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/TestApplication.kt, firebase-sessions/test-app/src/main/res/values/strings.xml, firebase-sessions/test-app/test-app.gradle.kts
Enable multidex in the sessions test app to support min api level 16, which is the min level Crashlytics supports
=> Sessions test app run on min api level 16

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/rollouts/package-info.java
Hides internal sub-package from doc generation.
Follow up from internal cl/581411075
=> Create package-info.java for rollouts package.

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/rollouts/package-info.java
Hides internal sub-package from doc generation.
Follow up from internal cl/581411075
=> Create package-info.java for rollouts package. (#5543)

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCapture.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/Utils.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/RolloutAssignmentList.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/UserMetadata.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java
Some of the methods donot have the right nullable annotations. This pr updates all of them
=> Fix crashlytics copybara

firebase-messaging/CHANGELOG.md, firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessagingService.java, firebase-messaging/src/test/java/com/google/firebase/messaging/FirebaseMessagingServiceRoboTest.java
* Called messageHandled() after a message has been handled to indicate that the message has been handled successfully.
=> Call messageHandled after a message has been handled.

firebase-firestore/CHANGELOG.md, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteLruReferenceDelegate.java, firebase-firestore/src/test/java/com/google/firebase/firestore/local/LruGarbageCollectorTestCase.java
Fixes: https://github.com/firebase/firebase-android-sdk/issues/5417
=> Fixed an issue where GC runs into a infinite loop in a certain case.

firebase-ml-modeldownloader/CHANGELOG.md, firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileDownloadService.java
Possible fix for #5593
Android 14 requires `RECEIVER_EXPORTED` or `RECEIVER_NOT_EXPORTED` flag when using `registerReceiver` command:
Currently, `com.google.firebase:firebase-ml-modeldownloader:24.2.1` uses the `registerReceiver` without this flag:
https://github.com/firebase/firebase-android-sdk/blob/ac19e5d561d6a7a24a6004746d95f4e08024fdc4/firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileDownloadService.java#L214-L215
Proposed fix:
```java
context.registerReceiver(
broadcastReceiver,
new IntentFilter(DownloadManager.ACTION_DOWNLOAD_COMPLETE),
context.RECEIVER_NOT_EXPORTED);
```
An alternative solution is using ContextCompat but requires version 1.9.0 of `androidx.core:core`. I noticed in the [Android …
=> Proposed fix for issue 5593

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/AggregationTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CountTest.java
Add a comment to Firestore's integration tests about removing special logic when testing for the "missing index" error message. Formerly, the "missing index" error message was different for the default database and a non-default database; however, their logic has been unified, and will be rolled out to production soon. Once rolled out, these tests should be updated to remove the special logic for non-default dbs.
Also, remove the "else" branch that verified a different error message when a non-default db was used because when that change rolls out that "else" block will start to fail, seemingly without reason. This also brings the test into parity with the js sdk.
A similar change was made to the js sdk in https://github.com/firebase/firebase-js-sdk/pull/7874.
Googlers see b/316359394 for …
=> Firestore: add TODO comments about removing special 'missing index' test logic for multidb

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/AggregationTest.java
Fix variable name: compositeIndexCountQuery -> compositeIndexAggregateQuery (was a copy/paste oversight).
=> Firestore: AggregationTest.java: fix variable name (no functionality changed)

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/AggregationTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CountTest.java
Rename some tests from "FailWithGoodMessage" to "ErrorMessageShouldContainConsoleLink" to be more descriptive, as suggested in another code review: https://github.com/firebase/firebase-ios-sdk/pull/12189. No functionality is changed by this PR, merely the test's names.
A similar change was made to the js sdk in https://github.com/firebase/firebase-js-sdk/pull/7875.
=> Firestore: Improve test name of "missing index" error message tests

buildSrc/src/main/java/com/google/firebase/gradle/plugins/MakeReleaseNotesTask.kt
The task is only invoked on projects that are scheduled to be released. And projects that publish refdocs are the ones that also publish release notes. The task now verifies that if it's called in a project that publishes refdocs, it has to have release notes, otherwise it breaks.
=> Update MakeReleaseNotes to crash if notes are missing.

README.md
Having an additional list of SDKs to update creates unnecessary maintenance load.
=> Remove list of SDKs from README.md

firebase-sessions/CHANGELOG.md, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionDatastore.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/SessionsSettings.kt
Handle corruption in DataStore Preferences more gracefully.
Tested manually by piping junk data into the datastore files.
When the Settings data store preferences gets corrupt, it will be replaced by an empty preferences with all null values. This will cause settings to fall through to sdk defaults until the next settings fetch. If the Sessions data store preferences gets corrupt, it will lose the session id until the next session is generated on the next foreground. I could not force a session to upload will a null session id, but I expect it to be rare but possible with a multi-process app.
=> Handle corruption in DataStore Preferences gracefully

buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaGenerationTask.kt
Per [b/321049856](https://b.corp.google.com/issues/321049856),
This fixes an issue where the docs were being generated with the `com.google` package prefix in the toc files. This behavior was originally fixed by `FiresiteTransform`, but was removed with #5550 in favor of the "newly" added dackka configuration option. Although, it seems the actual configuration managed to be skipped over in the original PR, so this properly enabled it.
[b/321753481](https://b.corp.google.com/issues/321753481) has also been created to track investigating why this initially wasn't caught by our CI job.
=> Fix package prefix removal in doc generation

.github/workflows/build-release-artifacts.yml, .github/workflows/diff-javadoc.yml, firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
Per [b/321263425](https://b.corp.google.com/issues/321263425),
This switches our `macos` runners to `ubuntu`, which should help up save a considerable sum- not only in instance overhead/usage (as macos runners are 10x as expensive as standard linux runners), but in the engineering time saved by the CI not needing to wait for a macos runner to be available (as they come in a more limited quantity).
Since [GItHub has increased the amount of cores provided to their ubuntu machines](https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/), we can effectively work around [b/271315039](https://b.corp.google.com/issues/271315039) (which forced us to use `macos-latest` instead of `ubuntu-latest` for anything involving our javadoc generation).
=> Migrate macos runners to ubuntu

firebase-perf/dev-app/dev-app.gradle
Namespace should be `com.googletest.firebase.perf.testapp` without the `prod` suffix
=> Fix perf devapp namespace

firebase-database/CHANGELOG.md, firebase-database/src/main/java/com/google/firebase/database/core/utilities/encoding/CustomClassMapper.java, firebase-database/src/test/java/com/google/firebase/database/KotlinEntities.kt, firebase-database/src/test/java/com/google/firebase/database/MapperTest.java, firebase-firestore/CHANGELOG.md, firebase-firestore/src/main/java/com/google/firebase/firestore/util/CustomClassMapper.java, firebase-firestore/src/test/java/com/google/firebase/firestore/util/KotlinEntities.kt, firebase-firestore/src/test/java/com/google/firebase/firestore/util/MapperTest.java
This PR was inspired by [this question](https://stackoverflow.com/questions/77739613/kotlin-multiple-setters-getters-generics/). The `@Exclude` annotation has not been propagated to Kotlin's corresponding bridge methods. Additionally, there is no straightforward way to eliminate their 'get-' and 'set-' prefixes, as `@JvmName` is not propagated to them either.
It seemed possible to solve this issue by redesigning the models. However, including bridge methods in the exceptions list – alongside other checks nearby – anyway seems to be a viable solution.
=> Handle bridge methods while mapping

firebase-config/CHANGELOG.md, firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigGetParameterHandler.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/rollouts/RolloutsStateFactory.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigGetParameterHandlerTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/rollouts/RolloutsStateFactoryTest.java
The `getString(String parameterKey)` method calls listeners as a side-effect, which isn't the behavior we want when `activate()` is called and Rollouts are published.
This duplicates the `getString` method without the side-effects (as well as a helper method to access the cache). Alternatively we could duplicate this method _within_ `ConfigGetParameterHandler`, but it'd have to be `public` which implies other callers should use it (they shouldn't - there's no other use case besides Rollouts).
Google internal: b/324275156
=> Get parameter value for rollout without side effects.

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHandler.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
Store the Realtime client's `HttpUrlConnection` reference on the class instance so it can used by another client instance method (`closeRealtimeHttpStream`) to disconnect when the app is backgrounded.
The rest of the changes are follow on work to handle network errors thrown when `HttpUrlConnection#disconnect` is called. Since HttpUrlConnection enforces a [strict lifecycle](https://android.googlesource.com/platform/external/okhttp/+/602d5e4/okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpConnection.java#43) and this code (1) interacts with the connection in several methods/classes and (2) holds open the connection for a long time, it's likely randomly disconnecting when backgrounded will occur at an inopportune lifecycle state.
This change inserts a few conditionals to ensure …
=> Disconnect from RC real-time server when app is backgrounded.

firebase-database/CHANGELOG.md, firebase-database/src/main/java/com/google/firebase/database/core/utilities/encoding/CustomClassMapper.java, firebase-database/src/test/java/com/google/firebase/database/KotlinEntities.kt, firebase-database/src/test/java/com/google/firebase/database/MapperTest.java, firebase-firestore/CHANGELOG.md, firebase-firestore/src/main/java/com/google/firebase/firestore/util/CustomClassMapper.java, firebase-firestore/src/test/java/com/google/firebase/firestore/util/KotlinEntities.kt, firebase-firestore/src/test/java/com/google/firebase/firestore/util/MapperTest.java
Restore PR: https://github.com/firebase/firebase-android-sdk/pull/5626
The majority of the code in this PR was contributed by [vladd-g](https://github.com/vladd-g)
For more context, please refer to the linked PR.
=> Fixed the missing handling setter annotations bug

firebase-inappmessaging-display/CHANGELOG.md, firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplay.java, firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/internal/FiamImageLoader.java, firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/internal/GlideErrorListener.java, firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/internal/injection/components/AppComponent.java, firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/internal/injection/modules/GlideModule.java, firebase-inappmessaging-display/src/test/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplayTest.java, firebase-inappmessaging-display/src/test/java/com/google/firebase/inappmessaging/display/internal/FiamImageLoaderTest.java, firebase-inappmessaging/CHANGELOG.md
Changed `GlideErrorListener` to a normal class and pass a new instance of the listener into each load image request instead of being injected as a defaultRequestListener.
Refactored `InAppMessage` and `FirebaseInAppMessagingDisplayCallbacks` assignment code for clarity.
Internal tracking: b/321732964
Issue: #5644
=> FIAM: Fix FirebaseInAppMessagingDisplayErrorListener not being called

buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaGenerationTask.kt
Per [b/326624050](https://b.corp.google.com/issues/326624050),
This deletes the configuration that was removing the package prefix from our toc files. 
We previously needed to remove the `com.google` package prefix from our docs; since of the SDKs were still using the old doc engine. Now that everyone has migrated, this is no longer needed. We should remove this transformation from our doc generation to align with internal systems.
=> Allow package prefix in docs

firebase-common/CHANGELOG.md, firebase-common/firebase-common.gradle.kts
There's no need for common to have a project level dependency on components, as they are both released separately.
This should fix issue #5732
=> Pin firebase-common dependency in components

buildSrc/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt, buildSrc/src/main/java/com/google/firebase/gradle/plugins/ReleaseGenerator.kt
markdown should always generate, but can be generated seperately
=> broke up the release report generation into two tasks

firebase-sessions/CHANGELOG.md, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/InstallationId.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvent.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionFirelogPublisher.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/RemoteSettings.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionFirelogPublisherTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeFirebaseInstallations.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/TestSessionEventData.kt
This adds the auth token to sessions, which forced the client to validate the fid, as well as allow us to validate it on the backend.
I will make a similar change in Crashlytics in the next PR.
=> Add auth token to sessions

firebase-sessions/firebase-sessions.gradle.kts, firebase-sessions/src/androidTest/kotlin/com/google/firebase/sessions/SessionLifecycleServiceBinderTest.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleServiceBinder.kt
Pair with @PolinaGo. This fixes #5718.
=> Handle when the session lifecycle service binding fails

transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java, transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctTransportBackendTest.java, transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/UploaderIntegrationTest.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/AlarmManagerScheduler.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoScheduler.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/SchedulerConfig.java, transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/Uploader.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/AlarmManagerSchedulerTest.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoSchedulerTest.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/UploaderTest.java
Per [b/327603525](https://b.corp.google.com/issues/327603525),
This adds support for batching the new `PseudonymousId`. Events are batched according to age- the oldest event will be batched with its type. For example:
If the oldest event does **_not_** have a `PseudonymousId`, then all events without a `PseudonymousId` will be sent.
If the oldest event **_does_** have a `PseudonymousId`, then all events with the **_SAME_** `PseudonymousId` will be sent.
The following needs to be complete before merging:
=> Add support for new batching

firebase-config/CHANGELOG.md, firebase-config/gradle.properties
Per [b/329272808](https://b.corp.google.com/issues/329272808),
This is the mergeback for the previous hotfix release (m144_1)- to avoid pulling config into the current release.
=> m144_1 mergeback

transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/AlarmManagerSchedulerTest.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoSchedulerTest.java
Per [b/329880433](https://b.corp.google.com/issues/329880433),
This fixes a complaint from TAP about us mocking an autovalue class. Apparently, it's mean to mock auto value classes. Instead, we should be nice and create instances of them. So we are no longer mocking `EventInternal`.
=> Stop mocking EventInternal

firebase-crashlytics-ndk/CHANGELOG.md, firebase-crashlytics/CHANGELOG.md, firebase-crashlytics/firebase-crashlytics.gradle
Per [b/330156705](https://b.corp.google.com/issues/330156705),
Sessions is invoking the release of Crashlytics. As such, there needs to be changelog entries on both Crashlytics and the NDK reflecting their respective dependency bumps. This adds those changelogs.
This PR also fixes the following:
- [b/330156817](https://b.corp.google.com/issues/330156817) - Ensure there's a project level dependency between sessions and crashlytics
=> Add missing changelog entries

transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/UploaderTest.java, transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/InMemoryEventStore.java
Per [b/330185088](https://b.corp.google.com/issues/330185088),
This adds a cleanup step to our uploader tests. This hasn't been needed up until now, as tests have not only *not* cared about the order of events- but they make use of all the events they store. With the addition of our new tests, this is no longer the case. Depending on the order these new tests run it, it can produce a pass or fail for certain tests that are ascertaining the order of the events.
As such, the store will now be wiped after each test.
=> Cleanup Uploader tests

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/analytics/BlockingAnalyticsEventLoggerTest.java, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleClient.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleServiceBinder.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionLifecycleClientTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionsActivityLifecycleCallbacksTest.kt
This fixes flaky test due to "default firebase app not initialized" when running crashlytics or sessions tests.
Removes the `instance` function from the companion object of the binder, and pass it in the FirebaseSessions ctor instead.
=> Fix flaky test

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionCallingConfig.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ToolConfig.kt
Based on the changes made in https://github.com/google/generative-ai-android/pull/103
=> Add support for constrain decoding

firebase-common/api.txt, firebase-common/firebase-common.gradle.kts, firebase-common/src/main/java/com/google/firebase/Timestamp.java, firebase-common/src/main/java/com/google/firebase/util/package-info.java, firebase-common/src/test/java/com/google/firebase/TimestampTest.java, firebase-firestore/api.txt, firebase-firestore/firebase-firestore.gradle, subprojects.cfg
Per [b/243534168](https://b.corp.google.com/issues/243534168),
This moves `Timestamp` from the firestore package to the common package-  as `Timestamp` actually lives under the `com.google.firebase` package name, but the file itself was residing in the firestore module.
This is intended to just be a near 1:1 move.
=> Move Timestamp to common

buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt
Per [b/333554068](https://b.corp.google.com/issues/333554068),
This removes the `Timestamp` workarounds we had in our doc generation. Now that `Timestamp` has been moved to common with #5842, we no longer need these workarounds. In the interest of removing unnecessary artifacts, I've gone ahead and created this PR.
=> Remove Timestamp workarounds from doc generation

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt
`@JvmStatic` should allow Java developers to use:
```java
FirebaseVertexAI instance = FirebaseVertexAI.getInstance()
```
instead of:
```java
FirebaseVertexAI instance = FirebaseVertexAI.Companion.getInstance()
```
And `@JvmOverloads` should generate method overloads that substitute default parameter values so that developers don't need to pass all the parameters when calling `FirebaseVertexAI.getInstance().generativeModel(...)`.
=> improve java interoperability

firebase-messaging/CHANGELOG.md, firebase-messaging/firebase-messaging.gradle, firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessaging.java, firebase-messaging/src/main/java/com/google/firebase/messaging/GmsRpc.java, firebase-messaging/src/main/java/com/google/firebase/messaging/ProxyNotificationPreferences.java, firebase-messaging/src/test/java/com/google/firebase/messaging/FirebaseMessagingRoboTest.java, firebase-messaging/src/test/java/com/google/firebase/messaging/GmsRpcRoboTest.java, firebase-messaging/src/test/java/com/google/firebase/messaging/ProxyNotificationPreferencesRoboTest.java
- Add setting of proxy notification retention based on whether the app uses Google Analytics or has BigQuery export enabled.
- Add retrieval and logging to GA or BigQuery of proxied notifications at startup.
=> Log analytics for proxied notifications.

firebase-sessions/CHANGELOG.md, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleServiceBinder.kt
Fix for #5869.
`Fatal Exception: java.lang.IllegalArgumentException: Service not registered: [obfuscated]` happens when the context calls `unbindService` on a service connection that has not been bounded. Either due to `SecurityException` or the existing service cannot be found from the map of services that has been bounded.
Simulating tests by calling `unbindService` without initially calling `bindService` will result to the same stacktrace as with the issue:
```
java.lang.IllegalArgumentException: Service not registered: com.example.testunbinding.MainActivity$onCreate$serviceConnection$1@8988566
at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1289)
at android.app.ContextImpl.unbindService(ContextImpl.java:1511)
at …
```
=> Safely handle unbinding service connection

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
It's an implementation detail and shouldn't be exposed in the API
=> Make controller private in GenerativeModel

firebase-vertexai/CHANGELOG.md, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerationConfig.kt
Per [b/338382359](https://b.corp.google.com/issues/338382359),
This adds support for the `response_mime_type` property of `GenerationConfig`. Although, this won't properly work until `generativeai:common` releases again. Schema support will be provided in a follow up PR.
=> Add responseMimeType support

firebase-vertexai/CHANGELOG.md, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Exceptions.kt
Per [b/339846019](https://b.corp.google.com/issues/339846019),
This renames the `GoogleGenerativeAIException` to `FirebaseVertexAIException` in the Vertex SDK, to not only better align with the actual product name- but other Firebase products as well.
=> Rename Vertex exception

firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/generated/GeneratedConnector.kt, firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/generated/GeneratedOperation.kt
From b/340910059: In order to document the behavior of the equals() and hashCode() methods of the generated classes, these methods were added to the GeneratedConnector and GeneratedOperation interfaces in the Android Core SDK; however, adding these methods is a breaking change that requires the implementing classes to explicitly define them, rather than inheriting the (correct) default behavior from kotlin.Any. Since the released codegen does not explicitly define these methods it fails to compile. However, once the codegen that does define those methods is sufficiently soaked, they should be uncommented.
=> Comment the equals() and hashCode() methods in GeneratedConnector and GeneratedConnector

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/RemoteSettings.kt
This is part of an effort to prevent ANRs.
The Sessions sdk was blocking the main thread for a split second to load the cache from disk. By making the cache lazy, it is still safe to fetch it anytime and assume it is loaded at any time, but it will not block initialization, instead it will block the first read. The first time Sessions reads from the cache is in a background thread, so it will be loaded then. But if we ever tried to read the cache after say a failed initiation, we can still safely assume when we get `settingsCache` it will have loaded from disk.
=> Make the settings cache load lazy, improving init time

firebase-crashlytics/CHANGELOG.md, firebase-crashlytics/firebase-crashlytics.gradle
Fix compatibility issues with Crashlytics.
Tested manually with a test app. Not sure why we had an old version pinned with exclude rules?
Should we do something with the version catalog instead? Keep all the SDK's dependencies pinned to versions, but those versions are defined consistently with the BoM.
=> Fix compatibility issues with Crashlytics

firebase-crashlytics/CHANGELOG.md, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/IdManager.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
Improve cold initialization time by not validating the fid on init. We only need to detect if the fid has changed on initialization, we don't care if it's valid. Changing it, deleting it, manipulating it, whatever... should cause the Crashlytics id to rotate. That will still happen after this change.
In my local experiments, this improved the cold init time from about 300 ms to 50 ms. This does not affect warm init, when the fid and auth token are already cached. On the first report, if the auth token has not yet been fetched, it will get fetched at upload time. If validating the fid caused the fid to rotate, the Crashlytics id will also rotate on the next launch.
=> Improve cold initialization time

firebase-appdistribution/test-app/test-app.gradle
Doesn't build without this right now.
=> Add namespace to firebase-appdistribution/test-app/test-app.gradle

firebase-dataconnect/emulator/emulator_noauth.sh, firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/FirebaseDataConnect.kt
In cl/636395279 the grpc and http ports were combined. Also, that CL changes the --grpc_port and --http_port flags into a single flag: --listen, whose default value is 127.0.0.1:3628. This change will be included in the v1.1.18 release of the Data Connect emulator, and will be used by firestore-tools with https://github.com/firebase/firebase-tools/pull/7211 merged in.
=> Change default port of useEmulator() to 9399 (was 9510).

ci/fireci/fireciplugins/binary_size.py, ci/fireci/fireciplugins/coverage.py, ci/fireci/fireciplugins/macrobenchmark/commands.py
The custom domain "firebase-sdk-health-metrics.com" currently associated with the Metric Service will be deprecated eventually, due to the acquisition of Google Domains by Squarespace.
Switching to the original URL created by Google Cloud Run (which hosts the Metric Service) to avoid service disruption.
See b/303931111 for more details.
=> Update the URL for the Metric Service

firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/FirebaseDataConnect.kt, firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/DataConnectGrpcRPCs.kt
The strict mode violations were fixed by simply moving the grpc initialization onto another coroutine dispatcher.
Here are the violations that are fixed by this PR:
```
StrictMode policy violation: android.os.strictmode.CustomViolation: gcore.dynamite
at android.os.StrictMode$AndroidBlockGuardPolicy.onCustomSlowCall(StrictMode.java:1625)
at android.os.StrictMode.noteSlowCall(StrictMode.java:2693)
at amyr.a(:com.google.android.gms@242013041@24.20.13 (190800-633713831):3)
at com.google.android.gms.chimera.container.GmsModuleChimeraProvider.query(:com.google.android.gms@242013041@24.20.13 (190800-633713831):135)
at aiym.query(:com.google.android.gms@242013041@24.20.13 (190800-633713831):3)
at android.content.ContentProvider.query(ContentProvider.java:1455)
at …
```
=> DataConnectGrpcRPCs.kt: fix strict mode violations when initializing grpc

firebase-appdistribution-api/CHANGELOG.md, firebase-appdistribution-api/gradle.properties, firebase-appdistribution/CHANGELOG.md, firebase-appdistribution/gradle.properties, firebase-crashlytics-ndk/CHANGELOG.md, firebase-crashlytics-ndk/gradle.properties, firebase-crashlytics/CHANGELOG.md, firebase-crashlytics/gradle.properties, firebase-dynamic-links/CHANGELOG.md, firebase-dynamic-links/gradle.properties, firebase-perf/CHANGELOG.md, firebase-perf/gradle.properties, firebase-sessions/gradle.properties
=> Mergeback for release m148

firebase-crashlytics-ndk/CHANGELOG.md, firebase-crashlytics-ndk/src/main/jni/libcrashlytics-common/Android.mk, firebase-crashlytics-ndk/src/main/jni/libcrashlytics-handler/Android.mk, firebase-crashlytics-ndk/src/main/jni/libcrashlytics-trampoline/Android.mk, firebase-crashlytics-ndk/src/main/jni/libcrashlytics/Android.mk
Update libcrashlytics to support 16 kb page sizes.
Tested using the instructions in [Verifying Your App](https://docs.google.com/document/d/11EG6_7vqIxvi517mivD34tBV_3k5SmpaTzaqMElvPXI/edit?resourcekey=0-rUve940xNkPV9DkvYgVBGw&tab=t.0#bookmark=id.rmsr6g9is475)
1. ```bash
$ adb shell getconf PAGE_SIZE
16384
```
2. ```bash
out/lib/arm64-v8a/libcrashlytics-handler.so: ALIGNED (2**14)
out/lib/arm64-v8a/libapp.so: ALIGNED (2**14)
out/lib/arm64-v8a/libcrashlytics.so: ALIGNED (2**14)
out/lib/arm64-v8a/libcrashlytics-trampoline.so: ALIGNED (2**14)
out/lib/arm64-v8a/libcrashlytics-common.so: ALIGNED (2**14)
```
3. ```bash
$ /google/src/head/depot/google3/third_party/java/android/android_sdk_linux/platform-tools/zipalign -c -P 16 -v 4 app-test.apk
...
11172592 resources.arsc (OK)
Verification …
```
=> Update libcrashlytics to support 16 kb page sizes

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/send/ReportQueue.java
Addressing issue #6001. This will avoid failing on the early upload and instead report the errors with either the next scheduled time by Firelog, or the next app launch
=> Changing caught exception type to fail safely on any exception type.

firebase-vertexai/CHANGELOG.md, firebase-vertexai/firebase-vertexai.gradle.kts
Per [b/346811894](https://b.corp.google.com/issues/346811894),
This fixes an issue with the VertexAI SDK failing to decode json literals. More specifically, the fix was applied to `generativeai:common` with `0.7.1`, and this PR bumps said dependency to bring in the change.
Fixes #6028
=> Fix JSON literal parsing in VertexAI

firebase-vertexai/CHANGELOG.md
We are being more explicit about the changes, as only one change is
truly breaking. There's a single breaking API change, while the other
is marking as deprecated, but not removing, another API.
=> Update vertexAI changelog entries around schema changes

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/ExecutorUtils.java
- Use backgroundExecutorService from firebase common executor to process setting fetch task 
- Remove some legacy logic
#no-changelog
=> Refactor startup executor

firebase-components/proguard.txt
This is needed since newer versions of R8 no longer implicitly keeps the default constructor in full mode: https://r8.googlesource.com/r8/+/06e32a8d0d2e7e28bc4e597e4ce96e2e0c229d08
=> Explicitly keep default constructor in subtypes of ComponentRegistrar

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/AggregationTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ArrayTransformsServerApplicationTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ArrayTransformsTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/BundleTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CompositeIndexQueryTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CountTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CursorTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/DocumentSnapshotTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FieldsTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/IndexingTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ListenerRegistrationTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/NumericTransformsTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/POJOTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ServerTimestampTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/SmokeTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/SnapshotListenerSourceTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/SourceTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/TransactionTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/TypeTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/WriteBatchTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
- Fix testing bug where host was not being set correctly for testing against nightly.
- Make teardown concurrent to speed up tests.
- Avoid running clear persistence when using in memory cache.
- Use in memory persistence more in tests to avoid creating SQLite databases that then need to be cleared.
- Remove logic to prime database, because this was being executed many times due to test runner. Also, this doesn't actually help prevent timeout because time spent on priming database is included in timeout.
=> Faster tests

firebase-crashlytics/CHANGELOG.md, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/FileStoreTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/FileStore.java
New Crashlytics file system v3 to avoid long file names. Shorten the Crashlytics folder name itself. If a file name is longer than 40 chars, hash it to a 40 char hash. Also use the new `ProcessDetailsProvider` to get the process name on older Android versions so they can take advantage of the process-aware file system.
=> New Crashlytics file system v3 to avoid long file names

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java
I noticed tests were failing when testing on api 21 for the file system change. They were failing because the `ApplicationExitInfo` class isn't available until Android 11, that's api level 30.
=> Fix tests on lower api levels

firebase-crashlytics/firebase-crashlytics.gradle, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreInitializationTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/metadata/MetaDataStoreTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/UserMetadata.java, firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerRobolectricTest.java
Remove `CrashlyticsBackgroundWorker` from `UserMetaData`, use Firebase background common executor for user metadata logging such as user id, custom key value, internal key value and rollouts.
Test:
Checking with log and see key data is writing from different Firebase background common thread
Also same unit test is tested on current implementation with Crashlytics Background Worker. Current way of doing it is actually less efficient since everything is run on the same Junit Test Thread, every iteration of change it need to update the writes to disk (where as the new implementation log you can see we skipped a lot writing entry):
=> Decouple user metadata from Crashlytics backend worker

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/metadata/MetaDataStoreTest.java
Since we have refactored using common backend executor to set user metadata, fix all unit tests which use UserMetadata to set value.
=> Fix unit tests

smoke-tests/README.md
The task in the README wasn't found. I found this by running `:tasks` and saw the same failures I saw in a couple previous PR's smoke tests.
=> Update task name in README instructions for smoke test

firebase-crashlytics/firebase-crashlytics.gradle, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/RemoteConfigDeferredProxyTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CommonUtilsTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/DefaultSettingsControllerTest.java, firebase-sessions/firebase-sessions.gradle.kts
Update Crashlytics and AQS dep versions. Fixed some of the tests because of changes to Mockito. The Mockito version in the Android tests is still pinned a bit old, because after that version a lot more things break.
=> Upgrade Crashlytics dep versions

buildSrc/src/main/java/com/google/firebase/gradle/plugins/SdkUtil.kt, firebase-crashlytics-ndk/CHANGELOG.md
Per [b/352147122](https://b.corp.google.com/issues/352147122),
This adds release metadata for Vertex, so that it can properly generate release notes.
This PR also fixes the following:
- [b/352147570](https://b.corp.google.com/issues/352147570) -> Add missing changelog entry for crashlytics ndk
=> Add release metadata for Vertex

.github/workflows/ci_tests.yml, .github/workflows/firestore_ci_tests.yml, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/AggregationTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ArrayTransformsServerApplicationTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ArrayTransformsTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/BundleTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CompositeIndexQueryTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ConformanceTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CountTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CursorTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/DocumentSnapshotTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FieldsTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/IndexingTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ListenerRegistrationTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/LoadBundleTaskTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/NumericTransformsTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/POJOTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ServerTimestampTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/SmokeTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/SnapshotListenerSourceTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/SourceTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/TransactionTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/TypeTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/WriteBatchTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/CompositeIndexTestHelper.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
Run Firestore Integration tests from Android Emulator, this brings down the tests runtime to around 10 minutes from 40.
There are several changes in this PR:
1. Take firestore out of ci_tests.yml. 
2. Create firestore_ci_tests.yml so that other SDKs do not have to setup emulators.
3. Revert https://github.com/firebase/firebase-android-sdk/pull/6057. This PR is causing failures like: https://github.com/firebase/firebase-android-sdk/actions/runs/9910054539/job/27379655403?pr=6094 after we switch to emulator, may be related to its more concurrent nature.
4. Commented out a test that fails on CI.
=> Run Firestore CI from Android Emulator instead

firebase-vertexai/src/test/java/com/google/firebase/vertexai/StreamingSnapshotTests.kt, firebase-vertexai/src/test/java/com/google/firebase/vertexai/UnarySnapshotTests.kt
This adds test cases to cover more of the [mock response files](https://github.com/FirebaseExtended/vertexai-sdk-test-data/tree/main/mock-responses).
=> Add more VertexAI unit tests

.github/workflows/create_releases.yml, .github/workflows/post_release_cleanup.yml
Per [b/353295303](https://b.corp.google.com/issues/353295303),
This updates our `post_release_cleanup` workflow to use the `google-oss-bot` as the signee. This should allow the workflow to pass CLA, as `github-actions` is not supported.
Note that while `create_release` _does_ create a PR that could take advantage of this, we've chosen to keep it in a state where the CLA fails; such that the PR is not accidentally merged (as _that_ PR should _not_ be merged).
=> Fix CLA issues in workflows

firebase-common/firebase-common.gradle.kts
Per [b/353766765](https://b.corp.google.com/issues/353766765),
This fixes the issues with the `makeReleaseNotes` task when running against common. We don't publish release notes for common, but somehow made it this far without release notes disabled for it?
=> Fix makeReleaseNotes

firebase-crashlytics/CHANGELOG.md, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/Utils.java, firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/common/DataCollectionArbiterRobolectricTest.java
Ensure that on-demand fatal events are never processed on the main thread.
Also decreased the timeout on main to under 3 seconds, to give more time to other uncaught exception handlers in the chain.
Also fixed some formatting.
Tested cases:
Uncaught exception thrown from the main thread
Uncaught exception thrown from a background thread
ODF triggered on the main thread
ODF triggered on a background thread
=> Ensure that on-demand fatal events are never processed on the main thread

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/FileStore.java
Per [b/353751840](https://b.corp.google.com/issues/353751840),
This fixes the issues that were causing tests to fail when trying to copy the changes into head. More specifically:
- It suppresses a Kotlin Internal usage- as it's a false positive (they live under the same package, which is _okay'd_ internally)
- It adds a type to a `Class` usage- as this seems to be required at head
=> Fix m150  issues

firebase-vertexai/src/test/java/com/google/firebase/vertexai/StreamingSnapshotTests.kt, firebase-vertexai/src/test/java/com/google/firebase/vertexai/UnarySnapshotTests.kt, firebase-vertexai/src/test/java/com/google/firebase/vertexai/util/tests.kt
This will allow these files to be scanned by a coverage tool to be added to https://github.com/firebaseextended/vertexai-sdk-test-data.
=> VertexAI: update test cases to use full name of mock response files

firebase-crashlytics/firebase-crashlytics.gradle, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/CrashlyticsWorkerTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/CrashlyticsWorker.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsBackgroundWorker.java
Generalize the CrashlyticsWorker.
The old CrashlyticsBackgroundWorker has a lot of overhead. Local experimentation shows this generalized worker manages submitting tasks about 4 times as fast.
The old background worker has some inaccurate Javadoc. I corrected and verified every detail mentioned in the Javadoc with integration tests. We can rely on it now.
I also found a bug in the old worker. If you cancel a task then submit a runnable or callable, that will never execute because the chain breaks. I fixed it in the general worker and added test cases.
Next steps will be to utilize the generic worker for the proposed common, network, and disk write workers.
=> Generalize the CrashlyticsWorker

firebase-crashlytics/firebase-crashlytics.gradle, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/CrashlyticsTestCase.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreInitializationTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/metadata/MetaDataStoreTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/DefaultSettingsControllerTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/DefaultSettingsSpiCallTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/CrashlyticsPreconditions.kt, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/CrashlyticsWorker.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/Utils.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/UserMetadata.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/network/HttpGetRequest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/DefaultSettingsSpiCall.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsController.java, firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerRobolectricTest.java
Migrate to Firebase common executors. Use the new `CrashlyticsWorker` for common and disk write workers.
=> Migrate to Firebase common executors

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/UserMetadata.java, firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerRobolectricTest.java
- Creating common and disk worker based on Firebase background common executor
- Move all user action directly to background thread and remove some unnecessary task submit
- Add unit tests dependency for firebase common executor
- Decouple crashlytics backend handler from user metadata and use disk writing working for persistence write.
=> User action refactor

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/CrashlyticsPluginsTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
Add test cases for internal apis used by development platform plugins so we don't break them by accident during refactoring.
We should consider making the internal api more explicit.
=> Add tests for internal apis used by development platform plugins

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/CrashlyticsWorkerTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/CrashlyticsWorker.java
Added a method to submit a task followed by a continuation to the worker. This is useful for making a continuation happen right after the submitted task, even if other tasks were submitted to the worker in the meantime. This will be useful for fetching settings from a network executor, then continuing on the common worker to parse the settings json.
Also added a method to race two tasks on the worker. This is useful for things like waiting for an for explicit data collection enable call, or automatic data collection being enabled.
Both methods have their behaviour fully documented in the javadoc and tested in unit tests.
=> Improvements to the CrashlyticsWorker

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/concurrency/ConcurrencyTesting.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/concurrency/CrashlyticsTasksTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/concurrency/CrashlyticsWorkerTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/concurrency/CrashlyticsTasks.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/concurrency/CrashlyticsWorker.java
Create a util for Crashlytics-specific Tasks, and move `race` into it. This util class will hold other things later, so they don't make the worker class a mess. We will need something like `submitWaiting` next to block until a task is complete, this is how data collection is implemented.
=> Create a util for Crashlytics tasks, and move race into it

firebase-vertexai/src/test/java/com/google/firebase/vertexai/StreamingSnapshotTests.kt, firebase-vertexai/src/test/java/com/google/firebase/vertexai/UnarySnapshotTests.kt, firebase-vertexai/update_responses.sh
The set of mock responses were updated to reduce some more duplication: https://github.com/FirebaseExtended/vertexai-sdk-test-data/pull/12
This updates the test code to use the updated version.
=> VertexAI: use updated set of mock responses

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/metadata/MetaDataStoreTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java, firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerRobolectricTest.java
Move file clean up task to disk write worker.
Fix unit test: close session has to run on a background thread
=> move more jobs to disk write

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
Avoid `Task`s in `checkForPreviousCrash`. This is a step towards removing the nasty `awaitEvenIfOnMainThread`.
=> Avoid Tasks in checkForPreviousCrash

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/IdManager.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/Utils.java
Deprecate `awaitEvenIfOnMain`. Next PR will be to drain the worker and remove this util.
=> Deprecate awaitEvenIfOnMain

firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/FirebaseDataConnectRegistrar.kt
Change platform logging tag to `fire-data-connect` (was `fire-dataconnect`)
Googlers see https://docs.google.com/spreadsheets/d/16kRJGsann0Kt2ohTGiei0Aa_c7mWBGD0w9EQ9AgoMVI/edit?gid=0#gid=0
=> Change platform logging tag to "fire-data-connect", was "fire-dataconnect"

firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/DataConnectGrpcMetadata.kt, firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/DataConnectGrpcMetadataUnitTest.kt
See for rationale: https://github.com/firebase/firebase-js-sdk/pull/4810
=> DataConnectGrpcMetadata.kt: Omit x-firebase-gmpid if appId is empty or blank (i.e. contains only whitespace characters)

firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
Make init suspend on settings only, not on race. This allows us to avoid having a separate queue just for init and settings.
If the app has unsent reports, but data collection and send unsent reports both have not been triggered, still let user actions queue up.
=> Make init suspend on settings only

build.gradle, encoders/firebase-encoders-processor/src/test/resources/ExpectedAtEmptyAnnotation.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedAtMyAnnotation.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedGenericsEncoder.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedGenericsEncoderWithUnknownType.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedMyClassEncoderWithExtraProperty.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedRecursiveGenericEncoder.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedSimpleClassEncoder.java, encoders/firebase-encoders-processor/src/test/resources/ExpectedTypeWithListEncoder.java
Per [b/361535657](https://b.corp.google.com/issues/361535657),
This fixes the encoders unit test failures. Encoders generates imports that aren't necessarily needed, just for the sake of being safe. This also means that our resource files that we use for checking the generated encoding have the extra imports. But, our formatting/linting (spotless) removes these imports as it recognizes they're not needed.
Since we're testing the expected behavior of encoders- we expect these imports to be present regardless. It's also a reasonable assumption that spotless doesn't need to check resource files. So this PR re-adds the missing imports, and configures spotless to ignore files under `test/resources` directories.
=> Fix encoding failure

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/IdManager.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/concurrency/CrashlyticsWorkers.kt
Add a precondition check for not main thread. This is more useful when we just want to enforce not main thread, not a specific thread.
=> Add a precondition check for not main thread

.github/workflows/post_release_cleanup.yml
Per [b/361612219](https://b.corp.google.com/issues/361612219),
This updates the committer email we use in our post release cleanup to use the proper robot email, so that it properly passes CLA checks.
=> Fix robot CLA

.github/workflows/build-release-artifacts.yml
Per [b/361778952](https://b.corp.google.com/issues/361778952),
This renames the exported release notes in the build artifact workflow to be `release_notes` instead of `release_artifacts`. It seems my previous commit to do this didn't make it in before the branch was merged.
This PR also fixes the following:
- [b/361781459](https://b.corp.google.com/issues/361781459) -> Fix build artifact double zipping
=> Fix release notes export name

firebase-dataconnect/emulator/dataconnect/connector/alltypes/alltypes_ops.gql, firebase-dataconnect/emulator/dataconnect/schema/alltypes_schema.gql, firebase-dataconnect/src/androidTest/kotlin/com/google/firebase/dataconnect/AnyScalarIntegrationTest.kt
This is the first part of adding `Any` scalar support to Data Connect (Googlers see b/361367932). This PR merely ensures that the wire protocol handles `Any` types as expected. Follow-up PR(s) will actually implement the functionality for the generated SDK.
=> AnyScalarIntegrationTest.kt added

buildSrc/src/main/java/com/google/firebase/gradle/plugins/semver/DeltaType.kt
The check fails if the `after` state is null. This cases only happens when the entry has been removed entirely, instead of only changed from static to non-static.
There are other tests that look for those changes, so it's safe to ignore it from the CHANGED_FROM_STATIC check.
=> Ignore removed entries in CHANGED_FROM_STATIC

firebase-vertexai/gradle.properties
This was missed on the last mergeback that included vertexAI. Version beta04 is already out
=> Bump latest released version of vertexai

firebase-functions/firebase-functions.gradle.kts
There's no need for functions to depend at a project level on the appcheck interop library.
=> Pin appcheck-interop dependency to latest released version

firebase-appdistribution-api/CHANGELOG.md, firebase-appdistribution/CHANGELOG.md, firebase-crashlytics-ndk/CHANGELOG.md
The next release of the NDK doesn't contain any new features, it only bumps the value to maintain parity with the crashlytics SDK.
Additional entries are for appdistribution and appdistribution-api.
=> Add entry in the changelog for next release

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerationConfig.kt
=> Fix typo in GenerationConfig.kt

buildSrc/src/main/java/com/google/firebase/gradle/plugins/semver/DeltaType.kt
The error message for classes made final has "abstract" instead of "final" on them.
=> Fix typo in class made final check in semver

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
Fix Javadoc for `isCrashlyticsCollectionEnabled()` in FirebaseCrashlytics
=> Fix Javadoc in FirebaseCrashlytics

firebase-storage/CHANGELOG.md, firebase-storage/src/main/java/com/google/firebase/storage/UploadTask.java
Fix issue https://github.com/firebase/firebase-android-sdk/issues/6214
=> Fix `putBytes()`API to use `maxUploadRetryTimeMillis` parameter 

build.gradle, firebase-vertexai/firebase-vertexai.gradle.kts, gradle/libs.versions.toml
A previous change, https://github.com/firebase/firebase-android-sdk/pull/6186, added the Kotlin serialization plugin to every single Gradle module; however, only one module actually used it. Moreover, it is becoming more conventional to define dependency versions in `gradle/libs.versions.toml`. This PR removes the global dependency on the Kotlin serialization plugin and, instead, moves the version into `gradle/libs.versions.toml`, and also modifies the dependency on the Kotlin JSON serialization library to use `gradle/libs.versions.toml`. This will make sure that every module uses the same version, which will become important once Data Connect, which also uses these libraries, is merged into main.
=> Move Kotlin serialization gradle plugin into libs.versions.toml

encoders/protoc-gen-firebase-encoders/protoc-gen-firebase-encoders.gradle, gradle/libs.versions.toml
This is a change that will be required once data connect is merged into main so that they share the same dependency versions.
=> protoc-gen-firebase-encoders.gradle: use libs.versions.toml

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/server/Types.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/PromptFeedback.kt, firebase-vertexai/src/test/java/com/google/firebase/vertexai/StreamingSnapshotTests.kt, firebase-vertexai/src/test/java/com/google/firebase/vertexai/UnarySnapshotTests.kt
=> Add support for blockReasonMessage 

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/client/Types.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionCallingConfig.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ToolConfig.kt, firebase-vertexai/src/test/java/com/google/firebase/vertexai/common/APIControllerTests.kt
A note about `@SerialName("allowed_function_names")`: This is not strictly necessary, the backend will parse it if it's camel case too. We should eventually remove all unnecessary `@SerialName` declarations, but for now, and to keep consistency, I'm adding it to this declaration.
=> Add support for allowed_function_names

firebase-vertexai/firebase-vertexai.gradle.kts
=> fix(vertexai): export the firebase-common dependency

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerationConfig.kt
Since the constructor is private, and the builder sets it to null if missing, this declaration is actually redundant.
b/368368914
=> Remove redundant null declaration

firebase-crashlytics/CHANGELOG.md, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsUncaughtExceptionHandler.java
Fixed exception propagation in the case of no default uncaught exception handler. Exit code 1 is what the default java uncaught exception handler exits with.
=> Fixed exception propagation on null default uncaught exception handler

firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigComponentTest.java
The flaky test is: registerRolloutsStateSubscriber_firebaseNamespace_callsSubscriptionHandler
The flaky failure is due to a race condition, and the error looks like this:
```
Argument passed to verify() is of type RolloutsStateSubscriptionsHandler and is not a mock!
Make sure you place the parenthesis correctly!
See the examples of correct verifications:
verify(mock).someMethod();
verify(mock, times(10)).someMethod();
verify(mock, atLeastOnce()).someMethod();
org.mockito.exceptions.misusing.NotAMockException: 
Argument passed to verify() is of type RolloutsStateSubscriptionsHandler and is not a mock!
at com.google.firebase.remoteconfig.RemoteConfigComponentTest.registerRolloutsStateSubscriber_firebaseNamespace_callsSubscriptionHandler(RemoteConfigComponentTest.java:194)
```
=> RemoteConfigComponentTest.java: fix flaky test

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/server/Types.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/shared/Types.kt, firebase-vertexai/src/test/java/com/google/firebase/vertexai/common/UnarySnapshotTests.kt
It's only necessary on enums we receive from the backend, not from the ones we send.
=> Add missing `FirstOrdinalSerializer` to enum

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionDeclaration.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Schema.kt
By creating the schema earlier, any errors when declaring the schema will be caught at the declaration site, which makes debugging much easier.
=> Create the function declaration schema at construction time

firebase-dataconnect/CHANGELOG.md, firebase-dataconnect/emulator/dataconnect/connector/alltypes/alltypes_ops.gql, firebase-dataconnect/emulator/dataconnect/schema/alltypes_schema.gql, firebase-dataconnect/src/androidTest/kotlin/com/google/firebase/dataconnect/OrderDirectionIntegrationTest.kt, firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/util/ProtoStructDecoder.kt, firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/util/ProtoStructEncoder.kt, firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/Arbs.kt, firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/TestUtils.kt
Add `OrderDirection` enum support.
For example:
```
query GetAllFoos($dir: OrderDirection) {
foos(orderBy: { bar: $dir }) {
bar
}
}
```
A follow-up PR, https://github.com/firebase/firebase-android-sdk/pull/6308, will add generated SDK tests once the data connect toolkit is released with OrderDirection support in Android codegen.
Googlers see b/369348331 for details.
=> Add OrderDirection support

firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigCacheClientTest.java
Fix a race condition in `ConfigCacheClientTest.java` causing the test `getBlocking_hasNoCachedValueAndFileReadTimesOut_returnsNull` to flakily fail.
The failure looks like this:
```
value of: getBlocking(...)
expected: null
but was : {"configs_key":{"long_param":"1L","string_param":"string_value"},"fetch_time_key":1000,"abt_experiments_key":[],"personalization_metadata_key":{},"template_version_number_key":0,"rollout_metadata_key":[]}
```
The reason for the flake is that sometimes the thread scheduler will run the code that calls `ConfigStorageClient.read()` _before_ `getBlocking()` returns; therefore, `getBlocking()` would return a non-null object in that case. The fix was to cause the mocked `read()` method to block indefinitely, making it _impossible_ for the read _not_ to timeout. …
=> ConfigCacheClientTest.java: fix flaky test due to race condition

firebase-dataconnect/gradleplugin/gradle/libs.versions.toml, firebase-dataconnect/gradleplugin/plugin/build.gradle.kts, firebase-dataconnect/gradleplugin/settings.gradle.kts, gradle/libs.versions.toml
The gradle plugin for Data Connect (located in `firebase-dataconnect/gradleplugin`) had its own, isolated `libs.verisons.toml` which duplicated the Kotlin version. This PR changes it to instead use the Kotlin version from the _main_ `libs.verisons.toml`, in `gradle/libs.verisons.toml`.
Future PRs will eventually move _all_ of the dependencies defined in `firebase-dataconnect/gradleplugin/gradle/libs.versions.toml` into `gradle/libs.verisons.toml`.
=> dataconnect: gradleplugin now gets kotlin version from the main libs.versions.toml

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt, firebase-vertexai/src/test/java/com/google/firebase/vertexai/UnarySnapshotTests.kt
Their *part counter parts will now wrap them, instead of exposing the underlying structure directly.
=> Introduce `FunctionCall` and `FunctionResponse` types

firebase-dataconnect/gradleplugin/plugin/src/main/kotlin/com/google/firebase/dataconnect/gradle/plugin/DataConnectRunEmulatorTask.kt
The `schemaExtensionsOutputEnabled` knob of the Data Connect gradle plugin was always meant to be optional; however, it was accidentally made to be required, resulting in the following unnecessary error if it was not explicitly specified:
```
A problem was found with the configuration of task ':firebase-dataconnect:connectors:runDebugDataConnectEmulator' (type 'DataConnectRunEmulatorTask').
- In plugin 'com.google.firebase.dataconnect.gradle.plugin.DataConnectGradlePlugin$Inject' type 'com.google.firebase.dataconnect.gradle.plugin.DataConnectRunEmulatorTask' property 'schemaExtensionsOutputEnabled' doesn't have a configured value.
Reason: This property isn't marked as optional and no value has been configured.
Possible solutions:
1. Assign a value to 'schemaExtensionsOutputEnabled'.
2. …
```
=> dataconnect: fix gradle plugin to gracefully handle schemaExtensionsOutputEnabled not being explicitly specified

build.gradle, firebase-dataconnect/gradleplugin/gradle/libs.versions.toml, firebase-dataconnect/gradleplugin/plugin/build.gradle.kts, gradle/libs.versions.toml
Specifying the spotless version centrally in gradle/libs.versions.toml avoids duplicating the version number in multiple places.
=> Use gradle/libs.versions.toml to specify the Spotless version

firebase-dataconnect/gradleplugin/plugin/build.gradle.kts, firebase-dataconnect/gradleplugin/plugin/src/main/kotlin/com/google/firebase/dataconnect/gradle/plugin/DataConnectExecutable.kt, firebase-dataconnect/gradleplugin/plugin/src/main/resources/com/google/firebase/dataconnect/gradle/plugin/DataConnectExecutableVersions.json
Previously, the version information about data connect toolkit executables was hardcoded in Kotlin.
=> dataconnect: gradle plugin modified to load executable versions from a json file

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
Update the Crashlytics Javadoc to add appropriate `link` and `code` tags.
=> Add code and link tags to Crashlytics Javadoc

firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/util/ProtoUtil.kt, firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/ProtoStructDecoderUnitTest.kt, firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/ProtoStructEncoderUnitTest.kt, firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/serializers/TimestampSerializerUnitTest.kt, firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/ProtoTestUtils.kt, firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/TestUtils.kt, firebase-dataconnect/testutil/testutil.gradle.kts
The main changes are replacing Truth and assertThrows with kotest assertions (https://kotest.io/docs/assertions/assertions.html) and using kotest property testing (https://kotest.io/docs/proptest/property-based-testing.html) instead of hand-picking example values. Future PRs will modernize other tests.
=> dataconnect: modernize tests in ProtoStructDecoderUnitTest.kt, ProtoStructEncoderUnitTest.kt, and TimestampSerializerUnitTest.kt

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Schema.kt
`sealed` classes have nice properties but they don't play well with API backward compatibility. Adding a new class to a `sealed` class set is a breaking change since they require exhaustive switching.
=> Use abstract class instead of sealed classes for StringFormat

.github/workflows/build-src-check.yml, .github/workflows/ci_tests.yml
Per [b/370923997](https://b.corp.google.com/issues/370923997),
This updates our `publish-unit-test-result` action usage to `2.9.0` instead of the old versions we were using. This should help avoid the secondary rate limits we've been hitting as of late.
=> Update publish unit test results

firebase-crashlytics-ndk/gradle.properties
We forgot to bump the Crashlytics NDK version in the mergeback, this fixes that.
=> Mergeback Crashlytics NDK

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Content.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt
The order of the parameters should be consistent between them, and it should be (url/byte, mime-type).
=> Change InlineDataPart to match ImagePart

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Content.kt, firebase-vertexai/src/test/java/com/google/firebase/vertexai/GenerativeModelTesting.kt
Although the model has been ignoring the role in the content declared as part of "system_instruction", the correct value should be "system"
=> Ensure system instruction content has system role

firebase-vertexai/CHANGELOG.md
It includes the full list of changes since the last release.
=> Update vertexai changelog file

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Schema.kt
Adding the overloads is necessary to ensure the devEx in Java is better, and no unnecessary parameters are passed to the Schema factory methods.
=> Add @JvmOverloads to schema declarations

firebase-vertexai/CHANGELOG.md, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt, firebase-vertexai/src/test/java/com/google/firebase/vertexai/UnarySnapshotTests.kt
This better aligns FunctionCallParts with the other Parts.
=> Revert "Introduce FunctionCall and FunctionResponse types (#6311)" 

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/Chat.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Content.kt
The order of the arguments was changed from (mimeType, bytes) to (bytes, mimeType).
=> Update inlineData Java specific API to match Kotlin

firebase-dataconnect/connectors/connectors.gradle.kts, firebase-dataconnect/gradleplugin/plugin/src/main/kotlin/com/google/firebase/dataconnect/gradle/plugin/UpdateDataConnectExecutableVersionsTask.kt, firebase-dataconnect/gradleplugin/plugin/src/main/kotlin/com/google/firebase/dataconnect/gradle/plugin/Util.kt
This PR adds a task that can be used to update the DataConnectExecutableVersions.json file with versions of the data connect toolkit executable.
=> dataconnect: add firebase-dataconnect:connectors:updateJson task

firebase-vertexai/CHANGELOG.md, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/client/Types.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerateContentResponse.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ToolConfig.kt
There's no need for the response accessor, as under normal circunstances there's no need to have easy access to the [FunctionResponsePart] the app adds to a prompt.
Additionally, to make evolving the API easier and backward compatible, made `functionCallingConfig` parameter nullable in `ToolConfig`.
=> Remove `functionResponse` accessor, and mark `functionCallingConfig` nullable

firebase-crashlytics-ndk/CHANGELOG.md, firebase-messaging-directboot/CHANGELOG.md, firebase-sessions/CHANGELOG.md, transport/transport-api/CHANGELOG.md
Per [b/373458620](https://b.corp.google.com/issues/373458620),
This PR adds changelogs that were missing from #6343; due to library groups.
=> Add missing changelogs

encoders/firebase-encoders-proto/CHANGELOG.md, firebase-config/CHANGELOG.md, firebase-crashlytics/CHANGELOG.md, firebase-dataconnect/CHANGELOG.md, firebase-dataconnect/firebase-dataconnect.gradle.kts, firebase-firestore/CHANGELOG.md, firebase-inappmessaging-display/CHANGELOG.md, firebase-inappmessaging/CHANGELOG.md, firebase-messaging/CHANGELOG.md, firebase-ml-modeldownloader/CHANGELOG.md, firebase-perf/CHANGELOG.md, firebase-vertexai/CHANGELOG.md, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/java/ChatFutures.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/java/GenerativeModelFutures.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Content.kt, transport/transport-backend-cct/CHANGELOG.md, transport/transport-runtime/CHANGELOG.md
Per [b/373637986](https://b.corp.google.com/issues/373637986),
This fixes the release notes configuration for the `data-connect` SDK, as they seemed to be incorrect.
This PR also fixes the following:
- [b/373639079](https://b.corp.google.com/issues/373639079) -> Refactor github vuln links to `nist.gov`
- [b/374115995](https://b.corp.google.com/issues/374115995) -> Fix VertexAI Javadocs
=> Fix release notes + dataconnect config

build.gradle, firebase-annotations/firebase-annotations.gradle.kts, firebase-common/data-collection-tests/data-collection-tests.gradle.kts, firebase-common/firebase-common.gradle.kts, firebase-common/ktx/ktx.gradle.kts, firebase-components/firebase-components.gradle.kts, firebase-components/firebase-dynamic-module-support/firebase-dynamic-module-support.gradle.kts, firebase-config-interop/firebase-config-interop.gradle.kts, firebase-config/firebase-config.gradle.kts, firebase-config/test-app/test-app.gradle.kts, firebase-database-collection/firebase-database-collection.gradle.kts, firebase-database/firebase-database.gradle.kts, firebase-database/ktx/ktx.gradle.kts, firebase-dataconnect/androidTestutil/androidTestutil.gradle.kts, firebase-dataconnect/connectors/connectors.gradle.kts, firebase-dataconnect/firebase-dataconnect.gradle.kts, firebase-dataconnect/testutil/testutil.gradle.kts, firebase-functions/firebase-functions.gradle.kts, firebase-functions/ktx/ktx.gradle.kts, firebase-sessions/firebase-sessions.gradle.kts, firebase-sessions/test-app/test-app.gradle.kts, firebase-vertexai/firebase-vertexai.gradle.kts, integ-testing/integ-testing.gradle.kts, tools/lint/lint.gradle.kts
The more we cover by the formatter the better.
That being said, support for groovy is broken. I hit https://github.com/diffplug/spotless/issues/1922 when trying to use groovyGradle formatting.
=> Add spotless support for *.gradle.kts files

firebase-vertexai/CHANGELOG.md, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
The header for authenticated request from vertex was using an invalid authorization value
=> Fix vertexAI authorization header

.github/workflows/api-information.yml, .github/workflows/copyright-check.yml, .github/workflows/fireci.yml, .github/workflows/fireperf-e2e.yml, .github/workflows/health-metrics.yml, .github/workflows/make-bom.yml, .github/workflows/release-note-changes.yml, .github/workflows/update-cpp-sdk-on-release.yml
Instead of using the tagged version, the change moves to the actual commit has instead.
=> Bump python-setup version to v5.2

firebase-vertexai/CHANGELOG.md, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
The app check backend can differentiate between apps that do not use appcheck at all, and those sending invalid data, by using a special placeholder token when errors happen. We were previously not including the token value in error cases, but we should.
=> [vertexai] Include appcheck token unconditionally

firebase-dataconnect/connectors/connectors.gradle.kts, firebase-dataconnect/testutil/testutil.gradle.kts, gradle/libs.versions.toml
Add "ThreeTenAbp" to `libs.versions.toml`. This library is a backport of the new JDK8 date and time classes in `java.time` to JDK7. Although we should definitely NOT use this library in production, it's quite useful in unit and integration tests to perform complicated date and time mathematics. Once the minSdkVersion is changed to 26 or later, we can drop this dependency and simply use the java.time classes from the standard library.
Although this PR does not contain any actual uses of the library, a follow-up PR will use it, and I wanted to separate the global change of modifying `libs.versions.toml` from the test code that makes use of it because changing `libs.versions.toml` has a project-wide blast radius.
For details, see https://www.threeten.org/threetenbp/ and …
=> libs.versions.toml: add ThreeTenAbp (backport of java.time for Android)

firebase-vertexai/CHANGELOG.md, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Schema.kt
The improvements include:
- Clarify that `integer` and `float` types are hints to the model, and the returned data could potentially overflow the respective native types.
- Include missing parameters for some of the functions.
- Add examples for `enumerations` and `obj`.
=> Improved refdocs for Schema 

firebase-dataconnect/firebase-dataconnect.gradle.kts, gradle/libs.versions.toml
Add "kotlinx.datetime" to `libs.versions.toml`. Although this PR does not contain any actual uses of the library, a follow-up PR will use it, and I wanted to separate the global change of modifying `libs.versions.toml` from the code that makes use of it because changing `libs.versions.toml` has a project-wide blast radius.
See https://github.com/Kotlin/kotlinx-datetime and https://kotlinlang.org/api/kotlinx-datetime/ for more details about the kotlinx.datetime library.
=> libs.versions.toml: add kotlinx-datetime

firebase-dataconnect/connectors/connectors.gradle.kts
The `updateJson` custom task in `firebase-dataconnect/connectors/connectors.gradle.kts` would unnecessarily throw an exception if neither the `version` nor `versions` property was specified. This was fine if explicitly invoking the task; however, the task would fail to configure if it is merely being _created_ but not executed, such as when running `./gradlew :firebase-dataconnect:connectors:tasks`:
```
Execution failed for task ':firebase-dataconnect:connectors:tasks'.
> Could not create task ':firebase-dataconnect:connectors:updateJson'.
> bm6d5ezxzd 'version' or 'versions' property must be specified
```
This PR downgrades the error to a warning, and only emits the warning when the task is executed. The other properties that get interrogated by the `updateJson` task were also improved …
=> dataconnect: connectors.gradle.kts: fix unwarranted error from updateJson task during configure time

firebase-functions/firebase-functions.gradle.kts
Old declaration is deprecated. The generated error message is
xx-xx: 'annotationProcessor' dependencies won't be recognized as kapt annotation processors. Please change the configuration name to 'kapt' for these artifacts: 'com.google.auto.value:auto-value:1.10.1'.
=> Replace auto-value dependency declaration with kapt

firebase-messaging/CHANGELOG.md, firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessaging.java, firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessagingService.java, firebase-messaging/src/main/java/com/google/firebase/messaging/RemoteMessage.java
* Also removed references to upstream in documentation.
=> Deprecate additional FCM upstream messaging methods.

firebase-vertexai/CHANGELOG.md, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/APIController.kt, firebase-vertexai/src/test/java/com/google/firebase/vertexai/GenerativeModelTesting.kt
If an invalid location is used when creating the `FirebaseVertexAI`
object, all requests will fail. The error returned is 404 and HTML
content. The message as-is is not easy to read.
The new messaging points to the most likely reason for the
404 (invalid location).
=> Improve error message for invalid locations

firebase-dataconnect/CHANGELOG.md, firebase-dataconnect/api.txt, firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/LocalDate.kt, firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/serializers/LocalDateSerializer.kt
This PR adds the Firebase Data Connect classes `LocalDate` and `LocalDateSerializer`, which will replace `java.util.Date`. Tests will be added in a follow-up PR due to a dependency on the data connect emulator.
These changes will be required by v1.6.1 or later of the Firebase Data Connect emulator code generation.
=> dataconnect: LocalDate and LocalDateSerializer added

firebase-common/firebase-common.gradle.kts, firebase-components/firebase-components.gradle.kts, firebase-components/firebase-dynamic-module-support/firebase-dynamic-module-support.gradle.kts, firebase-config-interop/firebase-config-interop.gradle.kts, firebase-config/firebase-config.gradle.kts, firebase-database-collection/firebase-database-collection.gradle.kts, firebase-database/firebase-database.gradle.kts, firebase-dataconnect/firebase-dataconnect.gradle.kts, firebase-functions/firebase-functions.gradle.kts, firebase-sessions/firebase-sessions.gradle.kts, firebase-vertexai/firebase-vertexai.gradle.kts
`targetSdk` has been moved out of `defaultConfig` for libraries, and should be declared inside `testOptions` and/or `lint`
=> Replaced defaultConfig.targetSdk with testOptions.targetSdk

firebase-dataconnect/src/androidTest/kotlin/com/google/firebase/dataconnect/GrpcMetadataIntegrationTest.kt, firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/DataConnectCredentialsTokenManager.kt, firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/FirebaseDataConnectImpl.kt, firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/FirebaseDataConnectImplUnitTest.kt, firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/CleanupsRule.kt
This PR fixes a race condition in `GrpcMetadataIntegrationTest.kt` where the query/mutation may be sent before the Auth and/or AppCheck provider was registered, which is done asynchronously. This race condition resulted in flaky tests. We _may_ want to expose this functionality to customers if they run into similar issues.
For the record, the test case failures look like this:
```
failed: executeQueryShouldSendAppCheckMetadataWhenAppCheckIsEnabled(com.google.firebase.dataconnect.GrpcMetadataIntegrationTest)
java.lang.AssertionError: key=Key{name='x-firebase-appcheck'}, metadata=Metadata(user-agent=grpc-java-okhttp/1.62.2,content-type=application/grpc,te=trailers,x-goog-request-params=location=TestLocationr24xs74t3s&frontend=data,x-goog-api-client=gl-kotlin/1.8.22 gl-android/35 …
```
=> dataconnect: GrpcMetadataIntegrationTest.kt: Fix race condition waiting for auth/appcheck to be ready

firebase-dataconnect/androidTestutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/TestFirebaseAppFactory.kt, firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/DataConnectCredentialsTokenManager.kt, firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/DataConnectAuthUnitTest.kt
This PR fixes a race condition in the Data Connect tests where if a `FirebaseApp` is deleted very shortly after creating it then an IllegalStateException can be thrown, crashing the test app entirely, resulting in a flaky test.
The "fix" is really a "workaround", in that it waits for 1 second before calling `FirebaseApp.delete()` to minimize the chances that the FirebaseAuth worker thread will try to access the deleted FirebaseApp instance. Googlers see b/378116261 for details.
The crash fixed by this PR looks like this:
```
FATAL EXCEPTION: TokenRefresher
Process: com.google.firebase.dataconnect.connectors.test, PID: 7058
java.lang.IllegalStateException: FirebaseApp with name test-app-nwdpj3757g doesn't exist. Available app names: [DEFAULT]
at …
```
=> dataconnect: TestFirebaseAppFactory.kt: work around IllegalStateException in tests by adding a delay before calling FirebaseApp.delete()

firebase-dataconnect/src/androidTest/kotlin/com/google/firebase/dataconnect/AuthIntegrationTest.kt, firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/DataConnectAppCheck.kt, firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/DataConnectAuth.kt, firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/DataConnectCredentialsTokenManager.kt, firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/FirebaseDataConnectImpl.kt, firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/DataConnectAuthUnitTest.kt
This PR changes the initialization of Data Conect's "Auth" and "AppCheck" mechanisms to be more synchronous. Not only does this fix a bug introduced a few commits ago by #6446 but also simplifies the logic and reduces the amount of non-determinism.
The race condition fixed by this PR manifested only on on my MacBook laptop (not on my Linux workstation) and is simply due to arbitrary thread scheduling differences. One such test failure looked like this:
```
failed: collect_gets_notified_of_per_data_deserializer_successes(com.google.firebase.dataconnect.QuerySubscriptionIntegrationTest)
java.lang.IllegalStateException: getToken() cannot be called before initialize()
at com.google.firebase.dataconnect.core.DataConnectCredentialsTokenManager.getToken(DataConnectCredentialsTokenManager.kt:322) …
```
=> dataconnect: DataConnectCredentialsTokenManager: initialize synchronously to fix race condition

firebase-perf/src/main/java/com/google/firebase/perf/metrics/AppStartTrace.java
=> Add null check rootView to fix issue #6367

firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/util/NullableReference.kt
This is an internal-only improvement and has no effects on customers.
=> dataconnect: relax variance of the NullableReference type parameter to covariant (was invariant)

firebase-dataconnect/scripts/compile_kotlin.sh, firebase-dataconnect/scripts/emulator_run.sh, firebase-dataconnect/scripts/generate_data_connect_sources.sh, firebase-dataconnect/scripts/run_all_tests.sh, firebase-dataconnect/scripts/run_integration_tests.sh, firebase-dataconnect/scripts/spotlessApply.sh
These script updates merely benefit data connect sdk developers; there is no customer impact whatsoever.
=> dataconnect: internal convenience script updates

firebase-dataconnect/connectors/src/androidTest/kotlin/com/google/firebase/dataconnect/connectors/demo/DateScalarIntegrationTest.kt, firebase-dataconnect/connectors/src/androidTest/kotlin/com/google/firebase/dataconnect/connectors/demo/KeyVariablesIntegrationTest.kt, firebase-dataconnect/connectors/src/androidTest/kotlin/com/google/firebase/dataconnect/connectors/demo/ListVariablesAndDataIntegrationTest.kt, firebase-dataconnect/gradleplugin/plugin/src/main/resources/com/google/firebase/dataconnect/gradle/plugin/DataConnectExecutableVersions.json, firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/DateTimeTestUtils.kt, firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/property/arbitrary/dates.kt
The update to CLI version 1.7.0 causes `com.google.firebase.dataconnect.LocalDate` to be used instead of `java.util.Date` in generated code. As a result, some of the integration tests needed to be fixed to compile and pass as part of this PR.
=> dataconnect: DataConnectExecutableVersions.json updated with version 1.7.0

firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/FirebaseDataConnect.kt
During the "alpha" release cycle of Data Connect, the release notes were published in the kdoc comments of the `FirebaseDataConnect` class. Now that Data Connect has been in "beta" for 1.5 months, these "alpha" release notes are no longer relevant because the release notes of the Data Connect SDK are now published, along with the release notes of other Firebase products, at https://firebase.google.com/support/release-notes/android. This PR removes these obsolete "alpha" release notes.
=> dataconnect: Remove obsolete "alpha" release notes from the kdoc comments of FirebaseDataConnect

firebase-dataconnect/connectors/src/androidTest/kotlin/com/google/firebase/dataconnect/connectors/demo/DateScalarIntegrationTest.kt, firebase-dataconnect/emulator/dataconnect/connector/demo/demo_ops.gql, firebase-dataconnect/emulator/dataconnect/schema/demo_schema.gql, firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/property/arbitrary/dates.kt
This PR rewrites `DateScalarIntegrationTest.kt` to use the new date-testing facilities added by the unit and integration tests for the new `LocalDate` class.
=> dataconnect: DateScalarIntegrationTest.kt rewritten

firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/property/arbitrary/arbs.kt
This PR only affects the unit and integration tests; nothing in this PR affects production behavior.
=> dataconnect: tests: increase tag size from 20 to 50 characters, to reduce the chance of collisions

ci/fireci/fireciplugins/macrobenchmark/commands.py
There are some scenarios in which we can't find the valid output for a given project. We need to log and continue instead of crashing.
=> Handle null case in macrobenchmark

ci/fireci/fireciplugins/macrobenchmark/run/test_project_builder.py, health-metrics/benchmark/template/app/build.gradle.mustache, health-metrics/benchmark/template/app/src/main/AndroidManifest.xml, health-metrics/benchmark/template/build.gradle, health-metrics/benchmark/template/macrobenchmark/build.gradle, health-metrics/benchmark/template/macrobenchmark/src/main/AndroidManifest.xml
The old version stop working due to a combination of gradle version and outdated deps
=> Update benchmark app

.github/workflows/build-src-check.yml, .github/workflows/changelog.yml, .github/workflows/fireci.yml, .github/workflows/update-cpp-sdk-on-release.yml
=> Improve github action naming

firebase-config/ktx/src/test/kotlin/com/google/firebase/remoteconfig/TestConstructorUtil.kt, firebase-config/ktx/src/test/kotlin/com/google/firebase/remoteconfig/ktx/RemoteConfigTests.kt, firebase-config/src/androidTest/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigIntegrationTest.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandler.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHandler.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigSharedPrefsClient.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/FirebaseRemoteConfigInfoImpl.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigComponentTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigTests.kt, firebase-config/src/test/java/com/google/firebase/remoteconfig/TestConstructorUtil.kt, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandlerTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigSharedPrefsClientTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/ktx/RemoteConfigTests.kt
Rename ConfigMetadataClient to ConfigSharedPrefsClient
Reflects expanded functionality to store both metadata and custom signals in shared preferences.
=> Rename ConfigMetadataClient to ConfigSharedPrefsClient

firebase-crashlytics/CHANGELOG.md, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/CrashlyticsRegistrar.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
To prevent unwanted executions in the main thread, callbacks should specify the executor explicitly.
=> [crashlytics] Specify the executor when calling onFailureListener

firebase-config/ktx/src/test/kotlin/com/google/firebase/remoteconfig/TestConstructorUtil.kt, firebase-config/ktx/src/test/kotlin/com/google/firebase/remoteconfig/ktx/RemoteConfigTests.kt, firebase-config/src/androidTest/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigIntegrationTest.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandler.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHandler.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigSharedPrefsClient.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/FirebaseRemoteConfigInfoImpl.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigComponentTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigTests.kt, firebase-config/src/test/java/com/google/firebase/remoteconfig/TestConstructorUtil.kt, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandlerTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigSharedPrefsClientTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/ktx/RemoteConfigTests.kt
Reflects expanded functionality to store both metadata and custom signals in shared preferences.
=> Rename ConfigMetadataClient to ConfigSharedPrefsClient 

firebase-common/data-collection-tests/data-collection-tests.gradle.kts, gradle/libs.versions.toml
The dependencies were pulling kotlin stdlib versions that were breaking version alignment. 
The solution is to depend on the BOM as decribed in https://kotlinlang.org/docs/whatsnew18.html#usage-of-the-latest-kotlin-stdlib-version-in-transitive-dependencies
=> Fix data-collection-tests

firebase-crashlytics/CHANGELOG.md, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/CrashlyticsTests.kt, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/metadata/MetaDataStoreTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.kt, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/KeyValueBuilder.kt, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
Fixed inefficiency in the Kotlin `FirebaseCrashlytics.setCustomKeys` extension.
The old implementation called `setCustomKey` for every key/value pair, which serializes to disk, and is not an intuitive behaviour for customers. This now calls `setCustomKeys` once with the entire built map.
This proxies to the existing Java `CustomKeysAndValues.Builder` but gives nice Kotlin syntax. The old class had a public ctor, I plan to make this internal since customers shouldn't instantiate this class directly. This is done in a way to not break the api, even though the api is internal.
pair=tejasd
=> Fix inefficiency in the setCustomKeys Kotlin extension

firebase-functions/CHANGELOG.md, firebase-functions/src/main/java/com/google/firebase/functions/FirebaseContextProvider.kt, firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.kt, firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctionsException.kt, firebase-functions/src/main/java/com/google/firebase/functions/FunctionsRegistrar.kt, firebase-functions/src/main/java/com/google/firebase/functions/Serializer.kt, firebase-functions/src/test/java/com/google/firebase/functions/FunctionsTests.kt
Improvements include:
- Make overriden arguments have the same name as the original ones
- Inline variable declarations
- Remove unused lambda bodies
=> Address Functions compiler warnings

tools/lint/src/main/kotlin/FirebaseAppGetDetector.kt
The override for `visitMethodCall` was using a different name for the `UCallExpression` which could cause an issue if called by name
=> Address warning in FirebaseAppGetDetector

firebase-vertexai/src/test/java/com/google/firebase/vertexai/common/UnarySnapshotTests.kt, firebase-vertexai/src/test/java/com/google/firebase/vertexai/common/util/tests.kt
This reduces the noise we are seeing in our builds
=> Add missing experimentalApi annotations to vertex tests

firebase-crashlytics/CHANGELOG.md, firebase-crashlytics/api.txt, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/EventMetadata.kt, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/KeysMap.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/UserMetadata.java
This PR adds a method `public void recordException(@NonNull Throwable throwable, CustomKeysAndValues keysAndValues)` as an overload to the existing `recordException` method in Crashlytics to allow attaching additional custom keys to the specific event.
Details:
- The total number of custom key/value pairs are still restricted to 64
- App level custom keys take precedence over event specific custom keys for the 64 key/value pair limit
- The values of event keys override the value of global custom keys if they're identical
Additionally:
- Creates a new EventMetadata class to represent `sessionId` and `timestamp` attached to non fatal events.
=> Add an overload to FirebaseCrashlytics.recordException to attach additional custom key value pairs

.github/workflows/dataconnect_demo_app.yml, firebase-dataconnect/demo/.gitignore, firebase-dataconnect/demo/build.gradle.kts, firebase-dataconnect/demo/firebase/dataconnect/connector/connector.yaml
Added GitHub actions to continuously test the firebase-dataconnect demo app that was recently added in #6561. Also tweak the gradle build script to better support cachability.
=> dataconnect: .github/workflows/dataconnect_demo_app.yml added

firebase-dataconnect/demo/build.gradle.kts
`firebase-dataconnect/demo/build.gradle.kts`: make DataConnectGenerateSourcesTask cacheable to demonstrate making a task cacheable, and, in theory, could speed up incremental builds.
=> dataconnect: demo: make codegen gradle task cacheable

firebase-dataconnect/gradleplugin/plugin/src/main/resources/com/google/firebase/dataconnect/gradle/plugin/DataConnectExecutableVersions.json
DataConnectExecutableVersions.json updated with versions 1.7.1, 1.7.2, 1.7.3, and 1.7.4 by running:
```
./gradlew -PdefaultVersion=1.7.4 -Pversions=1.7.1,1.7.2,1.7.3,1.7.4 :firebase-dataconnect:connectors:updateJson
```
=> dataconnect: DataConnectExecutableVersions.json updated with versions 1.7.1, 1.7.2, 1.7.3, and 1.7.4

appcheck/firebase-appcheck-debug/firebase-appcheck-debug.gradle
`firebase-appcheck-debug.gradle`: add `implementation platform(libs.kotlin.bom)` to fix duplicate classes build error.
This PR is based on https://github.com/firebase/firebase-android-sdk/pull/6540.
The build error looked like this:
```
./gradlew :appcheck:firebase-appcheck-debug:deviceCheck
...
Execution failed for task ':appcheck:firebase-appcheck-debug:checkDebugAndroidTestDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
> Duplicate class kotlin.collections.jdk8.CollectionsJDK8Kt found in modules kotlin-stdlib-1.8.22 (org.jetbrains.kotlin:kotlin-stdlib:1.8.22) and kotlin-stdlib-jdk8-1.6.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21)
Duplicate class kotlin.internal.jdk7.JDK7PlatformImplementations found in …
```
=> Fix "duplicate class" errors when running `./gradlew :appcheck:firebase-appcheck-debug:deviceCheck`

.github/workflows/dataconnect_demo_app.yml, firebase-dataconnect/demo/firebase/dataconnect/connector/operations.gql
This PR includes a workaround for b/382688278 where compiling the generated Kotlin code may result in the following error:
> `Serializer has not been found for type 'java.util.UUID'. To use context serializer as fallback, explicitly annotate type or property with @Contextual`
=> dataconnect: demo: upgrade firebase-tools to v13.28.0

firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandler.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandlerTest.java, firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClientTest.java
When we update custom signals using setCustomSignals, the latest custom signals are not retrieved in the subsequent fetch. Currently, we are required to reload the app to fetch them.
Link to the bug: [Fetch uses stale custom signal values](https://b.corp.google.com/issues/381353888)
=> Update fetch to utilize latest custom signals

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/BasePath.java
Document ID supports strings and well as long integers in the format of  "__id<Long>__" . When sorting documents by document ID, it should be sorted in the following order:
1. Long (numeric order)
2. String (lexicographic order)
=> Fix: sort document reference by long type id

firebase-firestore/CHANGELOG.md, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/BasePath.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/Values.java, firebase-firestore/src/main/java/com/google/firebase/firestore/util/Util.java
Strings should be sorted in UTF-8 encoded byte order. Public document: https://cloud.google.com/firestore/docs/concepts/data-types#data_types
SDK sorts strings using built in comparator method, which sorts lexicographically, and leads to mismatch between server and sdk when special characters are present. This PR fixes the string order mismatches on document field, map key, and document key.
=> FIX: sort strings in UTF-8 encoded byte order

firebase-dataconnect/gradleplugin/plugin/src/main/resources/com/google/firebase/dataconnect/gradle/plugin/DataConnectExecutableVersions.json, firebase-dataconnect/scripts/missingversions.py
DataConnectExecutableVersions.json updated with version 1.7.5 by running:
```
./gradlew :firebase-dataconnect:connectors:updateJson -Pversions=1.7.5 -PdefaultVersion=1.7.5
```
=> dataconnect: DataConnectExecutableVersions.json updated with version 1.7.5

firebase-vertexai/README.md
We have been using the spotless plugin for a while already.
=> Update code formatting command in vertex's README

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt
Empty text parts go from a nuance when processed, to an exception when send to the backend. To prevent this issue, we are dropping them when parsing the response from the server.
=> Drop empty text parts when parsing the model's response

firebase-vertexai/src/test/java/com/google/firebase/vertexai/UnarySnapshotTests.kt, firebase-vertexai/update_responses.sh
We've updated from version 3.* to 5.*. Test were added were necessary to match the coverage in the iOS repo.
A few changes (v5.1 and v5.2) don't have tests covering the new files yet
=> Update the vertex golden file version being pulled

.github/workflows/create_releases.yml
The old version was failing to succeed, this version was tested and works
=> Update create pull request version

firebase-firestore/CHANGELOG.md, firebase-vertexai/CHANGELOG.md
This updates the changelog entries that had their contents changed in the m150 CL.
=> Update changelogs for m150

.github/workflows/dataconnect.yml
This PR fixes an issue where the GitHub Actions for the Data Connect integration tests would not actually upload the log files when the tests failed. This made it nearly impossible to debug test failures. This PR fixes it by ensuring that log files are uploaded even when the test fails.
=> dataconnect.yml: ensure that test logs are uploaded even when the tests fail

.github/workflows/make-bom.yml, plugins/src/main/java/com/google/firebase/gradle/bomgenerator/GenerateBomReleaseNotesTask.kt, plugins/src/main/java/com/google/firebase/gradle/bomgenerator/GenerateBomTask.kt, plugins/src/main/java/com/google/firebase/gradle/plugins/KotlinExtensions.kt, plugins/src/main/java/com/google/firebase/gradle/plugins/ModuleVersion.kt, plugins/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt, plugins/src/main/java/com/google/firebase/gradle/plugins/datamodels/PomElement.kt, plugins/src/test/kotlin/com/google/firebase/gradle/plugins/GenerateBomReleaseNotesTests.kt, plugins/src/test/kotlin/com/google/firebase/gradle/plugins/GenerateBomTests.kt, plugins/src/test/kotlin/com/google/firebase/gradle/plugins/ModuleVersionTests.kt
Per [b/394908865](https://b.corp.google.com/issues/394908865),
This fixes an issue where `ModuleVersion.bump()` was not properly resetting the smaller version types. Additionally, this fixes some other minor issues with bom generation.
Namely, this PR also fixes:
- [b/394908773](https://b.corp.google.com/issues/394908773) -> Fix bom release note ordering
- [b/394909103](https://b.corp.google.com/issues/394909103) -> Separate published bom artifacts
=> Fix ModuleVersion bumping

firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerformance.java, firebase-perf/src/main/java/com/google/firebase/perf/session/SessionManager.java, firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/CpuGaugeCollector.java, firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/GaugeManager.java, firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/GaugeMetadataManager.java, firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/MemoryGaugeCollector.java, firebase-perf/src/test/java/com/google/firebase/perf/session/SessionManagerTest.java, firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/GaugeMetadataManagerTest.java
Based on the behaviour of AQS w/ Fireperf, an AQS session isn't available when (currently) logging gauge metadata.
Changes:
- Remove the current logging of gauge metadata - will be re-introduced in a future PR.
- Switch Gauge collection from `scheduleAtFixedRate` to `scheduleWithFixedDelay`. As [documented](https://stackoverflow.com/a/78405653), this *should* prevent a potentially large amounts of gauge collection if a process is cached, and then restored during a verbose session - which *should* make it work better w/ AQS.
- Remove API restricted behaviour which is no longer relevant.
=> Remove the logging of GaugeMetadata to allow using AQS

firebase-dataconnect/gradleplugin/plugin/src/main/resources/com/google/firebase/dataconnect/gradle/plugin/DataConnectExecutableVersions.json
DataConnectExecutableVersions.json updated with versions 1.7.6 and 1.7.7 by running:
```
./gradlew :firebase-dataconnect:connectors:updateJson -Pversions=1.7.6,1.7.7 -PdefaultVersion=1.7.7
```
=> dataconnect: DataConnectExecutableVersions.json updated with versions 1.7.6 and 1.7.7

.github/workflows/dataconnect.yml, .github/workflows/dataconnect_demo_app.yml
The output now looks like this, with nice separators:
```
===============================================================================
Running Command: uname -a
Linux fv-az1911-92 6.8.0-1020-azure #23-Ubuntu SMP Mon Dec  9 16:58:58 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
===============================================================================
Running Command: which java
/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.14-7/x64/bin/java
===============================================================================
Running Command: java -version
openjdk version "17.0.14" 2025-01-21
OpenJDK Runtime Environment Temurin-17.0.14+7 (build 17.0.14+7)
OpenJDK 64-Bit Server VM Temurin-17.0.14+7 (build 17.0.14+7, mixed mode, sharing) …
```
=> dataconnect.yaml: improve readability of the output of the "tool versions" step

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/KeyValueBuilder.kt
Fix deprecated message in KeyValueBuilder to render properly. The old syntax was showing the backtick marks on https://firebase.google.com/docs/reference/kotlin/com/google/firebase/crashlytics/KeyValueBuilder#KeyValueBuilder(com.google.firebase.crashlytics.FirebaseCrashlytics). See http://b/382483629.
=> Fix deprecated message in KeyValueBuilder to render properly

firebase-perf/firebase-perf.gradle, firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerfRegistrar.java, firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerformance.java, firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigResolver.java, firebase-perf/src/main/java/com/google/firebase/perf/session/FirebasePerformanceSessionSubscriber.kt, firebase-perf/src/main/java/com/google/firebase/perf/session/PerfSession.java, firebase-perf/src/main/java/com/google/firebase/perf/session/SessionManager.java, firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/GaugeManager.java, firebase-perf/src/main/java/com/google/firebase/perf/transport/TransportManager.java, firebase-perf/src/test/java/com/google/firebase/perf/session/SessionManagerTest.java, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/api/FirebaseSessionsDependencies.kt
This is a follow up for: https://github.com/firebase/firebase-android-sdk/pull/6678
This PR doesn't change the use of session ID to AQS - except in GaugeMetadata. I've added TODOs to identify the missing locations.
=> Implement a SessionSubscriber for Firebase Performance

firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/property/arbitrary/javatime.kt, firebase-functions/CHANGELOG.md, firebase-vertexai/api.txt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/CountTokensResponse.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/UsageMetadata.kt, firebase-vertexai/src/test/java/com/google/firebase/vertexai/UnarySnapshotTests.kt
There were some issues when generating Timestamp values for testing.  The first was some bad math when generating nanosecond values, where values exceeding the maximum value of 999,999,999 were being generated. The second was a boundary case where the time zone offset would push the second/nanosecond value above the maximum value or below the minimum value. This PR fixes both of those.
=> dataconnect: fix generation of invalid timestamp values in internal test utilities

firebase-vertexai/api.txt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ImagenGenerationConfig.kt
Should be more careful with those changes...
=> Remove test code left by mistake

firebase-crashlytics-ndk/CHANGELOG.md, firebase-crashlytics/CHANGELOG.md
There were changes to the Sessions SDK but not Crashlytics or Crashlytics NDK
=> Update CHANGELOG for Crashlytics and NDK

firebase-firestore/CHANGELOG.md, firebase-inappmessaging-display/CHANGELOG.md, firebase-inappmessaging/CHANGELOG.md, firebase-perf/CHANGELOG.md, firebase-perf/firebase-perf.gradle, protolite-well-known-types/CHANGELOG.md, protolite-well-known-types/README.md, protolite-well-known-types/gradle.properties, protolite-well-known-types/protolite-well-known-types.gradle
Per [b/398840288](https://b.corp.google.com/issues/398840288),
This bumps `protolite-well-known-types` to properly utilize `3.25.5`. It seems as though this was an oversight in #6343, but since gradle uses the highest version when resolving dependency conflicts (and all the existing libraries already use `3.25.5`), this isn't a major issue. This is only really an issue if someone is using `protolite-well-known-types` in isolation (which isn't really a use-case we're shipping for). But the main reason for fixing this is that it causes a bit of confusion when trying to track dependency issues (see issue #6674 for an example of this).
Fixes #6674
=> Bump well known types

plugins/src/main/java/com/google/firebase/gradle/plugins/CopyApiTask.kt, plugins/src/main/java/com/google/firebase/gradle/plugins/FirebaseAndroidLibraryPlugin.kt, plugins/src/main/java/com/google/firebase/gradle/plugins/FirebaseJavaLibraryPlugin.kt, plugins/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryExtension.kt
Prerequisite of Metalava based SemVer
=> Add copyApiTxtFile task

firebase-functions/CHANGELOG.md
The mergeback PR from last release didn't include the update to function's CHANGELOG.md file
=> Update functions changelog

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/KeyValueBuilder.kt
Remove code style from deprecated message since it does not render properly. I could not find any syntax that rendered properly in both the IDE and in the generated html. I found many examples of deprecated messages that just don't add any code style to method or class names, see https://source.corp.google.com/search?q=%22@Deprecated(message%22. The Kotlin doc for `@Deprecated` does not mention any style, see https://kotlinlang.org/api/core/kotlin-stdlib/kotlin/-deprecated/.
=> Remove code style from deprecated message

firebase-messaging/CHANGELOG.md, firebase-messaging/src/main/java/com/google/firebase/messaging/SyncTask.java
For issue #6558, this is an attempt at fixing the IllegalArgumentException by ensuring that the context we use for registering the SyncTask is the same context we use to unregister the task. Race conditions dont seem like a culprit here since unregister is only triggered by the Receiver itself, which should be only executed synchronously on the main thread.
New PR needed to fix CLA issue
=> Store registered context for sync task unregistrations

firebase-functions/CHANGELOG.md, firebase-functions/src/androidTest/java/com/google/firebase/functions/FirebaseContextProviderTest.java, firebase-functions/src/main/java/com/google/firebase/functions/FirebaseContextProvider.kt
=> [Functions] Send the placeholder appcheck token in case of error

firebase-crashlytics/CHANGELOG.md, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
Read version control info from an Android string resource, then fall back to the old slower method.
The Crashlytics Gradle plugin will need to be updated to generate this string resource.
=> Read version control info from Android resource

firebase-sessions/CHANGELOG.md, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt
Detect and log the following warning for the known issue https://issuetracker.google.com/328687152
```md
Your app is experiencing a known issue in the Android Gradle plugin, see https://issuetracker.google.com/328687152
It affects Java-only apps using AGP version 8.3.2 and under. To avoid the issue, either:
1. Upgrade Android Gradle plugin to 8.4.0+
Follow the guide at https://developer.android.com/build/agp-upgrade-assistant
2. Or, add the Kotlin plugin to your app
Follow the guide at https://developer.android.com/kotlin/add-kotlin
3. Or, do the technical workaround described in https://issuetracker.google.com/issues/328687152#comment3
```
=> Add warning for known issue b/328687152

.github/workflows/create_releases.yml
We need explicit permissions to create PRs now, this adjusts our create release workflow to specify them.
=> Adjust Create Release

firebase-vertexai/CHANGELOG.md, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/Request.kt
=> Add GenerationConfig to CountTokenRequest's

firebase-functions/firebase-functions.gradle.kts
Alternative to #6774 - we'll keep that PR for a follow-up release.
For now, we're exposing the `reactive-streams` dependency to make sure it works out of the box for Java developers.
=> chore(functions): export reactive-streams as a transitive dependency

firebase-functions/src/androidTest/java/com/google/firebase/functions/StreamTests.kt, firebase-functions/src/main/java/com/google/firebase/functions/PublisherStream.kt
Throwing inside the `PublisherStream` causes a Runtime exception that can't be caught in the call site.
Instead, we should use `notifyError()` so that the error can be caught in the `Subscriber#onError()` function.
I tried to catch the exception using both of the code snippets below, but none of them worked. (they both work with the changes in this PR):
```kotlin
functions.getHttpsCallable("nonExistentFunction")
.stream().asFlow()
.catch {
// Handle error for a 404 function
}
.collect {
// ...
}
```
```kotlin
try {
functions.getHttpsCallable("nonExistentFunction")
.stream().asFlow()
.collect {
// ...
}
} catch(e: Exception) {
// Handle error for a 404 function
}
```
Runtime exception thrown:
```
FATAL EXCEPTION: OkHttp Dispatcher
Process: com.google.samples.quickstart.functions, PID: …
```
=> fix(functions): use notifyError() instead of throwing

build.gradle.kts, gradle/libs.versions.toml
Setup kotlinx.serialization plugin in the project wide gradle build file. This will be used by AQS. The plugin needs to use the same version as as the kotlin version.
=> Setup kotlinx.serialization plugin

.github/workflows/release-note-changes.yml
In the light of recent security issues, we are choosing to use our own code to replace an external action.
See
https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised for context
b/403703743
=> Swap external action to verify changed files for inline code

plugins/src/main/java/com/google/firebase/gradle/plugins/FiresiteTransformTask.kt
Per [b/379093944](https://b.corp.google.com/issues/379093944),
This adds a transform action to remove the `com.google.` package prefix in the TOC files, as it pollutes the visual landscape for consumers. Long-term, this action will be replaced by a parameter offered via newer versions of dackka- but we don't currently have the bandwidth for such an upgrade. A tracking bug has been left with the implementation to migrate to said parameter whenever we have the time to upgrade.
=> Add transform action to remove package prefix in toc files

plugins/src/main/java/com/google/firebase/gradle/bomgenerator/GenerateTutorialBundleTask.kt
I suspect this is what is causing the plugin to try and remove the `com.google.android.libraries.identity.googleid:googleid:1.1.1` library. (as seen in [cl/738906664](https://critique.corp.google.com/cl/738906664/depot/google3/third_party/devsite/firebase/en/android-studio/firebase_assistant/firebase_tutorial_bundle.xml?version=r201#43))
=> include the full googleid module in GenerateTutorialBundleTask.kt

.github/workflows/plugins-check.yml, plugins/src/main/java/com/google/firebase/gradle/bomgenerator/GenerateTutorialBundleTask.kt
This might be the cause of https://github.com/firebase/firebase-android-sdk/actions/runs/13979443579/job/39141224363?pr=6789
Update: confirmed in https://github.com/firebase/firebase-android-sdk/actions/runs/13979884815/job/39142572824?pr=6790
=> ci: add missing permissions to .github/workflows/plugins-check.yml

firebase-dataconnect/CHANGELOG.md
The changelog entry was erroneously removed by automated tooling in https://github.com/firebase/firebase-android-sdk/pull/6793
=> [DataConnect] Add changelog entry back

firebase-dataconnect/scripts/generateApiTxtFile.sh
This new script makes it easy to regenerate the api.txt file without having to remember the gradle command.
=> dataconnect: generateApiTxtFile.sh added

firebase-functions/src/androidTest/java/com/google/firebase/functions/StreamTests.kt
The test `genStreamError_receivesError` is flaky due to timeout issues. Bumping timeout to 10s.
=> [VertexAI] Bump timeout for error test

firebase-vertexai/CHANGELOG.md, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt
Added a warning message to the initializers of GenerativeModel and ImagenModel that is logged when the provided model name does not start with the expected prefix ("gemini-" for GenerativeModel and "imagen-" for ImagenModel). The warning message includes a link to the documentation for supported models.
Note: No error is thrown in case the naming scheme is changed in the future, though we would want to update the logic/message at that time.
Related iOS PR https://github.com/firebase/firebase-ios-sdk/pull/14610
=> [VertexAI] Log warning for unsupported model names

firebase-vertexai/firebase-vertexai.gradle.kts, firebase-vertexai/src/testUtil/java/com/google/firebase/vertexai/JavaCompileTests.java
This is a starting point for compilation testing, broadly using most symbols Vertex exposes to Java users, lightly validating usability and structure. As a note, there are some builder patterns in Vertex that don't work as expected from Java and were omitted, as fixing that would be a breaking change.
=> Add basic Vertex Java compilation tests

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/LiveGenerativeModel.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/LiveSession.kt
It's an internal tracker that should not be modified while instantiating.
=> Remove `isRecording` from constructor

health-metrics/benchmark/template/app/build.gradle.mustache, health-metrics/benchmark/template/macrobenchmark/build.gradle
Per [b/407077784](https://b.corp.google.com/issues/407077784),
This bumps the `compileSdkVersion` and `targetSdkVersion` within our health metrics test app and benchmarks to match what our SDKs actually use. This also fixes the issue with our startup checks failing due to certain SDK dependencies requiring a higher compile target.
=> Fix startup check failures

firebase-functions/src/androidTest/java/com/google/firebase/functions/StreamTests.kt
Integration tests are being flaky  due to short timeouts.
no-changelog
=> [Functions] Bump all test timeouts to 10 seconds

firebase-vertexai/CHANGELOG.md, firebase-vertexai/api.txt, firebase-vertexai/firebase-vertexai.gradle.kts, firebase-vertexai/lint-baseline.xml, firebase-vertexai/src/main/AndroidManifest.xml, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAIMultiResourceComponent.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAIRegistrar.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/LiveGenerativeModel.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/APIController.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/java/LiveModelFutures.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/java/LiveSessionFutures.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/AudioHelper.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/BidiGenerateContentClientMessage.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Exceptions.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/LiveContentResponse.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/LiveGenerationConfig.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/LiveSession.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/MediaData.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ResponseModality.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/SpeechConfig.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/StreamOutput.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Voices.kt, gradle/libs.versions.toml
Bidirectional streaming for android. Creates a bunch of helper classes for the same. The main classes which handle the bidirectional streaming are LiveGenerativeModel and LiveSession
=> Bidirectional Streaming Android

firebase-dataconnect/src/androidTest/kotlin/com/google/firebase/dataconnect/QuerySubscriptionIntegrationTest.kt
Fix a flaky test by ensuring that the query subscription started in backgroundScope gets its first result before continuing the test.
=> dataconnect: QuerySubscriptionIntegrationTest.kt: fix flaky test using backgroundScope

.github/workflows/dataconnect.yml
This fixes the "Warning: Key is not specified" warning in the scheduled nightly runs in the "Save Gradle cache" and "Save AVD cache" steps of the dataconnect github actions workflow. The problem was that it was defining the key as `${{ steps.restore-gradle-cache.outputs.cache-primary-key }}` and `${{ steps.restore-avd-cache.outputs.cache-primary-key }}`, respectively, but since those dependent steps were explicitly _skipped_ in nightly runs their outputs were not defined.
=> dataconnect: github actions cache key fix

firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/serializers/LocalDateSerializerUnitTest.kt
Fix `unparseableDash()` in `LocalDateSerializerUnitTest.kt` to not include numbers in the set of "invalid" characters because they become "valid" when adjacent to other numeric digits. In certain situations, using a "digit" as an invalid character was causing flaky test failures such as this one in `deserialize() should throw IllegalArgumentException when given unparseable strings`:
```
Arg 0: "96-082895-312"
Repeat this test by using seed -7108070269336260794
Caused by: Expected exception java.lang.IllegalArgumentException but no exception was thrown.
at com.google.firebase.dataconnect.serializers.LocalDateSerializerUnitTest$deserialize() should throw IllegalArgumentException when given unparseable strings$1.invokeSuspend(LocalDateSerializerUnitTest.kt:104)
at …
```
=> dataconnect: fix flaky test that ensures deserialize() throws IllegalArgumentException on invalid input

firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerformance.java, firebase-perf/src/main/java/com/google/firebase/perf/logging/DebugEnforcementCheck.kt, firebase-perf/src/main/java/com/google/firebase/perf/session/FirebasePerformanceSessionSubscriber.kt, firebase-perf/src/main/java/com/google/firebase/perf/session/PerfSession.java, firebase-perf/src/main/java/com/google/firebase/perf/session/SessionManager.java, firebase-perf/src/test/java/com/google/firebase/perf/application/AppStateMonitorTest.java, firebase-perf/src/test/java/com/google/firebase/perf/session/PerfSessionTest.java, firebase-perf/src/test/java/com/google/firebase/perf/session/SessionManagerTest.java, firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/GaugeManagerTest.java, firebase-perf/src/test/java/com/google/firebase/perf/transport/TransportManagerTest.java
- Override PerfSession session id to aqs session id when possible
- Add assertion for debug mode to double check if aqs session id available by the time of use
=> convert perf session to use aqs support session id

firebase-dataconnect/src/androidTest/kotlin/com/google/firebase/dataconnect/AuthIntegrationTest.kt
This PR fixes two tests in `AuthIntegrationTest.kt` that would flakily fail: `queryShouldRetryOnUnauthenticated` and `mutationShouldRetryOnUnauthenticated`.
The fix was to ensure that FirebaseAuth was ready in the `FirebaseDataConnect` instance _before_ starting the test. I had thought that the test was _already_ doing this because the `signIn()` method calls `awaitAuthReady()` on a `FirebaseDataConnect` object; however, the test actually used a _different_ `FirebaseDataConnect` object and no call to `awaitAuthReady()` was made on it. As a result, occasionally the query would be executed _before_ FirebaseAuth was ready and in those cases the test would fail. The fix was to simply call `awaitAuthReady()` on the _other_ `FirebaseDataConnect` object that was used by the test to run the …
=> dataconnect: fix two flaky tests due to their failure to wait for FirebaseAuth to be initialized

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionFirelogPublisher.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SharedSessionRepository.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionFirelogPublisherTest.kt
send session event based on data collection and setting config
=> send session event based on data collection and setting config

firebase-vertexai/CHANGELOG.md, firebase-vertexai/README.md, firebase-vertexai/api.txt, firebase-vertexai/gradle.properties, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/HarmBlockThreshold.kt
Per [b/409040155](https://b.corp.google.com/issues/409040155),
This adds support for `HarmBlockThreshold.OFF`, and also adds javadocs that clearly articulate the difference it holds from `NONE`.
=> Add support for HarmBlockThreshold.OFF

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SharedSessionRepository.kt
Fix where we generate and send session details to firelog. Before this, we might send false positives to firelog, or even update the session details with a stale copy. Now the session generate and send to firelog happen inside the datastore transform with the data in datastore.
=> Fix firelog send

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CompositeIndexQueryTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/VectorTest.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/CompositeIndexTestHelper.java, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
This PR improves the way `checkOnlineAndOfflineResultsMatch` test util function was written.
It does so by first pre-populating the cache with the entire collection, then performing the query from cache (this results in a full collection scan), then performing the query from the server, and then performing the query from cache again (this results in using `performQueryUsingRemoteKeys`. It then ensures that all of these 3 results are the same and equal to the expected results.
#no-changelog
=> Improve the integration test coverage for online vs offline comparisons.

firebase-perf/src/main/java/com/google/firebase/perf/metrics/validator/PerfMetricValidator.java
The `validateAttribute` method is static and can be called multiple times, which makes re-compiling the key regex validation every time a waste of resources.
Originally reported as https://github.com/firebase/firebase-android-sdk/issues/6862
=> [Perf] Cache attribute key validation regex

firebase-firestore/CHANGELOG.md, firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/FieldFilter.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/NotInFilter.java, firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java
ported from https://github.com/firebase/firebase-ios-sdk/pull/14704
=> fix: remove null value inclusion from `whereNotEqualTo` and `whereNotIn` filter results 

plugins/src/main/java/com/google/firebase/gradle/plugins/FirebaseJavaLibraryPlugin.kt
`JavaPluginConvention` and the use of convetions in general is deprecated and will cause an error when migrated to Gradle 9.0. The recommended replacement is to use extensions.
=> [plugins] Remove JavaPluginConvention from FirebaseJavaLibraryPlugin

.github/workflows/check-vertexai-responses.yml
The task began failing recently likely due to changes in global permissions, this updates the workflow to explicitly have write permissions to make comments.
=> Add write permisison to VertexAI Response Checking task

firebase-perf/firebase-perf.gradle, firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerformance.java, firebase-perf/src/main/java/com/google/firebase/perf/logging/FirebaseSessionsEnforcementCheck.kt, firebase-perf/src/main/java/com/google/firebase/perf/session/FirebasePerformanceSessionSubscriber.kt, firebase-perf/src/main/java/com/google/firebase/perf/session/FirebaseSessionsHelper.kt, firebase-perf/src/main/java/com/google/firebase/perf/session/PerfSession.java, firebase-perf/src/main/java/com/google/firebase/perf/session/SessionManager.java, firebase-perf/src/main/java/com/google/firebase/perf/util/Constants.java, firebase-perf/src/test/java/com/google/firebase/perf/session/FirebaseSessionsTestHelper.kt, firebase-perf/src/test/java/com/google/firebase/perf/session/PerfSessionTest.java, firebase-perf/src/test/java/com/google/firebase/perf/session/SessionManagerTest.java, firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/GaugeManagerTest.java, firebase-perf/src/test/java/com/google/firebase/perf/transport/TransportManagerTest.java
This is a subset of changes in [#6693](https://github.com/firebase/firebase-android-sdk/pull/6693).
=> Update PerfSession and SessionManager to identify Legacy sessions.

firebase-sessions/src/test/kotlin/com/google/firebase/sessions/FakeDataStoreTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeDataStore.kt
Implement fake datastore for unit tests. This fake can act like a simple in memory datastore, but it can also throw provided exceptions on specific actions. It can throw on update, throw on collect, throw on init. This will help write unit tests for when datastore fails.
=> Implement fake datastore for unit tests

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SharedSessionRepository.kt
Using try catch block to make datastore fall back to a pre multi-process supported version. Generate a new session locally then notify to subscribers
=> Fallback try catch block

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionData.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SharedSessionRepository.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SharedSessionRepositoryTest.kt
Make background time nullable
For each new session generated, reset background time
Update unit tests
=> background time nullable

firebase-perf/src/main/java/com/google/firebase/perf/transport/TransportManager.java, firebase-perf/src/main/proto/firebase/perf/v1/perf_metric.proto, firebase-perf/src/test/java/com/google/firebase/perf/transport/TransportManagerTest.java, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/ProcessDetailsProvider.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvent.kt
Leverage on `ProcessDetailsProvider` to retrieve process name info
=> Add process name to application info

firebase-firestore/CHANGELOG.md, firebase-firestore/src/main/java/com/google/firebase/firestore/remote/AbstractStream.java
This should fix issue https://github.com/firebase/firebase-android-sdk/issues/6883
=> Handle error when stream was cancelled prior to calling halfClose.

firebase-vertexai/CHANGELOG.md, firebase-vertexai/api.txt, firebase-vertexai/gradle.properties, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerateContentResponse.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerationConfig.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ResponseModality.kt
This change enables use of multiple modalities when calling generateContent from the model. 
This change adds a new field into the GenerationConfig to specify the responseModalities which would be sent to the server. Also for easier response handling it exposes a function inlineDataParts which should return all the data sent back by the model.
=> Enable multimodal response generation in android

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt
The private function `encodeBitmapToBase64Png` in `firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt` was already compressing Bitmap images to JPEG format, not PNG.
This commit renames the function to `encodeBitmapToBase64Jpeg` to accurately reflect its behavior. The single call site within the same file has also been updated.
no-changelog
=> Refactor: Rename encodeBitmapToBase64Png to encodeBitmapToBase64Jpeg

protolite-well-known-types/gradle.properties
Current version needs to match previously released version otherwise releases will attempt to depend on nonexistent releases.
=> Pin protolite-well-known-types

firebase-vertexai/CHANGELOG.md, firebase-vertexai/api.txt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/LiveContentResponse.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/LiveSession.kt
Per [b/410855548](https://b.corp.google.com/issues/410855548),
This removes the `LiveContentResponse.Status` class, and instead nests the status as corresponding fields directly on `LiveContentResponse`.  This is done to ensure we can support the model returning multiple statuses, since the model does not define them as exclusive.
Note that proto alignment efforts will be in a separate PR. This PR is _only_ for migrating `Status` to properties.
=> Migrate LiveContentResponse.Status to properties

plugins/src/main/java/com/google/firebase/gradle/plugins/PostReleasePlugin.kt, plugins/src/main/java/com/google/firebase/gradle/plugins/VersionBumpTask.kt
Per [b/413403910](https://b.corp.google.com/issues/413403910),
This adds filtering logic to not bump the version of `protolite-well-known-types` when it releases. This solves the issue of the `version` and `latestReleasedVersion` not aligning (which must be enforced due to [b/285892320](https://buganizer.corp.google.com/issues/285892320)).
More specifically, this PR adds a toggle for the default `bump` behavior in `VersionBumpTask`. We then set this to `false` when the project's `artifactId` is `protolite-well-known-types`.
This allows us to still [automatically] update the `latestReleasedVersion` (should we ever release well known types again), without bumping the `version`.
The `VersionBumpTask` docs have been updated to accommodate this.
=> Exclude protolite well known types from version bump.

firebase-ai/CHANGELOG.md, firebase-ai/api.txt, firebase-ai/src/main/kotlin/com/google/firebase/ai/type/GenerateContentResponse.kt
Per [b/414639898](https://b.corp.google.com/issues/414639898),
This adds a helper property to `GenerateContentResponse` for getting all the `InlineDataPart` present in the first candidate, similar to `text`.
This was actually added in #6901, but it seems to have been missed during our `firebase-ai` migration.
=> Add inlineDataParts helper property

firebase-ai/CHANGELOG.md, firebase-ai/api.txt, firebase-ai/src/main/kotlin/com/google/firebase/ai/type/GenerationConfig.kt
Per [b/414638874](https://b.corp.google.com/issues/414638874),
This adds support for `ResponseModality` in `GenerationConfig`. #6901 added this, but it seems it was missed during the migration to `firebase-ai`.
=> Add ResponseModality support to GenerationConfig

firebase-ai/src/test/java/com/google/firebase/ai/util/tests.kt, firebase-vertexai/src/test/java/com/google/firebase/vertexai/util/tests.kt
Per [b/414406390](https://b.corp.google.com/issues/414406390),
This fixes the issue with long text golden files timing out the tests. This occurred because the text contents were too large for the channel's buffer- so the channel entered a suspension point until the content was read. Unfortunately, this suspension point blocked the test thread. To solve this, we do the same thing we do for `goldenStreamingFile`- we write to the channel in a separate coroutine scope. This allows Kotlin to properly recognize that the suspension point within the writer should allow for the test thread to continue.
=> Fix AI test timeout

firebase-ai/src/main/kotlin/com/google/firebase/ai/type/Candidate.kt, firebase-ai/src/main/kotlin/com/google/firebase/ai/type/PromptFeedback.kt, firebase-ai/src/test/java/com/google/firebase/ai/VertexAIStreamingSnapshotTests.kt, firebase-ai/src/test/java/com/google/firebase/ai/VertexAIUnarySnapshotTests.kt
Due to a bug in the backend, it's possible that we receive an invalid `SafetyRating` value, without either category or probability. We return null in those cases to enable filtering by the higher level types.
=> [Ai] Add workaround for invalid SafetyRating from the backend.

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
=> fix more strict mode violation

firebase-ai/CHANGELOG.md, firebase-ai/api.txt, firebase-ai/src/main/kotlin/com/google/firebase/ai/type/Content.kt, firebase-ai/src/main/kotlin/com/google/firebase/ai/type/GenerationConfig.kt, firebase-ai/src/testUtil/java/com/google/firebase/ai/JavaCompileTests.java
Fixes all Firebase AI builder patterns to be properly usable by Java consumers. Small breaking binary change, no breaking source change. Additionally, now that the builder pattern can be used, compile tests for the builders and other classes like `Schema` have been implemented.
=> Fix AI builders for Java consumers

firebase-ai/src/main/kotlin/com/google/firebase/ai/common/APIController.kt, firebase-ai/src/test/java/com/google/firebase/ai/DevAPIStreamingSnapshotTests.kt, firebase-ai/src/test/java/com/google/firebase/ai/VertexAIStreamingSnapshotTests.kt, firebase-ai/src/test/java/com/google/firebase/ai/util/tests.kt, firebase-ai/update_responses.sh
The devAPI helper method should read from the `googleai/` directory instead of the `vertexai/` one.
Additionally, fixed tests broken by the change.
=> [Ai] Fix test code to point to the right resource dir

.github/workflows/check-firebaseai-responses.yml
Instead of verifying vertexAI, we should do the verification on firebase-ai only.
=> [Ai] Update test response check to verify firebase-ai

firebase-ai/src/main/kotlin/com/google/firebase/ai/common/APIController.kt
Originally we were not tracking bidi usage in android. This PR enables it by adding certain headers when the initial websocket connection is made. There was some refractoring done wrt to extract out the part which just adds the headers from the applyCommonConfiguration function
=> Add headers to be able to track bidi usage 

firebase-storage/CHANGELOG.md, firebase-storage/src/test/java/com/google/firebase/storage/DownloadTest.java, firebase-storage/src/test/java/com/google/firebase/storage/TestUtil.java
The Robolectric Scheduler APIs are designed for LEGACY Looper mode, where tasks were controlled by Scheduler objects. LEGACY Looper mode has been deprecated for 5+ years. Migrate from Robolectric.flushForegroundThreadScheduler to ShadowLooper APIs.
See cl/752917858 for reference
=> [Storage] Migrate from Robolectric.flushForegroundThreadScheduler to ShadowLooper.runToEndOfTasks

firebase-config/CHANGELOG.md, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
This change addresses a ``NetworkOnMainThreadException`` that was observed  on Android API levels below 26.
The crash happened during background transitions when disconnecting an ``HttpURLConnection`` because background callbacks on these older OS versions could run on the main thread. The fix restricts the disconnect logic to run only on API level 26 (Android 8.0) and higher.
=> Fix NetworkOnMainThreadException for API levels below 26

firebase-perf/src/main/java/com/google/firebase/perf/metrics/NetworkRequestMetricBuilder.java, firebase-perf/src/main/java/com/google/firebase/perf/metrics/Trace.java, firebase-perf/src/main/java/com/google/firebase/perf/session/PerfSession.java, firebase-perf/src/main/java/com/google/firebase/perf/session/SessionManager.java, firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/CpuGaugeCollector.java, firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/GaugeCounter.kt, firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/GaugeManager.java, firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/MemoryGaugeCollector.java, firebase-perf/src/test/java/com/google/firebase/perf/metrics/NetworkRequestMetricBuilderTest.java, firebase-perf/src/test/java/com/google/firebase/perf/metrics/TraceTest.java, firebase-perf/src/test/java/com/google/firebase/perf/session/PerfSessionTest.java, firebase-perf/src/test/java/com/google/firebase/perf/session/SessionManagerTest.java, firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/GaugeManagerTest.java
- Update Gauge metrics collection frequency to be independent of Session Change.
- Update GaugeMetric logging to log them based on metrics count
- Necessary changes in SessionManager (remove app state monitor)
There's a non-trivial number of unit test failures in GaugeManager. This PR marks them as Ignore so I can make necessary changes in a followup PR.
=> Update GaugeManager for AQS

firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/ImagenModel.kt, firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/LiveGenerativeModel.kt
This change is required to track the usage of vertex ai/developer api in kotlin. This change adds a suffix to the version value in the headers we send to the backend (This will mainly distinguish between the 16.0.0 versions from the old sdk and the new one)
=> Update headers to track vertex ai/developer usage in kotlin

firebase-crashlytics-ndk/CHANGELOG.md
#6945 was missing a changelog entry for the dependent library. This PR adds that changelog.
=> Add crashlytics-ndk changelog entry

firebase-sessions/CHANGELOG.md, firebase-sessions/firebase-sessions.gradle.kts, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsComponent.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/ProcessDataManager.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionData.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SharedSessionRepository.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/ProcessDataManagerTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SharedSessionRepositoryTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeFirebaseApp.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeProcessDataManager.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeRunningAppProcessInfo.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeUuidGenerator.kt
Implement new cold app start detection heuristic.
This is just the reading part, and all the scaffolding. Next step will be to start writing the process data map.
Tested by unit tests and manual testing with the sessions test app
=> Implement new cold app start detection heuristic

plugins/src/main/java/com/google/firebase/gradle/bomgenerator/GenerateTutorialBundleTask.kt, plugins/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt
Per [b/416734504](https://b.corp.google.com/issues/416734504),
This updates the `GenerateTutorialBundleTask` that we use to generate the tutorial bundle versions (recipe versions) to support `firebase-ai`. More specifically, it replaces the existing `firebase-vertexai` entry in the process.
While this PR removes `firebase-vertexai` from the tutorial bundle, it does _not_ remove it from the BoM. That will be a breaking change we'll make down the road.
=> Add Firebase AI to recipe version generation

plugins/src/main/java/com/google/firebase/gradle/bomgenerator/GenerateTutorialBundleTask.kt
All SDK dependency declarations follow the same pattern, `<libname>-dependency`
=> [ai] Include missing dependency suffix to firebase-ai

.github/workflows/merge-to-main.yml
The "Merge to main" workflow adds a comment to the PR so authors know that their changes shouldn't break the main branch, as it should always remain stable and releasable. This only makes sense when the change affects an SDK, as only those get released. Now we filter the message so it doesn't spam PRs that only touch infra (plugin & github folders)
=> [action] Only include merge message on sdk changes

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/ProcessDataManager.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/ProcessDataManagerTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeProcessDataManager.kt
Implement ProcessDataManager in the way we designed in https://docs.google.com/document/d/1yEd8dCIzwNwLhRRwkDtzWFx9vxV5d-eQU-P47wDL40k/edit?usp=sharing
Tested manually in the sessions test app, and with unit tests
=> Implement ProcessDataManager

firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/GaugeCounter.kt, firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/GaugeManager.java, firebase-perf/src/test/java/com/google/firebase/perf/FirebasePerformanceTestBase.java, firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/GaugeManagerTest.java
- Fixes relevant unit tests - specifically requiring a definite `ApplicationProcessState`
- Adds new unit tests for the updated behaviour
- Deletes unit tests that *should* be OK to delete.
=> Add unit tests for new logging in GaugeManager using GaugeCounter.

firebase-perf/src/main/java/com/google/firebase/perf/metrics/AppStartTrace.java, firebase-perf/src/main/java/com/google/firebase/perf/transport/TransportManager.java, firebase-perf/src/main/java/com/google/firebase/perf/util/AppProcessesProvider.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/ProcessDetailsProvider.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvent.kt
- This is based on `firebase-sessions/src/main/kotlin/com/google/firebase/sessions/ProcessDetailsProvider.kt`
- Usage in `AppStartTrace` and `TransportManager`
- Reverts changes in `firebase-sessions/src/main/` to `main`
=> Refactor usage of ProcessName in Fireperf.

firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/CpuGaugeCollector.java, firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/MemoryGaugeCollector.java, firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/GaugeManagerTest.java
As part of looking into refactoring `GaugeCounter` I noticed I'd missed this increment.
=> Add missing `GaugeCounter` increment.

firebase-ai/CHANGELOG.md, firebase-ai/src/main/kotlin/com/google/firebase/ai/type/FunctionDeclaration.kt, firebase-ai/src/test/java/com/google/firebase/ai/type/FunctionDeclarationTest.kt
It seems like the value set in `FunctionDeclaration#description` was never making it to the API.
~Aside: I wonder if this is why some function calls would sometimes fail (ie. the model wouldn't know which function to call)~ Nevermind, I found a bug in the implementation I was testing with.
=> fix(ai): pass FunctionDeclaration#description arg to internal class

firebase-ai/CHANGELOG.md, firebase-ai/src/main/kotlin/com/google/firebase/ai/FirebaseAI.kt
=> Fix Firebase AI StackOverflow

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/ProcessDataManager.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/ProcessDetailsProvider.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SharedSessionRepository.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/ApplicationInfoTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/ProcessDataManagerTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/ProcessDetailsProviderTest.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeProcessDataManager.kt
Implement cold start detection logic as described in https://docs.google.com/document/d/1yEd8dCIzwNwLhRRwkDtzWFx9vxV5d-eQU-P47wDL40k/edit?usp=sharing
Also renamed process related functions to be more consistent to make the code less error prone. This is also described in the doc
Tested by unit tests and with the sessions test app
=> Implement cold start detection logic

firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/ForegroundNotifierTest.java
Robolectric.flushForegroundThreadScheduler is going to be removed in a forthcoming Robolectric release. The Robolectric Scheduler APIs are designed for LEGACY Looper mode which has been deprecated for years.
=> Migrate from Robolectric.flushForegroundThreadScheduler to ShadowLooper.runToEndOfTasks

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SharedSessionRepository.kt
Tested manually using sessions test app. This is a trivial change
=> Do not notify subscribers when session didn't change

firebase-ai/src/main/kotlin/com/google/firebase/ai/type/ImagenPersonFilterLevel.kt
This PR updates the ImagenPersonFilter refdocs to match the [iOS SDK](https://github.com/firebase/firebase-ios-sdk/blob/4f6c342424df416d78dfc12d08c97769fd4e1152/FirebaseAI/Sources/Types/Public/Imagen/ImagenPersonFilterLevel.swift#L33-L45), including the information about the [Person and face generation allowlist](https://cloud.google.com/vertex-ai/generative-ai/docs/image/responsible-ai-imagen#person-face-gen).
=> Update ImagenPersonFilterLevel refdocs to match the iOS SDK

firebase-sessions/src/main/kotlin/com/google/firebase/sessions/EventGDTLogger.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsComponent.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/InstallationId.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionFirelogPublisher.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SharedSessionRepository.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/api/FirebaseSessionsDependencies.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/RemoteSettings.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/SettingsCache.kt
Use the same tag for all logs in sessions. This will make it easier to dogfood, and is consistent with Perf and Crashlytics
If any context is lost by losing the tag named after the class, we can update those log lines as we run into them. A future change we can do is refactor to use the firebase common logger
=> Use the same tag for all logs in sessions

firebase-dataconnect/CHANGELOG.md, firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/DataConnectCredentialsTokenManager.kt, firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/FirebaseDataConnectImpl.kt, firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/DataConnectAuthUnitTest.kt
This PR fixes a race condition in Data Connect where `DataConnectAuth` could register a null token listener before its constructor completed, leading to spurious `NullPointerException` and downstream `UNAUTHENTICATED` errors. It introduces an explicit `initialize()` API to control the setup phase, hooks `initialize()` into `FirebaseDataConnectImpl` for both Auth and AppCheck, and augments unit tests to cover `initialize` and `close` behaviors.
There is, unfortunately, no workaround for the bug. The only mitigation would be to close the `FirebaseDataConnect` object, re-open it, and try again. This fix will be included in the release of the firebase-android-sdk in about 4 weeks, near the end of June 2025.
The bug was easy to reproduce: simply add a call to `Thread.sleep()` in a certain …
=> dataconnect: Fixed occasional `NullPointerException` leading to erroneous UNAUTHENTICATED exceptions

.github/workflows/dataconnect.yml, .github/workflows/dataconnect_demo_app.yml, firebase-dataconnect/emulator/dataconnect/connector/person/person_ops.gql, firebase-dataconnect/gradleplugin/plugin/src/main/resources/com/google/firebase/dataconnect/gradle/plugin/DataConnectExecutableVersions.json, firebase-dataconnect/src/androidTest/kotlin/com/google/firebase/dataconnect/OperationExecutionErrorsIntegrationTest.kt
DataConnectExecutableVersions.json updated with versions 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.5.0, 2.6.0, 2.6.1, and 2.6.2 by running:
```
./gradlew :firebase-dataconnect:connectors:updateJson -Pversions=2.3.0,2.3.1,2.4.0,2.4.1,2.5.0,2.6.0,2.6.1,2.6.2 -PdefaultVersion=2.6.2
```
As part of this upgrade, 2 test failures needed to be fixed because the `@check` directive on a field with side effects became illegal since cl/756896487. The fix in this PR adds a "query" field (which has no side effects) and, instead, attaches the `@check` directive to that.
This fixes the following 2 test failures in `OperationExecutionErrorsIntegrationTest`:
* `executeMutationFailsWithNonNullDataNonEmptyErrorsDecodingSucceeds`
* `executeMutationFailsWithNonNullDataNonEmptyErrorsDecodingFails`
The test failures looked …
=> dataconnect: DataConnectExecutableVersions.json updated with versions 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.5.0, 2.6.0, 2.6.1, and 2.6.2

firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/FirstFragment.kt, firebase-sessions/test-app/src/main/res/layout/fragment_first.xml, firebase-sessions/test-app/src/main/res/values/strings.xml, firebase-sessions/test-app/test-app.gradle.kts
Add more trace buttons to sessions test app to match the detailed test cases easier
=> Add more trace buttons to sessions test app

firebase-ai/src/main/kotlin/com/google/firebase/ai/type/ImagenPersonFilterLevel.kt, firebase-ai/src/main/kotlin/com/google/firebase/ai/type/Voice.kt, firebase-ai/src/main/kotlin/com/google/firebase/ai/type/Voices.kt, plugins/src/main/java/com/google/firebase/gradle/bomgenerator/GenerateTutorialBundleTask.kt
=> Change docs for m165

firebase-ai/CHANGELOG.md, firebase-ai/src/main/kotlin/com/google/firebase/ai/type/CountTokensResponse.kt
I've marked the `totalBillableCharacters` field in `CountTokensResponse.kt` as deprecated. This includes adding the `@Deprecated` annotation and a corresponding KDoc `@deprecated` tag.
The field is planned to be removed in a future version of the SDK.
=> [Ai] Deprecate totalBillableCharacters

firebase-ai/CHANGELOG.md
The changes in #7013 mistakenly put the changelog entry for the change in the "16.1.0" section, when it should be part of the "Unreleased" section
=> [Ai] Move changelog entry to the correct section

firebase-messaging-directboot/CHANGELOG.md
There are no planned changes for FCM-DirectBoot to go with the planned changes for FCM. Add changelog note about it.
=> [FCM-DB] Update changelog to align with FCM

firebase-sessions/test-app/src/main/AndroidManifest.xml, firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/BaseActivity.kt, firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/CrashBroadcastReceiver.kt, firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/FirstFragment.kt, firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/ForegroundService.kt, firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/MyServiceA.kt, firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/MyServiceB.kt, firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/SecondActivity.kt, firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/TestApplication.kt
Make the Sessions test app more convenient to test
Initialize Firebase on the Application, not Activity, so it can be initialized in background services
Fixed the process name for older Android API levels
Made all the logcat tags be the same, so it will be easier to give test instructions like `tag:SessionsTestApp tag:FirebaseSessions`
Added 2 background services with easy actions to interact with in the background, e.g., `am startservice -n com.google.firebase.testing.sessions/.MyServiceA -a PING`
=> Make the Sessions test app more convenient to test

firebase-dataconnect/demo/build.gradle.kts
Update the dependencies used in the Data Connect demo application's build file. The primary change involves adopting the recommended practice of using the Firebase Bill of Materials (BoM) to manage the version of the `firebase-dataconnect` library. Additionally, several other key library versions are updated to more recent releases.
* **Dependency Management**: Switched the `firebase-dataconnect` dependency in the demo app's `build.gradle.kts` to use the Firebase Bill of Materials (BoM) version `33.15.0` instead of specifying an explicit version for the individual library.
* **Dependency Updates**: Updated several other dependencies in the demo app, including the Android Gradle Plugin (`8.10.1`), `kotlinx-serialization-core` (`1.8.1`), `androidx.appcompat` (`1.7.1`), and …
=> dataconnect: demo: build.gradle.kts: update dependencies

firebase-ai/firebase-ai.gradle.kts
The release notes were being generated with the outdated {{firebase_ai}} instead of the correct {{firebase_ai_logic}}.
Reference cl/773420536
=> [Ai] Use correct release notes name

.github/workflows/dataconnect_demo_app.yml, firebase-dataconnect/demo/build.gradle.kts, firebase-dataconnect/demo/gradle.properties
Enhance the Data Connect demo's Gradle build configuration by introducing a new option to explicitly define the path to the Data Connect emulator executable. This provides flexibility for developers who may need to use a specific version or a locally-built emulator binary instead of relying on the one automatically managed by the Firebase CLI.
* **Emulator Executable Path**: Added ability to specify the path to the Data Connect emulator executable via a new Gradle property (`dataConnect.demo.dataConnectEmulatorExecutable`). This allows overriding the default emulator used by the `firebase` command.
* **Environment Variable**: When the custom emulator path is provided, the build script now sets the `DATACONNECT_EMULATOR_BINARY_PATH` environment variable before executing the `firebase` …
=> dataconnect: demo: build.gradle.kts: add ability to specify the Data Connect emulator executable to use

firebase-ai/api.txt
=> [Ai] Update api.txt

firebase-common/src/test/java/com/google/firebase/DataCollectionPreNDefaultEnabledTest.java, firebase-common/src/test/java/com/google/firebase/platforminfo/FirebasePlatformLoggingTest.java
Tests will use the Config.OLDEST_SDK instead of a hardcoded SDK if the corresponding hardcoded SDK would be below our intended minSdk.
I'll also need to re-evaluate whether these tests are necessary to keep around, or if they are irrelevant when bumping the minSdk.
Related to cl/769912845
=> [Common] Replace hardcoded SDK version with Config.OLDEST_SDK (2)

firebase-ai/src/main/kotlin/com/google/firebase/ai/type/Schema.kt
The sample code was not correctly enclosed in backticks (`), causing the code to be incorrectly rendered.
=> [Ai] Fix `anyOf` refdoc

firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java, firebase-sessions/api.txt, firebase-sessions/gradle.properties, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsComponent.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SharedSessionRepository.kt, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/api/CrashEventReceiver.kt, firebase-sessions/src/test/kotlin/com/google/firebase/sessions/api/CrashEventReceiverTest.kt, firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/MyServiceA.kt
Notify Sessions when a fatal crash occurs. Sessions will treat it like a background event. This will preserve session background time when a process ends due to a crash
=> Notify Sessions when a fatal crash occurs

.github/workflows/metalava-semver-check.yml
The metalava-semver-check.yml workflow was previously configured to run on all pull requests. This change updates the trigger to only run on pull requests that target the `main` branch.
=> Fix: Workflow trigger updated to run only on PRs to main

firebase-crashlytics/CHANGELOG.md, firebase-crashlytics/api.txt, firebase-crashlytics/gradle.properties, firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/CrashlyticsTests.kt, firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/KeyValueBuilder.kt
prepare for next major bump
Original change:https://github.com/firebase/firebase-android-sdk/pull/6536
=> Removed deprecated public constructor KeyValueBuilder

firebase-config/firebase-config.gradle.kts, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigContainer.java
The return value from Builders can safely be ignored dependending as they only enable chaining. This change fixes a warning thrown by errorprone.
(internal) See b/424298831
=> [Config] Annotate Builder with @CanIgnoreReturnValue

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
The `unused` vars were added to address a warning raised by errorprone about ignoring returned types.
(internal) See b/424298831
=> [Config] Add unused vars for some call sites

firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandler.java, firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigSharedPrefsClient.java
Some methods are currently marked with `@VisibleForTestingOnly` but are being used directly within the SDK code. This annotation is intended to restrict usage to tests, and its presence causes errors when integrating the SDK into internal systems via copybara.
Internal Tracking: b/429425834
=> Remove VisibleForTesting from SDK production code

firebase-firestore/CHANGELOG.md, firebase-firestore/src/main/java/com/google/cloud/datastore/core/number/NumberComparisonHelper.java, firebase-firestore/src/main/java/com/google/firebase/firestore/core/View.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/DocumentReference.java, firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteMutationQueue.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/BasePath.java, firebase-firestore/src/main/java/com/google/firebase/firestore/model/Values.java, firebase-firestore/src/main/java/com/google/firebase/firestore/util/Util.java, firebase-firestore/src/test/java/com/google/firebase/firestore/util/UtilTest.java
This PR replaces the bespoke `Util.compareIntegers()` and `Util.compareLongs()` methods with standard Java `Integer.compare()`, `Long.compare()` and `Character.compare()` methods. It also updates the tests to validate comparisons based on sign rather than exact values, as these tests were previously brittle, erroneously failing due to `Character.compare()` returning values other than `1`, `0`, and `-1`.
The `Util.compareIntegers()` and `Util.compareLongs()` methods were originally added because they required minSdkVersion of 19 or greater which, at the time, was not the case. However, minSdkVersion has been 21 for some time now (and is increasing to 23 in the foreseeable future) so there is no longer any need for the bespoke implementations.
- Replaced all calls to …
=> Firestore: use Integer.compare() and Long.compare() instead Firestore bespoke implementations

firebase-installations/firebase-installations.gradle
The dependency on com.google.firebase:firebase-installations-interop twice, and once with the wrong version
=> [Installations] Remove duplicated interop declaration

.github/workflows/ci_tests.yml
We use `EnricoMi/publish-unit-test-result-action`, and we are reconfiguring it to stop publishing comments, and comparing between runs since the numbers it report are not correct in our case.
=> [Infra] Reduce noise produced by test unit workflow

firebase-appdistribution-api/firebase-appdistribution-api.gradle, firebase-storage/test-app/test-app.gradle
firebase-appdistribution-api wasn't bumped and it's causing build failures.
`firebase-storage/test-app` was still running on a unsupported version (16).
=> [Infra] Missing minSdk bumps

firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/serializers/JavaTimeLocalDateSerializerUnitTest.kt, firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/serializers/KotlinxDatetimeLocalDateSerializerUnitTest.kt, firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/serializers/LocalDateSerializerUnitTest.kt
This PR refines the test data generation for `LocalDateSerializer` unit tests across various date/time library integrations, enhancing the reliability of tests designed to validate the handling of unparseable date strings by preventing the generation of test data that could inadvertently be interpreted as valid numeric components.
The `unparseableDash()` function in `LocalDateSerializer` unit tests has been updated to ensure that the generated "invalid" strings do not contain any digit characters. This prevents scenarios where digits could combine with adjacent characters to unexpectedly form a valid integer. The fix is applied consistently across `JavaTimeLocalDateSerializerUnitTest.kt`, `KotlinxDatetimeLocalDateSerializerUnitTest.kt`, and `LocalDateSerializerUnitTest.kt`.
Note that this …
=> dataconnect: tests: fix unparseableDash() in LocalDateSerializerUnitTest.kt et al

firebase-sessions/test-app/src/main/AndroidManifest.xml, firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/TestApplication.kt
This changes the main activity to be on the default process, allowing the more typical FirebaseInitProvider initialization of Firebase. The other processes will still initialize manually
=> Make the AQS Test App behave more typically for Perf start up

firebase-perf/CHANGELOG.md, firebase-perf/gradle.properties, firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/GaugeManagerTest.java, firebase-perf/src/test/java/com/google/firebase/perf/transport/TransportManagerTest.java
- The `fireperf-aqs` branch was rebased on `main` yesterday.
- This PR bumps up the version to be a minor version bump.
=> Bump up minor version for Fireperf for AQS

firebase-dataconnect/demo/build.gradle.kts, firebase-dataconnect/demo/gradle.properties
This PR performs some maintenance of the Data Connect demo application. It introduces a mechanism to pass 'preview flags' to the Data Connect cli, updates the dependencies to the latest versions, and improves some null-handling logic to be more Kotlin-idiomatic.
* **Data Connect Preview Flags Support**: Introduced a new Gradle property, `dataConnect.demo.dataConnectPreviewFlags`, allowing the specification of preview flags for the Data Connect emulator and code generation. These flags are passed as a `DATA_CONNECT_PREVIEW` environment variable to the Firebase CLI.
* **Dependency Updates**: Updated numerous dependencies for the Data Connect demo, including Android Gradle Plugin, Google Services, Firebase BOM, Kotlin Coroutines, Kotlin Serialization, and AndroidX Lifecycle, to their latest …
=> dataconnect: demo: add support for data connect preview flags and update dependencies

.github/workflows/dataconnect.yml, .github/workflows/dataconnect_demo_app.yml
Notably, this updated version adds official support for user-defined enums.
=> dataconnect: upgrade firebase-tools to 14.11.0 (was 14.10.1) in github actions workflows

firebase-dataconnect/emulator/emulator.sh
This PR enhances Data Connect's `emulator.sh` script by introducing robust command-line argument parsing. This improves the developer experience when launching the Firebase Data Connect and Authentication emulators for local development, offering easier control over the Data Connect Emulator binary and PostgreSQL database configuration.
This change does _not_ affect customers at all; this script is only used for development of the data connect sdk itself.
* **Enhanced Command-Line Argument Parsing**: The `emulator.sh` script now supports command-line arguments (`-c`, `-p`, `-w`, `-h`).
* **Custom Emulator Binary Support**: Users can specify a custom Data Connect Emulator binary path using the `-c` option, allowing for local development with specific emulator versions.
* **Flexible …
=> dataconnect: emulator.sh: add fancy command-line argument parsing to improve devx

firebase-dataconnect/connectors/connectors.gradle.kts, firebase-dataconnect/connectors/src/androidTest/kotlin/com/google/firebase/dataconnect/connectors/demo/EnumIntegrationTest.kt, firebase-dataconnect/connectors/src/test/kotlin/com/google/firebase/dataconnect/connectors/demo/EnumValueKnownUnitTest.kt, firebase-dataconnect/connectors/src/test/kotlin/com/google/firebase/dataconnect/connectors/demo/EnumValueSerializerUnitTest.kt, firebase-dataconnect/connectors/src/test/kotlin/com/google/firebase/dataconnect/connectors/demo/EnumValueUnknownUnitTest.kt, firebase-dataconnect/emulator/dataconnect/connector/demo/demo_ops.gql, firebase-dataconnect/emulator/dataconnect/schema/demo_schema.gql, firebase-dataconnect/src/androidTest/kotlin/com/google/firebase/dataconnect/EnumIntegrationTest.kt, firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/WithNullAppended.kt, firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/property/arbitrary/misc.kt, firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/property/arbitrary/tuples.kt, firebase-dataconnect/testutil/src/test/kotlin/com/google/firebase/dataconnect/testutil/WithNullAppendedUnitTest.kt
This pull request adds test coverage for user-defined enum support in Data Connect. It includes new GraphQL schema definitions and operations to handle various enum configurations, such as nullable and non-nullable fields, lists of enums, default values, and enums serving as primary keys. The changes are backed by integration and unit tests that validate the correct behavior, serialization, and deserialization of these enum types both in the core sdk and the generated sdk.
=> dataconnect: add tests for user-defined enum support

firebase-ai/src/main/kotlin/com/google/firebase/ai/type/LiveServerMessage.kt
The error message should include the actual content of the message that couldn't be de-serialized instead of class around java class names, which are not useful before de-serialization succeds.
=> [AI] Improve error messaging for LiveServerMessageSerializer

.github/workflows/dataconnect.yml, .github/workflows/dataconnect_demo_app.yml, firebase-dataconnect/connectors/src/test/kotlin/com/google/firebase/dataconnect/connectors/demo/EnumValueUnknownUnitTest.kt, firebase-dataconnect/gradleplugin/plugin/src/main/resources/com/google/firebase/dataconnect/gradle/plugin/DataConnectExecutableVersions.json
dataconnect: upgrade data connect emulator for codegen and testing to 2.10.1 (was 2.10.0) and, correspondingly, `firebase-tools` to 14.11.1 (was 14.11.0) in github actions workflows.
This upgrade picks up the following changes relevant to Kotlin:
* cl/785477120: Add `value` property to the `EnumValue` base interface.
With this upgrade, this PR also re-enables the unit test for the new `value` property in `EnumValueUnknownUnitTest.kt`.
=> dataconnect: upgrade data connect emulator to 14.11.1

firebase-dataconnect/connectors/src/androidTest/kotlin/com/google/firebase/dataconnect/connectors/demo/EnumIntegrationTest.kt, firebase-dataconnect/emulator/dataconnect/connector/demo/demo_ops.gql, firebase-dataconnect/src/androidTest/kotlin/com/google/firebase/dataconnect/EnumIntegrationTest.kt
The data connect emulator v2.10.1 has the fix for the crash b/432793533 and was included in firebase-tools release https://github.com/firebase/firebase-tools/releases/tag/v14.11.1
Googlers see b/432793533 for details.
=> dataconnect: re-enable tests for user-defined enums as primary keys.

firebase-ai/CHANGELOG.md, firebase-ai/src/main/kotlin/com/google/firebase/ai/FirebaseAI.kt, firebase-ai/src/main/kotlin/com/google/firebase/ai/LiveGenerativeModel.kt, firebase-ai/src/main/kotlin/com/google/firebase/ai/common/APIController.kt
This PR adds bidi support for developer api
=> Add developer api to bidi.

firebase-perf/firebase-perf.gradle
The current dependency was set to HEAD. This switches it back to 3.0.0.
This is needed for shipping it in an EAP.
=> Update the version dependency of firebase sessions

firebase-dataconnect/emulator/emulator.sh
This PR enhances the Data Connect `emulator.sh` script by adding support for the special value `gradle` to the `-c` flag, causing it to use the same data connect emulator binary as the Gradle build. The new `-g` flag was added as a convenient shorthand.
* **Enhanced Emulator Binary Selection**: The `emulator.sh` script now supports a special value of "gradle" for the `-c` command-line argument, or `-g` as a shorthand. When this value is provided, the script will automatically execute the necessary Gradle task to download the Data Connect emulator binary and then use that specific binary, ensuring consistency with the Gradle build's environment.
* **Improved Error Handling**: A new utility function, `log_error_and_exit`, has been introduced within `emulator.sh` to standardize error logging …
=> dataconnect: emulator.sh: add flag to use the same data connect emulator as the gradle build

firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
This PR fixes the flaky test `realtime_stream_listen_backgrounded_disconnects` in `FirebaseRemoteConfigTest.java`. The flake was due to a race condition in the test.
The test called `ConfigRealtimeHttpClient.beginRealtimeHttpStream()` followed immediately by a call to `ConfigRealtimeHttpClient.setIsInBackground(true)`. It then ensured that `HttpURLConnection.disconnect()` was called by `setIsInBackground(true)`. The problem is that `beginRealtimeHttpStream()` sets the `HttpURLConnection` asynchronously and if `setIsInBackground(true)` is called _before_ it is set then its `disconnect()` method is never called. 
The flake is easily reproduced by adding a call to `Thread.sleep(500)` into the asynchronous task in `ConfigRealtimeHttpClient.beginRealtimeHttpStream()`: …
=> FirebaseRemoteConfigTest.java: fix flaky test: realtime_stream_listen_backgrounded_disconnects

firebase-ai/CHANGELOG.md
The backend won't be published until sometime next week, removing this until it's ready. No changes to the code are necessary as there are no public API changes and it'll still hit a runtime error.
=> Temporarily remove CHANGELOG entry

.github/workflows/ci_tests.yml
The unit tests steps in `.github/workflows/ci_tests.yml` had a small bug: if the tests failed then the following step, which calculated the name of the artifact to upload, was skipped, causing the upload artifacts step to use an empty string as the artifact name, resulting in the wrong artifact name.
I first noticed this issue in https://github.com/firebase/firebase-android-sdk/actions/runs/16682145664/job/47223202941?pr=7215 where the "Upload Test Results" step curiously failed with the error "Conflict: an artifact with this name already exists on the workflow run". It turns out this was because there were more than one jobs that failed and both tried to use the same artifact name because the artifact name environment variable was not set.
This PR fixes the issue by simply ensuring that …
=> ci_tests.yml: ensure that upload artifact name is calculated before uploading the artifacts

firebase-perf/src/main/java/com/google/firebase/perf/logging/FirebaseSessionsEnforcementCheck.kt, firebase-perf/src/main/java/com/google/firebase/perf/session/FirebasePerformanceSessionSubscriber.kt, firebase-perf/src/main/java/com/google/firebase/perf/session/SessionManager.java, firebase-perf/src/main/java/com/google/firebase/perf/transport/TransportManager.java, firebase-perf/src/test/java/com/google/firebase/perf/session/FirebaseSessionsTestHelper.kt, firebase-perf/src/test/java/com/google/firebase/perf/session/PerfSessionTest.java
Based on our discussion, updated this PR with the following changes:
- Removed excessive logs for legacy sessions.
- Changed the logs for sessions list to log only if *all* the sessions were legacy.
- Added unit tests to verify the behaviour of verbose and legacy sessions, which keeps legacy sessions as the first *only* if there's no verbose session.
=> Update legacy session enforcement and debugging logic

firebase-perf/CHANGELOG.md, firebase-perf/src/main/java/com/google/firebase/perf/metrics/AppStartTrace.java, firebase-perf/src/test/java/com/google/firebase/perf/metrics/AppStartTraceTest.java
Reverts firebase/firebase-android-sdk#7274
Reverting this if the current change is going to be included in M169. 
An additional change is needed to verify that the `mainThreadRunnableTime` should be set only if no activity's onCreate has been called - otherwise this can cause a regression of *genuine* background starts.
=> Revert "Make a change to prevent false positive background app starts."

firebase-ai/CHANGELOG.md, firebase-ai/src/main/kotlin/com/google/firebase/ai/FirebaseAI.kt
Per [b/440356335](https://b.corp.google.com/issues/440356335),
This updates the limited-use token related docs to point to the web page that will go live with the release. Initially, it was planned for the docs to go live when Unity released, but Rachel now intends to have them live immediately -- with a note about Unity until they go live.
The updates are made per Rachel's recommendations and discussions in the javadoc CL/ALF doc.
=> [FAL] Update limited-use token docs

plugins/src/main/java/com/google/firebase/gradle/plugins/ci/AffectedProjectFinder.java
This change improves the CI process by skipping test runs for pull requests that only contain changes to documentation files.
The logic is implemented in `AffectedProjectFinder.java`. It filters out files with common documentation extensions (`.md`, `.txt`, `.html`) and files in the `docs/` directory from the set of changed files.
If all changed files in a pull request are documentation files, the set of affected projects will be empty, and no tests will be run. This avoids unnecessary test runs and saves CI resources.
=> feat: Skip tests for doc-only changes

.github/workflows/ci_tests.yml
The unit tests CI workflow has been failing when no modules were affected. See https://github.com/firebase/firebase-android-sdk/actions/runs/17332506204/job/49221502380?pr=7303 as an example
The solution has been to fully skip jobs in the workflow when there are no affected jobs.
=> Make sure unit_tests don't fail if no modules are affected

firebase-ai/CHANGELOG.md, firebase-ai/api.txt, firebase-ai/src/main/kotlin/com/google/firebase/ai/type/HarmCategory.kt
There are a number of new HarmCategory values, this patch adds support for parsing them all.
=> Updated HarmCategory

.github/workflows/ai-daily-tests.yml
Re comments in #7250
Changes
* Rename from nightlies to not be confused with daily builds
* Add explicit permissions
* Remove fetch depth as no actions are performed on git history
* Pins the API Level to our current target SDK instead of an outdated one
Unadjusted
* GCloud setup remains in order to run integ tests
=> Make AI Daily adjustments

firebase-dataconnect/CHANGELOG.md
This PR updates the change log for Data Connect to add the link to https://github.com/firebase/firebase-android-sdk/pull/7314 (Ignore unknown fields in response data instead of throwing) for its entry. This was overlooked in the original PR and having the link gives more context to readers of the change log who are interested in details.
=> dataconnect: CHANGELOG.md: add PR link for "Ignore unknown fields in response data" entry

firebase-perf/src/main/java/com/google/firebase/perf/metrics/AppStartTrace.java, firebase-perf/src/main/java/com/google/firebase/perf/network/InstrURLConnectionBase.java, firebase-perf/src/main/java/com/google/firebase/perf/util/FirstDrawDoneListener.java, firebase-perf/src/main/java/com/google/firebase/perf/util/Timer.java
#nochangelog
As part of the app start trace change, I noticed there were some API checks which were always true/false.
=> Remove API checks that are always true/false.

health-metrics/benchmark/template/build.gradle
It will make it match our actual required min version of 2.0.21
=> [Infra] Bump benchmark kotlin plugin version

firebase-common/src/test/java/com/google/firebase/heartbeatinfo/HeartBeatInfoStorageTest.java
Apply some java style & lang fixes to the `HeartBeatInfoStorageTest.java` file
=> [Common] Style fixes

firebase-ai/src/androidTest/kotlin/com/google/firebase/ai/AIModels.kt, firebase-ai/src/androidTest/kotlin/com/google/firebase/ai/ToolTests.kt, firebase-ai/src/test/java/com/google/firebase/ai/GenerativeModelTesting.kt, firebase-ai/src/test/java/com/google/firebase/ai/common/APIControllerTests.kt
Update all model used in test to point to the 2.5 family
Internal b/438111636
=> [AI] Update model name's in tests

firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ServerTimestampTest.java
firestore: test: fix `ServerTimestampTest.java` that was accidentally broken by #6235
The test failure fixed by this PR is:
```
com.google.firebase.firestore.ServerTimestampTest > testPOJOWithWrongType[emulator-5554 - 12] FAILED
org.junit.ComparisonFailure: expected:<...ring instead of Date[ or Timestamp].> but was:<...ring instead of Date[, Timestamp, or Instant].>
at org.junit.Assert.assertEquals(Assert.java:117)
```
It simply updates the expected exception message as follows:
```
- "java.lang.String instead of Date or Timestamp.",
+ "java.lang.String instead of Date, Timestamp, or Instant.",
```
=> firestore: test: fix expected message in ServerTimestampTest.java to include "Instant"

firebase-crashlytics/CHANGELOG.md, firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsComponent.kt
Prepare the DataStore files directly in the Sessions SDK, instead of relying on DataStore to do it.
DataStore uses the old `File.mkdirs` api, which lacks any meaningful error messages. This will use the better `Files.createDirectories` api if available, which has proper error messages. 
Also renamed the parent directory from `aqs` to `firebaseSessions` to avoid any collision with any other libraries that might use DataStore and a 3 letter file name. If there is an unexpected file where the `firebaseSessions` directory should be, this will safely remove it.
Tested manually by creating the conflicting file and running the Sessions Test App on both old and new api levels.
=> Make creating DataStore files more resilient

firebase-crashlytics-ndk/CHANGELOG.md, firebase-sessions/CHANGELOG.md
The change introduced in #7440 will force the release of both  
crashlytics-ndk and sessions. This PR adds the corresponding entries  
to the changelog files.
=> [crash] Add missing entries to changelogs
